### ISSUE TITLE
Automatic test of elasticsearch mapping definitions

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1]
As developers we want a unit test which ensures that
1. there is a mapping file for the english and the german index
2. all attributes are covered by the mapping file
in order to prevent missing attributes in the elasticsearch index.

**Comment by rreitmann** [comment]
@dkatzberg
- change AbstractWebTest to AbstractTest
- remove debug output
- Use once concrete test for all Classes inheriting from AbstractDocument

**Comment by rreitmann** [comment]
@dkatzberg Adding a property "hurz" to VariableSurvey results in a NullPointerException. Please fix this.

**Comment by dkatzberg** [comment]
i added a log error message in the case of a missing field (e.g. hurz). The assertion gives no information about the missing field.

**Comment by rreitmann** [comment]
@dkatzberg added todos for discussion
