### ISSUE TITLE
Update DS-Report with new FDZ style defintions

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#1003]
- [x] Update Style Definition
- [x] Install Calibri as Local Latex Font (local texmf)
- [x] Update Backend for handling binary files
- [x] Update Table Definition
- [x] Update If conditions and handling for box plots and bar charts
- [x] Scale Level: Invervals have only a box plot in the future
- [x] Problems with Table if DataType = String

**Comment by kpstephan** [comment]
Further Updates of dsreport.sty, dsreport.ist, dsreport.xdy and main.tex are necessary due to a new version v0.95 of  the dsreport package. These changed will be reviewd and tested  in #956
