### ISSUE TITLE
Exclude the list of included variables in a own latex document (DS-Report)

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#1012]
The list of all included variables should be excluded in a own latex document. This separated latex document should be included into the main.tex. The user have just disable one include command and not thousands.

**Comment by rreitmann** [comment]
Here are some general remarks regarding the data set report:
- [ ] we should only depend on the files in the uploaded zip which we need to fill with freemarker, all other (arbitrary) files should be copied from the input zip to the outpout zip
- [ ] the directory structure with the expected files for freemarker should be described in the wiki here https://github.com/dzhw/metadatamanagement/wiki/Interfaces
- [ ] we should load a related question only if it has not been loaded before
- [ ] ensure that all input and output streams are closed

**Comment by rreitmann** [comment]
@KeLange Please get in touch with us in order to learn how to create a DataSet-Report

**Comment by KeLange** [comment]
Please add the variablelist.tex file in the wiki. Then you can close the issue
