### ISSUE TITLE
Define dara process

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1019]
current idea is to import dara information for our study on release.
what are the interfaces provided by dara? how do we identify a study...

Another idea is to push data automatically to dara on release. Is this somehow possible?

**Comment by rreitmann** [comment]
see #650 as well

**Comment by dkatzberg** [comment]
You find all information here: https://github.com/dzhw/metadatamanagement/wiki/Dara-DOI

**Comment by dkatzberg** [comment]
Updated Version is online

**Comment by rreitmann** [comment]
To sum up: We will implement dara as an external service to which we will push all required infos on release. On unrelease we will notify dara as well. The status (health) page will be extended by the state of the dara service.
