### ISSUE TITLE
Survey images with the content type "application/octet-stream"

### ISSUE THREAD

**Issue by limouri** [dzhw/metadatamanagement#1054]
During the surveys upload process, the content type of images is currently being set up as "application/octet-stream". This happens when drag&drop and Firefox(v.52) are used.

**Comment by rreitmann** [comment]
This codepen demonstrates the behaviour:
https://codepen.io/rreitmann/pen/gWmLaE

Currently we can only reproduce it in firefox running on windows.

**Comment by rreitmann** [comment]
I have asked for help here: danialfarid/ng-file-upload#1915

**Comment by rreitmann** [comment]
We will not rely on the content-type given by the client anymore. Instead we will use apache tika (see https://stackoverflow.com/questions/19711956/alternative-to-files-probecontenttype) to detect the content type of all files on the server.
