### ISSUE TITLE
Implement study attachment for method report

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1069]
Same as instrument attachments (including type). Valid types are in german ("Daten- und Methodenbericht", "Sonstiges"). English types follow: ("Method Report", "Other")

**Comment by KeLange** [comment]
- "Replace all Surveys?" although it is study upload
- The english error message when there is an invalid type for the attachment has to be changed.
- The german card title for the attachments should be "Materialien zu der Studie".
