### ISSUE TITLE
Create welcome dialog and link to Github Issues

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1084]
In order to tell the users that the prod system is still being developed we should display a modal dialog (which can be closed forever) on startup of the application. Further more we should provide a link to Github (https://github.com/dzhw/metadatamanagement/issues/new) for collecting feedback...

**Comment by dkatzberg** [comment]
There is no option to close the dialog forever (local storage).

**Comment by KeLange** [comment]
- Add the github link in the menu.
- Change welcome dialog so that the user knows that it is possible to give feedback later even if he closes the dialog forever.
