### ISSUE TITLE
Validation InstrumentAttachmentMetadata: rename valid value of attribute type

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1091]
Rename german valid value "Filterdiagramm" as "Filterführungsdiagramm"

**Comment by rreitmann** [comment]
@MarenStephan I have already changed it. Please ensure that you do so on for the input files and reimport all instruments after we have deployed a new version...

**Comment by MarenStephan** [comment]
@rreitmann i changed the import files, please deploy

**Comment by rreitmann** [comment]
@MarenStephan Done

**Comment by MarenStephan** [comment]
reimport of all instruments done
