### ISSUE TITLE
Search in title attributes in order to increase the score for all domain objects...

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1106]
If you currently search for "erste welle" in surveys you find "zweite welle" with a high score :-(

**Comment by KeLange** [comment]
Unexpected behavior:
https://metadatamanagement-test.cfapps.io/#!/de/search?page=1&type=variables&query=promotion%20monat
https://metadatamanagement-test.cfapps.io/#!/de/search?page=1&type=variables&query=note%20schule

**Comment by dkatzberg** [comment]
https://www.elastic.co/blog/understanding-query-then-fetch-vs-dfs-query-then-fetch
