### ISSUE TITLE
add attribute annotation to all details pages

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1115]
attribute already exists for variables details page, please add to the other details pages

show attribute annotations (I18nString, german string: Anmerkungen), if content length >0
display as last element in Card Details

**Comment by dkatzberg** [comment]
The annotation field has the same validator like on variable (Large, 2048 signs)
It will be shown in every Details Card at last element, if it is filled.

**Comment by KeLange** [comment]
- In the survey import file from the interface annotations are added to the excel sheet attachments, but belong to the excel sheet surveys.
- The same for instruments and datasets.
- If the annotation is to long I get the error message: {{instrument-management.error.variable.annotations.i18n-string-size}} 
- In the error message: "Unable to read at least one of the excel sheets "study, authors, attachment"!" from study, survey and dataset upload it has to be "attachments" (plural)

**Comment by KeLange** [comment]
There is no line break when I have long annotations so only the first 100 signs are visible.

**Comment by KeLange** [comment]
Should behave like relatedpublication.citationHint

**Comment by dkatzberg** [comment]
@KeLange Please use spaces. A String without spaces is hardly to split.
