### ISSUE TITLE
variables details page, card descriptive metrics: don't display deviance and mean absolute deviation

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1116]

**Comment by dkatzberg** [comment]
This issue includes NOT the decision for removing the deviation and mean absolute deviation completly from the interface, import and so on. It will be just removed from the details page.

**Comment by dkatzberg** [comment]
Commit: https://github.com/dzhw/metadatamanagement/commit/79581825b562225c11d40e9bc4d6b5c0179246fc

**Comment by rreitmann** [comment]
To clarifiy: This issue is not about removing the deviation (=Standardabweichung) it is about removing the deviance (Devianz) and the mean absolute deviance from the GUI.

**Comment by rreitmann** [comment]
@KeLange Please review the changes and read my last comment
