### ISSUE TITLE
change or delete validator for histogram

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1117]
favoured solution: also accept variables with scale level ratio without histogram (bzw. bins) but display warning for publisher, that variable doesn't have the necessary information to show histogram

minimal solution: don't validate histogram and bins information

in both cases, like it was before implementing the histogram validator: card figure frequencies will show empty coordinate system for variables with scale level ratio but without histogram information

**Comment by KeLange** [comment]
- spelling mistakes: german warning: "... eines Histogramms", english version: "a histogram"
- When I upload a variable with valid start and end value but "numberOfBins" : null, a histogram is displayed.
