### ISSUE TITLE
mixed representation of numbers (point and comma) in frequency table in german version

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1121]
please check variable details page of [abs05-ds1-astu03c!](https://metadatamanagement.cfapps.io/#!/de/variables/var-abs2005-ds1-astu03c!)
german version, frequency table, column value: mixed representation of numbers, 1.0 (with point) and 1,1 (with comma)
therefore wrong presentation of frequency figure

the english version of this varibale details page is ok

**Comment by dkatzberg** [comment]
Commit: https://github.com/dzhw/metadatamanagement/commit/3cdc5dd570d4f0d91032615bfd6f0ace4d8d53db

**Comment by rreitmann** [comment]
@KeLange Please verify the changes...
