### ISSUE TITLE
Check error message "Title mandatory in both languages" for instrument upload 

### ISSUE THREAD

**Issue by KeLange** [dzhw/metadatamanagement#1124]
I guess the validator that the title for instrument upload is mandatory in both languages was deleted. So the error message for a title with more than 128 characters has to be adapted.
"The titel must not contain more than 128 characters." instead of "The titel is mandatory in both languages and must not contain more than 128 characters."

**Comment by dkatzberg** [comment]
@KeLange Please check the changed error messages.
