### ISSUE TITLE
Add human readable error message for uploading of not interface confirmed jsons

### ISSUE THREAD

**Issue by KeLange** [dzhw/metadatamanagement#1142]
A part of the json is:
```
"instruction":{
        "de":[
            "Genaue Berufsbezeichnung:",
            "(bitte möglichst genau; z. B. Ingenieur(in) für Messtechnik, Personalentwickler(in), Schulsozialarbeiter(in))"
        ]
    },
```
The de field is an array, but the interface accepts only a string. I got the not human readable error message:

{{Can not deserialize instance of java.lang.String out of START_ARRAY token at [Source: org.apache.catalina.connector.CoyoteInputStream@663f8085; line: 1, column: 2482] (through reference chain: eu.dzhw.fdz.metadatamanagement.questionmanagement.domain.Question["instruction"]->eu.dzhw.fdz.metadatamanagement.common.domain.I18nString["de"])}}

**Comment by dkatzberg** [comment]
Merge commit bc0b7944c2eaa326468da81f5879a5941c789212
