### ISSUE TITLE
get BMBF logo as SVG

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1148]
minimum 40 points :-)

**Comment by AndyDaniel1** [comment]
As an Wikipedia veteran I had the blod idea to check the BMBF- Wikipedia article and guess what I found 😎  

https://de.wikipedia.org/wiki/Bundesministerium_f%C3%BCr_Bildung_und_Forschung#/media/File:BMBF_Logo.svg

**Comment by AndyDaniel1** [comment]
and just for the record: the logo is in the public domain

**Comment by AndyDaniel1** [comment]
too bad... we need the 40  points to add the sponsed by de/en to the .svg . Maybe one of our students is capable to edit the .svg

**Comment by rreitmann** [comment]
To clarify:
- We need the strings "Sponsored by:" and "Gefördert vom:"
- We need an english version with "Federal Ministry of Education and Research"
