### ISSUE TITLE
check fitting of different mandatory strings

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1149]
~~study details page: surveyDesign is limited to "Querschnitt" and "Panel". Does not fit for qualitative studies, maybe also not for all quantitative studies?~~

~~data set details page: format ist limited to "breit" and "lang". Strings like "long-Format" or "long" in german view should be possible. Delete limitation?~~

~~instrument details page: type is limited to PAPI, CAPI, CATI, CAWI. Strings like "Paper-and-Pencil-Interview (PAPI)" should be possible~~

**Comment by rreitmann** [comment]
@kpstephan needs further input. Hint: If we want to filter by these attributes it needs to be controlled vocabulary...

**Comment by AndyDaniel1** [comment]
#1258 provides solution for the study and survey detail pages
