### ISSUE TITLE
add attribute subtitle to instrument

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1152]
some instruments (like Abs05 instruments) have subtitles
two possibilities: add attribute subtitle or increase length of attribute title

**Comment by rreitmann** [comment]
we will add a new attribute instrument.subtitile (max length equal to new title length see #1188)

**Comment by dkatzberg** [comment]
- [ ] Domain Model Image
- [ ] Domain Model Validation
- [ ] Interface
- [ ] Projection
- [ ] Elasticsearch
- [ ] Domain Model Image
- [ ] Domain Object
- [ ] SearchDocument
- [ ] Importer
- [ ] Details Page

**Comment by dkatzberg** [comment]
Merge development to this Branch: 94001470d55248563a52a3da1f6826be57466d1b

**Comment by rreitmann** [comment]
We have to recreate elasticsearch indices cause the mapping of instruments has changed.
