### ISSUE TITLE
Show publications if a data project is selected and has related publications

### ISSUE THREAD

**Issue by KeLange** [dzhw/metadatamanagement#1154]

**Comment by rreitmann** [comment]
We will implement a filter by studyId if there is a project selected and enable the publication tab if a project is selected...

**Comment by rreitmann** [comment]
A few remarks:
- [ ] remove studyIds from RelatedPublicationSubDocument (+Projection)
- [ ] Use bool.should in filter context of outer bool query
- [ ] move StudyIdBuilder to searchDao instead of search controller
