### ISSUE TITLE
problems with the "!" in MDM links 

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1156]
if you copy a MDM link to an email (outlook) and you try to follow this link in the mail you get an error-page in MDM because the " ! " at the end of the link is not treated as part of the link and a MDM page "without link" is opened 
@UteH reported that it is the same with MDM links sent with Threema

**Comment by rreitmann** [comment]
We will replace the "!" by "$". When these changes get deployed we need to delete all data and reimport it.
