### ISSUE TITLE
Variables cannot be imported due to duplicate indexInDataSet error

### ISSUE THREAD

**Issue by kimsommer** [dzhw/metadatamanagement#1173]
Fehlermeldung, dass Index schon vergeben wurde, obwohl dem nicht so ist. Wird erneut hochgeladen, ist immer eine Variable weniger betroffen. 

1. Versuch

Die Variable vom Skalenniveau Verhältnis mit dem Namen cjob0529c hat nicht alle Informationen für die Erzeugung eines Histrogram.
Die Variable vom Skalenniveau Verhältnis mit dem Namen cjob0529d hat nicht alle Informationen für die Erzeugung eines Histrogram.
Die Variable vom Skalenniveau Verhältnis mit dem Namen cjob0530c hat nicht alle Informationen für die Erzeugung eines Histrogram.
Die Variable vom Skalenniveau Verhältnis mit dem Namen cjob0530d hat nicht alle Informationen für die Erzeugung eines Histrogram.
Variable mit FDZ-ID var-sb2008-ds1-wave! wurde nicht gespeichert:
Der Index der Variable ist innerhalb des Datensatzes schon vergeben.
Variable mit FDZ-ID var-sb2008-ds1-asys01! wurde nicht gespeichert:
Der Index der Variable ist innerhalb des Datensatzes schon vergeben.
Variable mit FDZ-ID var-sb2008-ds1-asys01_g1! wurde nicht gespeichert:
Der Index der Variable ist innerhalb des Datensatzes schon vergeben.
Variable mit FDZ-ID var-sb2008-ds1-asys02_g1! wurde nicht gespeichert:
Der Index der Variable ist innerhalb des Datensatzes schon vergeben.
Variable mit FDZ-ID var-sb2008-ds1-asys02_g2a! wurde nicht gespeichert:
Der Index der Variable ist innerhalb des Datensatzes schon vergeben.
Upload von 1280 Variablen mit 4 Warnungen und 5 Fehlern beendet!

2. Versuch

Die Variable vom Skalenniveau Verhältnis mit dem Namen cjob0529c hat nicht alle Informationen für die Erzeugung eines Histrogram.
Die Variable vom Skalenniveau Verhältnis mit dem Namen cjob0529d hat nicht alle Informationen für die Erzeugung eines Histrogram.
Die Variable vom Skalenniveau Verhältnis mit dem Namen cjob0530c hat nicht alle Informationen für die Erzeugung eines Histrogram.
Die Variable vom Skalenniveau Verhältnis mit dem Namen cjob0530d hat nicht alle Informationen für die Erzeugung eines Histrogram.
Variable mit FDZ-ID var-sb2008-ds1-wave! wurde nicht gespeichert:
Der Index der Variable ist innerhalb des Datensatzes schon vergeben.
Variable mit FDZ-ID var-sb2008-ds1-asys01! wurde nicht gespeichert:
Der Index der Variable ist innerhalb des Datensatzes schon vergeben.
Variable mit FDZ-ID var-sb2008-ds1-asys01_g1! wurde nicht gespeichert:
Der Index der Variable ist innerhalb des Datensatzes schon vergeben.
Variable mit FDZ-ID var-sb2008-ds1-asys02_g1! wurde nicht gespeichert:
Der Index der Variable ist innerhalb des Datensatzes schon vergeben.
Upload von 1280 Variablen mit 4 Warnungen und 4 Fehlern beendet!

Beim hochladen in ein neues Projekt treten keine Fehler mehr auf.

**Comment by rreitmann** [comment]
Is it possible that you have changed the order of the variables in the dataSet between two uploads?

**Comment by rreitmann** [comment]
After talking to @MarenStephan I am convinced that we should not validate the uniqueness of the indexInDataSet anymore...
