### ISSUE TITLE
can no longer delete projects in MDM prod.

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1179]
wanted to delete se19, didn't work, the same with project test2017
error message: Das Datenaufbereitungsprojekt "se19" konnte nicht gelöscht werden
3 days ago I succesfully deleted pp2014

**Comment by dkatzberg** [comment]
It is not a bug. The projects have not the "hasBeenReleasedBefore" field, because the projects are older than the update.
