### ISSUE TITLE
as publisher I want to save the error protocol of MDM

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1182]

**Comment by dkatzberg** [comment]
FileSaver.js https://github.com/eligrey/FileSaver.js/

The Angular-File-Saver using the FileSaver.js https://github.com/alferov/angular-file-saver

**Comment by rreitmann** [comment]
A few remarks:
- [ ] rename button 'protokoll speichern' to 'speichern'
- [ ] buttons need tooltips
- [ ] buttons should be raised
- [ ] use angular date filter for timestamp creation
- [ ] use CR LF as line ending on windows (implement service which uses bowser)
- [ ] add newline after each error/info/warning
- [ ] remove total from heading and use some ascii art for the header
