### ISSUE TITLE
Overhaul all Elasticsearch Mappings/Setting and reconfigure them on requirement

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#1183]
Some Field of the domain object (e.g. survey.surveyMethod) are defined at the elasticsearch mapping/setting as keyword and not analyzed. This fields are added to the bool should match query to optimize the quality of the search results. That means, they should be a text and analyzed fields. This is a conflict. 
This is a new requierement and all Elasticsearch Mappings / Settings should be overhaul.

**Comment by rreitmann** [comment]
We need to identify all fields which need to "analyzed" and "not-analyzed"...

**Comment by rreitmann** [comment]
We will rework search as specified here:
https://github.com/dzhw/metadatamanagement/wiki/Search-Use-Cases
