### ISSUE TITLE
Successor questions cannot be loaded

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#1187]
The subsequent question are not loaded on the question details page. 
There is a Status Code of 400 with the _mget call 

`{"error":{"root_cause":[{"type":"parsing_exception","reason":"unexpected token [START_OBJECT], expected [FIELD_NAME] or [START_ARRAY]","line":1,"col":10}],"type":"parsing_exception","reason":"unexpected token [START_OBJECT], expected [FIELD_NAME] or [START_ARRAY]","line":1,"col":10},"status":400}`

**Comment by rreitmann** [comment]
@dkatzberg I cannot reproduce it on any system (local, dev, test). Can you please try to reproduce it...

**Comment by dkatzberg** [comment]
I could reproduce the problem and I analyzed the issue. 

I installed Elasticsearch 5.4.0 on my local system. I went back to the 5.1.2 (which is used by our prod and test system) and the error is gone. It seems that the Elasticsearch 5.4.0 has a Jackson problem with mget calls. Please **do not** use Elasticsearch 5.4.0.
