### ISSUE TITLE
check length of all title fields

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1188]
for most title fields the length is limited to 128 characters, recheck this requirement, also for the title fields of attachments

discuss the title length in connection with issue https://github.com/dzhw/metadatamanagement/issues/1152 (subtitle)

**Comment by rreitmann** [comment]
We can increase the length to 2048 characters

**Comment by dkatzberg** [comment]
The title will be changed from 128 Max length to 2048 at following objects:
* StudyAttachmentMetadata
* Survey
* SurveyAttachmentMetadata
* DataSetAttachmentMetadata
* Instrument
* InstrumentAttachmentMetadata
* CodingSchemeAttachmentMetadata (only Wiki, not implemented yet)

**Comment by dkatzberg** [comment]
Merge commit from development 84e0b42637834c31360bae1ae4a67d10e1086a96
