### ISSUE TITLE
variable search cards get new order, when you click previous or next

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1190]
example: project gsl2008, question: que-gsl2008-ins1-05$

I selected the question details page, I clicked variables in card related objects (seven variables), I got the variables search page (five cards on first page); I clicked "next" and got the second page of variables search with two variable search cards, but sometimes the same variables as on first page
same effect with previous-button, the order of variables search cards changed with every click

**Comment by rreitmann** [comment]
This is a general problem with search. Each click results in a new search, the order of the search results is determined by the relevance score which in this case is equal for all results. Therefore the order is undefined or random for each click and also it is undefined on which page the results are.
In this special case we could sort the variables by indexInDataSet or variable.name or whatever attribute you think is appropriate for sorting the variables of a question...

**Comment by rreitmann** [comment]
We will sort by variable.name...

**Comment by rreitmann** [comment]
Since neither variable.name nor variable.indexInDataSet are unique for the variables in a question we will sort by variable.id...
