### ISSUE TITLE
domain objects disappear

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1194]
I made several observations, I am not sure, if it is the same problem

1. on study details page sometimes the dataSet search card are disappeared, if you click reload sometimes they are back, sometimes not. On relatedObejcts card they are present. I think it is only a problem with study and datasets pages I imported this afternoon after new deployment of prodMDM

2. on question details pages we lost the previous and successor questions. It affects all studies not only the studies I imported after the deployment

3. I reimported gra2005 questions to check, if I could get back predecessor und successor questions. The MDM succesfully imported all 146 questions, I clicked on some question details pages and then on question search and with the exception of 12 questions all are disappeared. I imported the questions again, now they are there. I cannot reconstruct the problem.

**Comment by MarenStephan** [comment]
I sent you an email with screenshots of study details pages with and without dataSets

**Comment by MarenStephan** [comment]
relatedObjects are infected, too: variable details page, card relatedObjects, question is not displayed (screenshot see email: 1930.png). After reload question appears :-)

**Comment by MarenStephan** [comment]
additional hint: every page you reload shortly shows "Fehlerseite" before being reloaded. Not only today imported details pages

**Comment by rreitmann** [comment]
@MarenStephan Should be fixed now...
