### ISSUE TITLE
Link to data access page in the sidebar

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#1195]
We need a link to the data access page in the sidebar 

de: Datenzugang (https://fdz.dzhw.eu/kontakt/index_html)
en: Data Access (https://fdz.dzhw.eu/kontakt/index_html) currently no english version thus link to the german page

**Comment by rreitmann** [comment]
- [ ] remove FAB buttons on dataset details and study details page
- [ ] add link with icon to sidenav
