### ISSUE TITLE
Visualize already implemented question filters

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1202]
Currently we filter questions when the user comes from all details pages by the following attributes:
```
'instrument': 'instrumentId',
'variable': 'variables.id',
'related-publication': 'relatedPublications.id',
'study': 'studyId'
```
We need to visualize these filter settings for the user. Ideally the user can edit these.

**Comment by rreitmann** [comment]
Implemented with #1199

**Comment by svietgen** [comment]
@rreitmann Show question.Text instead of instrument title.

**Comment by svietgen** [comment]
Internet Explorer 11: when I use a filter, there are two close-icons

![grafik](https://user-images.githubusercontent.com/22055122/29607120-86375df6-87f0-11e7-861e-d707470ea22a.png)
