### ISSUE TITLE
Implement landing pages for previous releases

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1206]
Currently we have no possibility to show previous releases of projects to the user. There are several challenges:
- Each detail page has links to images and/or attachments
- Each detail page has links to the search page (e.g. related objects)
- Currently a project has zero or one release object depending if it is currently released or not (no list of releases)
- Currently we register exactly one DOI per project at DARA (we do not maintain multiple dois per project)

**Comment by dkatzberg** [comment]
We like to enable the registration=true parameter for the dara api permantly.

**Comment by rreitmann** [comment]
Here are the most important requirements from the versioning concept:
- We want to do beta releases which are marked by a version number < 1.0.0 and are not registered at dara. Each Details page should indicate that this is a beta version.
- The DOIs registered at DARA shall contain the current version number and the landing page URL shall contain a param holding this version param.
- If the user comes with a previous version in the URL there should be a Hint describing that this is not the expected version

**Comment by dkatzberg** [comment]
@rreitmann I define: if there is no old version in the history, the client sets the version to 0.0.0 as default.

**Comment by rreitmann** [comment]
We have to remove the doi from all studies in mongo:
`db.getCollection('studies').update({}, { $unset: {doi:1}}, {multi: true})`

**Comment by rreitmann** [comment]
@rbirkelbach See https://github.com/dzhw/metadatamanagement/issues/1206#issuecomment-359825412 for a more or less detailed specification. Access for dara test system will come via mail...

**Comment by rbirkelbach** [comment]
- On study details page: on unrelease no edit button. Only if reloaded.
- What happens to a dara update when dara is down?

**Comment by rreitmann** [comment]
@rbirkelbach Here are my comments:
1. This will be covered in #1615
2. I have improved this for the case that dara is updated asynchronously after uploading publications. Admins should now get an email. If dara is down during normal releases the user should see a toast indicating that something went wrong when releasing to dara
3. Beta released study are not queued for dara update anymore
