### ISSUE TITLE
DataSet attribute "type": rename english valid values

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#1210]
The english valid value "Personal Record" should be renamed to "Individual Data".
The english valid value "Episode Record" should be renamed to "Spell Data".

**Comment by dkatzberg** [comment]
- [ ] Rename Attributes
- [ ] Change JUnit Tests / Helper Methods
- [ ] Change Wiki Documentation
- [ ] Change Data in IO Project and Re-Import Data ( @svietgen )

**Comment by svietgen** [comment]
@dkatzberg I have tested this issue and changed the data (io-Project). I will re-import the data at the beginning of Sprint 49.
