### ISSUE TITLE
Reorganize unit tests

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#122]
The unit tests don't use the same BasicTest class. Their aren't consitent in the way of implementation (generated from JHipster and self written). The purpose of this issue is to get all unit tests standardized in a default way.

**Comment by rreitmann** [comment]
@dkatzberg Please ensure that only one completely configured mvc mock is generated.

**Comment by rreitmann** [comment]
We keep the mvc mocks per test cause with these it is possible to use a mocked service layer...
