### ISSUE TITLE
study: number of survey waves

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1225]
As a user I want to know how many waves are available at the first glance (i.e. study page)
https://metadata.fdz.dzhw.eu/#!/de/studies/stu-gsl2008$  
-> suggestion: list "Wellen" beneath "Erhebungsdesign"?  

(if we do this we should add this to the summary table of the method report)

**Comment by rreitmann** [comment]
We will add one new field wave (integer, mandatory) to the domain object survey and display the max wave (overall surveys of the study) on the study details page ("Verfügbare Wellen", link to survey search filtered by study)

**Comment by dkatzberg** [comment]
We ( @AndyDaniel1 , @UteH  and me ) discussed about the "link". We didn't understand this part and decided to not implement the "link" in this issue.
