### ISSUE TITLE
Change order of question search cards

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#1226]
When you search for questions you get the "wrong" order: 1.1, 1.10, 1.11,... instead of 1.1, 1.2,...

https://metadata.fdz.dzhw.eu/#!/de/search?page=1&type=questions&sort-by=number&instrument=ins-gsl2008-ins3$

**Comment by rreitmann** [comment]
We will add a field "indexInInstrument" to the question object...

**Comment by dkatzberg** [comment]
@rreitmann FYI: There is no working sortBy and that concludes no working sorting by number in the actual version. I had to redesign this sortBy interface.

**Comment by kimsommer** [comment]
It seems to work in all browsers and also works for several questions related to one variable. They are sorted by indexInIntrument. 

prod:
https://metadata.fdz.dzhw.eu/#!/de/search?page=1&type=questions&variable=var-gra2005-ds2-begin_m$

test:
https://metadatamanagement-test.cfapps.io/#!/de/search?page=1&type=questions&sort-by=indexInInstrument&variable=var-test-ds2-begin_m$

When I uploaded questions with the same indexInInstrument I was not given an error or warning. 
And indexInInstrument is missing in the Question Import File in Interfaces.

**Comment by dkatzberg** [comment]
@kimsommer please test the new warning for non unique index in instrument
