### ISSUE TITLE
surveys: display only if a study encompasses seperate samples

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1227]
I think in many cases, the _survey_ dimension is confusing for users.
- Example gsl2008: we don't (want to) provide the separate waves but only the pooled three-waves-dataset. Thus, we should only offer information (questionnaires etc.) on a pooled three-waves level (-> study)?
- Only if studies do have seperate samples this dimenion is helpful? (e. g. gra2005: bachelor vs. traditionelle; but not: wave one vs. wave two) 

We could discuss where to put the information from the _survey_ page in those cases
a) study page
b) _one_ survey page  
- Grundgesamtheit: -> study?
- Erhebungsmethode: -> study?
- Feldzeit: -> study?
- Bruttostichprobe: -> only method report?
- Nettostichprobe: -> only method report?
- Rücklaufquote: -> only method report?

Maybe, we could talk about this together.

**Comment by UteH** [comment]
con: maybe users want to look for variable only within one wave. 
-> Maybe a filter ([x] wave 1, [ ] wave 2, [ ] wave 3) could be helpful?

**Comment by rreitmann** [comment]
We can simplify displaying survey information on the study details page. However you (@UteH, @kpstephan) have to define the survey fields which we can use to aggregate the survey information.

**Comment by UteH** [comment]
I am just adding some further thoughts
## idea 1:
- display surveys according to dataset availability (product)
## this means:

### gsl2008: 
- one dataset with three waves    

  **->  ✔️ one survey page** 

### gra2005/phd2014: 
- two datasets  
  - individual data (wave 1 and 2)
  - episode data (wave 1 and 2)  

  **-> ✅ (better than before**  
  **-> 😒 but this is only a difference in data structure _not_ different survey (as the episode data was conduted in the same survey/instrument as the personal data)**
  **-> :bulb: if so, we should rather display wave 1 and 2 as different surveys than personal and episode data (even though we do not want to offer the waves seperately)**

### slc (just an idea)


### eurostudent (just an idea)
- which way is the dataset available? pooled? by country?
  - each country each wave 

## idea 2:
-

**Comment by UteH** [comment]
I think we can close this issue .... or deassign the persons
