### ISSUE TITLE
attribute 'value' (variables): we need more than two decimal places

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#1228]
Especially for weighting variables:
https://metadata.fdz.dzhw.eu/#!/de/variables/var-phd2014-ds1-wgt_t1t2d$

**Comment by svietgen** [comment]
@AndyDaniel1 FYI

**Comment by dkatzberg** [comment]
@svietgen Let us discuss this issue, please.

**Comment by svietgen** [comment]
@dkatzberg We can discuss this when you are back.
