### ISSUE TITLE
Connect variables that have been derived from each other

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1229]
I think we talked about this several times but I don't remember why we did not do this, so sorry in advance:

I think users will appreciate it if variables that only differ by suffix were conntected, e.g.:
Someone looks at the variable questionnaire and is interested in "1. Qualifikation: Hochschulart" which is bstu09_a, thus not accessible. As users do not (yet) know how the variable suffix works it could be very helpful to display other variables that come from bstu09_a (and are accessible) which are:
- bstu09_g1r	->	1. Qualifikation: Bundesland der Hochschule
- bstu09_g2a	->	1. Qualifikation: Staat einer ausl. Hochschule
- bstu09_g3r	->	1. Qualifikation: Staat einer ausl. Hochschule
- bstu09_g4o	->	1. Qualifikation: Hochschulart
- bstu09_g5r	->	1. Qualifikation: Hochschulart (FH/Uni; ohne Saarland)

Could these be "cross-listed" in all these variables in "related variables"?

**Comment by UteH** [comment]
Karsten pointed out that we have to define what kind of relations can occur and what kind of relations these specific variables have

**Comment by AndyDaniel1** [comment]
I also think that we have to find a more general definition of what should be flagged as related variable. In my view currently the following types occur in our data (feel free to complete the list :-) ):

- panel variables
- semi-panel variables (aka _v-Variables)
- variables as part of item scales
- generated variables
- harmonized variables 

The current DZHW-data has not the complexity level which would cause any problem when assigning these relations (apart from the harmonization over time series, which is currently not in our scope). But in the future the study designs will gain complexity and we will have to find ways to handle it (think about a 10-wave-multi-cohort-study). I think we should have this in mind when we think about data edition functions of the MDM.

**Comment by dkatzberg** [comment]
- [ ]  Define validators (Not Mandatory)
- [ ] Backend (implement issue #724) 
- [ ] Importer Update
- [ ] Interface / Wiki Update
- [ ] Extend related objects
- [ ] Update one data for release
- [ ] Identifier similar to panel variable

**Comment by rreitmann** [comment]
All derived variables are contained in one dataset => Reuse the pattern of panelIdentifier!
