### ISSUE TITLE
study: we want to (try to) synchronize the study detail page with the method report

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1232]
e.g.
[gra2005_Abschnitt_II.pdf](https://github.com/dzhw/metadatamanagement/files/1094641/gra2005_MethodReport_de.1.pdf) with https://metadata.fdz.dzhw.eu/#!/de/studies/stu-gra2005$

- also check if number of waves should be listed #1225 (Karsten pointed out that strictly speaking this information is not a study information)
- maybe list some information that are currently listed at survey detail page #1227
- also keep [quali data](https://metadata.fdz.dzhw.eu/public/files/studies/stu-win2015$/attachments/win2015_ql_MethodReport.pdf) in mind
- also talk to @anneweber regarding https://github.com/dzhw/FDZ_Allgemein/issues/72
- also maybe try indent text or format text as a table? (easier to process) 
  - (maybe also table for other detail pages 🙈 )
![image](https://user-images.githubusercontent.com/18573122/27482537-2cafb830-5822-11e7-86bd-8e69d89171a1.png)

**Comment by UteH** [comment]
@anneweber, @kpstephan and me discussed the synchronization of the methods report with the MDM as a preparation for the **input masks**.

- We want **input masks** of the MDM for these information.
- We want to **save** these synchronized information in the MDM. (What about back up? csv? ask the Versionierungsteam!)
- We want to **export** some of these information for tables in the methods report (as a formatted word document)

**Comment by rreitmann** [comment]
@kpstephan get in touch with @UteH
