### ISSUE TITLE
discount usability test

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1233]
after visualizing already implemented filters (#1199  to #1203) and giving more information on the study page (#1217) a dicscount usability test might give us an impression on how the system is percieved by users

@dkatzberg is experienced in this field

check with Karsten and Andy where resources could be taken from

**Comment by dkatzberg** [comment]
If the filter are finished ( e.g. #1199 and more), it could be a good moment for the usability test

**Comment by rreitmann** [comment]
Duplicates #1830
