### ISSUE TITLE
Rework display of numbers in histogram (or scale level?)

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1239]
I think this was an issue before (did not find an actual issue or wiki explanation) but I do not quite remember the results, so please have mercy ;)

### 1. Decimal places

**example 1: https://metadata.fdz.dzhw.eu/#!/de/variables/var-phd2014-ds1-asys04$**  
  ![image](https://user-images.githubusercontent.com/18573122/27474063-6f2356a2-5801-11e7-814f-fdd9ecdddfd9.png)  
-> should only display integers: 0,1,2

**example 2: https://metadata.fdz.dzhw.eu/#!/de/variables/var-phd2014-ds1-asys03_o$**  
  ![image](https://user-images.githubusercontent.com/18573122/27474435-8366b9dc-5802-11e7-839a-4a30005a7adb.png)
-> should only display integers; no decimal places of year  
-> x and y axis very close (not sure if we can change this?) 

**btw: year in gls2008 is displayed correctly sometimes**
https://metadata.fdz.dzhw.eu/#!/de/variables/var-gsl2008-ds1-adem01_g1$ ->  no decimal places
https://metadata.fdz.dzhw.eu/#!/de/variables/var-gsl2008-ds1-cstu32b_g1$ -> decimal places

### 2. collapse of categories 
https://metadatamanagement-test.cfapps.io/#!/de/variables/var-ssy19-ds1-job04a$
![image](https://user-images.githubusercontent.com/18573122/27485522-5c35d9ee-582d-11e7-9ff1-ea3be55406c9.png)
(-> collapse of categories intended?)   
-> numbers should be integers

### 3. percent and absolute numbers
is it possible to show percent _and_ absolute numbers in the tool tip (?) in a neat way?

**Comment by rreitmann** [comment]
During this Sprint we will analyze the capabilities of plotly regarding displaying only integers.
As a remark: Currently we cannot distinguish between integer and float variables (both have dataType numeric)

**Comment by rreitmann** [comment]
@UteH: Please define which dataTypes instead of numeric you can deliver (e.g. integer, float,...)
@rreitmann: Find out how plotly can be configured by using these dataTypes...

**Comment by UteH** [comment]
### Stata:
- [storage type](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjF_Mvb--rVAhXD2xoKHV6JCN0QFggtMAA&url=http%3A%2F%2Fwww.stata.com%2Fmanuals13%2Fddatatypes.pdf&usg=AFQjCNH9aT5pi477kAtbSrRnVtP-i76Y1Q)
  ![grafik](https://user-images.githubusercontent.com/18573122/29568402-8a441272-8750-11e7-9878-328821e559ab.png)

**Comment by rreitmann** [comment]
We should extent variable.dataType (replacing numeric with the storage type). Additionally we need a flag like variable.doNotDisplayThousandsSeperator which needs to be set manually.

**Comment by dkatzberg** [comment]
- [ ] Add "doNotDisplayThousandsSeperator"
  - [ ] Update Wiki and Domain Modell
  - Information: Validation at import: Mandatory
- [ ] Change dataType with Storage Type
  - [ ] Update DataType Class
  - [ ] Update Wiki
  - Information: No detailed Storage Type. 
  - De=Speichertyp, En=Storage Type

**Comment by rreitmann** [comment]
@kimsommer Please list all available R storage types...

**Comment by kimsommer** [comment]
possible values for storage type in R:
- "logical", "integer", "double", "complex", "character", "raw" and "list", "NULL", "closure" (function), "special" and "builtin" (basic functions and operators), "environment", "S4" (some S4 objects)

unlikely values:
- "symbol", "pairlist", "promise", "language", "char", "...", "any", "expression", "externalptr", "bytecode" and "weakref"

However at the moment we only have "integer" and "double".

**Comment by rreitmann** [comment]
We are currently running into a plotly bug:
plotly/plotly.js#1264

**Comment by rreitmann** [comment]
To sum up the problems mentioned by @UteH:
1. Decimal places: Should be fixed
2. Collapse of categories: Won't fix, is intended
3. percent and absolute numbers: Histograms and Bar charts should display absolute and relative frequencies now

**Comment by UteH** [comment]
Hi  @rreitmann 
not sure if we are talking about the same thing on "2. Collapse of categories"

![grafik](https://user-images.githubusercontent.com/18573122/31887699-a4ebf372-b7f9-11e7-8910-1f5b6e5149ad.png)

**Comment by kimsommer** [comment]
![astu011a_firefox](https://user-images.githubusercontent.com/19772575/32040213-4466941a-ba30-11e7-92bf-ed901984c808.png)
y axis tick labels are very close to the border when the values are large.
