### ISSUE TITLE
problem: Internet Explorer 11

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#1240]
There are several problems (values, labels and histogram) when users are using the Internet Explorer (variable detail page).
For example: https://metadatamanagement-test.cfapps.io/#!/de/variables/var-ssy19-ds1-abr02c$

![grafik](https://user-images.githubusercontent.com/22055122/27546227-7f64f500-5a92-11e7-84f8-48825f1265d8.png)

![grafik](https://user-images.githubusercontent.com/22055122/27546252-953729de-5a92-11e7-85ac-ad7a352769c0.png)

**Comment by rreitmann** [comment]
variable-datatype.filter.js uses String.includes which is not supported by IE (see https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/includes)

We should include a shim like (https://github.com/es-shims/es6-shim) so that all browsers have a similar API...
