### ISSUE TITLE
Display DataSets in order of entry in interface

### ISSUE THREAD

**Issue by fbaillet** [dzhw/metadatamanagement#1241]
#### So far on the study and data set page, data sets are displayed in a random ordner:
1. https://metadata.fdz.dzhw.eu/#!/de/studies/stu-gra2005$ 
2. https://metadata.fdz.dzhw.eu/#!/de/search?page=1&type=data_sets&study=stu-gra2005$

#### Data Sets should be displayed in order of the entry in the interface, as some data sets of one study have a higher priority then others.
 - See f. Ex. project **gra2005** Interface dataSets.xls

**Comment by dkatzberg** [comment]
we need to add an indexInStudy field to data set, depending on the position in the excel document

**Comment by rreitmann** [comment]
We can sort by dataSet.number...
