### ISSUE TITLE
Display Surveys in order of entry in interface

### ISSUE THREAD

**Issue by fbaillet** [dzhw/metadatamanagement#1242]
#### So far on the study and survey page, surveys are displayed in a random order:
1. https://metadata.fdz.dzhw.eu/#!/de/studies/stu-gra2005$ 
2. https://metadata.fdz.dzhw.eu/#!/de/search?page=1&type=surveys

#### Surveys should be displayed in order of the entry in the interface
 - See f. Ex. project **gra2005** Interface Surveys.xls

**Comment by dkatzberg** [comment]
we need to add an indexInStudy field to survey, depending on the position in the excel document

**Comment by rreitmann** [comment]
We can sort by survey.number...
