### ISSUE TITLE
wrong order if i search by variable name

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#1246]
https://metadata.fdz.dzhw.eu/#!/de/search?page=1&type=variables&query=bdem12d&sort-by=indexInDataSet&data-set=dat-phd2014-ds1$

**Comment by rreitmann** [comment]
Currently variable names are matched by our trigram analyzer and I think that we are missing a minimum_should_match of 100% as we do for the _all field...

**Comment by dkatzberg** [comment]
This issue should be fixed with the changes for the issue #1257 . @svietgen please check and test it. :)
