### ISSUE TITLE
study: link studies of the same survey series

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1256]
It might be helpful to link other studies of the same survey series, such as gra2005 and gra2009 -
 something like _relatedStudy_.

I think, we need a seperate page to list the studies as more and more studies of the same survey series will come. 

https://metadata.fdz.dzhw.eu/#!/de/studies/stu-gra2005$

**Comment by UteH** [comment]
I just found this issue #52 which seems kind of similar?

**Comment by rreitmann** [comment]
We will implement a new study filter by surveySeries. The field surveySeries on studyDetails will become a link to all studies filtered by surveySeries sorted by id.
