### ISSUE TITLE
variable search: difficulties when looking for terms that also part of other objects?

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1257]
In [gsl2008](https://metadata.fdz.dzhw.eu/#!/de/studies/stu-gsl2008$) I wanted to extract the "Beruf"-Variablen (@dkatzberg and I had already discussed this with "Hochschule") of the dataset.

Problem: all variables of the dataset are displayed. 

I am not quite sure why this is. I assume this is because other study information contain these words or similar words?

**Comment by rreitmann** [comment]
@dkatzberg Please create a wiki document for collecting search use cases!
