### ISSUE TITLE
Attribute "data type" on survey and study detail page

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#1258]
We need a new attribute which adresses the specific data type that is targeted by the study. On frist glance you might wonder why this is an attribute of study instead of survey. Here you are correct :-) . If we want to model the data type correctly it should be attributed to survey. BUT it is absolutely necessary that we display the information on the study detail page. Thus we should consider to attribute the data type to survey and display the data type on the study detail page according to the information on the survey detail page. Here we have to keep in mind that surveys with diffent data types which are linked to one study should be displayed with "mixed methods" on the study detail page (e.g. survey1==quali; survey2==quanti; study==mixed methods). 

Please note that some studies don't have survey detail pages but must anyway display the data type information on the study detail page. 

The following attributes should be possible: 
- de: Quanitative Daten  en: quantitative data
- de: Qualitative Daten en: qualitative data
- de: Mixed Methods en: mixed methods (only for study)
- ~~~de: Bibliometrische Daten en: bibliometric data~~~

**Comment by dkatzberg** [comment]
@AndyDaniel1 Controll vacabulary on DDI for the data types

**Comment by AndyDaniel1** [comment]
My research concerning controlled vocabulary for data type shows that DDI seems to have no such vocabulary.

Thus I strongly recommend to use a self defined controlled vocabulary as developed above. 

As new data types will be brought to us we should expand this vocabulary, but for now the list above should fit our purposes. 

---

In the course of my research on data type I found this list: http://www.ddialliance.org/Specification/DDI-CV/ModeOfCollection_1.0.html

I think this list fits the attribute survey method. We should compare the controlled vocabulary of this list with our controlled vocabulary for this attribute. --> **new issue?**

**Comment by dkatzberg** [comment]
@AndyDaniel1 Should the field 'datatype' added to study or survey? Because no survey Details page means no uploaded survey object and no datatype field.

**Comment by rreitmann** [comment]
We will add a new field dataType to survey (I18nString either 'quali' or 'quanti'). This will be displayed on the survey details page. On the study details page we will display a string computed from all surveys of the study: 
- 'quanti' if and only if all surveys are 'quanti'
- 'quali' if and only if all surveys are 'quali'
- else 'mixed'

**Comment by rreitmann** [comment]
@dkatzberg I think this solution does not work as the user expects. After a discussion with @svietgen I think that the users want to search studies for "Mixed Methods" :-(
We need to extend StudySearchDoccument with surveyDataType (and numberOfWaves, computed in the constructor) and remove the dynamic computation...
