### ISSUE TITLE
Second instrument in questions was not uploaded with IE(Edge)

### ISSUE THREAD

**Issue by kimsommer** [dzhw/metadatamanagement#1264]
#1048
The second instrument in questions was not uploaded, whereas it worked in other browsers. The first instrument was uploaded without any problems. 

•	Die Datei "1.2.json" in Instrument "ins2" konnte nicht gelesen werden! 
•	Die Datei "1.3.json" in Instrument "ins2" konnte nicht gelesen werden! 
•	Die Datei "1.4.json" in Instrument "ins2" konnte nicht gelesen werden!

**Comment by rreitmann** [comment]
Data Uploads are currently not supported within IE 11 and Edge cause these browsers do not support directory uploads...
