### ISSUE TITLE
Feedback via Email

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#1265]
As discussed in [Sprint Retro 49](https://github.com/dzhw/metadatamanagement/wiki/Sprint-History#Sprint_49) we need to implement a feedback channel via email which enable the users of our MDM to give a quick and "register free" feedback. 

The e-mail feedback will be put in issues by the Sowi-Team. The user will be notified that the further discussion concering the feedback will be held in the issue. It's then on the user to choose wheater she/he will register at GitHub to participate in the discussion. 

We disussed this topic thoroughly and came to the conclusion that this is the best way to get optimal feedback. This is still true if we take the amount of ressources into account which are needed to translate the emails into issues.

A further advantage of this apporach is the possibility to check for duplicates before the issue is entered into GitHub.

**Comment by dkatzberg** [comment]
- [ ] Link in sidebar call the same feedback dialog at the application start 
- [ ] Extend feedback dialog
- [ ] Make a new mail adress (fdz.feedback@dzhw.eu)
