### ISSUE TITLE
click through previously searched variables

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1266]
after #1180 it might be helpful to be able to click through variables you searched for previously.   
e.g. I was looking for "Eltern" and want to click only through "Eltern"-variables, not all variables of a dataset.
not sure if we need this as you can also use the browser's "back" button

**Comment by kpstephan** [comment]
a small paginator with information cencerning the position in list would bee cool, e.g.:
|<  <   23/223  >  >|
Maybe the "first element" and "last element" button are to big for mobile devices
