### ISSUE TITLE
Change sorting on question tab if queryterm is given

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#1267]
Actually, the sorting is based on the indexInInstrument. If there is a query term, the searching should be based on the score and not on the indexInInstrument.

**Comment by svietgen** [comment]
@dkatzberg I tried to test this issue but there is something wrong with our testsystem: 
![grafik](https://user-images.githubusercontent.com/22055122/28627446-215b84d6-7222-11e7-9d2d-2ea0338159b8.png)
