### ISSUE TITLE
rename 'IndexInInstrument' to 'IndexInStudy'

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#1268]

**Comment by dkatzberg** [comment]
We have to migrate the MongoDB and update the field name by the rename pattern here:
https://gist.github.com/guyellis/9948091

Or a specific example:
https://stackoverflow.com/questions/9254351/how-can-i-rename-a-field-for-all-documents-in-mongodb

**Comment by dkatzberg** [comment]
We are using this command in MongoDB, before reindex:

`db.getCollection('questions').update({}, {$rename:{"indexInInstrument":"indexInStudy"}}, false, true);`

**Comment by svietgen** [comment]
@kimsommer FYI

**Comment by svietgen** [comment]
I tried to test this issue but there is a problem with our testsystem
https://github.com/dzhw/metadatamanagement/issues/1267#issuecomment-318076517
