### ISSUE TITLE
Internet Explorer 11: DZHW-logo shrinks when I open the sidebar

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#1280]
And there is a larger gap between the DZHW-logo and the BMBF-logo (compared to Chrome, Firefox and Edge)
![sidebar](https://user-images.githubusercontent.com/22055122/28356590-eebd2dae-6c68-11e7-84a5-f1b87ddb424d.jpg)

**Comment by dkatzberg** [comment]
https://gist.github.com/larrybotha/7881691
This is one part of the solution. 

The second of the shrinking based on the column layout of the div tag.
