### ISSUE TITLE
Wrong related Question

### ISSUE THREAD

**Issue by fbaillet** [dzhw/metadatamanagement#1314]
---------------------------------
Quelle:
https://metadata.fdz.dzhw.eu/#!/de/variables/var-gra2009-ds1-afec09f$
---------------------------------
@svietgen I think there is a mistake with the related question to variable afec09f (survey gra2009), if you go from the variablepage to the question, the following picture is displayed:

https://metadata.fdz.dzhw.eu/#!/de/questions/que-gra2009-ins1-3.3$

Although the related question is:

![grafik](https://user-images.githubusercontent.com/18573349/29914173-da7fce0a-8e37-11e7-9842-c9201c09d07b.png)

--> "Bezug zu Inhalten des Studiums"

@svietgen could you please look into this?

Thx :bowtie:

**Comment by fbaillet** [comment]
Here seems to be a similar problem https://metadata.fdz.dzhw.eu/#!/de/variables/var-gra2009-ds1-aocc23b$

**Comment by svietgen** [comment]
@fbaillet Is it possible that the variable label of afec09f is wrong/inaccurate (Bezug erstes Studium --> Bezug erste Studienphase)?

**Comment by fbaillet** [comment]
Erledigt
