### ISSUE TITLE
Use automatic hyphenation

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1315]
We could use automatic hyphenation:
https://github.com/mnater/Hyphenopoly

**Comment by svietgen** [comment]
When I use the Internet Explorer I get the following image headline:

![grafik](https://user-images.githubusercontent.com/22055122/30328364-6a2672d4-97cf-11e7-9bb0-87e945f45d72.png)

**Comment by rreitmann** [comment]
@svietgen Fixed, but in #1277. So we have to wait until Daniel has reviewed this...
