### ISSUE TITLE
Specify DOI requirements

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1316]
Define what we need and want to do.

**Comment by rreitmann** [comment]
In future we want to register DOIs for studies and subDataSets at DARA. The studies will use semantic versioning (major.minor.patch e.g. 1.0.1) which will be concretely defined by @svietgen. The dataSets of a study and its subDataSets shall get sub(-sub)-DOIs of the study DOI. The study DOI shall contain the version number. The landing page for studies will be the study details page and for dataSets and subDataSets it will be the dataSet details page. For each DOI we want to register our landing page with the version as URL param (e.g. https://metadata.fdz.dzhw.eu/#!/de/studies/stu-phd2014$?version=1.0.1). Our pages will compare the version in the url to the currently displayed one and tell the user if there are major changes, minor changes or just patch changes. There shall also be a link to the release notes which will be maintained in public GitHub repositories per dataAcquisitionProject (e.g. https://github.com/dzhw/gra2005). These repository names have to match the project name exactly.

**Comment by rreitmann** [comment]
@UteH Please provide details on what needs to be changed in the documentation...

**Comment by UteH** [comment]
After a brief discussion we came to the conclusion that this has major effects on the data curation/documentatian and on the data distrubution processes that need to be discussed.

We decided that @svietgen and @fbaillet (@anneweber) will be mostly in charge of evaluation the effects on the
- data curation and documentation
- data distribution / user notification processes

We planned to discuss this in October/November (reminder is on 9th October)
