### ISSUE TITLE
Visualize sort criterias

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1317]
Currently we sort search result by fields when the user comes from a details page. We should show the sort criterias and/or make them editable. Another idea is to set sort-criteria depending on filters.

**Comment by rreitmann** [comment]
@svietgen: Define a list of implicit sort criterias resulting of chosen filters.

**Comment by svietgen** [comment]
| | no filter, search input | filter (no matter which), search input | no filter, no search input
| --- | --- | --- | --- |
| **studies** | scoring | scoring | alphabetically (study-id)
| **surveys** | scoring | scoring | study + survey number
| **instruments** | scoring | scoring | study + instrument number
| **questions** | scoring | scoring | study + instrument number + index in instrument
| **data sets** | scoring | scoring | study + data set number
| **variables** | scoring | scoring | study + data set + variable index
| **publications** | scoring | scoring | year (newest to oldest) + alphabetically within year

**filter, no search input**

**studies**
studies filtered by survey series: sort alphabetically (study-id)
studies filtered by survey: sort alphabetically (study-id)
studies filtered by instrument: sort alphabetically (study-id)
studies filtered by question: sort alphabetically (study-id)
studies filtered by data set: sort alphabetically (study-id)
studies filtered by variable: sort alphabetically (study-id)
studies filtered by publication: sort alphabetically (study-id)

**surveys**
surveys filtered by survey series: sort by study + survey number
surveys filtered by study: sort by survey number 
surveys filtered by instrument: sort by survey number 
surveys filtered by questions: sort by survey number 
surveys filtered by dataSets: sort by survey number 
surveys filtered by variables: sort by  survey number 
surveys filtered by publications: sort by study + survey number

**instruments**
instruments filtered by survey series: sort by study + instrument number
instruments filtered by study: sort by instrument number 
instruments filtered by survey: sort by instrument number 
instruments filtered by question: sort by instrument number 
instruments filtered by data set: sort by instrument number 
instruments filtered by variable: sort by instrument number 
instruments filtered by pubilcation: sort by study + instrument number

**questions**
questions filtered by survey series: sort by study + instrument number + question number
questions filtered by study: sort by instrument number + question number
questions filtered by survey: sort by instrument number + question number
questions filtered by instrument: sort by question number
questions filtered by data set: sort by instrument number + question number
questions filtered by variable: sort by instrument number + question number
questions filtered by publication: sort by study + instrument number + question number
previous questions: sort by index in instrument
subsuquent questions: sort by index in instrument

**data sets**
data sets filtered by:
data sets filtered by:
data sets filtered by:
data sets filtered by:
data sets filtered by:


**variables**

**publications**

**Comment by dkatzberg** [comment]
@svietgen and me had a discussion to simplify the rules for the case: "filter and no search input" There is only one rule for every domain object in this case.
We are using just the rule with the most filter. E.g.: sort by study + data set number for DataSet. If a study is chosen, the study filter is set by default.

@rreitmann , @kimsommer We have to discuss about the case of the sorting rule for publications.
We need the title for an alphabetical sorting within a year. The title is an elasticsearch text type at the moment (have a look into the mapping.json).  Elasticsearch supports only alphabeticlal sorting, if a string field is an keyword field. What should we do?

**Comment by svietgen** [comment]
@dkatzberg I think that we need the author (which is also part of the id) for an alphabetical sorting within a year.

**Comment by rreitmann** [comment]
To summarize: The sorting rules can be simplified to the following table

| domain object | sort-criteria |
| --- | --- |
| **studies** | scoring + alphabetically (study-id) |
| **surveys** | scoring + study + survey number |
| **instruments** | scoring + study + instrument number |
| **questions** | scoring + study + instrument number + index in instrument |
| **data sets** | scoring + study + data set number |
| **variables** | scoring + study + data set + variable index |
| **publications** | scoring + year (newest to oldest) + alphabetically within year |

**Comment by rreitmann** [comment]
@dkatzberg: Here are a few remarks (see 5bb3e2c as well):
- in turned out the sort criteria are independent of query and filters :-)
- you have changed elasticsearch mappings but have not increased version in indices_version.json
