### ISSUE TITLE
Request of Change: Instrumentpage

### ISSUE THREAD

**Issue by fbaillet** [dzhw/metadatamanagement#1319]
As discussed in todays meeting with @kpstephan @AndyDaniel1 @svietgen @anneweber the card **Materialien zum Instrument** has a redundant column. The column **"Titel** is not needed [see f. ex](https://metadata.fdz.dzhw.eu/#!/de/instruments/ins-gra2009-ins1$). Would it be possible to delet this column?

**Comment by rreitmann** [comment]
@svietgen I will deploy this to the test system after we have deployed and tested the hotfix..
