### ISSUE TITLE
rework freemarker interface for dataset report generation

### ISSUE THREAD

**Issue by kpstephan** [dzhw/metadatamanagement#1323]
1. We need to access the title of the instrument, which is related to the variable within a freemarker  template.
2. On Freemaker level firstTenValidResponses[ ] and lastTenValidResponses[ ] didn't contain the last element 
3. is it possible to get the mode on freemarker level?

**Comment by rreitmann** [comment]
@dkatzberg have a look on commit ac8027da0831785aadb78a7971791e88076faa0a your fix for first ten and last ten was not working!
