### ISSUE TITLE
Filter: please correct error messages

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#1327]
Instrument filter: "**Keine** gültiges Instrument ausgewählt" to "Kein gültiges Instrument ausgewählt"
DataSet Filter: "No data set selected" to "No **valid** data set selected"
Variable Filer: "Keine gültige Erhebung ausgewählt" to "Keine gültige **Variable** ausgewählt" and the same in english "No valid survey selected" to "No valid **variable** selected"

Sorry that I didn't find these while testing the filter issues.

**Comment by rreitmann** [comment]
Fixed
