### ISSUE TITLE
Change texts in the filter search boxes

### ISSUE THREAD

**Issue by anneweber** [dzhw/metadatamanagement#1338]
If possible please change the texts in the filter search boxes as shown in the pictures below. :tulip:

![image](https://user-images.githubusercontent.com/17066262/30629053-1482c0ec-9dda-11e7-832e-07fb64ec9655.png)

![image](https://user-images.githubusercontent.com/17066262/30629061-1a6b86a6-9dda-11e7-95c2-17fc46d82994.png)

**Comment by dkatzberg** [comment]
@rreitmann changes are in development.

**Comment by rreitmann** [comment]
@dkatzberg:
- For instance the term "Erhebungsfilter" in the md-select shall be "Erhebungen"
- You have to apply the changes to the survey series filter as well (already merged into development)

**Comment by annegaertner** [comment]
Is it possible to change all the filters to singular like "Datensatz" oder "Instrument"? 

Anne W. had this idea when I mentioned the problem of plural words following the introduction "Filtern nach...". Therefore the plural always needs an "n" at the end like "Datensätzen" oder "Instrumenten" which appears a bit unpleasant. 
Thanks!

**Comment by svietgen** [comment]
My three commits: 372c1fd0cc20ac0a3aabde10850bf9f0fa7a2439
9ca8b950662d667d2710c4c90a6f5b1626dd8be6
247f4edbdded89535cf7d5f87d7f993bece92957
