### ISSUE TITLE
Links auf metadata.fdz.dzhw.eu Website

### ISSUE THREAD

**Issue by schellep** [dzhw/metadatamanagement#1339]
@AndyDaniel1 und @anneweber haben mich ermutigt, meine Idee/Anmerkung als Issue zu formulieren: 
1.  Wir wollen mit Daniel über Vor- und Nachteile von rdc.dzhw.eu als englische Adresse des FDZ reden (statt https://fdz.dzhw.eu/en/): Ist es möglich eine Seite metadata.rdc.dzhw.eu als Ersatz (o. Umleitung) für https://metadata.fdz.dzhw.eu/#!/en/ einzurichten? Letzteres ist auf Flyern und Plakaten etwas sperrig.
1.  Auf unserer [Metadaten-Suchseite](https://metadata.fdz.dzhw.eu/#!/de/search?page=1&type=studies) ist oben links das FDZ Logo mit einem Link hinterlegt. Dieser führt aber nicht, wie zumindest ich erwarte, auf die [FDZ-Seite](https://fdz.dzhw.eu/index_html) (zurück) sondern auf "Suche" (innerhalb) des der [Metadatensuche](https://metadata.fdz.dzhw.eu/#!/de/search)
(Ute: when discussing this issue: could we use a fdz-logo with description (I think only in the disclosure,  the mdm-website says "Forschungsdatenzentrum/Research Data Centre")
1. weniger wichtig und vielleicht meine Gewohnheit (sind die die [Suchfelder](https://metadata.fdz.dzhw.eu/#!/de/search) verändert worden?), ich habe versucht in den blauen Balken für die Suche zu tippen 

Cheers Percy

**Comment by rreitmann** [comment]
according to 1: We won't support multiple domains (fdz.dzhw.eu  and rdc.dzhw.eu) but we can redirect the user to her preferred language (depending on browser settings) when she visits https://metadata.fdz.dzhw.eu 
This way you need just one URL on all flyers.
according to 2: We prefer to replace the DZHW logo with the current fdz.DZHW logo and link to the fdz pages. Furthermore we want to replace the top logo with a new app logo.
according to 3: We will remove the magnifier icon from the toolbar when you are on the search site.

@schellep Feel free to comment :)
