### ISSUE TITLE
Make toolbar disappear when scrolling down 

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1344]
On mobile screens we currently display the browser bar and our toolbar even when the user scrolls down.
IMHO toolbar and browser bar should disappear but search criterias should stay. See
https://material.angularjs.org/latest/api/service/$mdSticky
https://material.angularjs.org/latest/demo/subheader
https://material.angularjs.org/latest/demo/toolbar#scroll-shrink

**Comment by rreitmann** [comment]
Hiding the browser bar when scrolling down does not work due to md-content. Scroll shrink does not work on the search page cause the height of md-content changes dynamically. Thus we for now we cannot do anything here :-(

**Comment by rreitmann** [comment]
We are now using fixed positioned navbar and toolbar. Which has the effect that the browser bar can disappear :-)

**Comment by svietgen** [comment]
When I use Chrome the toolbar does not disappear while scrolling down.
When I use Firefox the toolbar disappears while scrolling down and appears when I reach the end of the site or when I scroll up.
When I use Samsung Internet the toolbar disappears while scrolling down and appears when I scroll up.
