### ISSUE TITLE
discuss: FilterDescription without FilterExpression(Language)?

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#1349]
Should it be possible to specifiy a FilterDescription without a FilterExpression/FilterExpressionLanguage?

https://github.com/dzhw/abs2009/issues/76#issuecomment-332099757

@anneweber FYI

**Comment by rreitmann** [comment]
Of course it is possible to allow filterDetails without expression and expressionLanguage. But do you reall whant this? @kpstephan we need a decision

**Comment by rreitmann** [comment]
After a short discussion with @anneweber, we will allow filterDetails without expression and expressionLanguage..

**Comment by rreitmann** [comment]
To be more precise: We will allow empty expression **and** expressionLanguage. If one is present the other must be as well.
