### ISSUE TITLE
Spell Data - Cases

### ISSUE THREAD

**Issue by fbaillet** [dzhw/metadatamanagement#1350]
---------------------------------
Quelle:
https://metadata.fdz.dzhw.eu/#!/de/data-sets/dat-gra2005-ds2$
---------------------------------

I was wondering if it could be confusing, that if we have spell data the number of **cases** instead of number of **episodes** is given. Maybe you could discuss that? Thanks in advance!

![grafik](https://user-images.githubusercontent.com/18573349/30921925-fbab6f50-a3a7-11e7-959c-80ff9ef42c5c.png)

**Comment by rreitmann** [comment]
We will change the heading in the table column from "Fälle" to "Episoden" if and only if dataSet.type is "Spell Data". @fbaillet ok?

**Comment by fbaillet** [comment]
@rreitmann this would be perfect! Thx

**Comment by schellep** [comment]
Today I couldn't anwer [Christian Brzinsky-Fay](https://www.wzb.eu/de/personen/christian-brzinsky-fay) [the teacher](https://github.com/dzhw/Effizienzprojekt_Modul_E_F_G/issues/56) for the [user training](https://github.com/dzhw/Effizienzprojekt_Modul_E_F_G/issues/11) (which @annegaertner and @schellep are organizing)  the number of Cases in the CUF of the Spell-Data-Set. Maybe we should care of this usecase.

**Comment by rreitmann** [comment]
@schellep Please open a new issue for your point. This issue was about renaming cases to episodes for spell data sets. This was already implemented...
