### ISSUE TITLE
location of protocol field 

### ISSUE THREAD

**Issue by kimsommer** [dzhw/metadatamanagement#1356]
Protocol field appears under search cards and only when browser window is small (tested in chrome, firefox).

![protocol](https://user-images.githubusercontent.com/19772575/31078165-5aac6ca2-a781-11e7-8357-a3dbbc4f9cf7.png)

**Comment by dkatzberg** [comment]
Commit: 7864ee3d34125ee8078c6df75a52c2f708625307
