### ISSUE TITLE
Instrument/Attachments: change max length of attribute description?

### ISSUE THREAD

**Issue by anneweber** [dzhw/metadatamanagement#1358]
The description

> Hoch­schu­len nach De­sta­tis-Schlüs­sel­ver­zeich­nis für die Stu­den­ten- und Prü­fungs­sta­tis­tik (WiSe 2014/2015 und SoSe 2015), **Schlüssel 2.2**

for the coding scheme cl-destatis-hochschule-2015 is too long.

--> https://metadatamanagement-test.cfapps.io/#!/de/instruments/ins-gra2009-ins1$

Is it possible to change the max length?

**Comment by rreitmann** [comment]
We will change MEDIUM to 512 characters...

**Comment by rbirkelbach** [comment]
Error message wrong when uploading dataset & the description.de field is longer than 512, there's an error message: "(Error) Dataset with RDC-ID dat-beispielprojekt-ds2$ has not been saved!

  * The max length of the Name of the 1. Sub Data Set is 32 signs.
(Information) Finished upload of 3 Data Sets and 0 Attachments with 0 warnings and 1 errors."

**Comment by rreitmann** [comment]
@kimsommer and @rbirkelbach: Please be more precise, and provide the test which u have used. Generally this seems to be ok: The DataSet could not be uploaded which is why you do not get a validation error for the attachment metadata...
