### ISSUE TITLE
Update Dara to 4.0

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#1360]
We have to update the interface of dara from version 3.1 to 4.0 until the first of december.

- [x] Update to dara 4.0
- [x] Change behavior of avaibility
- [x] Update Wiki

**Comment by dkatzberg** [comment]
@rreitmann This issue is still in development until the Release of 4.0. This state works with the actual beta (Version from the 18.10.2017). You have to change your local key for the dara test server adresse. I will send you the new test server adresse with a mail.

**Comment by rreitmann** [comment]
@dkatzberg: Looks good so far. Please keep the branch in sync with development regularly...

**Comment by dkatzberg** [comment]
I will keep the branch in sync until the release of Dara 4.0 on 01. December.
