### ISSUE TITLE
study: how often was methods report downloaded

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1361]
the project team of phd2014 asked if we have information about how often the methods report was downloaded.

we should discuss the priority of this issue

**Comment by UteH** [comment]
@schellep [mentioned](https://github.com/dzhw/FDZ_Allgemein/blob/master/01_Organisatorisches/Protokolle/1_Jour_Fixe_FDZ/2018-01-04_Jour_Fixe_FDZ_Protokoll.md#sonstiges) that we might also need this information for VG Wort

**Comment by schellep** [comment]
hi @UteH, i opened for the same use the following issue https://github.com/dzhw/metadatamanagement/issues/1490#issuecomment-357179423 and we discussed it on thursdays 12th of januara refinement. cheers 2 hangover

**Comment by schellep** [comment]
https://github.com/dzhw/metadatamanagement/issues/1490

**Comment by rreitmann** [comment]
duplicates #1490
