### ISSUE TITLE
study/survey: rework display of information

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1368]
We have discussed this before. I'd really recommend a rework of the information we want to display on the study detail page 

# surveys

### [gra2009](https://metadatamanagement.cfapps.io/#!/de/studies/stu-gra2009$)

I am familiar the structure of gra2009 but I am confused when I look at "Verfügbare Daten" on the study detail page.

I am a little confused b/c of "erhoben in". 
I know there are two datasets with 4 access ways each (but it is not the four listed in "erhoben in").
![grafik](https://user-images.githubusercontent.com/18573122/31654446-5fe172fc-b326-11e7-8227-3ea1c71a3ccc.png)
https://github.com/dzhw/metadatamanagement/issues/1227

As we discussed before - everything is correct (!) but I am not sure if these information are useful or confusing for the users.

# attachments
show e.g. instruments on study page, not only on survey pages (e.g. gsl2008)

**Comment by UteH** [comment]
I think this would be very helpful for the users to show _some_ of the attachments also on the study page! 

my suggestion:

| attachment                                                      | show on study page |
|-----------------------------------------------------------------|:--------------------:|
| study &gt; attachments &gt; MethodReport                        |         yes        |
| instruments &gt; attachments &gt; Fragebogen                    |         yes        |
| instruments &gt; attachments &gt; Filterführungsdiagramm        |         no         |
| instruments &gt; attachments &gt; Variablenfragebogen           |         no         |
| surveys &gt; attachments &gt; Responserate.svg                  |         no         |
| dataSets &gt; attachments &gt; DataSetReport                    |         no         |
| instruments &gt; attachments &gt; Sonstige (z. B. Codierlsiten) |         no         |
| study &gt; attachments &gt; Overview_en                         |         yes        |

--> add only Fragebogen

feel free to comment on the selection of attachments

**Comment by rreitmann** [comment]
We will replace "Erhoben in" with "Enthält Daten aus diesen Erhebungen:"
