### ISSUE TITLE
Remove requirement of relatedQuestion.relatedQuestionStrings

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1371]
Creating the question string which belongs to the variable (including the correct answer option) is cumbersome. We could generate this string from all strings of the relatedQuestion...

**Comment by UteH** [comment]
external users can not provide these information. Can they just leave out these information and only provide the question text?

I think often, these information is also stored in the variable label, e.g. Item "fachliche Qualität der Betreuung"
```
"label" : {
		"de" : "Erfahrungen 2. Ausbildungsphase: fachliche Qualität der Betreuung",
		"en" : "experiences 2nd training phase: quality of acad. support"
	},
	"relatedQuestions" : [
		{
			"instrumentNumber" : 1,
			"questionNumber" : "3.3",
			"relatedQuestionStrings" : {
"de" : "Welche Erfahrungen haben Sie (bisher) in  Ihrer Ausbildungs- bzw. Praktikumsphase gemacht?\nFachliche Qualität der Betreuung",
```

**Comment by rreitmann** [comment]
We can make `relatedQuestionStrings` optional. If it is empty we copy `question.questionText` attribute for the search.

**Comment by UteH** [comment]
we need this information for further issues such as Skalenhandbuch.

**Comment by UteH** [comment]
@AndyDaniel1 
I would like to discuss the prio again. We are currently preparing several paper and pencil studies (ssy18, gsl2012, gsl2015) for which this workaround would be very helpful.

**Comment by rreitmann** [comment]
At the moment we think that the field is important and has to be used in the data set report. We cannot generate it automatically...
