### ISSUE TITLE
Input masks for MDM

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1407]
we want to have input masks for several information of the `study`, `survey `and `datasets `(maybe `instruments`)

- We want **input masks** of the MDM for these information.
- We want to **change some strings** b/c of the synchronization #1232 
- We want to **save** these synchronized information in the MDM. (What about back up? csv? ask the Versionierungsteam!)
- We want to **export** some of these information for tables in the methods report (as a formatted word document)
  - idea 1: save-as-docx-Button 💾  for those attributes that should be in the table (update table in report manually!)
  - idea 2: drag word-doc with freemarker in mdm -> generate table ✨ (update table in report manually!)

**Comment by UteH** [comment]
first try in #1416 for `study`

**Comment by rreitmann** [comment]
Will be covered in more detailed issues...
