### ISSUE TITLE
Improve Zofar export of MDM questions

### ISSUE THREAD

**Issue by kpstephan** [dzhw/metadatamanagement#1412]
- [ ] Try to import Zofar questions to MDM
- [ ] ... if it is not possible, give @dzhwmeisner Feedback
- [ ] Check the values of the questions for correctness

**Comment by rbirkelbach** [comment]
@rreitmann @AndyDaniel1 I think this would be a good candidate for the next sprint. question-image jsons are still not valid and contain irrelevant stuff. Not sure about question-jsons.

**Comment by AndyDaniel1** [comment]
You're completly right in stressing the importance of this topic. If you hadn't prioised this issue with 1 I would've done it. Still I need an update on the zofar import topic in general.

**Comment by UteH** [comment]
@rreitmann fyi our feedback for the zofar question export of gra2005.3 https://github.com/dzhw/zofar/issues/143#issuecomment-482171084

**Comment by rreitmann** [comment]
@UteH Have you informed Zofar about the requirements in my previous comment?

**Comment by UteH** [comment]
@rreitmann 
No. As I recall, we had agreed to just list the problems but not investigate further (yet).

I can provide the most current export for nacaps2018.2. You are welcome to review it an give me the most currenct version of your requirements. I can then ask zofar about it as we will be in contact soon.

(However, I will get in touch regarding https://github.com/dzhw/metadatamanagement/issues/2606 as we discussed)

**Comment by rreitmann** [comment]
@UteH I had a quick look on the Nacaps export. I have updated my https://github.com/dzhw/metadatamanagement/issues/1412#issuecomment-511739404. The current issues are all mitigated by converting the zofar export to the handcrafted one. IMHO there will always be the need for manually correcting the zofar export (at least due to conceptIds) and therefore there is no need to fix this on the Zofar side.

**Comment by UteH** [comment]
@rreitmann thanks for the quick review. So I could ask them to omit/change the remaining attributes mentioned above (but we do not depend on it)

**Comment by rreitmann** [comment]
@UteH if they change the `resolution` we would need to change `questionMetadataPreparation`. It is a minor change but we would need to know when they change it...
