### ISSUE TITLE
Extent interface for multiple question views for multiple (mobile) devices

### ISSUE THREAD

**Issue by kpstephan** [dzhw/metadatamanagement#1414]
at minimum we should provide mobile phone landscape view and dektop monitor view

**Comment by dkatzberg** [comment]
The idea is to add multiple images, generated by different screen resolutions depending on the language.
All changes in this issue are just for the interface. This issue includes no implementation.
- [ ] Extend Domain Model for Questions
- [ ] Add MetadataQuestionImageAttachment
- [ ] Support upload for many images for one question
