### ISSUE TITLE
Rework number of decimal places of values

### ISSUE THREAD

**Issue by kimsommer** [dzhw/metadatamanagement#1421]
- Not enough decimal places are shown for weight variables:
https://metadatamanagement-test.cfapps.io/#!/en/variables/var-gra2005-ds1-wgt_t1d$?search-result-index=1
- For example school grades only need zero or one decimal place:
https://metadatamanagement-test.cfapps.io/#!/en/variables/var-gra2005-ds1-astu03c$?search-result-index=1
- Integer variables which were wrongly stored as float in stata datasets have zero decimal places:
https://metadatamanagement-test.cfapps.io/#!/en/variables/var-gra2005-ds4-end_y$?search-result-index=2

**Comment by svietgen** [comment]
#1228

**Comment by svietgen** [comment]
You can close #1228 too when you close this issue.

**Comment by kimsommer** [comment]
During testing I found two things:
- Internet Explorer 11 hides objects on the right side (orange search button) under scroll bar
- plotly: large values on the y-axis are still cut --> https://metadatamanagement-test.cfapps.io/#!/de/variables/var-gra2005-ds2-begin_y$?search-result-index=1
