### ISSUE TITLE
change variables import

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1424]
external projects will not use our sheme for variable names. Thus, we have to provide a more generic interface. We can not expect to get metadata out of their variable names.
we have to make additional columns and use these instead of the variable names
- `wave` (actually: survey?)
- `accessWays`   (change string to separate columns )

**Comment by rreitmann** [comment]
As far as we understood we just need to remove parsing of the variable name from @kimsommer's R-script. The MDM does not parse and will never do the variable name.
