### ISSUE TITLE
Optimize registration mails for Admins

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#1425]
- [ ] Rewrite the information mail, if an user has registered to a MDM System (like dev, test and so on) 
- [ ] Add some more information to the information/register mail for admins

**Comment by kimsommer** [comment]
Somehow the mailto link does not work in my Outlook Desktop Client. Instead of a new mail, my Chrome Browser opens. In webmail.trustedcloud.it the link works fine.

**Comment by rreitmann** [comment]
Opening mailto urls with the correct program is a windows configuration problem see here for instance:
https://www.credera.com/blog/type/article/associating-mailto-links-with-outlook-in-windows-7-through-group-policy/
