### ISSUE TITLE
Upgrade and migrate data to Elasticsearch 2.1 

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#143]
Elasticseach 2.1 is the default version at searchly. Update all depended version whichs supports elasticsearch 2.1 and migrate the data to the new elasticsearch standard.

(Pom.xml)
* Upgrade Jest >=2.0.0
* Elasticsearch 2.1

Update:
* Mapping
* Data (if needed)
* Some workarounds which are no longer supported by Elasticsearch >=2.0

**Comment by rreitmann** [comment]
Don't forget the browser client!
