### ISSUE TITLE
Don't show the field "panel variables" when there is no panel identifier

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#1430]
I got the feedback that the information "Panel Variables: Not available!"/"Panelvariablen: Nicht vorhanden!" is misleading when there are panel variables but we don't add the panel identifier (for example when we have external projects without the prepared information which variables are panel variables).

Can we hide the field "panel variables" when there is no panel identifier?

e.g. https://metadata.fdz.dzhw.eu/#!/de/variables/var-phd2014-ds1-aphd031_g3$?search-result-index=11

**Comment by UteH** [comment]
I agree. Can we make this issue more generic?

e.g. winbus
![grafik](https://user-images.githubusercontent.com/18573122/32838821-85daf50c-ca12-11e7-9464-94ee56f8548c.png)
winbus does not have variables/instruments/questions at all. 

Can we hide this object if "Nicht vorhanden!"?

**Comment by svietgen** [comment]
@kpstephan

**Comment by rreitmann** [comment]
We will hide "panel variables" and "derived variables" if there is no panel identifier/derived variables identifier. Furthermore we will replace "Nicht vorhanden" with "Nicht erfasst" (see related publications).

**Comment by svietgen** [comment]
When we hide "panel variables" if there is no panel identifier I wouldn't replace "Nicht vorhanden" with "Nicht erfasst" because then we have panel variables and when there is no panel identifier it means that there are no panel variables ("Nicht vorhanden").

The same applies to derived variables.

**Comment by rreitmann** [comment]
Ok, we will keep "Nicht vorhanden" for derived variables/panel variables if there is an identifier but no other variables could be found. We will replace "Nicht vorhanden" with "Nicht erfasst" for links to other domain objects (see @UteH's  https://github.com/dzhw/metadatamanagement/issues/1430#issuecomment-344595192)

**Comment by kimsommer** [comment]
- Is it ok correct that "Question" is hidden and does not have the text "Nicht vorhanden"?
https://metadatamanagement-test.cfapps.io/#!/de/variables/var-gra2005-ds1-pid$?search-result-index=1
- How do I get the text "Nicht vorhanden" for panel variables? 
When one variable has a valid panel identifier but no other variables with the same identifer exist in the data set, the identifier is shown when I filter by panel identifier but the link "PanelIdentifier" is hidden
https://metadatamanagement-test.cfapps.io/#!/de/search?page=1&type=variables&study=stu-ssy19$&panel-identifier=ssy19-ds1-abr02a
- Same for derived variables + Why is the derivedVariablesIdentifier "ssy19-ds1-hallo" not in the dropdown menu when I filter by derivedVariablesIdentifier but I can go to the identifier via the variable page 
https://metadatamanagement-test.cfapps.io/#!/de/search?page=1&type=variables&data-set=dat-ssy19-ds1$&derived-variables-identifier=ssy19-ds1-hallo&study=stu-ssy19$

**Comment by rreitmann** [comment]
Regarding your findings:
- I have updated my comment above regarding related questions of variables
- "Nicht vorhanden" should be shown for panelIdentifier and derivedVariablesIdentifier now
- for the filter I have filed #1569
