### ISSUE TITLE
survey-prefix for dara-export

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1431]
At the momemt we can only list information about several surveys of a study which is not intuitive for users. we could add a "prefix" for survey information to give more information on which survey the information is about.

- before: 
![grafik](https://user-images.githubusercontent.com/18573122/32848383-a324cc36-ca2c-11e7-8106-881159893f86.png)
- after: 
![grafik](https://user-images.githubusercontent.com/18573122/32848654-4a2e6fb4-ca2d-11e7-83dc-876ca248b7ae.png)

to do Sowis:
- we need to "trim" the survey titles  
e.g. from "DZHW-Absolventenpanel 2009 - erste Welle" to "1. Welle"
-----------------------
We could also use this export for a table (chapter II) in the **methods report** 📖 🤓 
![grafik](https://user-images.githubusercontent.com/18573122/32842970-d43a32f6-ca1e-11e7-9fa5-639e7f51229b.png)
![grafik](https://user-images.githubusercontent.com/18573122/32843010-efc40a24-ca1e-11e7-9819-e50d5877ddc4.png)

**Comment by rreitmann** [comment]
We will extend the domain model: population becomes population.title and population.description. To dara we will export the survey.wave + population.title in collection mode and temporalCoverage ...

**Comment by rreitmann** [comment]
@dkatzberg: Send an email if automatic dara update fails (see TODO in the code)

**Comment by rreitmann** [comment]
@kimsommer you have to test at least
- reimport surveys (before you do anything else, this issue)
- release/unrelease and check what gets written to the dara test system (for all projects)
- automatic update of study at dara when related publications change
- check all fields at dara

**Comment by rreitmann** [comment]
@dkatzberg I had to change a couple of things during review. Have a look here a362bc5

**Comment by kimsommer** [comment]
- entries in Temporal Coverage and Collection Mode are not sorted by surveyNumber: (gra2009) 
http://labs.da-ra.de/dara/study/web_show?res_id=28133&lang=en&mdlang=de&detail=true
- after unreleasing a project it is still accessible in da|ra
- when relatedPublications change studies are not updated until the project is new released
- in Data and File Information Number of Variables is shown, however we show Number of Analyzable Variables (might be a bit confusing)

**Comment by rreitmann** [comment]
- [ ] entries in Temporal Coverage and Collection Mode are not sorted by surveyNumber: (gra2009)
http://labs.da-ra.de/dara/study/web_show?res_id=28133&lang=en&mdlang=de&detail=true
- [ ] ~~after unreleasing a project it is still accessible in da|ra~~ that is intended
- [ ] when relatedPublications change studies are not updated until the project is new released
- [ ] in Data and File Information Number of Variables is shown, however we show Number of Analyzable Variables (might be a bit confusing)
