### ISSUE TITLE
We need the role "Datengeber"/"data provider" 

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1439]
We decided to not yet implement authorizations but only when necessary.

**Comment by rreitmann** [comment]
The data provider must be able to upload/edit domain objects (apart from related publications). However the data provider must not release projects...

**Comment by dkatzberg** [comment]
Add the Role Data Provider to the MongoDB
`db.getCollection('jhi_authority').insert( { _id: 'ROLE_DATA_PROVIDER' } )`

**Comment by rreitmann** [comment]
@dkatzberg: Just one review remark:
- Please use Principal.hasAnyAuthority instead of two calls to hasAuthority and comparing the results with or

**Comment by rreitmann** [comment]
@dkatzberg: 
- We are calling Principal.hasAuthority (mapped as $scope.hasAuthority) in many templates as well. Please change these calls as well.
