### ISSUE TITLE
related Publications, wich are not related to studies

### ISSUE THREAD

**Issue by kpstephan** [dzhw/metadatamanagement#1443]
As public user I want to find publications wich are related to survey series, but wich are not related to avaliable studies

**Comment by rreitmann** [comment]
We would need a new field in the excel (study series). Furthermore we would enhance the validations (moving many post validations to validations during import). StudyIds or studySeries will be mandatory...

**Comment by rreitmann** [comment]
Maintaining a study serieses in the excel coming from CITAVI is cumbersome. Therefore we prefer to implement edit functionality for related publications. We would import all relevant data from CITAVI and the user can edit the relations to studies, study series, ...

**Comment by rreitmann** [comment]
- relations of related publications will be checked during import (related objects must be present during import)
- related publications can be uploaded for study serieses only (study Ids will be set automatically)
- nightly job ensuring that related publications contain all study ids (or study changed/deleted/created) event
- excel sheet will contain german version of study series (case insensitive)
- either studyIds or studySeries must be present
- publication.reference will be displayed on search result card

**Comment by rreitmann** [comment]
@rbirkelbach Please test in all browsers on the test system.

**Comment by rbirkelbach** [comment]
@rreitmann please discuss with me how we could implement clever tests. This is a bit overwhelming at this early hour and after a couple of days off of work ;)

**Comment by rbirkelbach** [comment]
As expected: commas cannot be in studyseries.de/studyseries.en

**Comment by rbirkelbach** [comment]
Some studyseries are not recognised even though they're present in the test system for example DZHW-Absolventenstudien and Testreihe.

**Comment by rbirkelbach** [comment]
updating & deleting a studyseries works.
