### ISSUE TITLE
SubDataSets: change strings of accessWays

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1451]
accessWay | de/en
-- | --
download-cuf | CUF: Download
download-suf | SUF: Download
remote-desktop-suf | SUF: Remote-Desktop
onsite-suf | SUF: On-Site

**Comment by rreitmann** [comment]
Ideally we would split accessWay in to two fields (product=CUF or SUF, and accessWay=download or remote-desktop or onsite) and the combination has to be unique. For the moment we can only change the strings.

**Comment by anneweber** [comment]
Would it also be possible to change the descriptions of the access ways? For example, the description "Can be used via Remote Desktop" is not very self explanatory in my opinion. If a change of the description is possible, I am happy to make more detailed suggestions, if desired.

**Comment by UteH** [comment]
fyi Kam im DLP-Usertest auch nochmal auf

**Comment by rreitmann** [comment]
@Ute will provide an english version too

**Comment by UteH** [comment]
data and methods report of gra2005 suggests the same wording
https://metadata.fdz.dzhw.eu/public/files/data-packages/stu-gra2005$-2.0.1/attachments/gra2005_MethodReport_en.pdf

![grafik](https://user-images.githubusercontent.com/18573122/111780018-1fde7f00-88b7-11eb-9cb4-e45e12c20c62.png)

-> ok for de/en

**Comment by UteH** [comment]
please also update the info i notation ℹ️ 😇

**Comment by rreitmann** [comment]
@UteH Please check if the way accessWays are displayed now is better...

**Comment by UteH** [comment]
approved. Some minor notes
Could you 
- make bold: "Campus Use File (CUF)" and "Scientific Use File (SUF)"
- add below:
  - "Mehr Informationen: https://www.fdz.dzhw.eu/de/datennutzung"
  - "More information: https://www.fdz.dzhw.eu/en/data-usage"

![grafik](https://user-images.githubusercontent.com/18573122/117400331-a2bca700-af02-11eb-9a2d-31820e9fbc97.png)

**Comment by rreitmann** [comment]
@Ute I have implemented your minor notes...

**Comment by UteH** [comment]
approved
