### ISSUE TITLE
Implement multiple question images

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1454]
We need to implement the changes designed in #1414

**Comment by dkatzberg** [comment]
@rreitmann I like to discuss a last question for this topic: 
It is about the case if a question has only one image. Do we use the carousel always to have a similar style or do we disable the carousel?

**Comment by dkatzberg** [comment]
Ng-Change on Ng-Select is an problem. Hacky workaround is linked under the issue: https://github.com/angular/material/issues/1576

**Comment by dkatzberg** [comment]
Mongoskript for searching just question files:
db.getCollection('fs.files').find({"filename": { $regex: /questions/ }})

Mongoskript for deleting just question files:
db['fs.files'].remove({"filename": { $regex: /questions/ }});

**Comment by rreitmann** [comment]
We can select all old image files by executing:
`db.fs.files.find({"filename": { $regex: /^\/questions/ }})`

Deleting files can be done with:
`db.fs.files.remove({"filename": { $regex: /^\/questions/ }})`

Afterwards the chunks are still present but can be cleaned up with:
```javascript
function removeChunkIfNoOwner(chunk){
  //Look for the parent file
  var parentCount = db.fs.files.find({'_id' : chunk.files_id}).count();

  if (parentCount === 0 ){
     db.fs.chunks.remove({'_id': chunk._id});
     print("Removing chunk " + chunk._id);
  }
}
db.fs.chunks.find().forEach(removeChunkIfNoOwner);
```

**Comment by rreitmann** [comment]
@dkatzberg Here are my remarks:
- [ ] We should refactor the question import so that it does not generate all resources at once but instead iterates over the questions of an instrument and does all required steps per question (including uploading the images of a question)
- [ ] We should display the question images on the question details page as discussed on the whiteboard

**Comment by dkatzberg** [comment]
@rreitmann The resizing is a problem. We should talk about this on monday.
@rreitmann The padding is from the md-card, not from the carousel. If I remove the padding, I remove it from the card, not just the from the carousel. I know that I could add the padding to the other string elements, but we should talk about this on monday too.

**Comment by kimsommer** [comment]
- It would be cool to have the whole image card with carousel as full screen when I click on open image in new tab 
- when I view the website in English and click on one question, the images first shown to me are not necessarily in English - is is possible to adapt this when English images exist?

**Comment by dkatzberg** [comment]
We should discuss the first point on monday for need.
