### ISSUE TITLE
wave numbers in dara: 0. wave

### ISSUE THREAD

**Issue by kimsommer** [dzhw/metadatamanagement#1466]
**win2015:**
Should 0 be allowed as wave number? Maybe 1. wave or a replacement string would be better.

![image](https://user-images.githubusercontent.com/19772575/33611043-64017512-d9cd-11e7-9b19-3cac0ab160f2.png)

**Comment by dkatzberg** [comment]
We have to do the following points:
- [ ]  Validator for survey.wave. The wave number has to be minimum 1

It is not allowed to write 0. wave in dara for "Querschnittsstudien" :  
- [ ] We will replace the collection mode with the 'survey.title: survey.method'. 
- [ ] We will replace the free text on temporal coverage with the survey.title
