### ISSUE TITLE
access statistic and download statistic of documents 

### ISSUE THREAD

**Issue by schellep** [dzhw/metadatamanagement#1490]
You might allready discussed the need for an access statistic of https://metadata.fdz.dzhw.eu. If not I would like to raise the issue and add for several reasons the need of a download statistic. 

Besides informing our stakeholder a use case (you call it like this?) would be that the authors of the publications could share the [distrubtion of the copyright levy ("Kopierabgabe")](http://www.vgwort.de/verguetungen/auszahlungen/wissenschaftliche-publikationen.html). The Deadline for the claim is January 31st.

**Comment by rreitmann** [comment]
When we think about solutions for this we should consider:
http://angulartics.github.io/

**Comment by schellep** [comment]
Fyi, hope it is fine with you, that I just forward Ruth Cordes Mail.

Von: Cordes, Ruth
Gesendet: Montag, 11. Dezember 2017 15:58
An: Scheller, Percy; Weber, Anne
Cc: Matthes, Daniel
Betreff: AW: Zugriffsstatistik für fdz.dzhw.eu?

Hallo Percy,
Du hast Zugriff auf Piwik und kannst dort die Zahlen abrufen:

Die Adresse: https://webstat-admin.his.de/piwik/

Deine Kennung ist dieselbe wie bei Zope.

Dort kannst Du Dir die Daten zusammensuchen. Allerdings weiß ich nicht, ob Du da erkennen kannst, von wo die Seitenbesucher kommen. Das wird bei Piwik nicht getrackt.  Eigentlich müßte Euch das die Seite zur Verfügung stellen, auf der Ihr die Werbung gepostet habt. Denn die können verfolgen, wie oft der Link angeklickt wurde.



Schöne Grüße aus LL113

Ruth Cordes

**Comment by rreitmann** [comment]
Google Analytics and "Datenschutz": https://www.datenschutzbeauftragter-info.de/fachbeitraege/google-analytics-datenschutzkonform-einsetzen/

**Comment by schellep** [comment]
Fyi: Piwik is not HIS e.G.! Our "sister institution" LIfBi uses Piwik [(see in their data privacy statement)](https://www.neps-data.de/en-us/admin/datenschutzwebsite.aspx) and by-the-way Piwik is now [Matomo](https://matomo.org/)...

**Comment by UteH** [comment]
let's talk about this again

**Comment by schellep** [comment]
@rreitmann & @rbirkelbach or (at)productowner 😉, I totally support @UteH attemp: The knowledge about our access is crucial for UX and for PR Considerations!

**Comment by rbirkelbach** [comment]
@AndyDaniel1 maybe we should consider this issue for one of the near future sprints? I think it would be a good idea, especially if we'd be able to implement it before the results of the usability study get implemented.

**Comment by schellep** [comment]
@rreitmann, I am checking Issues that I opened. Is it ok to leave this in the backlog ?

**Comment by rreitmann** [comment]
@schellep Yep, this is still relevant...

**Comment by rreitmann** [comment]
This corresponds to #1832
