### ISSUE TITLE
Upgrade Javers to 3.9.0 (pom.xml)

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#1501]
Upgrade Javers from 3.7.0 to 3.7.8 (pom.xml)

**Comment by rreitmann** [comment]
Had to revert to 3.7.0 because sometimes shadows are missing (are not loaded correctly). Could be an issue introduced with 3.7.5 (see https://javers.org/release-notes)

**Comment by rreitmann** [comment]
Javers 3.8.0 still has the issue.

**Comment by rreitmann** [comment]
Javers 3.8.4 still has this issues...
