### ISSUE TITLE
Edit/Create Studies: Automatic fill of translated versions of sponsor and institution and Edit/Create Survey.SurveyMethod

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#1513]
The sponsor and institution fields are I18nStrings. If the user added one language field of sponsor and institution, the edit/create form should set the second language field, if it known by the database.

This functionality should be available at survey.SurveyMethod, too

**Comment by dkatzberg** [comment]
- [ ] I added some new 128 MEDIUM fields in the client (md-input-maxlength=128). they have to be changed after merging this issue into development AND issue 1358

**Comment by rreitmann** [comment]
TODO:
- add search filters
- review
- change maxlengths... from 128 to 512

**Comment by rreitmann** [comment]
@kimsommer I had to make **study.institution and survey.surveyMethod mandatory in both languages** cause otherwise our suggestions of existing institutions/surveyMethods do not work! This is currently ok for all studies and surveys on the prod system

**Comment by kimsommer** [comment]
when I upload a study excel file with only a german or english sponsor, the error message for study.sponsor is incorrect
