### ISSUE TITLE
linkage MDM - DLP

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1517]
We need to define the linkage between the MDM and the DLP

In the specification of the DLP it says

> Ein   Kunde wählt auf einer Website (Metadatensuchsystem) verschiedene Produkte   aus, diese werden über eine Reminder-Funktion auf einen Merkzettel gesetzt.
> Hat der Kunde seine Auswahl der Produkte abgeschlossen, kann er   einen Button betätigen (z.B. "Produktauswahl abgeschlossen"),   wodurch die Produkte über eine Schnittstelle an das CRM-System übergeben   werden.
> Anschließend muss der Kunde sich über das Kundenportal anmelden   oder neu registrieren.
>

**Comment by AndyDaniel1** [comment]
We have also to consider the data providers who will be registered in the DLP as well. The linkage between MDM an DLP will (probably) be much more complex if we take this aspect into account.

**Comment by UteH** [comment]
@AndyDaniel1 atm I don't understand what you mean, we can discuss this tomorrow, I hope. 

Also, when talking the way through the MDM in January 2017 we realized that the actual product the data users is interested in is "study + access ways", not the dataSets.

We should have this in mind when we define the linkage (and maybe for the MDM in general).

**Comment by UteH** [comment]
for now, we discussed

### data users
- purchase of products via MDM -> transfer the following attributes to the DLP
  - display seperately: SUF/ CUF (is `dataSet.accessWay`)
  - `study.title` + `dataSet.accessWay` + `study.version` (+ `study.surveySeries`) (+ `dataSets.annotations`?)
- selection/editing of products via dropdown menu in the DLP

### data providers
- for now not linkage
- perhaps: transfer DAP-ID from DLP to MDM

**Comment by UteH** [comment]
> Von: Clemens Bastian 
> Gesendet: Donnerstag, 6. Dezember 2018 18:29
> 
> Hallo Frau Höffstätter,
> 
> vielen Dank für die Informationen. Wir werden darauf zurückkommen, sobald wir uns dem Thema ‚Schnittstelle zwischen MDM/DLP‘ widmen.

> 
> Von: Reitmann, René 
> Gesendet: Dienstag, 4. Dezember 2018 11:39
>
> auf dem Testsystem ist jetzt eine API, mit der das DLP Orders (Warenkörbe) im MDM aktualisieren kann:
> https://metadatamanagement-test.cfapps.io/swagger-ui.html#/order-resource
> Für das DLP ist nur PUT auf /api/orders/{id} relevant.
> 
> Sobald wir das DLP haben, werde ich die Attribute customer und state aus der Order entfernen.
> 
> Ich benötige jetzt noch eine analoge API mit der ich Orders in das DLP schreiben kann. Am besten auch auf einem Testsystem, damit ich auch den gesamten Prozess testen kann.
> 
>

**Comment by UteH** [comment]
@rreitmann close?
