### ISSUE TITLE
remove feedback dialog (pop up)

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1562]
@fbaillet asked for the feedback dialog to removed. I agree with her.

**Comment by dkatzberg** [comment]
Why?

**Comment by UteH** [comment]
Is this still a "Pre-Release-Version"? I would argue that we are in operation now?
I am open for discussion on Thursday :)

**Comment by dkatzberg** [comment]
- [ ] Remove Headline in Popup
- [ ] Pop up will not longer be display at first start
