### ISSUE TITLE
Writing issue with MongoDB

### ISSUE THREAD

**Issue by kimsommer** [dzhw/metadatamanagement#1564]
I get many error messages when uploading new attachments or images to new test projects (all domain objects). 
For example https://metadatamanagement-test.cfapps.io/#!/de/search?page=1&type=instruments&study=stu-test5$ when uploading instruments from gra2005:
`{"timestamp":"2018-02-14T10:55:55.944+0000","status":500,"error":"Internal Server Error","exception":"com.mongodb.WriteConcernException","message":"Write failed with error code 12501 and error message 'quota exceeded'","path":"/api/instruments/attachments"}`

**Comment by dkatzberg** [comment]
It seems there is an issue with the allowed max files/max size for the db

Further information:
https://stackoverflow.com/questions/34166991/getting-mongodb-error-on-write-quota-exceeded
https://docs.mongodb.com/manual/reference/configuration-options/#storage.mmapv1.quota.enforced

**Comment by rreitmann** [comment]
I am going to try this:
https://davidburgos.blog/how-fix-quota-exceeded-mlab-mongolab/

**Comment by rreitmann** [comment]
@kimsommer please check if the problem still exists...
