### ISSUE TITLE
alignment of drop down lists

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1570]
I just noticed that with drop down lists you can't read the caption of the fields, once you are using the chooser.

Example "Erhebungsdesign" (study):
![grafik](https://user-images.githubusercontent.com/18573122/36270479-18093662-127c-11e8-9dc1-c9c4eb45298f.png)
![grafik](https://user-images.githubusercontent.com/18573122/36270485-1c8b4eaa-127c-11e8-937f-db51bab862fd.png)

If you users are not that familiar with the fields this might be a bit difficult?

Is it possible to display the list beneath the caption?

**Comment by rreitmann** [comment]
This is on purpose by Google (see https://material.angularjs.org/latest/demo/input).
