### ISSUE TITLE
Update related object after removing assignment

### ISSUE THREAD

**Issue by kimsommer** [dzhw/metadatamanagement#1576]
For an existing variable I changed the question number from 45.1 (valid question) to 45.7 (invalid question). However the related question link to question 45.1 was still shown.

**Comment by rreitmann** [comment]
This is a bigger problem, which occurs each time when you remove related objects from an object. The object which has been removed is not updated correctly...

**Comment by rreitmann** [comment]
The following relationships are affected:
- instrument -> surveys
- dataSet -> surveys
- variable -> surveys
- variable -> questions
- relatedPublication -> *

**Comment by rreitmann** [comment]
@kimsommer, @rbirkelbach:
Please test releasing, unreleasing, project creation/deletion and every domain object creation, update, deletion...

**Comment by rreitmann** [comment]
@kimsommer Please test the variable upload in firefox and chrome. I am playing around with parallel uploads...

**Comment by rbirkelbach** [comment]
- Firefox cannot import questions, chromium is able to do that
- If a linked question is not valid and there's a valid linked question, it says that there are two linked questions, even though it should say 1.
- If there's no correct linked survey, there's an empty field nevertheless, causing a larger than necessary space between the fields.

**Comment by rreitmann** [comment]
@rbirkelbach and @kimsommer :+1: 
Firefox and Chrome should be able to upload questions now. Please verify.
No correct linked survey is displayed as 'Nicht vorhanden' now.
The second item is ok as it is. the post-validation will give an error before releasing...

**Comment by rreitmann** [comment]
After discussing with @rbirkelbach we think that this is ok. However we should give more information on the details pages if there is a missing related object which will be reported by the postvalidation.
