### ISSUE TITLE
Creation of New Data Acquisition Project not possible

### ISSUE THREAD

**Issue by annegaertner** [dzhw/metadatamanagement#1580]
I cannot create a new project (neither in test system nor in productive system) although I have publisher rights.
This is what I get:

![bug](https://user-images.githubusercontent.com/31613371/36474407-b253a9a8-16f7-11e8-99d0-fb5dfceecb33.png)

**Comment by annegaertner** [comment]
I talked to @dkatzberg and managed to create a new project (in both systems) after following his advice: **Logout and Login again**

**Comment by rreitmann** [comment]
Assumed: Login as user, Assign ROLE_PUBLISHER, Refresh and that should be it

**Comment by rreitmann** [comment]
I can confirm the use case. My solution is that we logout all sessions of the user who gets the new role. Thus clicking Refresh in the above use case leads to an unauthenticated instance of the app.

**Comment by rbirkelbach** [comment]
I assigned a user the role publisher, but did not get logged out and when trying to create a new project (the plus button on the left) got this error: Sie sind nicht berechtigt diese Aktion durchzuführen (Status 401).
