### ISSUE TITLE
Display human readable message if the user has disabled javascript

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1598]
We need to improve and test the following case:
- User has disabled javascript in all browsers
- User comes with IE <= 10

**Comment by rreitmann** [comment]
@rbirkelbach Please test on the test system.

**Comment by rbirkelbach** [comment]
I tested it with netrenderer.com and got the following result. I'm not sure however they disabled javascript. I still try to find out a way to install old versions of ie alongside edge on windows10. https://screenshots.firefox.com/1L1aLZsjJEVmjjfJ/netrenderer.com
