### ISSUE TITLE
Edge: SideNavBar in small Browser Window

### ISSUE THREAD

**Issue by kimsommer** [dzhw/metadatamanagement#1602]
Browser Window in Edge is small > scroll down > click on SideNavBar > SideNavBar appears further down or is not shown at all
![unbenannt](https://user-images.githubusercontent.com/19772575/37278664-b6502c84-25e8-11e8-889a-7ab226776889.png)

**Comment by rreitmann** [comment]
@YPeper Please test this on the dev system...

**Comment by YPeper** [comment]
Tested in Edge, IE, Firefox and Chrome. Bug fixed in Edge, no new problems in the other three.

**Comment by rbirkelbach** [comment]
Drop area not full screen.

**Comment by rreitmann** [comment]
Should be fixed now.
