### ISSUE TITLE
Possibility to add objects (especially surveys) which might never be released 

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#1605]
We have to implement a possibilty to add objects which are not or might never be released.

Example WinBus: 

1st Problem: The way the [WiNbus Study](https://metadata.fdz.dzhw.eu/#!/de/studies/stu-win2015$?search-result-index=7) is filed in the MDM is currently not correct, because it is filed as a survey whereas it is a study .

2nd Problem: The second survey of the WiNbus study, which is a quantitative one, is not filed (because we haven't worked on it yet). This leads to the problem that the "study" is displayed as purely qualitative despite the fact that it is mixed methods. 

If we had the option to add surveys to a study which are not yet (or might never be) available, the 2nd (and also the 1st) problem would be sovled.

edit Ute: Then, we also need to rethink the mandatory attributes of [`survey`](https://github.com/dzhw/metadatamanagement/wiki/Domain-Model#survey)

**Comment by rreitmann** [comment]
We will enable surveys without responseRate etc. within #1607. Then you should be able to add both Winbus surveys even though you publish only data sets for one of the two. @AndyDaniel1 Please check if this is ok...

**Comment by AndyDaniel1** [comment]
@rreitmann this should be sufficient. I will leave the issue open until WinBus is filed correctly.

**Comment by rreitmann** [comment]
The only thing which might disturb is the fieldPeriod. But you should be able to provide a planned fieldPeriod.

**Comment by svietgen** [comment]
@AndyDaniel1 I just stumbled across this issue. Does that also apply to Kompaed/cmp2014 (We are publishing the data of the quantitative sub-study)?

**Comment by AndyDaniel1** [comment]
@svietgen yes, if KomPaed has a mixed method design from which only the quantative part is released.

**Comment by UteH** [comment]
@rreitmann I know we talked about this before but: if we do not know fieldPeriod yet, we do not know sampleSize yet either. So, we need to change net sampleSize aswell?

**Comment by rreitmann** [comment]
@AndyDaniel1 What is blocking the progress of this issue?

**Comment by AndyDaniel1** [comment]
As said here: https://github.com/dzhw/metadatamanagement/issues/1605#issuecomment-421002169

> @rreitmann this should be sufficient. I will leave the issue open until WinBus is filed correctly.

Someone has to file WinBus correctly. I don't know who will take care for this kind of corrections  (@danbfdz ?).

**Comment by UteH** [comment]
maybe we should open a seprate issue for filing WiNbus

**Comment by AndyDaniel1** [comment]
@UteH has anyone done this so far? Maybe this should also be opened in the FDZ-Allgemein-Repo.

**Comment by UteH** [comment]
@AndyDaniel1 no, the study still has the [old structure](https://metadata.fdz.dzhw.eu/#!/de/studies/stu-win2015$?version=1.0.0). I think we would need to assign this to a specific person ...

Maybe we could also open a winbus-repo (not sure though how much more issues are there to come).

**Comment by AndyDaniel1** [comment]
@UteH Thanks for the quick response. I think an adding an issue to the FDZ-Allgemein-Repo will be sufficent for now. Than we (@danbfdz) has to decide when we will deal with that. If this decision is made we will open a Repo.

Could you please open an Issue with reference to this issue (tag "zu priorisieren")? Thank you 😸

**Comment by AndyDaniel1** [comment]
since we no longer document studies in MDM (we now document data packages), this issue is no longer relevant
