### ISSUE TITLE
Improve version label on study details page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1606]
Currently we show the string "Version der Datensätze" on the study details page even if there are no data sets. I would prefer "Version" and add the same field to all details pages....

**Comment by rreitmann** [comment]
We will change "Version der Datensätze" to "Version" but will not display it on the other details pages...

**Comment by YPeper** [comment]
Tested in IE11, Edge, Firefox and Chrome. Works as intended.
