### ISSUE TITLE
stepwise release: by domain object resp. by type of a domain object

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1607]
we want to be able to release domain objects resp. by types of a domain object stepwise (and in a different order), e.g. 
1. study
2. instruments
3. survey 1
4. survey 2
5. variables (_no_ questions)

To Do:
- ~currently, this is only an issue with post validation?~ change _survey-id_ in instrument to not mandatory? change attributes of survey (e. g. field period more general?)
- check use cases (e.g. 5)

**Comment by rreitmann** [comment]
I will check which validations we need to remove and list them here...

**Comment by rreitmann** [comment]
If survey.fieldPeriod is not mandatory we can release studies with planned surveys and winbus as well...

**Comment by rreitmann** [comment]
Currently we can set a future field period and set sample size to zero. This looks as follows:
![image](https://user-images.githubusercontent.com/12323832/49796141-30006f00-fd3c-11e8-8b9b-4062037649cd.png)

**Comment by AndyDaniel1** [comment]
The state of this issue is not clear to me. @UteH @rreitmann please provide more information. As I understood it a stepwise release is possible but not fully implemented?

**Comment by UteH** [comment]
@AndyDaniel1 Generally, stepwise release is possible. For beta releases, there are not restrictions. For releases >= 1.0.0 there are some restrictions: mandatory fields. Here, we were stumbling over field.Period, which is still mandatory.
- Either we decide that we still enter this information (important information for context). We were talking about simply entering a future planned field.period if the data collection has not yet taken place.
- Or we decide to make field.Period not mandatory (we need a new issue then).

I would test the first option. Then we do not have to change anything. 

@rreitmann please correct, if incorrect

**Comment by AndyDaniel1** [comment]
Ok, thanks for the quick response. I would go with the first option since planned field periods are mandatory parts of research proposals and as such be known from the start of the project. 

We need an adequate documentation for this: 
1. Data provider should be aware that a change in field periods should also be changed in the MDM
2. Publisher should be aware that they have to check wether the field period is filed correctly before releasing a study

I will provide a prio 2, but with a slight tendency to 1 since this will be relevant for NACAPS/SLC/EStud

**Comment by UteH** [comment]
@AndyDaniel1 so now, this is mainly a "documentation" issue, right?

**Comment by AndyDaniel1** [comment]
I will test this issue with gra1997 and gra2001

**Comment by AndyDaniel1** [comment]
I don't think we need a new implementation here. The field period should remain mandatory. If a stepwise release of a future survey is planned (as 1.0.0), the future field period should be known (at least roughly), otherwise a pre-release of a survey makes no sense.
