### ISSUE TITLE
Date and Time Variables

### ISSUE THREAD

**Issue by kimsommer** [dzhw/metadatamanagement#1608]
Currently we support date variables (yyyy-mm-dd) but not date time variables (yyyy-mm-ddThh:mm:ss+\-hh:mm). However for some variables (e.g. last time of access to survey from cmp2014) it would be correct to display both date and time.

Also up for discussion:
- How should English Dates be displayed? 
Dec 17, 2017 (at the moment) or 2017/12/17 (closer to the German date representation)

**Comment by rreitmann** [comment]
1. We will aggregate DateTime to Date (Day) variables for the MDM add add a hint in to the annotation
2. We will use Dec 17, 2017 and prevent the line break in the distribution table...

**Comment by rreitmann** [comment]
This has to wait until #1577 has been completed...

**Comment by rreitmann** [comment]
@rbirkelbach I have fixed the line break mentioned in my https://github.com/dzhw/metadatamanagement/issues/1608#issuecomment-380798280. Will you update `variableMetadataPreparation` for aggregation of DateTime variables?

**Comment by rbirkelbach** [comment]
I get the following error upon import of testdata: `The import of the object "Variable" from an json file failed, because the field "highWhisker" has an invalid value: 2010-10-10 `

**Comment by rreitmann** [comment]
To sum up:
- we will allow nominal, ordinal and interval scale level for date variables
- whiskers will be removed completely since they are not used at all

**Comment by rreitmann** [comment]
Remove whiskers from mongoDB:
```javascript
db.getCollection('variables').updateMany({}, {$unset: {'distribution.statistics.lowWhisker': '', 'distribution.statistics.highWhisker': ''}})
```
