### ISSUE TITLE
BMBF logo too low resolution

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1609]
The logo is of very low quality compared to our logo. This can be seen especially on mobile devices, not so much on a personal computer.

**Comment by rreitmann** [comment]
@rbirkelbach Get in touch with the BMBF. Do not forget to organize a german and an english logo with _exactly_ the same text as at the moment.

**Comment by rbirkelbach** [comment]
done
[logo-bmbf.zip](https://github.com/dzhw/metadatamanagement/files/1915558/logo-bmbf.zip)

**Comment by rreitmann** [comment]
@rbirkelbach 
Please test in all browsers and in all window sizes....
