### ISSUE TITLE
Link Data Access/Datenzugang

### ISSUE THREAD

**Issue by schellep** [dzhw/metadatamanagement#1612]
Der Link Data Access/Datenzugang führt durch Umstellungen an der FDZ-Seite nun auf die Subpage Kontakt. Falls @fbaillet das nicht anders sieht, solltet ihr ihn auf [Datennutzung](https://fdz.dzhw.eu/aufbau/index_html) ändern. Dort  werden die Schritte der Datenaufnahme beschrieben (@srKienast hat einen Vorschlag erarbeitet, denn @liedtke-dzhw demnächst umsetzt).

Vielleicht lässt sich das in einem Aufwasch mit https://github.com/dzhw/metadatamanagement/issues/1611 erledigen...

**Comment by fbaillet** [comment]
@schellep wir sollten damit warten, bis die von Rebecca/Anne/mir übarbeitete Website durch Annika umgesetzt wurde

**Comment by rreitmann** [comment]
duplicates #1733
