### ISSUE TITLE
Edit buttons available after release

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1615]
Currently the GUI displays or hides the edit and delete buttons of surveys and studies depending on the state of the domain object in elasticsearch. Since elasticsearch is updated eventually there is the possiblity that a user releases a project and afterwards (without unreleasing the project) changes data...

**Comment by YPeper** [comment]
Edit survey and edit study can't be accessed through link/URL oder edit buttons any longer after publishing the project. 
However, there are problems when publishing the project while being on the edit page. If the version is below 1.0.0 it does not refresh the page so the survey/study can be further edited. If the version is higher than 1.0.0 it gives the error warning that it couldn't send the metadata to da|ra.

**Comment by YPeper** [comment]
Above mentioned bugs (when version number below or above 1.0.0) are both fixed. No new bugs found. Tested in IE, Edge, Chrome and Firefox.
