### ISSUE TITLE
Search Result Navigation broken when using Back Button

### ISSUE THREAD

**Issue by kimsommer** [dzhw/metadatamanagement#1618]
When I am in the data set search, click on related surveys and afterwards go back one step, I would expect to be in the data set search again. Instead I am in the related surveys search.

**Clicking order:**

https://metadata.fdz.dzhw.eu/#!/de/search?page=1&type=data_sets&study=stu-gra2005$
-> click ds1 -> I am in the data set search -> click related surveys -> click back button -> I am not in the data set search anymore but in the related surveys search

**Comment by rreitmann** [comment]
I have to refine the patch: The stored search results will be deleted when the users navigates back and is currently on the search view.

**Comment by rbirkelbach** [comment]
It works now.
