### ISSUE TITLE
Scrolling down the options of the Select Box is not possible

### ISSUE THREAD

**Issue by kimsommer** [dzhw/metadatamanagement#1620]
When I click on Survey Design on the study edit page and scroll down, I scroll down the page but not the options of the select box.
![md-select_bug](https://user-images.githubusercontent.com/19772575/38719540-ceaae7d8-3ef2-11e8-92c3-a532357a8204.png)

**Comment by rreitmann** [comment]
@YPeper Please test this on the dev system...

**Comment by YPeper** [comment]
Tested in all four browsers (IE, Edge, FF, Chrome). Bug can no longer be reproduced. 
However, scrolling outside of the select box isn't possible when a select box is open. If intended it is working as it should be. @rreitmann

**Comment by rreitmann** [comment]
Scrolling down outside of select boxes, autocompletes, ... when they are open is not possible in angularjs material...

**Comment by rbirkelbach** [comment]
Drop area not full screen.

**Comment by rreitmann** [comment]
Should be fixed now.
