### ISSUE TITLE
gsl2008: instruments not released?

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1632]
I wanted to check the instruments of gsl2008 as a public user:

![grafik](https://user-images.githubusercontent.com/18573122/39140945-77f6b61a-4726-11e8-8131-c03d32299072.png)
![grafik](https://user-images.githubusercontent.com/18573122/39141002-b2782058-4726-11e8-845c-0a02fdc383b4.png)
https://metadata.fdz.dzhw.eu/#!/de/search?page=1&type=instruments&study=stu-gsl2008$

they are available for fdz members

**Comment by rreitmann** [comment]
Don't know how this happened but after reinitializing elasticsearch the problem is gone...

**Comment by rreitmann** [comment]
Should be fixed now. And will be included in v1.0.66
