### ISSUE TITLE
As publisher I want to deliver survey.population.unit to the VFDB

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#1634]
Could we implement a filter for the survey population (e.g. phd students, students, scientists, school leavers) at the study search page?

https://www.forschungsdaten-bildung.de/studienliste.php?la=de (Filtern nach Erhebungseinheiten)

**Comment by rreitmann** [comment]
@svietgen Currently we do not have a field survey.units or similar. We can create it (mandatory?, controlled vocabulary?), send it to dara? and finally filter every domain object by it. Let us know your thoughts...

**Comment by rreitmann** [comment]
@svietgen Please answer my previous question....

**Comment by svietgen** [comment]
If we create this field I would prefer to make it mandatory and use controlled vocabulary. But this is a lot of work so maybe we should discuss if it's worth it. I could join the daily for this discussion.

**Comment by UteH** [comment]
I have also thought about this kind of attribute. But I not sure about the level of information.

See two examples below.

#### VFDB
For the Verbund Forschungsdaten Bildung we have to deliver information about the survey.unit. They do not have a controlled vocabulary but use a list that can be extended. 

Here, we could extend the list according to our studies.

For now, the list is
- Schüler
- Lehrkräfte
- Pädagogisches Personal
- Eltern
- Schulleitung
- Behörden
- Vorschulkinder
- Auszubildende
- Jugendliche
- Studierende
- Referendare
- Schulen
- Hochschulabsolventen _(für uns ergänzt)_

## dara 
dara offers these (fur us very broad) attributes. Here we would only have "individuals" for now.

unitType | definition24
-- | --
Individual | Any individual person,   irrespective of demographic characteristics, professional, social or legal   status, or affiliation.
Organization | Any kind of formal   administrative and functional structure - in- cludes associations,   institutions, agencies, businesses, political parties, schools, etc.
Family | Two or more people related   by blood, marriage (including step- relations), adoption or fostering and who   may or may not live to- gether (National Community Services Data Dictionary,   Vers 3, AIHW, 2004). For example, used when researching the extent to which   people provide support and assistance for their relatives.
Family.HouseholdFamily | A more specific term,   refers only to related people who live in the same household at a point in   time. If not known whether the analy- sis unit is "Family" or   "Household family", use "Family".
Household | A person or a group of   persons who share the same dwelling unit and common living arrangements.   These common living arrange- ments may include pooling some, or all, of their   income and wealth, and consuming certain types of goods and services collec-   tively, mainly housing and food (Eurostat).
HousingUnit | U.S. Census: A housing unit   is a house, an apartment, a mobile home, a group of rooms, or a single room   that is occupied (or if vacant, is intended for occupancy) as separate living   quarters. Separate living quarters are those in which the occupants live and   eat separately from any other persons in the building and which have direct   access from the outside of the building or through a common hall.
EventOrProcess | Any type of incident,   occurrence, or activity. Events are usually one-time, individual occurrences,   with a limited or short duration. Examples: criminal offenses, riots,   meetings, elections, sports competitions, terrorist attacks, natural   disasters like floods, etc. Processes typically take place over time, and may   include multiple "events" or gradual changes that ultimately lead,   or are projected to lead, to a particular result. Examples: court trials,   criminal inves- tigations, political campaigns, medical treatments,   education, ath- letes' training, etc.
GeographicUnit | Any entity that can be   spatially defined as a geographic area, with either natural (physical) or   administrative boundaries.
TimeUnit | Any period of time: year,   week, month, day, or bimonthly or quar- terly periods, etc.
TextUnit | Books, articles, any   written piece/entity.
Group | Two   or more individuals assembled together or having some unify- ing   relationship.
Object | Anything   material, but inanimate, that has an independent exist- ence and may be   perceived by the senses. Examples: objects of art (paintings, sculptures,   etc.) or weapons, or vehicles, etc.
Other | Use if the unit of analysis   is known, but not found in the list.

**Comment by rreitmann** [comment]
For the VFDB we need to create a new mandatory field survey.population.unit which can contain one of the following list:
* Schüler
* Lehrkräfte
* Pädagogisches Personal
* Eltern
* Schulleitung
* Behörden
* Vorschulkinder
* Auszubildende
* Jugendliche
* Studierende
* Referendare
* Schulen
* Hochschulabsolventen

Do we need another field representing dara's unitTypes?

**Comment by rreitmann** [comment]
During this issue we will focus on the requirements of the VFDB, hence we need a mandatory field survey.population.unit (I18nString) which can contain in German only valid values from the list of the VFDB. Currently that list does not contain enough values for our surveys:
@Ute, @rbirkelbach Please define an extended list for our surveys and get in touch with the VFDB in order to extend their list.

**Comment by UteH** [comment]
my suggestions for survey.population.unit for our current studies

studie | survey.population.unit
-- | --
gra2005, gra2009 | Hochschulabsolventen
gsl2008 | Studienberechtigte
win2015 | wissenschaftliches Personel??? @DilekIkiz fragen
phd2014 | Promovierte
cmp2014 | Hochschulabsolventen??? @svietgen fragen
scs2016 | wissenschaftliches Personel
ssy19, ssy20, ssy21 | Studierende

**Comment by svietgen** [comment]
@UteH Since cmp2014 is an in-depth survey from the graduate panel, I would agree with you :+1:

**Comment by DilekIkiz** [comment]
@UteH The method report of win2015 contains the description: Wissenschaftliche und künstlerische Mitarbeiter*innen

**Comment by UteH** [comment]
@rreitmann our suggesions above. if @rbirkelbach is ok with it I will send our suggesions to the VFDB.

**Comment by rbirkelbach** [comment]
I think it's fine.

**Comment by rreitmann** [comment]
@UteH I would prefer a list of German units and corresponding English translations. Do we want to offer the complete list or only our subset to the users?

**Comment by UteH** [comment]
Rückmeldung vom Verbund:

> Liebe Ute,
>  
> Hochschulabsolventen, Studierende und wissenschaftliches Personal sind schon im kV enthalten.
>  
> Die Terme „Studienberechtigte“ und „Promovierte“ diskutieren wir dann bei unserem Verbundtreffen nächste Woche, wo wir ohnehin über das Thema kV reden wollen.
>  
> Ich gebe Dir danach Rückmeldung.
>  
> VG
>

**Comment by rreitmann** [comment]
For the migration we still need:
**Projects: bst02, gsl2015, gsl2018, lib2016, ssy18**

**Comment by rreitmann** [comment]
@rbirkelbach For migration we need survey.population.unit for all surveys in the system. Current we have only the one in #2132. IMHO bst02, gsl2015, gsl2018, lib2016, ssy18 are missing...

**Comment by rbirkelbach** [comment]
- bst02: Studierende
- gsl2015: Studienzugangsberechtigte
- gsl2018: Studienzugangsberechtigte
- lib2016: sonstiges
- ssy18: Studierende
