### ISSUE TITLE
As publisher I want to edit datasets details in a form

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1644]

**Comment by UteH** [comment]
@rreitmann could this be implemented https://github.com/dzhw/metadatamanagement/issues/1648 aswell or should this remain a separte issue?

**Comment by rbirkelbach** [comment]
Do we have a naming convention for subdatasets? I couldn't find one.

**Comment by rbirkelbach** [comment]
add subdataset tooltip
