### ISSUE TITLE
study detail page: surveys editable after release

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1646]
even for already released projects as a publisher I can edit the survey details - _not_ via the survey detail page _but_ via the integrated survey details on the study detail page

![grafik](https://user-images.githubusercontent.com/18573122/39575977-b852e57c-4edc-11e8-8792-a811b4635895.png)

:speak_no_evil: 

thanks @svietgen for realizing :sparkles:

**Comment by rreitmann** [comment]
Will be fixed within #1615
