### ISSUE TITLE
As a data provider and as a publisher I need documentation of variables.doNotDisplayThousandsSeparator

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1649]
for `variables`, there is the attribute [`doNotDisplayThousandsSeparator`](https://github.com/dzhw/metadatamanagement/issues/1239#issuecomment-330468164). I could not find a definition in neither in the mdm wiki nor io wiki. I need to know if this field is mandatory.

**Comment by rreitmann** [comment]
If it is not documented in the mdm wiki it is not mandatory (will be false as default). We document only validation rules.

**Comment by rreitmann** [comment]
Will be improved with #1659

**Comment by rreitmann** [comment]
Documentation is here:
https://metadatamanagement.readthedocs.io/de/latest/javadoc/eu/dzhw/fdz/metadatamanagement/variablemanagement/domain/Variable.html#donotdisplaythousandsseparator
