### ISSUE TITLE
As a public user I would like an option (e.g. a button) to reset all filters

### ISSUE THREAD

**Issue by YPeper** [dzhw/metadatamanagement#1652]
There should be an easy way to get rid of all filters at once while using the search engine.

**Comment by rreitmann** [comment]
@rbirkelbach Please test on the test system in all browsers.

**Comment by rbirkelbach** [comment]
The filter can be reset using the button. However, the filter is still present when going e.g. from study to instruments.

**Comment by rbirkelbach** [comment]
No -- sorry I forgot to close the issue.
