### ISSUE TITLE
Filter dropdowns change list entries after scrolling down fast

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1654]
Can be reproduced by using the mouse wheel on desktops and swiping up or down on mobiles.

This is currently visible here as well:
https://material.angularjs.org/latest/demo/autocomplete#inside-dialog

Open the dialog and select the autocomplete and scroll with the mouse wheel...

**Comment by rreitmann** [comment]
I opened an issue to get some input from the material team:
https://github.com/angular/material/issues/11283

**Comment by rreitmann** [comment]
I have filed a chrome bug for this issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=863672

**Comment by rbirkelbach** [comment]
I just checked it on chromium (70.0.3538.77) on my pc and on chrome in android (9.0.0)  on chrome (70.0.3538.80) and cannot reproduce it anymore. Their target version was 69 and 70 is out, so it might've been fixed. However, the ticket does not seem to be closed, so can you please double check it, @rreitmann ?

**Comment by rreitmann** [comment]
I cannot reproduce this anymore :)
