### ISSUE TITLE
Create Excel file for question generation

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1661]
For scs2016 I want to create the excel file which is needed to import the metadata to the mdm. However, the routine I found (json2excel.R in the folder ssy21/Lieferung_Zofar_2018_04_18) only creates the question sheet in the excel file, whereas the question-generation.R script by @kimsommer  also needs the images sheet. Can somebody (maybe @rreitmann ) point me to the solution please?

**Comment by rreitmann** [comment]
@rbirkelbach Close if you do not need further input...
