### ISSUE TITLE
Implement GDPR compliant privacy terms

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1677]
This should include stuff like google fonts.

**Comment by rbirkelbach** [comment]
https://dsgvo-muster-datenschutzerklaerung.dg-datenschutz.de

**Comment by rreitmann** [comment]
@kpstephan What is blocking the progress of this issue?

**Comment by AndyDaniel1** [comment]
please set a link to https://www.dzhw.eu/gmbh/datenschutz
