### ISSUE TITLE
Change robotframework to robertframework

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1683]
- Setup robotframework on roberts computer
- Show robotframework documentation to robert
- Walk robert through test code
- Implement at least one test with multiple test case together with robert
- get saucelabs account for robert

**Comment by rbirkelbach** [comment]
https://www.youtube.com/watch?v=5DBc5NpyEoo

**Comment by YPeper** [comment]
**Useful links:**

- Robot Framework 
http://robotframework.org/
- Robot Framework User Guide
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html
- Good Robot Framework Writing
https://github.com/robotframework/HowToWriteGoodTestCases/blob/master/HowToWriteGoodTestCases.rst

**Documentation of RF libraries:**

- BuiltIn
http://robotframework.org/robotframework/latest/libraries/BuiltIn.html
- Selenium2Library
http://robotframework.org/SeleniumLibrary/Selenium2Library.html
- Collections
http://robotframework.org/robotframework/latest/libraries/Collections.html
- String 
http://robotframework.org/robotframework/latest/libraries/String.html

**Comment by YPeper** [comment]
Libraries to have:
- Selenium2Library
- Collections
- String
- BuiltIn
- DateTime

**Comment by rbirkelbach** [comment]
Test: 
1) In fileupload-project open survey 
2) open edit survey page
3) edit something
4) save
5) check in versioning system whether it's there
6) teardown
