### ISSUE TITLE
As data provider i'm not able to generate a dataset report

### ISSUE THREAD

**Issue by kpstephan** [dzhw/metadatamanagement#1685]
When I sign in as data provider, navigate to the dataset page of ssy19 and move a template folder on the page the dropping area becomes green. But when I drop the folder, nothing happens (no message is displayed).

When I use the dataset generation button and select a template folder also nothing happens. 

Firefox, Chrome on Ubuntu 14.04

**Comment by rreitmann** [comment]
@kpstephan Please provide a zip containing the current templates in order to reproduce this...

**Comment by kpstephan** [comment]
[DSR-Template.zip](https://github.com/dzhw/metadatamanagement/files/2057321/DSR-Template.zip)

**Comment by rreitmann** [comment]
@kpstephan I will deploy a new version on the test system. There has been a bug in our zip writer service resulting from a breaking JSzip change :disappointed: In addition I have changed one line in the variable template which did not check if there is a variable.distribution object at all which caused an error.

[DSR-Template_fixed.zip](https://github.com/dzhw/metadatamanagement/files/2057616/DSR-Template_fixed.zip)

**Comment by rreitmann** [comment]
@kpstephan please test on the test system

**Comment by kpstephan** [comment]
@rreitmann 
When i try to run the (fixed) template on the test system, i get an Error (500)

**Comment by rreitmann** [comment]
@kpstephan The error occurred cause there have been no questions in gra2005. I have uploaded them and now the report fails with another missing reference (validReponse.label is not mandatory). Tomorrow I will check why the report fails when there are no questions...

**Comment by rreitmann** [comment]
@kpstephan I have found the line causing a NPE when the variable.relatedQuestion does not exist in the question db. Please check if you need question and instrument information in the report. If yes the report has to cope with the fact that instruments and questions given in the relatedQuestions are not present. That would affect the java code as well as your template...

**Comment by rreitmann** [comment]
@kpstephan I have fixed all NPEs in the Java Code and reviewed your template according to references to non-existing questions or instruments. Latterer should be ok. Please go on testing your template on the test system.

Furthermore you should use git for developing the template. The latest version is located here:
https://github.com/dzhw/metadatamanagement-io/tree/master/datasetreport/template

Changes to the template should be commited on this issue by using dzhw/metadatamanagement#1685 in the commit message (see my commit https://github.com/dzhw/metadatamanagement-io/commit/fb158e98818fa816510872c67bedfcb9961191d4)

Furthermore you should use a freemarker editor which beautifies the template (replaces tabs with spaces, uses a constant indentation length, ...)
