### ISSUE TITLE
as a public user I need a shopping cart to collect the products I am interested in 

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1692]
### shopping cart :shopping_cart: 
- the shopping cart contains
  - products: 
    - study.title 
    - study.version 
    - subDataSets.accessWay
  - additionally, as a public user I need 
    - ?.annotation (or similar, e.g. study XY not available to members of the DFG) (get in touch with @danbfdz)
  - additionally, as a rdc member I need (maybe not visible for public user) (get in touch with @danbfdz) 
    - study.studySeries? (for reporting)
    - ...
- the shopping cart is devided by (dataSet.accessWay)
  - suf
  - cuf

**Comment by rreitmann** [comment]
dataAvailability will be removed in #1780

**Comment by rreitmann** [comment]
Some notes regarding the shopping cart:
- every user who is not logged in will be able to put data products into the shopping cart
- users who have accidentally logged in and have therefore ROLE_USER will be able to put data products into the shopping cart as well
- only data products with version >= 1.0.0 can be put into the shopping cart

**Comment by rbirkelbach** [comment]
- Op­tions of the re­lated Data Prod­uct is shown for a short time when the study is <1.0.0
- Study is released as 1.0.0 but data availability chosen to be unavailable or in preparation -> public users can choose to order the study.

**Comment by rreitmann** [comment]
Test with #1780

**Comment by rbirkelbach** [comment]
- ~~Op­tions of the re­lated Data Prod­uct is shown for a short time when the study is <1.0.0~~
- ~~Study is released as 1.0.0 but data availability chosen to be unavailable or in preparation -> public users can choose to order the study.~~
- ~~Blank areas look ugly: https://metadatamanagement-test.cfapps.io/#!/de/variables/var-gra2005-ds1-pid$?search-result-index=1~~

Also see https://github.com/dzhw/metadatamanagement/issues/1780
