### ISSUE TITLE
as a public user I want to send my selected products to the DLP

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1693]
As I public user I want my shopping cart (#1692) to be transferred into the DLP without authentication by clicking a button.

**Comment by UteH** [comment]
In (mid/end of) May we want to launch the DLP for good. I will give the exact date later (with advance notice).

@github-luckow-org please tell us which information you need.

**Comment by rreitmann** [comment]
@UteH I do not get why the DLP uses the IP-Address of the mdm. It should use resolve the domain names cause we have no influence on the IP-Addresses. 
prod: metadata.fdz.dzhw.eu
test (currently): metadatamanagement-test.cfapps.io

**Comment by UteH** [comment]
@hexabinaer can u address the [comment](https://github.com/dzhw/metadatamanagement/issues/1693#issuecomment-621702642)?
(I just passed on the information).

**Comment by hexabinaer** [comment]
For the record: No need to use IP addresses, we are using domain names.

**Comment by rreitmann** [comment]
The DLP go-live is currently planned for Tuesday, 2nd July at 2 pm.

The DLP domain names will be:
- prod: https://fdz.dzhw.eu/
- test: http://stage.fdz.dzhw.eu

The MDM domain names will be:
- prod: https://metadata.fdz.dzhw.eu
- test: https://test.metadata.fdz.dzhw.eu
