### ISSUE TITLE
as a data provider I want a single sign-on for the DLP an the MDM

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1694]
when the data deposit procedure in the DLP is done I will be transferred to the MDM to enter my metadata. I want my user authentication information from the DLP to be transferred to the MDM.

**Comment by rreitmann** [comment]
Dataproviders will have two logins (DLP and MDM)

**Comment by AndyDaniel1** [comment]
@UteH @rreitmann so this issue can be closed? If so please do so!
