### ISSUE TITLE
as a data provider I want to upload excel interfaces containing formulas

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1705]
we beautified the excel interfaces of the domain objects (study, intruments etc.) in order to make it easier for data providers to fill in the interfaces. For example we worked with formulas for the translation of controlled vocabulary from German to English. But when the data providers wants to upload the interfaces, she/he will get an error message because of the (invisible) formulas in the interfaces 
 (e.g. 
`=WENN(C2="download-cuf";"can be downloaded after registration without a data use agreement";
WENN(C2="download-suf";"can be downloaded after the conclusion of a data use agreement";
WENN(C2="remote-desktop-suf";"can be used via remote desktop"; 
WENN(C2="onsite-suf";"available at the workspace for visiting scientists at the DZHW in Hannover";""))))`.

In the long run we want input masks for more domain objects solving these problems. But as I am not sure if/when we will have more input masks, I want to discuss this problem.

**Comment by rreitmann** [comment]
You have to save your excel without the formulas, they get evaluated when you open excel:
https://www.howtogeek.com/251854/how-to-create-a-copy-of-an-excel-worksheet-without-formulas/

**Comment by UteH** [comment]
as the data providers will upload the excel files themselves they would have to do this step for each file with several sheets ...

**Comment by rreitmann** [comment]
yep, thats how excel interface work...

**Comment by rreitmann** [comment]
If the complete excel rows containing formulas can be uploaded correctly then let the providers delete the incomplete row else the providers have to do what is written here:
https://www.howtogeek.com/251854/how-to-create-a-copy-of-an-excel-worksheet-without-formulas/

**Comment by UteH** [comment]
1. The formulas are being interpeted correctly when uploaded :+1:
2. We will work with our idea of deleting rows manually.

**Comment by rreitmann** [comment]
@UteH Seems to be solved. Please close if nothing left to do...
