### ISSUE TITLE
as a data provider I want a direct link to my DAP in the MDM

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1710]
currently, the data providers have access to several DAP in the MDM. It could be helpful to send them the dirct URL to *their* DAP. For now, the URL does not inidcate the DAP and the data provider has to choose the project himself/herself.

Is it possible for the DAP to be already selected in the project chooser and to write the DAP in the URL?

**Comment by rreitmann** [comment]
- we will store the current project in the browsers url
- we will not set a study filter anymore (filter by project will remain)

**Comment by rreitmann** [comment]
Done
