### ISSUE TITLE
Bug: cannot upload question jsons when using successorNumbers field

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#1711]
I generated the json files with the R-script on Faust. The successor numbers cause error messages on upload. If I replace the numbers with null it works. It's working in the test system.

![unbenannt](https://user-images.githubusercontent.com/22055122/42750545-e0b877f8-88e7-11e8-9705-5549210431db.PNG)
[Protokoll-2018-07-16T10-39-08.txt](https://github.com/dzhw/metadatamanagement/files/2197029/Protokoll-2018-07-16T10-39-08.txt)

**Comment by rreitmann** [comment]
@svietgen Please give me the files you have tried to upload...

**Comment by svietgen** [comment]
@rreitmann I have tried to upload the following files: https://github.com/dzhw/metadatamanagement-io/tree/master/project/scs2016/data/questions/ins1

**Comment by rreitmann** [comment]
@svietgen I cannot reproduce this on the dev system. Maybe it get fixed with our new version coming today. Please retry tomorrow.

**Comment by rreitmann** [comment]
@svietgen I have unreleased scs2016 and have tried to upload the questions for you. Generally it works however the database is full causing several 500 errors. Now we really need #1105.

I have deleted the questions and released scs2016 again.

**Comment by rreitmann** [comment]
@svietgen can we close this now?

**Comment by svietgen** [comment]
@rreitmann Yes! :+1:
