### ISSUE TITLE
As public user I want to use urls starting with www

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1716]
@schellep As far as I remember the problem you saw with the current ssl certificate was that the users type **www**.metadata.fdz.dzhw.eu. Which causes browsers to display an unsecure warning. Is that correct?

If so we do not need a new SSL certificate but will redirect the users to the correct url without www.

**Comment by rreitmann** [comment]
@rbirkelbach please test on prod

**Comment by rbirkelbach** [comment]
Works
