### ISSUE TITLE
Add metadata to response rate images

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1719]
Currently we do not store metadata (holding the project id for instance) with the response rate images.

**Comment by rreitmann** [comment]
@rbirkelbach We will need to (re-)upload all response rate images...

**Comment by rbirkelbach** [comment]
..but probably only after we have mongodb as a service?

**Comment by rbirkelbach** [comment]
I uploaded them where applicable to the test system.
