### ISSUE TITLE
Increase max file size to 15 MB

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1720]
The max file size for uploaded files is currently 10MB.

**Comment by rreitmann** [comment]
@anneweber Please test on the test system and close this issue if it is ok. Production deployment is currently scheduled for 20th August.

**Comment by anneweber** [comment]
:cool: thank you! :heart_eyes:

**Comment by anneweber** [comment]
![image](https://user-images.githubusercontent.com/17066262/43196399-062018da-9008-11e8-8660-db8c11c085f8.png)

(I cannot close the issue)
