### ISSUE TITLE
Buy prerender as a service

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1721]
For SEO we need a service which renders our SPA for crawlers.

**Comment by rreitmann** [comment]
There are the following options:
1. https://prerender.io/
2. https://www.prerender.cloud
3. https://prerender.com/
4. https://www.brombone.com/
5. http://getseojs.com/

**Comment by rreitmann** [comment]
Here are the requirements:
REQ1 (MUST): Automatically prerender and cache for one day 30.000 pages (currently on PROD) * 3 * 2 (TEST system) = 180.000 pages
REQ2 (MUST): Email alerts on quota limits
REQ3 (MUST): Prerender and cache for one day on the fly
REQ4 (MUST): Compatible with AngularJS
REQ5 (MUST): Documentation for Java EE/Spring integration
REQ6 (SHOULD): Report SEO issues
REQ7 (SHOULD): contract can be terminated at least monthly

**Comment by rreitmann** [comment]
| Service  | REQ1 | REQ2 | REQ3 | REQ4 | REQ5 | REQ6 | REQ7 | Price (Month) | Price (Year) |
| ----------- | -------- | -------- | -------- | -------- | -------- | --------- | -------- | ------------------ | ---------------- |
| https://prerender.io  | ? | ? |  ?  | ? | ? | ? | ? | ? | ? |
| https://www.prerender.cloud | ? | ? |  ?  | ? | ? | ? | ? | ? | ? |
| https://prerender.com | ? | ? |  ?  | ? | ? | ? | ? | ? | ? |
| https://www.brombone.com | ? | ? |  ?  | ? | ? | ? | ? | ? | ? |
| https://www.seo4ajax.com  | ? | ? |  ?  | ? | ? | ? | ? | ? | ? |

**Comment by rreitmann** [comment]
@AndyDaniel1 I have finished the market overview. We need to talk about this...

**Comment by AndyDaniel1** [comment]
We have to come back to this issue in September (after Daniels and my vacation). In the meantime we'll might get some additional hints on this topic by the ui-Experts.

**Comment by AndyDaniel1** [comment]
maybe I'll discuss this topic with @danbfdz before his vacation. @rreitmann if I got your classification right the most fitting service is expected to cost about 2.5K/y.

**Comment by rreitmann** [comment]
@AndyDaniel1 yep

**Comment by rreitmann** [comment]
I have recalculated the estimated number of pages in the mdm. => The only available option will cost 132$ / month,  1548$/ year

**Comment by rreitmann** [comment]
This comment was automatically created on 2020-11-18T14:21:56.387417
