### ISSUE TITLE
Ensure variableMetadataExtractor is executable for all projects

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1755]
Currently it is not due to a rights problem in the protected area (see #1493)

**Comment by rbirkelbach** [comment]
I asked them again when they think it'll be done. The last time I asked was 2018-08-08. I'll reply when I get a response.

**Comment by rbirkelbach** [comment]
@anneweber is it working with the new R version for you? If yes, please close this issue.

**Comment by anneweber** [comment]
@rbirkelbach No, it's still not working :(

![fehlermeldung](https://user-images.githubusercontent.com/17066262/45866452-2ab90700-bd81-11e8-9bd1-bef0768d35db.png)

**Comment by rbirkelbach** [comment]
Can you please tell them to install R 3.5.1 for you and the others working in the same environment? I thought they already had installed it, but apparently this information was wrong.

________________________________
Von: Anne Weber <notifications@github.com>
Gesendet: Freitag, 21. September 2018 09:31
An: dzhw/metadatamanagement
Cc: Birkelbach, Robert; Mention
Betreff: Re: [dzhw/metadatamanagement] Ensure variableMetadataExtractor is executable for all projects (#1755)


@rbirkelbach<https://github.com/rbirkelbach> No, it's still not working :(

[fehlermeldung]<https://user-images.githubusercontent.com/17066262/45866452-2ab90700-bd81-11e8-9bd1-bef0768d35db.png>

-

**Comment by anneweber** [comment]
![ticket](https://user-images.githubusercontent.com/17066262/46011744-2bc29f00-c0c7-11e8-9f11-3cf038c1e8a4.png)

@fbaillet @UteH @JohannaNiebuhr FYI

**Comment by anneweber** [comment]
@rreitmann @UteH Bei mir ist R 3.5.1 jetzt installiert und ich kann die Variablenmetadaten produzieren :thumbsup:
