### ISSUE TITLE
As the releasemanager I want to know how to deal with these repositories

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1759]
Is this gra2001? If so, why is it not in the mdm?
https://github.com/dzhw/abs2001/
What's this?
https://github.com/dzhw/sb1990-metadata/

Just to recap: This should be deleted, right?
https://github.com/dzhw/test2017-metadata

**Comment by svietgen** [comment]
abs2001 (Absolventenpanel) is gra2001, but we haven't started with data preparation yet. So there doesn't exist a metadata-file.

sb1990 (Studienberechtigtenpanel) is gsl1990. We haven't started with data preparation yet, but I think that some of our student assistants started to capture the question images. That may be the reason why there already exists a metadata-file. @kpstephan should know more about this.

When you don't need the test2017-file for test purposes you can delete the test2017-metadata-file.

**Comment by rreitmann** [comment]
@rbirkelbach can we close this now?
