### ISSUE TITLE
Bug: Subsequent questions are not displayed (prod and test system)

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#1760]
The subsequent questions are not displayed e.g. https://metadata.fdz.dzhw.eu/#!/en/questions/que-phd2014-ins1-1.4$?search-result-index=4 

This occurs in prod and test system.

**Comment by svietgen** [comment]
@rreitmann It works on the prod system but not on the test system.

**Comment by rreitmann** [comment]
@svietgen I had not deployed the test system. Now it should work on test as well.

**Comment by svietgen** [comment]
@rreitmann Yes, it now works on test and prod.
