### ISSUE TITLE
We need to get our metadata into google dataset search

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1778]
See here: https://www.blog.google/products/search/making-it-easier-discover-datasets/
I have only skimmed the blog post, but if this is what I think it is, this is *extremely* important.

**Comment by schellep** [comment]
@beirats-taskforce (@svietgen @anneweber?): könnte evtl. auch für die beiratsitzung relevant sein!

**Comment by anneweber** [comment]
Geben wir hiermit an @kpstephan weiter :)

**Comment by AndyDaniel1** [comment]
I just browsed a little bit through the documentation of Google. The recommended metadata scheme is  relative small and manageable but will serve its purpose. It has some similarities to the da|ra Scheme. 

Guide of Google: https://developers.google.com/search/docs/data-types/dataset

Google testtool for structured data: https://search.google.com/structured-data/testing-tool

The metadatenscheme Google uses/recommends: https://schema.org/Dataset

Google acquires the data via crawling. The usage of sitemaps is helpful to point at the relevant pages and to flag pages with equivalent information (sameAs).

**Comment by AndyDaniel1** [comment]
I changed the prio of this issue to 8 as part of the "make twos great again" (MTGA) agenda.
