### ISSUE TITLE
Refine handling of study.dataAvailability

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1780]
1. daras availibility tag needs to be "not available" if study.dataAvailibitlity is "in preperation" or "not available"
2. you cannot put data products into the shopping cart which are "in preperation" or "not available"

**Comment by rbirkelbach** [comment]
When product is in basket and study property gets changed back to unavailable it's still in the basket and can still be chosen.

**Comment by rreitmann** [comment]
Fixed test issue, closing without retest...
