### ISSUE TITLE
Bug: Internal Server Error when I open attachment

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#1782]
I changed and uploaded an attachment for the 20th Social Survey. When I try to open the attachment I get an Internal Server Error:

https://metadata.fdz.dzhw.eu/public/files/studies/stu-ssy20$/attachments/ssy20_MethodReport_en.pdf

**Comment by rreitmann** [comment]
Which browser did you use? I have reuploaded the file from here:
https://github.com/dzhw/ssy20-metadata/tree/master/data/study/attachments

And it works...

**Comment by svietgen** [comment]
I used Firefox.

Thanks for reuploading it - now I can open the file as well.

**Comment by rreitmann** [comment]
I cannot reproduce this anymore.
