### ISSUE TITLE
Send shopping cart via email

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1787]

**Comment by rreitmann** [comment]
send to dataservice at dzhw.eu
cc to user

**Comment by rreitmann** [comment]
During todays review the following improvements have been suggested:
- add study.title to dataproduct chooser
- show outdated version annotation on product card if and only if product version is outdated

**Comment by rreitmann** [comment]
During todays daily we have decided to sent an email to the user containing the information of the shopping cart. The same email will be sent to dataservice in cc. We will not fill in any pdf form...

**Comment by rbirkelbach** [comment]
Modal dialogue looks ugly in ie11.

**Comment by rreitmann** [comment]
Fixed test result.
