### ISSUE TITLE
Implement end to end test using protractor

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#179]
- has to run on travis after deployment
- test bookmarkable url
- test i18n
- test broken links

**Comment by dkatzberg** [comment]
The issue with defect travis buildings (coveralls 422 error) depends not specificly on our project: https://github.com/lemurheavy/coveralls-public/issues/713

I reported our status, too.

**Comment by dkatzberg** [comment]
no valid data is online. No specific tests on e.g. variables pages are available without valid data. these tests should be a new issue for later.

**Comment by rreitmann** [comment]
Some remarks:
- protractor.conf.js should be moved to /src/test/protractor
- you should not select elements you want to click on by bootstrap classes (e.g. 'dropdown-toggle' see loginHelper.js)
- pages of module 'findMissingTranslations' should not be exported (should be a param of testMissingTranslations)
