### ISSUE TITLE
As I data user I need a meaningful string for the shopping cart 

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1793]
The current string can be misleading for costumers (they might think that you cannot purchase any products at all right now). 

Please change the string from "Der Bestellvorgang wird demnächst implementiert..." to "Der automatisierte Bestellvorgang wird demnächst implementiert. Bitte klicken Sie links in der Leiste auf "Datenzugang" für weitere Informationen zum Bestellvorgang."

**Comment by UteH** [comment]
@AndyDaniel1 text alright?

**Comment by rreitmann** [comment]
Implement email within #1787
