### ISSUE TITLE
As a publisher I don't want users to order an older version of a product for no apparent reason

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1796]
We were discussing if we should display the versions of a product prominently in the product choosing pop up. 

We _do_ need to be able offer older versions (e. g. for reproducing publications based on older versions of a product) but we should not offer this on a regular basis as 
- we do not want users to work with older versions for no reason and 
- it is quite burdensome to for us to put together the data and documentation for older versions.

Users can ask for older versions via e-mail to dataservice@dzhw.eu. (should we put this annotation somewhere?)

We need a final decision on this.

**Comment by rreitmann** [comment]
Currently the default is to order the current version. In the future we could ask the user to confirm ordering of old versions...
