### ISSUE TITLE
As a user I want a comprehensive list of all studies available

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1797]
As we have more an more studies in the mdm the home page does not encompass all studies anymore. We were discussion if we need a list of all studies available in a more comprehensive overview (without authors and without a further description or with a more meaningful description.)

We discussed that we should not change the format of search cards on the home page of the mdm. Further, we were discussing if we should
- extract a compehensive list of the study titles on the website via an API and/or
- if we should change the descriptive string of the studies on the home page. We could not display an abbreviated version of the study.description but create a new attribute containing more relevant information

**Comment by rreitmann** [comment]
API need to show only released studies
