### ISSUE TITLE
As a publisher I want to deliver Studiendesign to the VFDB

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1801]
For the Verbund Forschungsdaten Bildung (VFDB) we need to describe our studies/surveys according to their core set of metadata. This controlled vocabulary is part of the set:
-	Experimentelles Design
-	Quasi-Experimentelles Design
-	Beobachtungsdesign
-	Fallstudie
-	Sonstiges

For now, we will deliver the metadata manually into their system (maybe later via an API). Atm, all of our studies can be described as "Beobachtungsdesign". Should we implement an attribute as above or just choose the Studiendesign "outside of the MDM"?

**Comment by rreitmann** [comment]
@UteH I cannot find this in the VFDB manual, can u help me?

**Comment by UteH** [comment]
@rreitmann the VFDB responded:

> Das ist ein Schreibfehler in unserer Anleitung.
> Studiensein ist optional und kann unter timeDimensionsfree eingetragen werden. 
> Wir schicken eine aktualisierte Fassung demnächst rum.

I think we can still ignore it as it is optional.
