### ISSUE TITLE
As a publisher I want to deliver timeDimension to the VFDB 

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1802]
For the Verbund Forschungsdaten Bildung (VFDB) we need to describe our studies/surveys according to their core set of metadata. This controlled vocabulary is part of the set:
- Längsschnitt
- Längsschnitt: Kohorten
- Längsschnitt: Trend/wdh. Querschnitt
- Längsschnitt: Panel
- Zeitreihen
- Querschnitt
- Sonstige

(based on http://www.ddialliance.org/Specification/DDI-CV/TimeMethod_1.2.html)

For now, we will deliver the metadata manually into their system (maybe later via an API). We could either map study.surveyDesign or change our study.surveyDesign.

**Comment by rreitmann** [comment]
Currently we have either 'Longitudinal.Panel' or 'CrossSection'. Shall we extent that list?

**Comment by rreitmann** [comment]
To summarize:
1. dara has a long list of possible study.surveyDesign's, VFDB has a different (possible subset) list
2. Simplest solution would be to map our "Panel" and "Cross-Section" to Dara's "Longitudinal.Panel" and "CrossSection"

@AndyDaniel1 and @UteH please decide what to do...

**Comment by rreitmann** [comment]
1. We will map our current study.surveyDesign to the VFDB ones.
2. We will create a new issue fur extending our domain model with the list above.

**Comment by svietgen** [comment]
@rreitmann @rbirkelbach I don't know what I should test.

**Comment by svietgen** [comment]
@rreitmann This works! But we only deliver the english term. If this is the intention, then the issue can be closed.

**Comment by rreitmann** [comment]
@svietgen This field is language independent. We deliver an identifier/code for the timeDimension. => Works as desired...
