### ISSUE TITLE
As a publisher I want to deliver collectionMode to the VFDB 

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1803]
For the Verbund Forschungsdaten Bildung (VFDB) we need to describe our studies/surveys according to their core set of metadata. This controlled vocabulary is part of the set:

**1 Interview**
1.1   Persönliches Interview
1.1.1   Persönliches Interview: CAPI (Computerunterstützte persönliche Befragung)   /CAMI (Computerunterstützte mobile Befragung)
1.1.2   Persönliches Interview: PAPI (Papierfragebogen)
1.2   Telefonisches Interview
1.2.1   Telefonisches Interview: CATI (Computerunterstützte telefonische Befragung)
1.3   E-mail Interview
1.4   Web-basiertes Interview
**2 Eigenständig auszufüllender Fragebogen**
2.1   Selbstausfüller: E-mail
2.2   Selbstausfüller: Papier
2.3   Selbstausfüller: SMS/MMS
2.4   Selbstausfüller: CAWI (Computerunterstütztes Web-Interview)
2.5   Selbstausfüller: CASI (Computerunterstützte Selbstbefragung)
**3 Fokusgruppe**
**4 Eigenständig durchgeführte schriftliche Aufzeichnung und/oder   Tagebücher**
**5 Beobachtung**
5.1   Feldbeobachtung
5.1.1   Teilnehmende Feldbeobachtung
5.1.2   Nicht-teilnehmende Feldbeobachtung
5.2   Laborbeobachtung
5.2.1   Teilnehmende Laborbeobachtung
5.2.2   Nicht-teilnehmende Laborbeobachtung
5.3   Computerbasierte Beobachtung
**6 Messungen und Tests**
6.1   Leistungs- und Kompetenztests
6.1.1   Paper & Pencil Test
6.1.2   Computerbasierter Test
6.2   Physische Tests
6.3   Psychologische Tests
6.3.1   Paper & Pencil Test
6.3.2   Computerbasierter Test
**7 Inhaltscodierung**
**8 Transkription**
**9 Kompilation**
**10 Synthese**
**11 Zusammenfassung**
**12 Aggregation**
**13 Simulation**
**14 Sonstige**

(based on http://www.ddialliance.org/Specification/DDI-CV/ModeOfCollection_1.0.html)

For now, we will deliver the metadata manually into their system (maybe later via an API). We could either map survey.surveyMethod (outside of the MDM) or change survey.surveyMethod.

Beware that qualitative studies are not well represented. WiNbus would simply be "1.1 Persönliches Interview", whereas now we call it "Pro­blem­zen­trier­tes In­ter­view".

**Comment by rreitmann** [comment]
We have a general problem here:
1. We do not have a field representing this in the surveys
2. We have surveys with multiple instruments (https://metadata.fdz.dzhw.eu/#!/de/surveys/sur-gra2009-sy2$) leading to multiple collectionModeType's which is not supported by dara.

**Comment by rreitmann** [comment]
@AndyDaniel1 and @UteH We need to discuss this soon, currently I think gra2009 is not filed correctly. The field surveyMethod (singular) has been used for **multiple** surveyMethod**s**....

**Comment by rreitmann** [comment]
1. We will map our current instrument.type's to the collectionModeType'S.
2. We will provide as many collectionModes as tehre are combinations of surveys and instruments.
3. We will create a new issue to offer instrument.type's based on the list above.

**Comment by rreitmann** [comment]
@UteH This issue means that studies which are released with version >= 1.0.0 must have an instrument. `win2015` does currently not have any instrument. What shall we do?

**Comment by UteH** [comment]
we need to talk to @DilekIkiz about this ... she will be back on Tuesday according to her calendar

**Comment by rreitmann** [comment]
I have implemented a first draft on a seperate branch. There are the following issues:
1. The controlled vocabulary of DARA is this one, it is incompatible with the one linked by @UteH: http://www.da-ra.de/fileadmin/media/da-ra.de/Technik/4.0/include/dara-collectionModeType-v4.xsd
2. We have not yet decided what we want to do with win2015, I suggest we use the complete controlled vocabulary from now on and win2015 creates an instrument. Thus there must be at least one instrument on release.
3. Currently we use the term PAPI for SelfAdministeredQuestionnaire.Paper which is not PAPI in the DARA sense (Interview.FaceToFace.PAPI)

**Comment by rreitmann** [comment]
I have talked to @UteH and we have decided to focus on the current data we have and the (minimal) requirements of the VFDB:
1. We will introduce a new instrument type "Interview" and map it to Interview.FaceToFace
2. win2015 needs to create an instrument of type "Interview"
3. post validation ensures that there is at least one instrument for versions >= 1.0.0
