### ISSUE TITLE
As a publisher I want to deliver geographicCoverages to the VFDB

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1804]
For the Verbund Forschungsdaten Bildung (VFDB) we need to describe our studies/surveys according to their core set of metadata. This controlled vocabulary is part of the set:

1.	geographicCoverageControlled = Land (z. B. „Deutschland“)
2.	geographicCoverageFree = kV VerbundFDB „Untersuchungsgebiet" (z. B. „Nordrhein-Westfalen“)

For now, we will deliver the metadata manually into their system (maybe later via an API). Atm, we do not have an attribute similar to geographicCoverages.

**Comment by rreitmann** [comment]
We could offer a field survey.population.geographicCoverage (I18nString). Currently this is a constant (Germany).

**Comment by rreitmann** [comment]
1. We need a field survey.population.geographicCoverages which is an array of GeographicCoverage objects.
2. Each object must contain one ISO 3166-1 alpha-2 code and can contain a freetext (I18nString)

**Comment by rreitmann** [comment]
@es-flavia one more remark:
- we should deduplicate geographicCoverage for the dara export
