### ISSUE TITLE
As a publisher I want to deliver resourceType+resourceTypeFree to the VFDB 

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1805]
For the Verbund Forschungsdaten Bildung (VFDB) we need to describe our studies/surveys according to their core set of metadata. This controlled vocabulary is part of the set:

- dara: resourceType AND resourceTypesFree / resourceTypeFree / typeName 
- Datentyp 

### 1. resourceType
resourceType | definition
-- | --
Collection | An aggregation of resources, which may encompass collections of one   resourceType as well as those of mixed types. A collection is described as a   group; its parts may also be separately described.
Dataset | Data encoded in a defined structure.
Text | A resource consisting primarily of words for reading.
deprecated; use Audiovisual   instead
Software | A computer program in source code (text) or compiled form.
Image | A visual representation other than text.
deprecated; use Audiovisual   instead
Audiovisual | A series of visual representations imparting an   impression of motion when shown in succession. May or may not include sound.
InteractiveResource | A resource requiring interaction from the user to be understood, exe-   cuted, or experienced.
DataPaper | A factual and objective publication with a focused intent to identify   and describe specific data, sets of data, or data collections to facilitate   dis- coverability.
Event | A non-persistent, time-based occurrence.
Model | An abstract, conceptual, graphical, mathematical   or visualization model that represents empirical objects, phenomena, or   physical processes.
PhysicalObject | An inanimate, three-dimensional object or substance.
Service | A system that provides one or more functions of value to the end-user.
Sound | A resource primarily intended to be heard.
Workflow | A structured series of steps which can be executed to produce a final   outcome, allowing users a means to specify and enact their work in a more   reproducible manner.
Other | If selected, supply a value for resourceTypeFree.
(Source of the term and definition of the da|ra resourceType is the DataCite Metadata Schema Documen- tation, version 4.1, https://doi.org/10.5438/0014.)

### 2. Datentyp
Datentyp |  
-- | --
Umfrage-   und Aggregatdaten |  
Qualitatives   nicht oder gering standardisiertes Datenmaterial |  
Kompetenz-   und Leistungsdaten |  
Sonstiges   Datenmaterial |  

For now, we will deliver the metadata manually into their system (maybe later via an API). We could either map our information or create new attributes.

**Comment by rreitmann** [comment]
We do always send resourceType=dataset to dara. The rest needs to be done manually.

**Comment by UteH** [comment]
reopen because we need to deliver the Datentyp to ResourceTypeFree per project.

**Comment by rreitmann** [comment]
Ok, but:
survey 1 data type = quanti, survey 2 data type = quali => ??

1. Umfrage- und Aggregatdaten; Qualitatives nicht oder gering standardisiertes Datenmaterial
2. Sonstiges Datenmaterial

**Comment by rreitmann** [comment]
To summarize:
1. resourceType will be hardcoded to "Dataset"
2. We want to compute the resourceTypeFree from the surveys of the study:
   1. If all surveys have dataType "Quantitative Data" we will use "Umfrage- und Aggregatdaten"
   2. If all surveys have dataType "Qualitative Data" we will use "Qualitatives nicht oder gering standardisiertes Datenmaterial"
   3. @AndyDaniel1, @UteH Which of the following options shall we use if there surveys of mixed dataTypes?
       1. Umfrage- und Aggregatdaten; Qualitatives nicht oder gering standardisiertes Datenmaterial
       2. Sonstiges Datenmaterial

**Comment by rreitmann** [comment]
Decision: 2.iii.a

**Comment by svietgen** [comment]
When I send surveys with dataType "Qualitative Data" to dara, then it says "Kompetenz- und Leistungsdaten". Shouldn't that be "Qualitatives nicht oder gering standardisiertes Datenmaterial"?
