### ISSUE TITLE
As a publisher I want to deliver contributor to the VFDB 

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1806]
For the Verbund Forschungsdaten Bildung (VFDB) we need to describe our studies/surveys according to their core set of metadata. This is part of the set:

> Definition contributortype distributor: “Institution tasked with responsibility to generate/disseminate copies of the resource in either electronic or print form.” (Pflicht)

Do we already deliver this field? 
We need to deliver: 
- Contributer Type: Distributer 
- Institution: 
  - Forschungsdatenzentrum für ~die?~ Hochschul- und Wissenschaftsforschung (FDZ des DZHW)
  (**not?:** Forschungsdatenzentrum des Deutschen Zentrum für Hochschul- und Wissenschaftsforschung (FDZ des DZHW) 
  - not in English

For now, we will deliver the metadata manually into their system (maybe later via an API). 

*******************
**da|ra 4.0:**
contributors / contributor / institution / institutionName 
AND contributorType  = 4 (Distributor)

**Comment by rreitmann** [comment]
We need **one** institutionName. There is no de/en....

**Comment by rreitmann** [comment]
To summarize:
@AndyDaniel1, @UteH This is simple. We just need to decide on one institutionName:
1. FDZ des DZHW
2. DZHW GmbH
3. ???

**Comment by rreitmann** [comment]
We take: "FDZ des DZHW"
