### ISSUE TITLE
As a publisher I want to deliver Veröffentlichungsdatum to the VFDB 

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1807]
[I see](https://www.da-ra.de/dara/search/search_show?res_id=567555&lang=en&mdlang=en&detail=true&q=defaultSearch%3A%28DZHW%5C-Absolventenpanel+2009%29&personal=false&widget=&widgetclient=) that we already deliver this information to dara. Can I see the date in the mdm aswell? If not, should we make it visible?

*******************
**da|ra 4.0:**
publicationDate

**Comment by rreitmann** [comment]
Currently the dara publicationDate is updated on every dara update. Therefore I would say it is not the publicationDate of the study but the publicationDate of the DOI. Shall we change this to the first releaseDate (1.0.0)?

**Comment by UteH** [comment]
We want the date of the current release

**Comment by rreitmann** [comment]
@UteH I think we can close this since we talked about it yesterday and decided to keep the current state....

**Comment by UteH** [comment]
### for the recored / my memory:
We said that we can deliver the currentRelease (as we do already). The currentRelease may 
- either be a real version update or 
- only a metadata update which is not reflected in a version update. 

But this is the best Date we can deliver right now. And this is ok. 

We could tell this to Andy (fhi) in the next refinement and then close in the refinement.

***************************

Above, I asked if we should make the currentRelease visible in the MDM, but we should create a new issue for that.
