### ISSUE TITLE
As a publisher I need to store projects like the SLC in a comprehendable and efficient way

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1809]
We were discussing how projects like the SLC can be stored in the MDM properly. Projects like the SLC will generate several products that should be clustered in a comprehendable way for users.

We will have several products (as studies), such as
- pooled datasets containing 
  - serveral waves
  - serveral cohorts
- cohorts (consisting of several waves)
- waves (consisting of several surveys?)

This picture should illustrate the possible products
![grafik](https://user-images.githubusercontent.com/18573122/46723409-0cf00b00-cc78-11e8-8fde-c6a8603a44b3.png)

For now, we concluded that we can store the SLC in the current system. Is this the case? 

We should rethink the name of "study.studySeries" (Studienreihe)?

**Comment by rreitmann** [comment]
I agree that depending on how we shape the data products we would have several SLC studies.
IMHO "study series" is not so bad...

**Comment by rreitmann** [comment]
We wait for a better string than "study series"...
