### ISSUE TITLE
As publisher and for the "export" to VFDB I want to see all attributes of the json behind the study details page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1810]
We could offer a JSON viewer on the details pages for publishers and admins. This would help testers as well....

**Comment by rreitmann** [comment]
@UteH Check if all attributes for the VFDB are available in the study source.

**Comment by UteH** [comment]
Every attribute that we need for the VFDB that we already have is part of the the study source :tada:

With the new attributes we don't know yet if it will be part of the study source.

**Comment by rreitmann** [comment]
JSON viewer will only be visible for publishers but on all details pages.

**Comment by rreitmann** [comment]
@es-flavia see my remarks in PR #1893
