### ISSUE TITLE
Merge user docs into metadatamanagement repository

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1818]
- get the docs from Anne G 
- migrate to readthedocs (https://readthedocs.org/)
- integrate docs from metadatamanagement-io

**Comment by rbirkelbach** [comment]
User doc is here: `\\faust\Abt4\FDZ\Mitarbeiter_innen\Anne_G\Metadatendoku\Erläuterungen_Metadatenabgabe_1-2-0.docx
 `
