### ISSUE TITLE
variableMetadataExtractor missing_conditions_numeric "mehr Elemente gegeben als zu ersetzen Sind"

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1819]
scs2016 throws an error. I need to check whether this is due to a real bug or problem sits in front of computer and has not setup the missing conditions properly.

Complete error message:

```
Fehler in private$missing_conditions[["numeric"]] = missing_conditions_numeric : 
mehr Elemente gegeben als zu ersetzen sind
Ruft auf: variable_metadata_generation -> <Anonymous> -> <Anonymous>
```

**Comment by svietgen** [comment]
Thanks for taking care of the problem. The correct "conditions" file is one level higher in the "data-raw" folder. I had edited the other table to see when the problem occurres (I therefore deleted some rows).
