### ISSUE TITLE
Write announcement for usability study

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1830]

**Comment by rbirkelbach** [comment]
@AndyDaniel1 please close this issue if you're fine with the text.

**Comment by rreitmann** [comment]
@AndyDaniel1 What is blocking the progress on this issue?

**Comment by AndyDaniel1** [comment]
@rreitmann my limited time ressources. I hope that I will complete the announcement in the next two weeks.

**Comment by UteH** [comment]
@AndyDaniel1 can I help you with something?
