### ISSUE TITLE
Logging of Search Variables and visited subpages

### ISSUE THREAD

**Issue by schellep** [dzhw/metadatamanagement#1832]
As I mentioned today, for several reaseons it would be helpful to know more about the users search phrases and intentions. 

- What are the [userstories/-journeys](https://github.com/dzhw/Effizienzprojekt_Modul_E_F_G/issues/58)?
- to know more about the users [language/vocabulary](https://github.com/dzhw/Effizienzprojekt_Modul_E_F_G/issues/57)
- to know more about there search strategies

- i.e. for the improvement of the usability of the 
    1. MDM
    2. fdz.dzhw.eu

**Comment by schellep** [comment]
@rreitmann, I am checking Issues that I opened. Is it ok to leave this in the backlog ?

**Comment by rreitmann** [comment]
@schellep Yep, this is still relevant too.
