### ISSUE TITLE
As a public user I want to know which index is used for long format data

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1834]
Long format is fine and all, but it could be long with regards to many different indices (and wide in other regards). We need to talk about this. For example, a dataset could be long with regards to a context variable (as is often done in multilevel modeling) but wide with regards to time. So we also need a "both" option or something more fine-grained. Or we can drop this detail, as it can be very confusing (especially if the data is not provided in a tidy format).

**Comment by rreitmann** [comment]
The "index"-variables should be documented in the DMB.
