### ISSUE TITLE
As data provider I want to edit relatedPublications details in a form

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1838]
I am not sure about the process, but @kpstephan expressed this idea casually today and I wanted to discuss this.

**Comment by rreitmann** [comment]
We will extend the study edit page in order to assign relatedPublications to the study. We will remove the import of study ids from the CITAVI import.

**Comment by rreitmann** [comment]
I am meanwhile convinced that the idea of extending the study edit page is a bad idea:
1. Editing a study domain object does not cover related publications
2. You can be ready with editing the study and you want to assign related pulbications later.

I suggest to add a "publications"-card to the project cockpit (users can mark them ready/not ready like the others). An "add" button opens a modal dialog in which the user can search for a related publication and add it to the study. @UteH let me know your thoughts on this...

**Comment by rreitmann** [comment]
@rbirkelbach Retest after automatic deployment
