### ISSUE TITLE
Document Project Cockpit

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1839]
Currently, [we say](https://metadatamanagement.readthedocs.io/de/latest/metadatenabgabe.html#neues-projekt-anlegen), data providers create their project in the mdm. In another discussion we said, that the publisher should create the project 

-> DAP-ID accoding to our wishes/standards or SISO?

**Comment by rreitmann** [comment]
@UteH That has changed with the project cockpit. Publishers create a project and assign a team for the project. See #1875

**Comment by UteH** [comment]
Yes, I would want it this way, too. The documentation is not yet up to date?
https://metadatamanagement.readthedocs.io/de/latest/metadatenabgabe.html 

or will the documentation be changed after the final implementation of the cockpit?

**Comment by rreitmann** [comment]
@rbirkelbach 
I have merged your changes into development, however we have to talk about the chapter for data providers, it currently contains misleading texts and content which is only relevant for publishers.
