### ISSUE TITLE
fix bugs of dataset report

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1841]
- [ ] title may span two pages
- [x] no table of contents
- [ ] page break after "variables"?
- [x] delete blank space before footnote, e. g. 
![image](https://user-images.githubusercontent.com/18573122/48353941-d8190e80-e690-11e8-8137-f2d02776102c.png)

**Comment by rbirkelbach** [comment]
@UteH what do you mean with pagebreak after variables? New page after each variable?

**Comment by UteH** [comment]
@rbirkelbach no, after the heading "1 variables" there seems to be a page break?

**Comment by rbirkelbach** [comment]
Okay, thanks. I see what you meant! :)

**Comment by rbirkelbach** [comment]
Won't fix pagebreak after variables (discussed with René).

**Comment by UteH** [comment]
never or not within this issue?

**Comment by rbirkelbach** [comment]
Definitely not currently. It is very difficult and has some other implications.
