### ISSUE TITLE
As publisher I want to assign data providers and other publishers to a project

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1842]
- publishers will always see all released and unreleased projects
- data providers must only see "their" projects and the data of "their" projects
- a publisher can always add/remove data providers and publishers (himself only if there is another)
- a data provider can always add/remove data providers (himself only if there is another)
- send an email to the added/removed users in the language of the user
- only publishers may delete projects (which have not been released yet)

**Comment by rbirkelbach** [comment]
In IE 11 it looks weird and I cannot select other users. See screenshot
![image](https://user-images.githubusercontent.com/1101547/48948915-7f6e2f00-ef36-11e8-80f0-50078a869c76.png)
