### ISSUE TITLE
As the release manager I want an up to date draft of a possible versioning concept

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1847]

**Comment by UteH** [comment]
PS: wir hatten ja auch über errata statt neuer Version gesprochen, zB 
- gesis https://dbk.gesis.org/dbksearch/sdesc2.asp?no=4574&search=allbus&search2=&field=all&field2=&DB=d&tab=0&notabs=&nf=1&af=&ll=10

**Comment by rbirkelbach** [comment]
The current way how to count the version numbers are here: https://github.com/dzhw/versionierungskonzept
We still need to find a workflow where to put specific files.

**Comment by svietgen** [comment]
@rbirkelbach What's the current status? Is there an issue about the workflow problem? I still don't know which files I have to store at Faust/Github or what I have to do when there are modifications.
