### ISSUE TITLE
Dataset report: change header and footer

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#1850]
The content of the header line is too long. Can you insert a line break or change the content of the header?
Problem appears for example at cmp2014 (because of the long study title).

header:
![image](https://user-images.githubusercontent.com/18573122/48353006-98512780-e68e-11e8-90c0-330b72c48d37.png)

footer:
![image](https://user-images.githubusercontent.com/18573122/48352941-6dff6a00-e68e-11e8-9cae-aecc11b254a1.png)

**Comment by rreitmann** [comment]
@rbirkelbach Try to truncate this with latex...

**Comment by rbirkelbach** [comment]
@rreitmann maybe we can have a look together tomorrow and find out where the header and footer are defined. Because I don't want to truncate on the title page, just in the header/footer.

**Comment by UteH** [comment]
maybe also look at #1857, maybe too much
