### ISSUE TITLE
Schrödinger's missing archeology (because of variablemetadataextractor upgrade)

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1853]
It's unclear whether and if yes where the missing categories of old studies reside.

**Comment by svietgen** [comment]
You will find the information in the data and method report (chapter 6.7). The missing values used are highlighted in the overview table.

**Comment by rbirkelbach** [comment]
thanks!

**Comment by rbirkelbach** [comment]
# todo
- [] gra2005
- [] gra2009
- [] phd2014
- [] ssy19
- [] ssy20
