### ISSUE TITLE
Dataset report: change format of header?

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1857]
https://metadata.fdz.dzhw.eu/public/files/data-sets/dat-gra2005-ds1$/attachments/dsreport-gra2005-ds1.pdf page 4

![image](https://user-images.githubusercontent.com/18573122/48353229-3218d480-e68f-11e8-85f0-74a30f078298.png)

ideas (please evaluate):

- keep "Variablendokumentation" OR "Datensatzreport"?
- we don't need the number (1.3) in the header (?)
- parting line between the two "variables" in the header, something like "|" or else
  - Variablendokumentation: Datensatzreport DZHW-Absolventenpanel **|** 20051.3 astu011a (1. Studium: Beginn (Semester))
- do we need the same information in header AND footer?
  - header:
    ![image](https://user-images.githubusercontent.com/18573122/48353006-98512780-e68e-11e8-90c0-330b72c48d37.png)
   - footer:
    ![image](https://user-images.githubusercontent.com/18573122/48352941-6dff6a00-e68e-11e8-9cae-aecc11b254a1.png)

**Comment by rreitmann** [comment]
We need to ensure that the long information is only used in the header of each page and that the header truncates the string...
