### ISSUE TITLE
As public user I want to see the release notes of projects

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1862]
Atm, public users do not know what has changed with a version update. In github, version updates are documented (and sent only to data users of the specific project)
- e. g.: https://github.com/dzhw/gra2009-metadata/releases 
- e. g.: https://github.com/dzhw/phd2014-metadata/releases 

#### ideas
- Aren't there release notes in the mdm aswell? (not sure) 
- unify the release notes in the mdm and github if neccessary
- standardize the release notes in github
- find a way to link the release notes in github to the mdm

**Comment by rbirkelbach** [comment]
@svietgen fixed.

**Comment by rreitmann** [comment]
We can link to the github release notes (e.g. https://github.com/dzhw/phd2014-metadata/releases/tag/2.0.0) from the study details page. @rbirkelbach needs to beautify the current release notes in order to make the understandable for data users...

**Comment by UteH** [comment]
we could also send them to dara?

**Comment by svietgen** [comment]
In the meantime we decided to have our release notes only on the data package site (we have a template now which every project is using). We are not using the tag-function on github (anymore).

The only open point is Ute's dara-question.
