### ISSUE TITLE
Assign correct user roles for each project

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1882]

**Comment by svietgen** [comment]
@rbirkelbach I'm done. Dilek is not registered yet and should be added to win2015.

**Comment by rbirkelbach** [comment]
Thank you!

________________________________
Von: Sandra Vietgen <notifications@github.com>
Gesendet: Montag, 3. Dezember 2018 14:51
An: dzhw/metadatamanagement
Cc: Birkelbach, Robert; Mention
Betreff: Re: [dzhw/metadatamanagement] Assign correct user roles for each project (#1882)


@rbirkelbach<https://github.com/rbirkelbach> I'm done. Dilek is not registered yet and should be added to win2015.

-
