### ISSUE TITLE
create repository for json2excel-questions script (zofar related)

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1896]
See https://github.com/dzhw/FDZ_Allgemein/issues/274

Needs packrat for dependencies.

**Comment by rbirkelbach** [comment]
@UteH I cannot find this folder: //faust/Abt4/FDZ/Drittmittelprojekte/Effizienzsteigerung_FDZ/Modul H/2_Maßnahmen/Issue_89/MDM_ifq_Update02102018/MDM/json/questions/ins1
Are you available to walk me through the script/folder structure?

**Comment by UteH** [comment]
@rbirkelbach i think this is now `\\faust\Abt4\FDZ\8_Infrastruktur\Zofar-Export\2_Maßnahmen/Issue_89/MDM_ifq_Update02102018/MDM/json/questions/ins1`

**Comment by rbirkelbach** [comment]
I'll already change the dependencies in this issue

**Comment by rbirkelbach** [comment]
for future references: https://martin.hoppenheit.info/blog/2014/mounting-windows-network-shares-in-linux/

**Comment by rbirkelbach** [comment]
@UteH please test the output, see here: https://github.com/dzhw/questionJsonToExcel/tree/master/output
Also, do you think it's okay to have a setup where the jsons are stored locally instead of faust? this would make things much easier.

**Comment by UteH** [comment]
@rbirkelbach I deleted the weird characters in a new branch. Please pull and generate a new excel to test https://github.com/dzhw/questionJsonToExcel/compare/ute?expand=1

**Comment by rbirkelbach** [comment]
please test again

**Comment by UteH** [comment]
deleted another one, please create again

**Comment by rbirkelbach** [comment]
and it's your turn again ;)

**Comment by UteH** [comment]
@rbirkelbach still the error messages :/ thus, i am still not sure if the excel error message is a general problem or a specific problem of the project :/
(maybe it is because of some accent (`) that excel has trouble with (had the same problem with Stata))

maybe just try another project, such as `\\faust\Abt4\FDZ\4_Datenaufnahme\Intern\Absolventenpanel\gra2005\4_Dokumentation\4_2 Metadaten\questions\_alt\2018-02-19\Export`?

**Comment by rbirkelbach** [comment]
Excel has trouble importing the created excel file, but this is due to wrongly encoded JSONs provided by zofar.
