### ISSUE TITLE
As data provider and as publisher I want to delete all questions and variables with one click

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1902]
For variables and questions (excel/json interfaces), I don't know how to delete previously uploaded variables or questions. I do not want to replace them, but just delete them all.

**Comment by rreitmann** [comment]
We will add a delete all button to all tabs in the search...

**Comment by rbirkelbach** [comment]
I don't see the delete button in the search (ie).

**Comment by rbirkelbach** [comment]
I also cannot reproduce it anymore. Weird. I'll close this issue.
