### ISSUE TITLE
As public user I might want more information/explanation on a beta release

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1908]
this is what a beta release looks like right now. 
![grafik](https://user-images.githubusercontent.com/18573122/49659862-6b055880-fa45-11e8-8e31-91d6be4db572.png)

I am not sure if it is intuitive for users what is going on. @AndyDaniel1 will this be part of the usability test? Then we could wait for the results.

### ideas
- people might not understand what a "beta release" is
  - use the term "preregistration"?
- we are not planning to update the version number of a beta release -> make it possible to not write a number but just "beta" or something else?
- enhance visibility of status "beta" or "data not yet available" or else
- "template text" for annotations of a beta release - what kind of information do we have to provide?
  - expected publication date/year?
  - ...

**Comment by rreitmann** [comment]
1. Doi: Die Studie ist noch nicht veröffentlicht und hat daher noch keine DOI,
2. "Verfügbare Wellen" will be renamed to "Wellen" and will be hidden if zero.
