### ISSUE TITLE
As data provider I want a welcome dialog giving information about how to use the MDM

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1909]

**Comment by rreitmann** [comment]
@UteH We need to talk about the content of this page...

**Comment by UteH** [comment]
ok, we should schedule a discusson about this with @danbfdz and @AndyDaniel1

**Comment by rreitmann** [comment]
We will implement a mockup and demonstrate it during the sprint for getting feedback...

**Comment by rreitmann** [comment]
@UteH Get in touch with me as soon as you have time and I will demonstrate the current state to you...

**Comment by rreitmann** [comment]
@es-flavia Please ensure that the frontend components are under usermanagement/welcome/{views,services,...}

**Comment by UteH** [comment]
@rreitmann now?

**Comment by rreitmann** [comment]
@es-flavia I have already taken care of moving the welcome components...
