### ISSUE TITLE
delete excel upload functionality in documentation (study, survey, instrument)

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1919]

**Comment by rreitmann** [comment]
Here are my review remarks:
- [ ] Datasets cannot be uploaded anymore, please ensure that the documentation does not state something different (multiple places currently)
- [ ] Picture 7 and 31 show an unsupported Instrumentupload-Folder
- [ ] Table one contains string "Erhebungs- instrumente"

@rbirkelbach I have already merged this into development. Please fix the review remarks there....

**Comment by rbirkelbach** [comment]
I didn't make a new screenshot of a folder, but wrote that it's not needed for instruments anymore. I made the mistake to work on a single branch for merging the io wiki with rtd though, so this pr is a bit messy. Apologies for that.
