### ISSUE TITLE
As a publisher I want an overview of project name + release status

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1925]
Some of the @dzhw/fdz-sowis indicated in the data prep jour fix that they want something like that.

**Comment by rreitmann** [comment]
I guess we need a project list view for publishers with:
project name, release status, assigned group, state of the different metadata types

**Comment by svietgen** [comment]
Everything works fine. There is just one (hopefully) little thing: The scroll bar moves up if no icon is displayed for variables (or the other icons accordingly).
![Issue_Chrome](https://user-images.githubusercontent.com/22055122/54430549-3bd94400-4724-11e9-8599-0e8e17985557.PNG)
Chrome
![Issue_Firefox_IE](https://user-images.githubusercontent.com/22055122/54430563-4562ac00-4724-11e9-85c5-04859fae42ca.PNG)
Firefox/IE/Edge
