### ISSUE TITLE
Refactor project cockpit directives

### ISSUE THREAD

**Issue by es-flavia** [dzhw/metadatamanagement#1928]
Some project cockpit directives copy the scope of project-cockpit.controller. They should instead isolate their scope and reduce bindings only to the required fields.

(See es-flavia/issue1844-cleanup)

**Comment by rreitmann** [comment]
We need to test the complete project handling due to this.

**Comment by rbirkelbach** [comment]
If I click on the project cockpit button after having edited something (it doesn't matter what I edited) I get a 404 toast, but the project cockpit shows up correctly otherwise:  "The requested page has not been found (404). "

**Comment by rbirkelbach** [comment]
images are missing

**Comment by rreitmann** [comment]
@rbirkelbach Fixed, please retest...
