### ISSUE TITLE
As a public user I want to know the original language of the files from the data providers

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1932]
They will want to know the original language because sometimes language carries some nuance which might be mistranslated.

**Comment by rreitmann** [comment]
Question pages contain images of the original questionnaire...

**Comment by rreitmann** [comment]
We could add a new array originalLanguages to the instrument.

@rreitmann Check with dara for an appropriate field name.

**Comment by rreitmann** [comment]
Dara does not care about the languages of the instrument which was used in a survey (collection in dara). So we can call the field `instrument.originalLanguages`. It is mandatory and must contain at least one entry....

**Comment by rbirkelbach** [comment]
The selection field is truncated in ie.
![image](https://user-images.githubusercontent.com/1101547/85271279-dde4f180-b47a-11ea-81b8-b300a42acfd1.png)
