### ISSUE TITLE
no citation text is provided

### ISSUE THREAD

**Issue by schellep** [dzhw/metadatamanagement#1933]
---------------------------------
Quelle:
https://metadata.fdz.dzhw.eu/#!/de/data-sets/dat-cmp2014-ds1$?search-result-index=1
---------------------------------

When looking for the releas year i discovered, that kompaed has no suggestion for the citation text.

**Comment by rreitmann** [comment]
@schellep We are working on it: #1917

**Comment by rbirkelbach** [comment]
done
