### ISSUE TITLE
Icons (study, ....) are missing in IE

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1976]
On initial load they are present, but when u use the app for a while they disappear....
![image](https://user-images.githubusercontent.com/12323832/51477627-511b9d00-1d89-11e9-81c6-9292eb96a43f.png)

**Comment by rreitmann** [comment]
The issue was introduced with an update of angular material. Rolling back to 1.1.10 helps for the moment but we schould get in touch with the material guys. The issue was introduced with https://github.com/angular/material/commit/47527f245acc8382a69a42a07989fd5f646e9744

**Comment by Systemcluster** [comment]
Fixed in https://github.com/dzhw/material/commit/c8582ea259695e5b4719d0c6e73b3294994bb6c9, waiting for merge. (ref. https://github.com/angular/material/issues/11603)
