### ISSUE TITLE
As public user I want to order data products of all released studies

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1988]
Currently it is possible to release (not beta) studies without surveys and data sets. However in order to be able to put those into the shopping cart we need at least one data set (because that is where the access ways are maintained).

@UteH Any idea?

**Comment by UteH** [comment]
@rreitmann the easiest way would be to make study, survey, dataset (and instrument) mandatory for a full realease (not beta), right?

If so, I would talk to Dilek if this would work for qualitative projects aswell and decide also so instrument.

**Comment by rreitmann** [comment]
@UteH Yep, that would be fine. I do not think that we need an instrument...

**Comment by UteH** [comment]
@svietgen (Dokumentationsstandard) and @DilekIkiz (Quali) agree that we could make study, surveys and dataSets mandatory for a full release.

(@AndyDaniel1 fyi)

**Comment by rreitmann** [comment]
We will implement a new post validation step for versions >= 1.0.0

**Comment by UteH** [comment]
with clicking on the **release button** (not post validation button), this post validation step is initiated for versions >= 1.0.0. It checks whether study, survey and DataSet exist and are valid.
