### ISSUE TITLE
As a publisher I want to deliver universes to the VFDB

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1995]
We need to deliver Sampling of all surveys to dara in order to be harvested by VFDB.
![grafik](https://user-images.githubusercontent.com/18573122/51893363-ebd93480-23a4-11e9-8025-199dafbd491b.png)

**Comment by rreitmann** [comment]
To summarize:
1. survey.population.title can be removed from the domain model
2. survey.population.description must be mandatory in all languages
3. survey.population.description will be used in both languages

**Comment by rreitmann** [comment]
We need to remove all existing population.titles:
`db.getCollection('surveys').update({}, {$unset: {'population.title':1}} , {multi: true});`

Ensure that population.description is currently set in both languages:
`db.getCollection('surveys').find( { 'population.description.en' : { $exists: false } } )`
`db.getCollection('surveys').find( { 'population.description.de' : { $exists: false } } )`

Elasticsearch will be reindexed as well...

**Comment by rreitmann** [comment]
@UteH We have a small problem here:
DARAs universes must only contain one universe per language. Thus we have to concatenate our survey.population.description's. Any suggestions on how to do this?

**Comment by rreitmann** [comment]
I suggest:
```
survey[1].title: survey[1].population.description
survey[2].title: survey[2].population.description
...

```
