### ISSUE TITLE
Project settings are changeable after project release

### ISSUE THREAD

**Issue by es-flavia** [dzhw/metadatamanagement#1998]
It is possible to change required fields and ready state for said fields in the project cockpit after a project has been released.

Desired changes:
- Disable modification of required fields in project settings and the metadata state fields on the status page.
- It should still be possible to add (but not remove) users as publishers or data providers (under the current rule set).
- It should still be possible to unrelease a project.

**Comment by rreitmann** [comment]
- expected metadata must not be changed as well
