### ISSUE TITLE
Automatic HTML5 W3C validation

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2]
As developers we want a unit test which ensures that all pages contain valid HTML5 in order to ensure cross browser compatibility.

**Comment by rreitmann** [comment]
@dkatzberg please provide your investigation results

**Comment by dkatzberg** [comment]
My investigation results:
https://github.com/WolfgangFahl/w3cValidator​
http://w3c.jcabi.com/index.html​
https://about.validator.nu/htmlparser/

**Comment by limouri** [comment]
Not found pages under this urls:
https://github.com/WolfgangFahl/w3cValidator​
http://w3c.jcabi.com/index.html​

**Comment by dkatzberg** [comment]
The first url works. I cheked the link. If it does not work, use google search and put the link into the search box. You will find the correct github project with the exact same link. I do not know why the link does not work correctly.

The second link works yesterday perfectly, too. Try this: http://w3c.jcabi.com/
