### ISSUE TITLE
Refine documentation for data providers

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2008]
Generally we need to ensure that the documentation helps new data providers:
- [x] register: the data provider will receive an activation link which she has to click, after being assigned to a project she will get another email, after the project is assigned to the data providers group she will get another email and can start working...
- [x] project creation: project creation (and id generation) is irrelevant for the user, however project ping pong between data providers and publishers until it is finally released needs to be described
- [x] project cockpit settings: Screenshot shows state for publishers
- [x] project cockpit status: Screenshot should show a project which is assigned to the data providers and is empty
- [x] Domänenmodell: is too much for a data provider
- [x] Create Study,...: The primary way for data providers to create a study (survey, data set, instrument) is through the project cockpit. This should be documented as well as the alternate way via the search
- [x] questions: question type "Undocumented" is missing, generally I do not think that the question process with excel and jsons and R-scripts and zofar should be documented here
- [x] variables: same like questions, document the process for data providers instead
- [x] related publications: same like questions and variables, document the process for data providers instead

**Comment by rbirkelbach** [comment]
If you want to you can already read

**Comment by rbirkelbach** [comment]
@dzhw/fdz-sowis please help me out:

- How do primary research projects send us question metadata?
- Do they provide us with any information on variables? E.G. do they provide the excel sheet?
- How are they supposed to send us related publications?

**Comment by rbirkelbach** [comment]
we decided to move out questions/variables and related publications because the processes are currently not well defined

**Comment by rreitmann** [comment]
@rbirkelbach For the future, please name your branch `rbirkelbach/issue2008` and put `#2008` in your commit messages!
