### ISSUE TITLE
Test questionexcel to json script with excel file created by questionjsontoexcel

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2018]

**Comment by rbirkelbach** [comment]
Can the question excel to question JSON script deal with the excel file generated by questionjsontoexcel r-script if the zofar JSONs have weirdly encoded characters?

**Comment by rreitmann** [comment]
We want one repository: questionMetadataPreperation

**Comment by rbirkelbach** [comment]
I'll have a meeting tomorrow with @UteH to discuss it further.

**Comment by rbirkelbach** [comment]
See here: https://github.com/dzhw/questionMetadataPreperation/pull/7

**Comment by rreitmann** [comment]
Currently we get question metadata and question image metadata from zofar. After running question_jsons_to_excel the image metadata is lost.
