### ISSUE TITLE
As publisher I want to deliver samplings to the VFDB

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2023]
Currently we do not have any controlled vocabulary for survey.sample. However the VFDB want these terms:
https://mdr.iqb.hu-berlin.de/#/catalog/1d791cc7-6d8d-dd35-b1ef-0eec9c31bbb5

We need to 
1. Create a mandatory dropdown on the survey edit page where the user can select one of these.
2. Replace existing survey.sample's with this
3. Export it to dara.

**Comment by rreitmann** [comment]
Just a remark: Dara does not enforce any controlled vocabulary here...

**Comment by rbirkelbach** [comment]
- win2015: Non-probability Sample: Purposive Sample, ggfs auch Non-probability Sample: Availability Sample

**Comment by rreitmann** [comment]
@rbirkelbach We need to migrate all existing surveys => I need a list of valid sample procedures for all surveys in the prod system...

**Comment by rbirkelbach** [comment]
@AndyDaniel1 What do you think -- which sampletype corresponds best to gsl2008? 

> Aufgrund  fehlender  oder  nicht  zugänglicher  Listen von  Studienbe-rechtigten auf Individualebene war es nicht möglich, eine einfache Zufallsstichprobe zu ziehen. So mussten  die  Individuen  über  die Schulenrekrutiert  werden. Als  Stichprobendesignwurde ein disproportionalgeschichtetes  Klumpenstichprobenverfahren als  Spezialfall  einer  mehrstufigen Zufallsauswahl  (vgl.  Häder,  2015, S.  169) gewählt.  DieSchulen bzw.  Schulzweige26stellen  dabei die „primary sampling units“ (Klumpen), die Studienberechtigtendes  Jahrgangs  2008  die „se-condarysamplingunits“ innerhalb dieser Klumpendar.27Die Auswahlgesamtheitbildete  eine Liste mit allen relevantenSchulen bzw. Schulzweigen. Die Schichtung erfolgte anhand der Merk-male Bundesland und Schultyp. Innerhalb der Schichten wurden Ziehungsquoten für die Klumpen undIndividuen festgelegt, die sich zum einen an der Verteilung des Studienberechtigtenjahrgangs2004/2005 laut amtlicher Statistik orientierten und zum anderen die Rücklaufquoten der letzten Erhebungen  berücksichtigten.  Im  Zuge  dessen  erhielten  Studienberechtigte  aus  Bremen,  Ham-burg und dem Saarland sowie Schülerinnen und Schüler von Abendgymnasien und -kollegs über-proportionale Auswahlwahrscheinlichkeiten, um in diesen Gruppen ausreichend große Fallzahlen zu generieren. Im  Rahmen  der  praktischen  Durchführung  des  Ziehungsverfahrens  erfolgte  zunächst  in  je-der  Schicht  die  Auswahl  der  Klumpen  (Schulen)  über  eine  einfache  Zufallsauswahl.  Die  ausge-wählten  Schulen  meldeten  im  Folgenden  ihre  Schulzweige  und  die  Schülerzahlen  zurück,  sodass ein  zweiter  Auswahlschritt  durchgeführt  werden  konnte,  der  die  Erfüllung  der  Ziehungsquoten auf Individualebene zum Ziel hatte. In diesem zweiten Schritt wurden in jeder Schicht sukzessive so  viele  Schulen/Schulzweige  zufällig  gezogen,  dass  mindestens  97der  schichtspezifischen  Zie-hungsquote  für  die Studienberechtigtenerreicht wurde.28Insgesamt  wurden  nach  diesem  Ver-fahren  fünf  unterschiedliche  Stichproben  erzeugt,  von  denen  jene  Variante  ausgewählt  wurde, dieam  besten  geeignet  erschien.29Hiernach  wurden  die  gezogenen  Schulen (oder Schulzweigean diesen)komplett erhoben.

**Comment by rbirkelbach** [comment]
@svietgen Do you know which of the sample types corresponds best with gsl2015? I'm a bit lost because we are still missing the documentation from Heidrun. Here's the list  https://mdr.iqb.hu-berlin.de/#/catalog/1d791cc7-6d8d-dd35-b1ef-0eec9c31bbb5 If you don't know, I'll use "other".

**Comment by svietgen** [comment]
@rbirkelbach I would use "other" until we have more information. Since the project is not yet released, this shouldn't be a problem, I think. But we have to keep in mind that later we have to change it. I will write an issue in the gsl2015-repo.

**Comment by rbirkelbach** [comment]
Thx for the rapid feedback! :)

________________________________
Von: Sandra Vietgen <notifications@github.com>
Gesendet: Montag, 8. April 2019 13:18
An: dzhw/metadatamanagement
Cc: Birkelbach, Robert; Mention
Betreff: Re: [dzhw/metadatamanagement] As publisher I want to deliver samplings to the VFDB (#2023)


@rbirkelbach<https://github.com/rbirkelbach> I would use "other" until we have more information. Since the project is not yet released, this shouldn't be a problem, I think. But we have to keep in mind that later we have to change it. I will write an issue in the gsl2015-repo.

-

**Comment by rbirkelbach** [comment]
@ElkeMi Could you please check whether "Probability Sample: Stratified Sample: Disproportional" fits to ssy18-ssy20? This is the definition we use:

> Wahrscheinlichkeitsauswahl: Disproportional geschichtete Zufallsauswahl:
> Die Grundgesamtheit wird in sich gegenseitig ausschließende und insgesamt erschöpfende Schichten unterteilt. Bei der disproportionalen Zufallsauswahl ist die Anzahl der aus jeder Schicht gezogenen Einheiten nicht proportional zum Anteil der Schichten an der Grundgesamtheit Sie können über die Schichten gleich verteilt sein oder sich an der Forschungsabsicht orientieren. Beispielsweise durch das so genannte Oversampling von in der Grundgesamtheit unterrepräsentierten Gruppen. Beispielsweise wird ein Land in zwei regionale Schichten unterteilt, wobei erstere 80 Prozent [West) und letztere 20 Prozent [Ost) der gesamten Bevölkerung umfassen. Sollen beide Regionen gleich repräsentiert werden, würden in beiden Teilen jeweils 50 Prozent der benötigten Stich probe gezogen werden. Bei einem Oversampling der Region Ost würden beispielsweise 60 Prozent der Stichprobe im Osten und 40 Prozent im Westen gezogen werden.

**Comment by ElkeMi** [comment]
@rbirkelbach wir beschreiben das Sampling der Sozialerhebungen (bis ssy21) immer als einfache, disproportional geschichtete Zufallsauswahl. Die (einzige) Schicht ist die Hochschule. Das kommt der von dir zitierten Definition doch recht nahe, oder?

**Comment by AndyDaniel1** [comment]
> @AndyDaniel1 What do you think -- which sampletype corresponds best to gsl2008?
> 
> > **Insgesamt  wurden  nach  diesem  Ver-fahren  fünf  unterschiedliche  Stichproben  erzeugt,  von  denen  jene  Variante  ausgewählt  wurde, die am  besten  geeignet  erschien**

--> **Mixed probability and non-probability Sample**

**Comment by rbirkelbach** [comment]
Thank you all for your input! :)

**Comment by rbirkelbach** [comment]
@rreitmann see this comment https://github.com/dzhw/metadatamanagement/issues/2023#issuecomment-478537029

**Comment by es-flavia** [comment]
Migration script for sample is now in #2132

**Comment by rreitmann** [comment]
@es-flavia Please use the correct spelling in the migration script as well as in the code...
