### ISSUE TITLE
project cockpit: change status icons

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2033]
Currently, we use emojis as these are the only 3-step-icons from angular. 

We talked about changing the icons from 
![grafik](https://user-images.githubusercontent.com/18573122/52555812-0f5f9e80-2deb-11e9-8078-07ab39b9e323.png)

to
![grafik](https://user-images.githubusercontent.com/18573122/52555780-fb1ba180-2dea-11e9-95e1-cd131d93e0ba.png)

The third icon does not exist in angular. We could ask Petra N. to create it.

**Comment by rreitmann** [comment]
@UteH Get in touch with Petra....

**Comment by UteH** [comment]
I sent her an e-mail.

**Comment by rreitmann** [comment]
Here are our current icons: https://github.com/dzhw/metadatamanagement/tree/development/src/main/webapp/assets/images/icons

**Comment by rreitmann** [comment]
Duplicates #2050
