### ISSUE TITLE
Create repo and refactor questionjson R scripts

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2045]
They do not need images anymore. Also, we shouldn't use the xlsx package and we should not auto-install packages from within the script.

**Comment by rbirkelbach** [comment]
not needing images still needs to be implemented

**Comment by rbirkelbach** [comment]
Please review

**Comment by rreitmann** [comment]
Here are some things we should further improve:
- The readme should contain a small setup doc for developers and another for users
- There is a typo in prep**e**ration
- The instrument number must be part of the containing directory ("ins1"). We should parse it from there.

**Comment by rreitmann** [comment]
@rbirkelbach You can test this. We still need to write a few lines in the `README.md` for our users. 
Generally the process is now the following: (zofar) -> handcrafted questionnaires -> mdm

Thus there are only two exported function left:
`convert_zofar_export_to_handcrafted_questionnaire` and
`convert_handcrafted_questionnaires_to_mdm_format`

The last one can deal with multiple instruments which is necessary when the questionnaires do not come from zofar.

**Comment by rreitmann** [comment]
@rbirkelbach I had to delete the test_that tests. If you have time you could write new ones...

**Comment by rreitmann** [comment]
@rbirkelbach We now have a generated documentation und https://dzhw.github.io/questionMetadataPreparation. Please refine the Read-the-docs documentation for FDZ-Employees and Dataproviders accordingly..
