### ISSUE TITLE
Replace smiley icons

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2050]

**Comment by rreitmann** [comment]
@UteH Please test on the dev system. Personally I think the smiley were better cause I laughing smiley was caused by several thinks:
1. Metadata not expected
2. Publisher Ready
3. Data Provider Ready && Publisher Ready

IMHO Displaying the clipboard with two checks in all these cases looks strange...

**Comment by UteH** [comment]
@rreitmann I am now registered in the dev system. Please assign the role publisher (or else) to me. Thx.

**Comment by rreitmann** [comment]
@UteH Done, you are admin, publisher and dataprovider now...

**Comment by UteH** [comment]
@rreitmann: Feedback from @TinaOe95 and me:
1. Metadata not expected **-> as you suggested we should actually hide the cards instead (new Issue)**
2. Publisher Ready **-> both Tina and me did not see this as a problem**
3. Data Provider Ready && Publisher Ready **-> we should talk face to face about this :speech_balloon: **

**Comment by rreitmann** [comment]
@UteH Please create a new issue for hiding the cards and search tabs depending on the project configuration and close this issue....
