### ISSUE TITLE
As a data provider, I only want to see objects for which metadata are expected

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2057]
We should hide the cards and search tabs depending on the project configuration. 

We should discuss this with @AndyDaniel1. Earlier we said we wanted them to be visible as a kind of "advertisenment" for the other objects. But as the data provider (richtfully) only gets "error toasts" when clicking on them I think we could also just hide them.
![grafik](https://user-images.githubusercontent.com/18573122/53408030-d3693380-39bd-11e9-93a5-ef9936cce86d.png)

**Comment by rbirkelbach** [comment]
It's working in ff, chromium, ie and, edge.
