### ISSUE TITLE
Set hreflang attribute for change language anchors

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2070]
See: https://www.w3schools.com/tags/att_a_hreflang.asp

**Comment by es-flavia** [comment]
Since the language switch is not a link, but a button executing an event handler this won't be implemented.

**Comment by rreitmann** [comment]
Reopened because for SEO we should change this to a (dynamic) link...

**Comment by AndyDaniel1** [comment]
let's come back to this issue after the usability test

**Comment by rreitmann** [comment]
We will get back to this after prerendering has been implemented....
