### ISSUE TITLE
Implement robot test for uploading related publications

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2077]

**Comment by rreitmann** [comment]
@saikotitis See my remarks here:
https://github.com/dzhw/metadatamanagement/pull/2085

**Comment by rreitmann** [comment]
@saikotitis Avoid using sleep, use wait until keywords:
http://robotframework.org/Selenium2Library/Selenium2Library.html#Wait%20Until%20Page%20Contains

**Comment by saikotitis** [comment]
@rreitmann sleep has been replaced with dynamic waiting keyword "Wait Until Element Is Visible"

**Comment by rreitmann** [comment]
@saikotitis You should watit until the upload finished toast appears...
