### ISSUE TITLE
Add study series link to products in shopping cart

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2101]
During the implementation of shadow copies (#1991) we have lost the feature that there is a link to all studies of the study series on the product cards....

**Comment by UteH** [comment]
@rreitmann does this mean work for esys aswell or just on mdm side?

**Comment by rreitmann** [comment]
Just MDM

**Comment by rreitmann** [comment]
We have added the study.studySeries to the DLP API as well during this issue.
