### ISSUE TITLE
As public user I want to know in which data format a specific data set is available

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2111]
e.g. Stata, SPSS for some data sets. Only Stata for some other data sets. Something else for qualitative data. We are talking about this in the context of the DLP. I am not sure if we should actually store this information in the MDM ...

Later, when applying for the data via DLP users have to specify the desired software for remote/on-site.

I am not sure where to make the cut between MDM and DLP.

**Comment by UteH** [comment]
@rreitmann CB suggests

> Ich würde es begrüßen und für sehr sinnvoll erachten, die "Warenkorb-relevanten" Vorgänge komplett im MDM abzubilden. Sie selbst werfen Ihrem Issue (https://github.com/dzhw/dienstleistungsportal/issues/12 bzw. https://github.com/dzhw/metadatamanagement/issues/2111) die Frage nach der Trennung zwischen MDM & DLP auf. Ich würde die **Auswahl des Datenformates und der gewünschten Analysesoftware (zukünftig auch in Abhängigkeit des Produktes) eher im MDM als im DLP sehen.** Auch jetzt wählen Sie bereits den Zugangsweg (Download/Remote/On-Site) im MDM aus, so wäre es meines Erachtens nach auch konsistent das Datenformat und die Analysesoftware dort abzufragen. So wäre auch eine klare Trennung "Warenkorb = MDM" und "Antrag = DLP" erkennbar. 

I also see data format in the MDM, but the analysis software ... I am not sure. Let's talk about it again ...

**Comment by UteH** [comment]
@rreitmann let's talk about this once more tuesday morning 🙈 (CC @fbaillet)

**Comment by rreitmann** [comment]
We have decided to enhance the domain model of the MDM in the following way:
1. There will be a new field [`SubDataSet.dataFormats`](https://metadatamanagement.readthedocs.io/de/latest/javadoc/eu/dzhw/fdz/metadatamanagement/datasetmanagement/domain/SubDataSet.html) which must contain one or more of the following: `Stata, R, SPSS, Word`. 
2. The [`OrderedStudy`](https://metadatamanagement.readthedocs.io/de/latest/javadoc/eu/dzhw/fdz/metadatamanagement/ordermanagement/domain/OrderedStudy.html) will contain a new field `surveyDataType` which is an [`I18nString`](https://metadatamanagement.readthedocs.io/de/latest/javadoc/eu/dzhw/fdz/metadatamanagement/common/domain/I18nString.html) holding one of [`MIXED_METHOD, QUALITATIVE_DATA, QUANTITATIVE_DATA`](https://metadatamanagement.readthedocs.io/de/latest/javadoc/eu/dzhw/fdz/metadatamanagement/studymanagement/domain/SurveyDataTypes.html)
3. The [`Product`](https://metadatamanagement.readthedocs.io/de/latest/javadoc/eu/dzhw/fdz/metadatamanagement/ordermanagement/domain/Product.html) will contain a new field `dataFormats` which will contain a computed deduplicated list of all `SubDataSet.dataFormats` within the study.

The DLP will show the `dataFormats` to the user and offer a list of analysis softwares depending on the `surveyDataType` of the `study`.

@Amacado Let us know your thoughts about this....

**Comment by UteH** [comment]
@AndyDaniel1 fyi

**Comment by UteH** [comment]
@rreitmann after talking to @DilekIkiz we propose "Word (docx und rtf)" or "Word"
