### ISSUE TITLE
Doc­u­ments re­lated to the Study are not displayed

### ISSUE THREAD

**Issue by anneweber** [dzhw/metadatamanagement#2114]
For the not yet published update of gra2005 the uploaded "documents re­lated to the study" are not displayed: https://metadata.fdz.dzhw.eu/#!/de/studies/stu-gra2005$
(In the shadow copy v1.0.0 everything is fine, in the test system as well.)

Maybe the problem will be solved when the study is re-released?

**Comment by rreitmann** [comment]
@anneweber Should be fixed on prod. Close this issue if fixed...

**Comment by anneweber** [comment]
Perfect, thank you!!!!! @rreitmann @es-flavia :bouquet::bouquet::bouquet:
