### ISSUE TITLE
Number of panel variables displayed at "related objects" is not correct

### ISSUE THREAD

**Issue by anneweber** [dzhw/metadatamanagement#2117]
Example 1: 
https://metadata.fdz.dzhw.eu/#!/en/variables/var-gsl2008-ds1-cfut03$?version=1.0.0
--> there should be 6 panel variables
--> https://metadata.fdz.dzhw.eu/#!/en/search?page=1&type=variables&data-set=dat-gsl2008-ds1$-1.0.0&panel-identifier=gsl2008-ds1-fut03&study=stu-gsl2008$-1.0.0 
--> there are only 3 panel variables

Example 2:
https://metadata.fdz.dzhw.eu/#!/en/variables/var-gsl2008-ds1-cgoa01o$?version=1.0.0
--> there should be 4 panel variables
--> https://metadata.fdz.dzhw.eu/#!/en/search?page=1&type=variables&data-set=dat-gsl2008-ds1$-1.0.0&panel-identifier=gsl2008-ds1-goa01o&study=stu-gsl2008$-1.0.0
--> there are only 2 panel variables

**Comment by rbirkelbach** [comment]
it behaves correctly now
