### ISSUE TITLE
Investigate: Shadow copy queue items get not processed after container restart

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2121]
...it seems that a locked shadow copy queue item is not processed and remains in the queue for ever if something broke the processing thread (e.g. container restart).

**Comment by es-flavia** [comment]
I did some tests and the `ShadowCopyQueueItemService` seems to pick up started processes just fine (although with a delay of 10 minutes. That is the same threshold `ElasticSearchUpdateQueueService` uses).

However, during my tests I've ran into this:

`java.lang.IllegalArgumentException: wrappedCdo is not an instance of given managedType 'ProjectState' but 'ProjectState'`

As a result the item was never deleted from the queue.

We had this issue during the development. Was this exception also thrown on the production system, too?

I'm still investigating why this is happening on my branch.

**Comment by rreitmann** [comment]
I have reproduced the following exception locally:
`java.lang.IllegalArgumentException: wrappedCdo is not an instance of given managedType 'ProjectState' but 'ProjectState'`

I turns out that somehow ProjectState is on different ClassLoaders caused by springs devtools. If I remove spring devtools from the dependencies I do not get that exception anymore!

In the cloud I could not find those exceptions. However validation errors can lead to the effect that shadow copies cannot be created.
