### ISSUE TITLE
Version is null if user unreleases a project while a shadow copy task is queued

### ISSUE THREAD

**Issue by es-flavia** [dzhw/metadatamanagement#2139]
If a shadow copy task is queued for a project, but the user unreleases the project before the task could be executed the version is removed and the process runs into a `NullPointerException`.
We need to read the version from Javers instead.

**Comment by rreitmann** [comment]
Here is the exception:
`
java.lang.NullPointerException: null
	at eu.dzhw.fdz.metadatamanagement.common.service.ShadowCopyService.createShadowCopies(ShadowCopyService.java:29)`
