### ISSUE TITLE
session based loading of shopping cart causes trouble when order is already completed (via api)

### ISSUE THREAD

**Issue by Amacado** [dzhw/metadatamanagement#2140]
**Error description / Steps to reproduce**
When visiting the MDM the last shopping cart is loaded via active session. When this loaded shopping cart is already completed (via external API request f.e.) you aren't able to modify it anymore.

1. Put any product in the shopping cart
2. Confirm order which redirects you to DLP
3. Complete order in DLP which sets the status to "COMPLETED" (via API) when application is finished - or "fake" this step with calling the API manualy to set the order status to "COMPLETED"
4. Return to MDM (f.e. you want to place another order)
5. You will see your already "COMPLETED" shopping cart (loaded via session/cookie) and you are not able to modify it anymore (not clearing the shopping cart nor adding new items). On any request regarding a update to the shopping cart the AJAX endpoint responses with the error "order-management.error.order-already-completed"

As a result you are not able to create a new shopping cart nor clearing the existing and therefore you're not able to proceed.

**Proposed solution**
When loading a shopping cart (via session or id in url) check if the order is already in "COMPLETED" state and create a new shopping cart when this case is true.

**Screenshots**
![image](https://user-images.githubusercontent.com/8781699/55476051-d20ed480-5615-11e9-8685-9ab1477bd25e.png)
![image](https://user-images.githubusercontent.com/8781699/55476075-dfc45a00-5615-11e9-89db-43f969b1be7a.png)

**Comment by rreitmann** [comment]
Remark: This needs to be implemented on top of **es-flavia/issue1981**

**Comment by rreitmann** [comment]
@Amacado Thx for the precise feedback. Should be fixed now, please check and close the issue if it is ok.

Generally I have a remark regarding your 4th step:
> Return to MDM (f.e. you want to place another order)

After completing the order, the user should only be able to return to the MDM without the orderId in the URL. We could reproduce the issue if and only if the url contains the stale orderId. However this edge case should be fixed now....

**Comment by Amacado** [comment]
@rreitmann i can confirm that the error does not occur anymore.

> After completing the order, the user should only be able to return to the MDM without the orderId in the URL. 
I agree, but this is already the case

> We could reproduce the issue if and only if the url contains the stale orderId.
I disagree with this point, i'm 100% sure i was able to reproduce this without and orderId in the url and just the still active session

But anyway, it seems working now. Thank you for the fast reply and fix! :)

**Comment by rreitmann** [comment]
There might be another case leading to the `order-already-completed-error`:
1. Put any product in the shopping cart
2. Confirm order which redirects you to DLP
3. Open mdm with current orderId in a new tab
4. Complete orderId in the DLP
5. Any interaction with the shopping card in the MDM will fail...

**Comment by Amacado** [comment]
I just noticed a strange, non repeatable issue where I wasn't able to have any interaction regarding the shopping cart in MDM. I could click any button (add to shopping cart/remove/clear all) but nothing happens (no javascript error, no ajax-call). After clearing the session I could not repeat this issue and everything was back to normal. 
Just reporting this here, might someone get into a similar problem and find a way to reproduce this behaviour. I will keep my eyes open.

**Comment by rreitmann** [comment]
@Amacado Please create a new issue when the observed behavior pops up again. Just a remark: We do not have any session nor do we have a cookie holding session information, the shopping cart is stored in the local storage of the browser, thus I do not get what you mean by clearing the session...
