### ISSUE TITLE
Link from dataset to survey does not work (empty)

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2163]

**Comment by rreitmann** [comment]
The problem occurs when you are not authenticated. The link on the data set page shows for instance 2 surveys but [the search](https://metadatamanagement-dev.cfapps.io/#!/de/search?page=1&type=surveys&data-set=dat-gra2005-ds1$&study=stu-gra2005$-1.0.2) does not show any.
