### ISSUE TITLE
As a user, I would like to see more quickly in which language the data is available

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#2167]
I have recently had two cases of English-speaking users contacting me from the MDM via the shopping cart but ordering data sets that were not available in English.
It would be nice if you could see more quickly in which language the data is available. Best (also) on the study page. Like it was done with our flyer (for example).

**Comment by rreitmann** [comment]
We need a field `subDataSet.languages`. We will show it in the subDataSets table and display an aggregation on the study page as well as in the shopping cart.

**Comment by rreitmann** [comment]
@UteH Can the DLP deal with an additional field in the shopping cart? I am not sure if it breaks or if it simply ignores the additional field (`product.study.dataLanguages`). Can you please clearify this?

**Comment by UteH** [comment]
mh, so the user does not choose the language they want to work with but it's merely a list of available languages that is displayed and should be sent to the DLP aswell?

I will clarify.

**Comment by rreitmann** [comment]
@UteH Do we have datasets per language? I thought it is just one dataset with labels in more than one language and therefore there is no need to choose a language...

**Comment by rreitmann** [comment]
After a short discussion with @UteH:
The languages of the dataset are independent of the access way. Thus we will implement a new field `dataSet.languages` not `subDataSet.languages`.

**Comment by UteH** [comment]
> So lange nur etwas dazu kommt sollte das funktionieren. Man könnte das von meiner Seite aus auch gerne auf der Stage Umgebung testen.

**Comment by rreitmann** [comment]
For now I will not send `study.dataLanguages` to the DLP cause it might get lost, when the user returns from the DLP to the MDM.

**Comment by rbirkelbach** [comment]
The same problem as stated in this comment is present: https://github.com/dzhw/metadatamanagement/issues/1932#issuecomment-647397092
