### ISSUE TITLE
shadow copy bug: study appears twice when searching for variables

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2169]
I searched for variables and filtered for
- study series
- accessWays
- ~~survey~~ study

-> ssy21 appears twice 

![grafik](https://user-images.githubusercontent.com/18573122/55935718-9935b780-5c34-11e9-875a-4b140705b9c0.png)

not sure if this is already in progress.

**Comment by rreitmann** [comment]
Could reproduce it on prod however not on the current branch. Should already be fixed.
 
@UteH retest and close if ok...

**Comment by UteH** [comment]
agree
