### ISSUE TITLE
Add and document validation for Data Acquisition Projects

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#217]

**Comment by rreitmann** [comment]
Please ensure the following things:
- constants in validation messages must be used as params (see https://github.com/dzhw/metadatamanagement/blob/master/src/main/resources/i18n/messages_de.properties#L49)
- releases must be marked for nested validation (ensure with a unit test)
- message string must contain the name of the attribute which is wrong

**Comment by rreitmann** [comment]
@anfranken Please test this issue

**Comment by anfranken** [comment]
- id 	
1. Mandatory: is working
2. Max Length SMAL:  is working
3. ß is not allowed
- other validation are not testable (surveySeries, panelName)

**Comment by rreitmann** [comment]
@anfranken ß is working now

please ensure that currently not testable validations are tested as soon as there is a more sophisticated project creation screen :-)
