### ISSUE TITLE
As a data provider I want to have less copy-&-paste work when entering the dataset citation

### ISSUE THREAD

**Issue by anneweber** [dzhw/metadatamanagement#2173]
See e.g. https://metadata.fdz.dzhw.eu/#!/de/data-sets/dat-gra2005-ds1$?version=2.0.0

- download-cuf: `Minks, K. H., Briedis, K., Schaeper, H., Euler, T., Grotheer, M., Isleib, S., Netz, N., Trennt, F. & Trommer, M. (2019): DZHW-Absolventenpanel 2005. Datenerhebung 2006/2011/2016. Version: 2.0.0. Hannover: FDZ-DZHW. Datenkuratierung: Baillet, F., Franken, A., Weber, A. Datensatz: gra2005_tS_p_c_2-0-0. doi: 10.21249/DZHW:gra2005:2.0.0.`
- download-suf: `Minks, K. H., Briedis, K., Schaeper, H., Euler, T., Grotheer, M., Isleib, S., Netz, N., Trennt, F. & Trommer, M. (2019): DZHW-Absolventenpanel 2005. Datenerhebung 2006/2011/2016. Version: 2.0.0. Hannover: FDZ-DZHW. Datenkuratierung: Baillet, F., Franken, A., Weber, A. Datensatz: gra2005_tS_p_d_2-0-0. doi: 10.21249/DZHW:gra2005:2.0.0.`
- remote-desktop-suf: `Minks, K. H., Briedis, K., Schaeper, H., Euler, T., Grotheer, M., Isleib, S., Netz, N., Trennt, F. & Trommer, M. (2019): DZHW-Absolventenpanel 2005. Datenerhebung 2006/2011/2016. Version: 2.0.0. Hannover: FDZ-DZHW. Datenkuratierung: Baillet, F., Franken, A., Weber, A. Datensatz: gra2005_tS_p_r_2-0-0. doi: 10.21249/DZHW:gra2005:2.0.0.` 
- onsite-suf: `Minks, K. H., Briedis, K., Schaeper, H., Euler, T., Grotheer, M., Isleib, S., Netz, N., Trennt, F. & Trommer, M. (2019): DZHW-Absolventenpanel 2005. Datenerhebung 2006/2011/2016. Version: 2.0.0. Hannover: FDZ-DZHW. Datenkuratierung: Baillet, F., Franken, A., Weber, A. Datensatz: gra2005_tS_p_o_2-0-0. doi: 10.21249/DZHW:gra2005:2.0.0.`

--> Only the dataset name varies.
(same for the English version: https://metadata.fdz.dzhw.eu/#!/en/data-sets/dat-gra2005-ds1$?version=2.0.0)
(same for the three other datasets (each German and English): https://metadata.fdz.dzhw.eu/#!/de/search?page=1&type=data_sets&study=stu-gra2005$-2.0.0

Could this perhaps be simplified? Could you discuss this in the Scrum team? I'm not sure if the open citation field is needed for other data types?

**Comment by anneweber** [comment]
@svietgen FYI

**Comment by rreitmann** [comment]
This has already been implemented :)
