### ISSUE TITLE
Write down potentially missing features of sdcMicro

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2177]

**Comment by maikad** [comment]
- comparison of sdcMicro and sdcMicro GUI -

Meindl stated in "A shiny GUI for sdcMirco" (find here #2179):
GUI includes **full** functionality of the sdcMicro package

 sdcMicro GUI:
**Advantages**       user - friendly, especially when selecting variable roles or summary display, easy overview of the sdcMicro features
**Disadvantages**  less overview of the process

sdcMicro:
**Advantages**       better overview and cotrol of the data set
**Disadvantages**  not as user - friendly

**Comment by maikad** [comment]
So far I have found following about the sdcMicro:

- it includes a wide range of commonly used SDC - methods, which makes it difficult to track the features that aren't included in the app 

**Disadvantages** 
- primarily focuses on raw micodata
- runs slow when working with very large data sets
