### ISSUE TITLE
Write down rough guide for sdcMicro/explain to me

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2179]

**Comment by maikad** [comment]
@rbirkelbach  
attached the word document including the rough guide, as well as the pdf - files used as literature


[Rhough Guide sdcMicro (GUI).docx](https://github.com/dzhw/metadatamanagement/files/3084564/Rhough.Guide.sdcMicro.GUI.docx)
[Templ_Introduction to Statistical Disclosure Control (SDC)_2018.pdf](https://github.com/dzhw/metadatamanagement/files/3084565/Templ_Introduction.to.Statistical.Disclosure.Control.SDC._2018.pdf)
[Templ_Statistical Disclosure Control for Microdata_2017.pdf](https://github.com/dzhw/metadatamanagement/files/3084566/Templ_Statistical.Disclosure.Control.for.Microdata_2017.pdf)
[Templ_Workshop on Anonymization tools and their practical relevance_2015.pdf](https://github.com/dzhw/metadatamanagement/files/3084567/Templ_Workshop.on.Anonymization.tools.and.their.practical.relevance_2015.pdf)
[Meindl_A new shiny GUI for sdcMicro_2017.pdf](https://github.com/dzhw/metadatamanagement/files/3084568/Meindl_A.new.shiny.GUI.for.sdcMicro_2017.pdf)
[Meindl_Guidelines for the Anonymization of Microdata Using R -Package sdcMicro_2012.pdf](https://github.com/dzhw/metadatamanagement/files/3084569/Meindl_Guidelines.for.the.Anonymization.of.Microdata.Using.R.-Package.sdcMicro_2012.pdf)

**Comment by maikad** [comment]
also useful:

https://sdcpractice.readthedocs.io/en/latest/sdcMicro.html

**Comment by rbirkelbach** [comment]
@maikad thank you! Could you please define L-diversity, local suppression, top/bottom coding, recoding, Minimum Sample Uniques? I don't really get what the alpha-parameter means from the description.

**Comment by maikad** [comment]
@rbirkelbach updated version, should include all answers to your question (:

[23042019 - Rough.Guide.sdcMicro.GUI.docx](https://github.com/dzhw/metadatamanagement/files/3107906/23042019.-.Rough.Guide.sdcMicro.GUI.docx)
