### ISSUE TITLE
Logged in users can open sites of project when another project is chosen

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2187]
If a project is already chosen via the project chooser and I directly enter a url, e.g. https://metadatamanagement-test.cfapps.io/#!/en/data-sets/dat-gra2005-ds3$/edit , I do not get redirected to https://metadatamanagement-test.cfapps.io/#!/en/search?page=1 but https://metadatamanagement-test.cfapps.io/#!/en/data-sets/dat-gra2005-ds3$/edit is opened as if the project gra2005 was chosen. When not realising this and trying to release, of course the version of the chosen project is shown, which is confusing.

**Comment by rreitmann** [comment]
I could successfully reproduce the described behavior in chrome as well.

1. Bookmark an edit page, e.g.: https://dev.metadata.fdz.dzhw.eu/#!/de/data-sets/dat-gra2005-ds1$/edit
2. Choose a different project
3. Open bookmark

**Comment by rbirkelbach** [comment]
Is it correct behavior that when I want to edit an existing study the url is not /en/study/stu-hurz$/edit but en/studies/new ie, without the project id?
