### ISSUE TITLE
As user I want the same language of MDM and DLP when switching

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2200]
from an English User test

> -    auch wenn MDM auf englisch war, lande ich via Warenkorb auf der deutschen Variante des DLP (MDM)
> -    wenn ich das DLP auf englisch geschaltet hatte, lande ich via Warenkorbbearbeitung dennoch auf der deutschen Variante des MDM

**Comment by rreitmann** [comment]
This is IMHO not an MDM issue. The MDM delivers the language of the user via the API. The DLP can direct back to a German or English shopping cart by using the correct language in the browser location...

**Comment by UteH** [comment]
@Amacado

**Comment by AndyDaniel1** [comment]
I give this issue a prio 2 for answering the question if this is an MDM issue or not. Even if this is not an MDM issue please give a short notice on the solution in this issue befor closing it.

**Comment by amacado** [comment]
Currently I follow the explanation by @rreitmann as I think we should be able to manage this behaviour in DLP (redmine 3028)

**Comment by amacado** [comment]
@rreitmann we implemented a handler which updates the order in MDM with the choosen language on DLP site (before redirecting to update the cart in MDM). So the user is able to change the language in DLP and when 'edit shopping cart' is clicked it will redirect to the correct language in MDM. On site of MDM you need to make sure to target language-specific endpoints based on the selected language in MDM.

Currently the redirect link always looks like: <code>https://dzhw-dlp.elementsystems.io/de/form/data-usage-application?mdm_order_id=XXX</code> indicating the language in <code>/de/</code>. The MDM have to implement a handler which either redirects to 

german:
<code>https://dzhw-dlp.elementsystems.io/de/form/data-usage-application?mdm_order_id=XXX</code>
or english:
<code>https://dzhw-dlp.elementsystems.io/en/form/data-usage-application?mdm_order_id=XXX</code>

based on the selected language in MDM. The implementation on DLP is completed, for the best UX the MDM has to implement the specified handling as well.

**Comment by rreitmann** [comment]
@UteH Done, however DLP shows a couple of errors in english...

**Comment by amacado** [comment]
@rreitmann those errors are for debugging reasons only and have nothing to do with the language changes and therefore can be ignored.

**Comment by amacado** [comment]
@UteH in my opinion this ticket can be closed

**Comment by UteH** [comment]
@amacado Editing the shopping cart works !  👍 

Actually, I started the process here https://dzhw-dlp.elementsystems.io/en/form/data-usage-application. Here, the URL behind "research portal" is still https://metadatamanagement-test.cfapps.io/. I think it should be the english version aswell?

**Comment by amacado** [comment]
@UteH done. Ticket can be closed in my opinion.

**Comment by UteH** [comment]
I tested it. I agree.
