### ISSUE TITLE
As a publisher I want to know the release dates (reporting)

### ISSUE THREAD

**Issue by anneweber** [dzhw/metadatamanagement#2201]
- for each version/doi
- If versions are re-released without changing the version number (e.g. if only metadata is corrected), I want to know the first release date.

Please discuss with @danbfdz

**Comment by anneweber** [comment]
https://github.com/dzhw/metadatamanagement/issues/2212

**Comment by rreitmann** [comment]
@anneweber Since #2305 I think we have exactly what you need. See https://metadata.fdz.dzhw.eu/#!/de/studies/stu-gra2005$?version=2.0.0 . Please close this issue if this is enough...
