### ISSUE TITLE
Redirect/link to dzhw-reporting tool on release

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2212]
https://www.dzhw.eu/dbadmin

**Comment by anneweber** [comment]
@rbirkelbach https://github.com/dzhw/metadatamanagement/issues/2201

**Comment by UteH** [comment]
https://github.com/dzhw/metadatamanagement/issues/2028

**Comment by rreitmann** [comment]
After a short discussion we will implement:
- a new (project independent) user role `RELEASE_MANAGER` for users which are responsible for maintaining the entries in the dzhw reporting tool
- if and only if a project is release with a new major version (1.x.x, 2.x.x, ...), the MDM will send an email to all `RELEASE_MANAGER`'s with the link above
- on prod @rbirkelbach and @anneweber will get the role `RELEASE_MANAGER`

**Comment by rreitmann** [comment]
`db.jhi_authority.insert({"_id" : "ROLE_RELEASE_MANAGER"});`

**Comment by rbirkelbach** [comment]
On new major release the study gets duplicated.

**Comment by rreitmann** [comment]
@rbirkelbach How fast have you released and unreleased? Have you waited until all shadow copies of the previous release have been created before the new release or have there been two shadow copy processes simultaneously?

**Comment by rbirkelbach** [comment]
It was rather quick. Did I cause a npe? Damn.

________________________________
Von: René Reitmann <notifications@github.com>
Gesendet: Donnerstag, 22. August 2019 14:57
An: dzhw/metadatamanagement
Cc: Birkelbach, Robert; Mention
Betreff: Re: [dzhw/metadatamanagement] Redirect/link to dzhw-reporting tool on release (#2212)


@rbirkelbach<https://github.com/rbirkelbach> How fast have you released and unreleased? Have you waited until all shadow copies of the previous release have been created before the new release or have there been two shadow copy processes simultaneously?

-

**Comment by rreitmann** [comment]
Nope, but shadow copies know there successor if they are not the latest shadow. So, if you create two shadow copies at the same time, one will not know its successor....

**Comment by rreitmann** [comment]
Here is a script to fix the missing successors in mongoDB:
```javascript
var collections = ['studies','surveys','instruments','data_sets','variables','questions'];

collections.forEach(collection => {
    db.getCollection(collection).find({dataAcquisitionProjectId: 'cmp2014', shadow: false}).forEach(master => {
        var documents = [];
        db.getCollection(collection).find({masterId:master._id, shadow: true}).sort({createdDate: 1}).forEach(document => {
            documents.push(document)
        });
        for (var i = 0; i < documents.length - 1; i++) {
            documents[i].successorId = documents[i+1]._id;
            db.getCollection(collection).save(documents[i]);
        }
    })
});

```

**Comment by rreitmann** [comment]
Fixed you can retest as soon as travis is ready:
https://travis-ci.org/dzhw/metadatamanagement/builds/575786963
