### ISSUE TITLE
Question: Links to shadow copies

### ISSUE THREAD

**Issue by anneweber** [dzhw/metadatamanagement#2214]
I sent the following link to @annegaertner : https://metadata.fdz.dzhw.eu/#!/de/studies/stu-gra2005$?version=1.0.0 (shadow copy)

![screen1](https://user-images.githubusercontent.com/17066262/57509140-c93fab80-7303-11e9-9a88-23e5b81ca81b.jpg)

But the link leads @annegaertner to this page:
![screen2](https://user-images.githubusercontent.com/17066262/57509210-eeccb500-7303-11e9-9412-8ea37d4c3486.jpg)

Is this correct?

**Comment by rreitmann** [comment]
@annegaertner was logged in when she opened the link. That's why she cannot see the shadow copy. We have not yet implemented viewing shadow copies as authenticated user...

**Comment by annegaertner** [comment]
@rreitmann I think I remember this was even topic at one of the latest reviews.. Sorry, I forgot and thanks for your quick help!

**Comment by rreitmann** [comment]
@annegaertner No problem, I'll keep this issue open and we will discuss if we implement that feature or if we just improve the message for authenticated users...

**Comment by rbirkelbach** [comment]
If I enter an invalid version number (in this case 2.3.1) in the url it does not show that this version is invalid - it just states 

> Your link refers to a former version (2.3.1) of this study. This page displays the current version (3.0.0) of the study[...] 

I'm unsure whether this should be a new issue.

**Comment by rbirkelbach** [comment]
The rest works as expected. I leave it open but assign @rreitmann until we can discuss whether this is worth a new issue.

**Comment by rreitmann** [comment]
Moved to new issue #2357.
