### ISSUE TITLE
Dataset report upload protocol still shows the failure message for the already uploaded file 

### ISSUE THREAD

**Issue by saikotitis** [dzhw/metadatamanagement#2215]
- i have uploaded Variablelist.tex file but the error shows that i have not uploaded it 
- remove the failure message for the uploaded file
- correct the failure count

**Comment by AndyDaniel1** [comment]
I think this should be easy to fix. I'll provide it with prio 1. If it takes too much effort we should postpone it.

**Comment by rreitmann** [comment]
This one becomes irrelevant if we implement #2265...
