### ISSUE TITLE
Sampling Procedure of ssy-projects

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2220]
I am currently preparing metadata for the ssy18. I think with migrating the samplingProcedure to the new vocabulary, the samplingProcedure for the ssy-projects were mismatched. Currently, it always states "Wahr­schein­lich­keits­aus­wahl: Pro­por­tio­nal ge­schich­te­te Zu­falls­aus­wahl". 

I would argue that it should be "Wahr­schein­lich­keits­aus­wahl: **Dis­**pro­por­tio­nal ge­schich­te­te Zu­falls­aus­wahl" for ssy18, ssy19, ssy20 ssy21. I looked up the terms in the MethodReport:

Studie | MethodReport | Thus, MDM should be
-- | -- | --
ssy19 | Einfach (disproportional) geschichtete Zufallsstichprobe | Wahr­schein­lich­keits­aus­wahl:   **Dis­**pro­por­tio­nalge­schich­te­te Zu­falls­aus­wahl
ssy20 | Einfach (disproportional) geschichtete Zufallsstichprobe | Wahr­schein­lich­keits­aus­wahl: **Dis­**pro­por­tio­nal ge­schich­te­te   Zu­falls­aus­wahl
ssy21 | Einfach (disproportional) geschichtete Zufallsstichprobe | Wahr­schein­lich­keits­aus­wahl: **Dis­**pro­por­tio­nal ge­schich­te­te   Zu­falls­aus­wahl

@anneweber is this also true for ssy21 (D/BI and BA)? Form the MethodReport it looks like it to me. **It is.**

**Comment by anneweber** [comment]
@UteH I had to look into the report, too. :see_no_evil: 

![ssy21_stichprobe](https://user-images.githubusercontent.com/17066262/57704037-74809580-7661-11e9-80a3-ab5f0c36dd8f.png)

I think you're right. :+1:
