### ISSUE TITLE
As Data provider I don't want scaleLevel to be manatory for variables that are not accessible

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2228]
It is true that we actually don't need the scale level as we do not show frequencies or the graph etc.?

For now, I just entered a "fake" scale level because I thought it didn't matter. I could also just keep entering "fake" scale levels, that's not a problem. I just wanted to make sure, that this is ok. 

(edit: it is a problem because it is displayed in the MDM)

**Comment by AndyDaniel1** [comment]
@UteH That's right and should be fitted soon. I'll provide it with a 1 and we'll how much effort it takes to implement it.

**Comment by AndyDaniel1** [comment]
@UteH let's discussion this issue f2f.

**Comment by AndyDaniel1** [comment]
Is this still an issue?

**Comment by rreitmann** [comment]
Closed because no one has complained about it recently....
