### ISSUE TITLE
Change doi prefix for dara test system

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2229]
DataCite has changed the its test services. The test prefix 10.5072 will be phased out. New test accounts will not use it. DataCite will shut it off in mid-2019. 
The da|ra test system will work with a new prefix for testing from 1 June 2019 onwards.
 
New da|ra test prefix is: 10.17889

**Comment by rreitmann** [comment]
@rbirkelbach You should test after the 31 May if releasing to dara is still possible on the test system....

**Comment by rbirkelbach** [comment]
ok
