### ISSUE TITLE
As a public user I want an export function for citation hints of subDataSets

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2232]
When clicking on the citation hints we could provide an export function for bibtex, endnote xml and other reference managers.

**Comment by rreitmann** [comment]
This is related to #2173.

We suggest that we implement a `CitationHintGenerator` that generates the citationHint automatically from the rest of our metadata. If we had this we could export it to different formats as well. However, at the moment the algorithm for creating a citationHint automatically has not been defined.

**Comment by AndyDaniel1** [comment]
Let's solve #2173 first and then come back to this issues if it has already been solved.

**Comment by rreitmann** [comment]
@AndyDaniel1 IMHO the `CitationHintGenerator` would be a solution for #2173 too...

**Comment by AndyDaniel1** [comment]
Ok, thanks for the feedback. Then we flip the prio of both issues

**Comment by rreitmann** [comment]
@rbirkelbach please provide the algorithm for computing a citation for a configured data package!

**Comment by UteH** [comment]
https://github.com/dzhw/FDZ_Allgemein/issues/328

**Comment by rbirkelbach** [comment]
@DilekIkiz proposals are:
[Autorinnen der Studie] (Veröffentlichungsdatum des Datensatzes). [Titel]. Datenerhebung: [YYYY oder YYYY/YYYY]. Version: [X.Y.Z]. [Veröffentlichungsort]: [Publikationsagent]. Datenkuratierung: [Namen der Datenkuratorinnen]. doi: [Identifikator].

[Creator] ([PublicationYear]). [Title]. Data Collection [Date, dateType, Collected]: [YYYY or YYYY/YYYY]. Version: [X.Y.Z]. [geoLocationPlace]: [Publisher]. Data Curation [Contributor]: [contributorName]. doi: [Identifier].

As we want to cite the configured data package I'd propose the following:

[Autorinnen der Studie] (Veröffentlichungsdatum des Datensatzes). [Titel]. Datenerhebung: [YYYY oder YYYY/YYYY]. Version: [X.Y.Z]. Datenpaketzugangsweg: [CUF/Onsite-Suf/Remote-Suf]. [Veröffentlichungsort]: [Publikationsagent]. Datenkuratierung: [Namen der Datenkuratorinnen]. doi: [Identifikator].

[Creator] ([PublicationYear]). [Title]. Data Collection [Date, dateType, Collected]: [YYYY or YYYY/YYYY]. Version: [X.Y.Z]. Data Package Access Way: [Cuf/Onsite-Suf/Remote-Suf]. [geoLocationPlace]: [Publisher]. Data Curation [Contributor]: [contributorName]. doi: [Identifier].

**Comment by rbirkelbach** [comment]
We need a new field at the study level: dataCurators

**Comment by rbirkelbach** [comment]
@DilekIkiz @AndyDaniel1 : @rreitmann told me that you now do *not* want the accessWays. What's the reason for changing your stance? In my opinion this is together with the version number and title the most important information.

**Comment by rbirkelbach** [comment]
@DilekIkiz could you please respond? I still think that we should include the accessWay, as this can have impact on the analysis and then it's good to know what exact subdataset was used.

**Comment by DilekIkiz** [comment]
As I recall, the primary concern is not to overload the data citation. accessWays is an element that is relevant to internal processes, but not to the data user. This information can also be found in the MDM and the data usage contract. In addition, accessWays can also change and can therefore render the citation unusable. Overall, @danbfdz and Andy have therefore jointly decided not to include this information in the data citation.  But I think @AndyDaniel1 can explain it to you better.

**Comment by rbirkelbach** [comment]
As discussed yesterday with @AndyDaniel1 we will keep the accessWay variable, as otherwise one cannot identify the level of granularity of the data in research which uses our data. Hence, we should use the following:

[Autorinnen der Studie] (first release date). [Titel]. Datenerhebung: [YYYY oder YYYY-YYYY]. Version: [X.Y.Z]. Datenpaketzugangsweg: [CUF/Onsite-SUF/Remote-SUF]. [Veröffentlichungsort]: [Publikationsagent]. Datenkuratierung: [dataCurators]. doi: [Identifikator].

[Authors of the Study] ([first release date]). [Title]. Data Collection: [YYYY or YYYY-YYYY]. Version: [X.Y.Z]. Data Package Access Way: [Cuf/Onsite-SUF/Remote-SUF]. [PublicationPlace]: [Publisher]. Data Curation: [dataCurators]. doi: [Identifier].

**Comment by DilekIkiz** [comment]
`[Autor*innen der Studie] ([first release date]). [Titel]. Datenerhebung: [YYYY oder YYYY/YYYY oder YYYY-YYYY]. Version: [X.Y.Z]. Datenpaketzugangsweg: [Download-CUF/On-Site-SUF/Remote-Desktop-SUF/Download-SUF]. Hannover: FDZ-DZHW. Datenkuratierung: [dataCurators]. doi: [Identifikator].`

`[Authors of the Study] ([first release date]). [Title]. Data Collection: [YYYY or YYYY/YYYY or YYYY-YYYY]. Version: [X.Y.Z]. Data Package Access Way: [Download-CUF/On-Site-SUF/Remote-Desktop-SUF/Download-SUF]. Hanover: FDZ-DZHW. Data Curation: [dataCurators]. doi: [Identifier].`

**Comment by rbirkelbach** [comment]
We need a possiblity to create a non-empty array of dataCurators. As we do not have a dataPackage domain object, we have to attach it to study. We need to migrate old versions. Should we show dataCurators on the study page? (In my opinion: yes) Should we send it to da|ra?

**Comment by rbirkelbach** [comment]
$study.authors ($study.release.firstDate). $study.title.de/en. Datenerhebung/Data Collection: $survey.fieldPeriod. Version: $release.version. Datenpaketzugangsweg/Data Package Access Way: $dataSet.subDataSet.accessWay. Hannover/Hanover: FDZ-DZHW. Datenkuratierung/Data Curation: $study.dataCurators. doi: $doi

**Comment by rbirkelbach** [comment]
@rreitmann please check whether I set the domain objects correctly.

**Comment by rbirkelbach** [comment]
Single Author: Brown, E.
Two Authors: Soto, C. J., & John, O. P.
Three to Twenty Authors: Nguyen, T., Carnevale, J. J., Scholer, A. A., Miele, D. B., & Fujita, K.
More Than Twenty Authors: Pegion, K., Kirtman, B. P., Becker, E., Collins, D. C., LaJoie, E., Burgman, R., Bell, R., DelSole, R., Min, D., Zhu, Y., Li, W., Sinsky, E., Guan, H., Gottschalck, J., Metzger, E. J., Barton, N. P., Achuthavarier, D., Marshak, J., Koster, R., . . . & Kim, H.

**Comment by rreitmann** [comment]
Ok, let me sum up:
- we want to remove the field `subDataSet.citationHint` and want to generate the hint dynamically in the `dataPackageConfigurator`
- we need a new field `study.dataCurators` (send to da|ra?, show on studyDetails?), the array must not be empty => migrate old shadows
- the `CitationHintGenerator` will generate an APA-Style citation hint based on current language, selected accessWay and current study

**Comment by rreitmann** [comment]
I would prefer mapping our fields to bibJSON http://okfnlabs.org/bibjson/ and use https://citation.js.org/ to present the citation hints in different technical formats and languages. 
However since we have decided to generate something special which uses different fields than defined in APA we need to implement our own version of APA...

**Comment by rreitmann** [comment]
We can experiment with citation.js here:
https://runkit.com/rreitmann/5e4fad6cadc8f20013197616

Furthermore there is an upcoming standard for citation which is developed by some bigger players:
https://citationstyles.org/
https://github.com/citation-style-language/schema
http://docs.citationstyles.org/en/1.0.1/specification.html

**Comment by rbirkelbach** [comment]
After we have decided on a solution we should update or deprecate this document: \\faust\Abt4\FDZ\2_Standards\Zitationsanleitung\Vorlage_Citation_Guideline.dot

**Comment by rreitmann** [comment]
Datacite or crosscite uses CSL as well:
https://datacite.org/citation.html

A simple REST request can give us citations in all citation styles defined by CSL:
`curl -LH "Accept: text/x-bibliography; style=bibtex; locale=de-DE" https://doi.org/10.21249/DZHW:gra2009:1.0.1`

Available styles are here: https://github.com/citation-style-language/styles

However, since the metadata registered with the doi comes via da|ra and since therefore we cannot influence the CSL-JSON which is used as input for citeproc-js, we should map our metadata to CSL-JSON ourselves...

**Comment by rreitmann** [comment]
And here is the wikepedia link to CSL: https://de.wikipedia.org/wiki/Citation_Style_Language

**Comment by rreitmann** [comment]
Ok, let me sum up again:
- we will not use CSL or citation.js
- we want to remove the field `subDataSet.citationHint` and want to generate the hint dynamically in the `dataPackageConfigurator`
- we need a new field `study.dataCurators` (send to da|ra as Contributor of type DataCurator and show it on studyDetails), the array must not be empty => migrate old shadows
- the `CitationHintGenerator` will generate an APA-like citation hint based on current language, selected accessWay and current study

**Comment by rreitmann** [comment]
Quick migration for dev and local:
```javascript
db.getCollection('studies').find({}).forEach(function(study) {
    study.dataCurators = study.authors;
    study.version = study.version + 1;
    study.lastModifiedDate = new Date();
    db.getCollection('studies').save(study);
})
```

**Comment by rreitmann** [comment]
Remove citationHint from all subDataSets:
```javascript
db.getCollection('data_sets').find({}).forEach(function(dataSet) {
    if (dataSet.subDataSets) {
        dataSet.subDataSets.forEach(function(subDataSet) {
            delete subDataSet.citationHint;
        });
    }
    dataSet.version = dataSet.version + 1;
    dataSet.lastModifiedDate = new Date();
    db.getCollection('data_sets').save(dataSet);
})
```

**Comment by UteH** [comment]
- [ ] the new attribute `study.dataCurators` should also be added to the PDF overviews. As we do not have a template we need to inform the rdc data curators

**Comment by rreitmann** [comment]
Add `dataCurators` to all studies on prod:
```javascript
/* global db, printjson */
'use strict';

var dataCuratorsMap = {
    'stu-bst02$': [{
      'firstName': 'Robert',
      'lastName': 'Birkelbach'
    }],
    'stu-cmp2014$': [{
      'firstName': 'Kim',
      'lastName': 'Sommer'
    },{
      'firstName': 'Karsten',
      'lastName': 'Stephan'
    },{
      'firstName': 'Sandra',
      'lastName': 'Vietgen'
    }],
    'stu-dps2017$': [{
      'firstName': 'N.',
      'lastName': 'N.'
    }],
    'stu-egr2018$': [{
      'firstName': 'N.',
      'lastName': 'N.'
    }],
    'stu-est2016$': [{
      'firstName': 'N.',
      'lastName': 'N.'
    }],
    'stu-gra2005$': [{
      'firstName': 'Florence',
      'lastName': 'Baillet'
    },{
      'firstName': 'Andreas',
      'lastName': 'Franken'
    },{
      'firstName': 'Anne',
      'lastName': 'Weber'
    }],
    'stu-gra2009$': [{
      'firstName': 'Florence',
      'lastName': 'Baillet'
    },{
      'firstName': 'Andreas',
      'lastName': 'Franken'
    },{
      'firstName': 'Anne',
      'lastName': 'Weber'
    }],
    'stu-gsl2008$': [{
      'firstName': 'Andreas',
      'lastName': 'Daniel'
    },{
      'firstName': 'Ute',
      'lastName': 'Hoffstätter'
    },{
      'firstName': 'Björn',
      'lastName': 'Huß'
    },{
      'firstName': 'Percy',
      'lastName': 'Scheller'
    }],
    'stu-gsl2012$': [{
      'firstName': 'Robert',
      'lastName': 'Birkelbach'
    },{
      'firstName': 'Sandra',
      'lastName': 'Vietgen'
    },{
      'firstName': 'Marten',
      'lastName': 'Wallis'
    }],
    'stu-gsl2015$': [{
      'firstName': 'N.',
      'lastName': 'N.'
    }],
    'stu-hth2017$': [{
      'firstName': 'N.',
      'lastName': 'N.'
    }],
    'stu-lib2016$': [{
      'firstName': 'Bernd',
      'lastName': 'Kleimann'
    },{
      'firstName': 'Dilek',
      'lastName': 'İkiz-Akıncı'
    },{
      'firstName': 'Malte',
      'lastName': 'Hückstädt'
    }],
    'stu-mog2020$': [{
      'firstName': 'N.',
      'lastName': 'N.'
    }],
    'stu-nac2018$': [{
      'firstName': 'N.',
      'lastName': 'N.'
    }],
    'stu-phd2014$': [{
      'firstName': 'Gesche',
      'lastName': 'Brandt'
    },{
      'firstName': 'Susanne',
      'lastName': 'de Vogel'
    },{
      'firstName': 'Steffen',
      'lastName': 'Jaksztat'
    },{
      'firstName': 'Iryna',
      'lastName': 'Kovalova'
    },{
      'firstName': 'Anne-Marie',
      'lastName': 'Lapstich'
    },{
      'firstName': 'Carola',
      'lastName': 'Teichmann'
    }],
    'stu-rub18yo$': [{
      'firstName': 'N.',
      'lastName': 'N.'
    }],
    'stu-scs2016$': [{
      'firstName': 'Jörg',
      'lastName': 'Neufeld'
    },{
      'firstName': 'David',
      'lastName': 'Johann'
    }],
    'stu-ssy17$': [{
      'firstName': 'Elke',
      'lastName': 'Middendorff'
    },{
      'firstName': 'Ute',
      'lastName': 'Hoffstätter'
    }],
    'stu-ssy18$': [{
      'firstName': 'Elke',
      'lastName': 'Middendorff'
    },{
      'firstName': 'Ute',
      'lastName': 'Hoffstätter'
    }],
    'stu-ssy19$': [{
      'firstName': 'Ute',
      'lastName': 'Hoffstätter'
    },{
      'firstName': 'Andreas',
      'lastName': 'Sarcletti'
    }],
    'stu-ssy20$': [{
      'firstName': 'Andreas',
      'lastName': 'Daniel'
    },{
      'firstName': 'Andreas',
      'lastName': 'Sarcletti'
    },{
      'firstName': 'Sandra',
      'lastName': 'Vietgen'
    }],
    'stu-ssy21$': [{
      'firstName': 'Karsten',
      'lastName': 'Becker'
    },{
      'firstName': 'Florence',
      'lastName': 'Baillet'
    },{
      'firstName': 'Anne',
      'lastName': 'Weber'
    }],
    'stu-tu18yo$': [{
      'firstName': 'N.',
      'lastName': 'N.'
    }],
    'stu-tuk18yo$': [{
      'firstName': 'N.',
      'lastName': 'N.'
    }],
    'stu-uzk18yo$': [{
      'firstName': 'N.',
      'lastName': 'N.'
    }],
    'stu-win2015$': [{
      'firstName': 'Adisa',
      'lastName': 'Beširović'
    },{
      'firstName': 'Thorben',
      'lastName': 'Sembritzki'
    },{
      'firstName': 'Lisa',
      'lastName': 'Thiele'
    },{
      'firstName': 'Dilek',
      'lastName': 'İkiz-Akıncı'
    }]
  };

Object.keys(dataCuratorsMap).forEach(function(studyId) {
    db.getCollection('studies').find({masterId: studyId}).forEach(
    function(study) {
      study.dataCurators = dataCuratorsMap[studyId];
      printjson(study);
      //study.version = study.version + 1;
      //study.lastModifiedDate = new Date();
      //db.getCollection('studies').save(study);
    });
  });
```
@rbirkelbach Please review the list of dataCurators for each study id. In some cases there is neither a project overview nor a method review therefore I had to put "N. N."...

**Comment by rbirkelbach** [comment]
egr2018: Wir brauchen die kompletten Namen folgender Personen: Meng, C., Maurer, S., Mühleck, K., Unger, M, Oelker, S., van der Velden, R., Wessling, K

**Comment by svietgen** [comment]
@rbirkelbach K. Lange -- > Kerstin Lange

**Comment by rbirkelbach** [comment]
@svietgen danke, bin mir bei egr nicht sicher. Das sollten vermutlich @McWallis @ElkeMi und @UteH denke ich wissen, da sie dafür im MDM stehen.

@rreitmann I made the following observation: 
`Minks, K., Briedis, K., Grotheer, M., Isleib, S., & Netz, N. (2020). DZHW-Absolventenpanel 2005. Datenerhebung: 2006-2019. Version: 1.1.1. Datenpaketzugangsweg: Download-SUF. Hannover: FDZ-DZHW. Datenkuratierung: test, T., & test2, T. H.. doi: 10.17889/DZHW:gra2005:1.1.1 `
You see that `test` and `test2` are lowercase, whereas `T.` and `T.H.` are capitalized. The raw input data was lower case. I personally think we should use lower case for all names, as in some languages parts of names can be lower case. For example in Dutch, `de Leeuw` is a more or less common last name.

**Comment by ElkeMi** [comment]
Ich stehe für dieses Projekt offenbar fälschlicherweise im MDM; kenne auch K. Lange nicht.

**Comment by UteH** [comment]
Elke hatte bei egr2018 Metadaten eingetragen, aber wird nicht als Datenkuratorin genommen. Ihr könnt Hoffstätter, U., Wallis, M. und Niebuhr, J. eintragen (oder ich ändere es später, ist ja noch nicht released)

**Comment by rbirkelbach** [comment]
I deleted the three of you and inserted `N.N`. This project isn't released anyways, so it doesn't hurt at the moment.
