### ISSUE TITLE
As any user I want to report missing publications

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2236]

**Comment by rreitmann** [comment]
We think we should focus on a small solution like offering an email link for reporting missing publications. The body and subject should be preset with some form details (study, doi, citation string, title)

**Comment by AndyDaniel1** [comment]
The topic has gained in urgency due to the discussions of the last weeks. We should implement a low level solution. 

Since some of the details are still unclear, I put it up for discussion again, but keep Prio 1.

**Comment by rreitmann** [comment]
We will implement a FAB which displays a "welcome"-message reminding the user of clicking on it....

**Comment by rreitmann** [comment]
@rbirkelbach Please review carefully the texts and email address which I have used.

**Comment by rbirkelbach** [comment]
I would change the text from:
```
Liebes FDZ-DZHW,

ich möchte folgende Publikation(en) melden:
```

to

```
Liebes FDZ-DZHW,

ich möchte folgende Publikation(en), welche zu Datenpaket X gehören melden:
```

```
Dear FDZ-DZHW,

I would like to report the following publication(s), which belong to data package X:
```
