### ISSUE TITLE
update related publications documentation

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2239]
https://github.com/dzhw/FDZ_Allgemein/issues/365

**Comment by rreitmann** [comment]
@rbirkelbach We should focus on defining what "related" to our domain objects means.

**Comment by UteH** [comment]
also please update the whole documentation as it is very outdated 

> Für dieses Objekt wird eine Citavi-Datenabank angelegt. Diese liegt unter: \faustAbt4FDZQuerschnittsaufgabenMetadatenErzeugenLiteraturexportrelatedPublication.

**Comment by UteH** [comment]
was also discussed again in the advisory board
