### ISSUE TITLE
Refactor backend services

### ISSUE THREAD

**Issue by es-flavia** [dzhw/metadatamanagement#2246]
Our domain services call their attachment service directly if a domain object is deleted to remove all associated attachments.

Additionally an event is fired before and after deletion so other services can run some required logic in an event handler.

We should implement such event handlers in each attachment service and remove direct calls from domain services (e. g. SurveyService should not call SurveyAttachmentService.deleteAllBySurveyId. SurveyAttachmentService should instead handle delete events for Survey)

**Comment by rreitmann** [comment]
While fixing #2269 I discovered that the entire layering and event handling in the server is not clean. We should introduce exactly one service per domain slice and implement the rule that there is no direct communication between the domain slice, only through events. Each domain service is responsible for:
- CRUD of the leading domain object
- CRUD of attachments and images if applicable
- management of shadow copies when needed
- updating its elasticsearch index when needed
- validating incoming domain objects
- sending events

Each service may use helper beans and the common package and the search package.

**Comment by AndyDaniel1** [comment]
I need to get a deeper understanding of this issues especially to comprehend the references to #2282.

**Comment by rbirkelbach** [comment]
If Surveys/Instruments/Data Sets are marked as ready by the publisher and the publisher clicks on the edit button, they do not get a toast, but get forwarded to the overview page of the object they wanted to edit.
