### ISSUE TITLE
discuss structure of documentation for data provider

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2262]
I think it would be good to first discuss the structure and then to revise the documentation.

**Comment by AndyDaniel1** [comment]
From my perspective this is one of the most important issues for the next weeks. We will soon have important data providers (SLC, NACAPS, Estud) and this gonna be a real test for the MDM and the FDZ. A good documentation is absolutly indispensable for this.

**Comment by rbirkelbach** [comment]
Focus on Study, Dataset, Survey, Instrument

**Comment by rbirkelbach** [comment]
- Is it true that question images cannot be pdf? 
- Is it true that response images can be pdf?
