### ISSUE TITLE
As publisher I want to decide if shadow copies of a project shall be visible for users

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2278]
We discussed that there might come the case when we want to update a project but do not want the older versions to be visible due to data protection concerns (e.g. we made a mistake in our anoymization procedere or #2249 or else). 

exmaple: 
We might want to take down a version immediately and for good because we provided frequencies of variables we must not provide.

We need to discuss the details and the priorisation (e.g. with regard to #2249).

**Comment by AndyDaniel1** [comment]
I see the conceptual relevance of this issue but for now the prio is from my point of view an 8. Please come back to this issue (and me) if the urgency (re)emerges.

**Comment by UteH** [comment]
@anneweber fyi (anybody else?)

**Comment by anneweber** [comment]
@svietgen

**Comment by svietgen** [comment]
@AndyDaniel1 The subject has reemerged.

**Comment by AndyDaniel1** [comment]
@svietgen thank for the feedback! @rreitmann @rbirkelbach @UteH we should discuss this issue in the next refinement. Until then it would be helpful if you roughly estimate the implementation efforts.

**Comment by rreitmann** [comment]
@AndyDaniel1 This is difficult to estimate without further details. Actually I would even implement something different: Delete shadow copies of a project if and only if there is a different released version.

**Comment by rreitmann** [comment]
I think I got the intention of hiding/deleting shadow copies. However there are a couple of open questions:
1. What shall we do with the metadata for that version at Da|ra? We should at least update the version and set it to unavailable...
2. What do we want to show to the user if she comes with a hidden/deleted version via the DOI?
3. Can we still offer the hidden/deleted version for adding to the shopping cart?

**Comment by rreitmann** [comment]
We have decided to offer a GUI for hiding outdated shadow copies. Shopping cart shall not be possible but I have to investigate how to do this...

**Comment by rbirkelbach** [comment]
Dataproviders see on mouseover "this version is currently visible for all users. click here to hide this version" while they should not see the second sentence.
