### ISSUE TITLE
As a public (iphone) user I need safari support

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2303]

**Comment by AndyDaniel1** [comment]
To be honest the fact that we don't support safari was not really clear to me. I think that might be one reason for the harsh critizsm.

**Comment by rreitmann** [comment]
The matrix with supported browsers is publicly displayed in our README:
https://github.com/dzhw/metadatamanagement/blob/development/README.md

**Comment by AndyDaniel1** [comment]
That was my mistake! I should have been aware of this fact. One thing I was also not aware of was that even firefox and chrome are in fact safari on apple mobile devices. Nevertheless I'm not sure if the missing safari support is a huge problem. I suppose that apple users are a specifc group... the questions are: are these users using apple mobile devices for visiting the mdm? if that's the case: are apple users important enough that we are willing to extend the support to safari.

**Comment by rreitmann** [comment]
Ok, let us be more precise: A browser has two major components which are relevant for us:
- Rendering Engine (render html and css to the screen): https://en.wikipedia.org/wiki/Comparison_of_browser_engines
- Javascript Engine (executing javascript): https://medium.com/@acparas/browsers-rendering-engines-js-engines-bea42b77a182

On iOS Apple restricts the use of other engines (both rendering and javascript) to the ones which power Safari (Webkit and https://en.wikipedia.org/wiki/WebKit#JavaScriptCore). Thus Firefox and Chrome and ... on iOS use the same engines as Safari.

**Comment by rreitmann** [comment]
For supporting Safari on iOS we would need two things:
- A browser which runs on the developers machine and uses the same engines as Safari
- An iOS device
- Automated tests on saucelabs (https://saucelabs.com/resources/automated-testing/selenium-for-ios)

**Comment by rreitmann** [comment]
Yesterday I have tested saucelabs appium support. With this we can run our robot tests on Safari on an ios simulator, or a macos. Generally it works, however the tests fail as expected.

For debugging and local testing we would still need apple devices...

**Comment by rbirkelbach** [comment]
Btw: It's not just Safari on iOS that causes trouble, but also Safari on macOS.
