### ISSUE TITLE
publication cannot be uploaded if studySerieses.de contains whitespace (Student Life Cycle)

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2318]
Error message: 

> Die Publikation mit FDZ-ID pub-Mentges.2018$ wurde nicht gespeichert!
>     Es gibt keine Studie mit der Studienreihe ""! 

[relatedPublications.xlsx](https://github.com/dzhw/metadatamanagement/files/3456646/relatedPublications.xlsx)

**Comment by rreitmann** [comment]
I changed the separator to comma in the cell and then it works...
