### ISSUE TITLE
Are we able to import and represent long-format-data?

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2355]
We need to discuss in general if we're currently able to import and represent long-format-data properly.

@rbirkelbach adressed in issue #1834 one question in this context

**Comment by rbirkelbach** [comment]
| t | v |
|---|---|
| 1 | 1 |
| 1 | 2 |
| 2 | 3 |
| 2 | 4 |

Variable details site for variable v has choser where you can select t.

**Comment by AndyDaniel1** [comment]
The MDM currently cannot display the distributions of long format variables. 

Question: does this pose a problem for the user?

**Comment by rreitmann** [comment]
For various reasons (dataset report, one distribution per variable) the MDM supports only the wide format which contains one variable per value of t (v_1, v_2). These can be connected by `panelIdentifier`. We can implement a dropdown on the variable details page (of v_1) in which the user can select the associated variables (v_2)
