### ISSUE TITLE
Identify basic properties from dara which are relevant for domain objects

### ISSUE THREAD

**Issue by kpstephan** [dzhw/metadatamanagement#236]

**Comment by rreitmann** [comment]
http://www.da-ra.de/de/technische-informationen/doi-registrierung/

**Comment by rreitmann** [comment]
Currently the process of in cooperation with dara is undefined. We need to develop a vision about what we want to do with dara!

**Comment by anfranken** [comment]
@kpstephan attributes for the doi-registration: http://www.da-ra.de/fileadmin/media/da-ra.de/PDFs/MDS_Tabelle_3_1_201503_de.pdf

**Comment by anneweber** [comment]
Example: https://www.neps-data.de/de-de/datenzentrum/datenunddokumentation/startkohorteerwachsene/datenundzitation.aspx

**Comment by anfranken** [comment]
At the moment this isn't important, because we will not build a export for da|ra
