### ISSUE TITLE
As a dataprovider I want to have checks for correct input format in questionMetadataPreparation

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2364]
E.g. successorNumbers should get checked that it's really delimited by a comma and not a dot or semicolon. This does not show an error when importing the jsons in the mdm and is thus prone to errors.

**Comment by rreitmann** [comment]
we need to raise an error in the R package

**Comment by rreitmann** [comment]
we should support comma and semicolon

**Comment by rbirkelbach** [comment]
Instead of throwing an error, we decided to allow `,`, `; ` and `-` as delimiters.
