### ISSUE TITLE
Discuss: Description of datasets / access ways

### ISSUE THREAD

**Issue by anneweber** [dzhw/metadatamanagement#2375]
As discussed yesterday in the sprint review, the description of the datasets and access ways (e.g. https://metadata.fdz.dzhw.eu/#!/de/data-sets/dat-gra2005-ds1$?version=2.0.0) should be revised, for example as follows (thanks to @fbaillet):

![accessways](https://user-images.githubusercontent.com/17066262/65014656-947dd980-d91f-11e9-89e3-a2bc4c4dde36.PNG)

**Comment by rreitmann** [comment]
Ideally the description is automatically added after choosing the access-way, currently the users have to type it in...

**Comment by UteH** [comment]
@anneweber

**Comment by AndyDaniel1** [comment]
There will be a new issue on this topic
