### ISSUE TITLE
Discuss: Link to studies from the research field that are published by other RDCs?

### ISSUE THREAD

**Issue by anneweber** [dzhw/metadatamanagement#2377]
While reading the FAQs for the new website (https://dzhw-dlp.elementsystems.io/de/node/1543) I just had the following question: Do we, as a research-field related RDC, also have to provide information on studies from the research field that are not published by us? For example, via a link to another RDC in the MDM?

(@schellep @fbaillet @AndyDaniel1)

**Comment by rreitmann** [comment]
We currently think that the MDM should only contain data of projects which our RDC hosts. Anyway the DZHW website and the project sites there should contain links to the datasets from other RDCs...

**Comment by schellep** [comment]
I agree. For me it seems to be impossible to offer links to all relevant information. And to foster all this information. Infact we can only give recommendations. We should recommend for data the [VFDB "Studiensuche"](https://www.forschungsdaten-bildung.de/studienliste.php?la=de), [da|ra](https://www.da-ra.de/dara/search/) etc. and for publications maybe some relevant websites ([BASE](https://www.base-search.net/), [Metager](https://metager.de/) and if you want google scholar) or subject specific databases (Current Contents, ProQuest, SOLIS, Web of Sciences).
