### ISSUE TITLE
move variable Json documentation from RTD to pkgdown

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2378]
As we now have pkgdown documentation for variableMetadataPreparation, we should move the relevant parts of the documentation from readthedocs to the pkgdown documentation.

**Comment by rreitmann** [comment]
I have discussed this with @anneweber and we think that pkgdown is the place for technical documentation for developers and the FDZ Wiki is the place for the user (publisher) documentation. Therefore I will not move the documentation from readthedocs to pkgdown.
