### ISSUE TITLE
Links to the MDM in Twitter

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2382]
Since Twitter accepts no "$" in links, it is not possible to set a link to a study detail page in twitter. 
![grafik](https://user-images.githubusercontent.com/17981185/65488683-f56e5a00-dea9-11e9-8d1f-491c44d2eae5.png)

**Comment by rreitmann** [comment]
$ could be escaped by %24

**Comment by rreitmann** [comment]
We need to investigate if we can force angular to escape $ automatically...

**Comment by MIKAGMR** [comment]
You can encode the dollar character (%24):
Original URL: https://metadata.fdz.dzhw.eu/#!/de/data-sets/dat-bst02-ds1$?version=1.0.0
New URL: https://metadata.fdz.dzhw.eu/#!/de/data-sets/dat-bst02-ds1%24?version=1.0.0

**Comment by rreitmann** [comment]
According to this https://stackoverflow.com/a/20050487/4758835 $ is ok to be used in URLs, thus I think it is a bug in the twitter app...

**Comment by MIKAGMR** [comment]
Why not use a URL shortener like https://bitly.com/ or https://goo.gl/?

**Comment by rreitmann** [comment]
@MIKAGMR Generally a good idea, however in this case the user is on the details page and clicks share in the browser which just sends the current url to the selected app. The app decides how to display the url...

**Comment by MIKAGMR** [comment]
We can use an alias for the URL: https://stackoverflow.com/questions/23830421/how-to-implement-path-aliases-in-ui-router

**Comment by rreitmann** [comment]
In addition to an alias we could remove the $ if the user comes with an URL containing the $

**Comment by rreitmann** [comment]
I have just opened an issue for twitter:
https://github.com/twitter/twitter-text/issues/287

**Comment by rreitmann** [comment]
I will remove the $ from all details urls. Internally I will add it to construct a valid `domainObject.id`.
