### ISSUE TITLE
Build an english dataset report template

### ISSUE THREAD

**Issue by anneweber** [dzhw/metadatamanagement#2388]

**Comment by rbirkelbach** [comment]
What do we have to do to achieve this...?

**Comment by rreitmann** [comment]
@rbirkelbach I have enabled english and german template processing on the dev system, so you can start working on the [template](https://github.com/dzhw/dataset-report-task/tree/development/src/main/resources/template). Each commit on the development branch will be deployed automatically...

The GUI still needs some improvements:
- align checkboxes
- disallow no language selection

**Comment by rreitmann** [comment]
@rbirkelbach GUI problems are solved, however there is a problem when switching the latex locale to EN in the english template....

**Comment by rbirkelbach** [comment]
@rreitmann Please explain the problem with the LaTeX locale to me later. Thx

**Comment by rreitmann** [comment]
@rbirkelbach I have created an english version of the latex package and it is already working. Additionally I have improved the error handling.

Still there are some TODOs in the english package for you to fix...

**Comment by rbirkelbach** [comment]
I think the German report should end with `_de` similar to the english which ends in `_en`.
