### ISSUE TITLE
Design filter panel for data package search

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2396]
The public user wants to search and find data packages. The following filters could IMHO be relevant:
- study.tags
- studySeries
- surveyDataType
- collectionPeriod (aggregate over all surveyPeriods)
- concept
- institute
- sponsor

Filter panel should show number of hits like here: https://www.forschungsdaten-bildung.de/studienliste.php?la=de

**Comment by MIKAGMR** [comment]
![Filterkriterien](https://user-images.githubusercontent.com/625114/66203319-5ff07880-e6a8-11e9-85c5-28a446db2a75.png)

**Comment by MIKAGMR** [comment]
![DZHW-Search-Layout-08102019](https://user-images.githubusercontent.com/625114/66380754-50c73e80-e9b8-11e9-9467-896e53d5b11e.png)

**Comment by rreitmann** [comment]
@MIKAGMR please adjust the design according to my previous [comment](https://github.com/dzhw/metadatamanagement/issues/2396#issuecomment-540543007)

**Comment by MIKAGMR** [comment]
![DZHW-Search-Layout](https://user-images.githubusercontent.com/625114/66632267-56b35e80-ec08-11e9-838f-237c8827a593.png)

**Comment by rreitmann** [comment]
Here are some remarks to consider:
![uebersichtsseite](https://user-images.githubusercontent.com/12323832/67693466-04ad5f80-f9a2-11e9-8c15-1b3630b021e1.jpg)
