### ISSUE TITLE
Design search result list for data package search

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2397]
The following attributes must be on each search result:
- study.title
- surveyDataType
- collectionPeriod (aggregate over all surveys)
- study.description
- direkt links to list of publications, materials like here (https://www.forschungsdaten-bildung.de/studienliste.php?la=de)
- some numbers (e.g. number of variables? number of datasets?)

**Comment by MIKAGMR** [comment]
![Study Search Result](https://user-images.githubusercontent.com/625114/65969657-75299500-e465-11e9-8172-da367d59e9ab.png)

**Comment by MIKAGMR** [comment]
![Study Search Result](https://user-images.githubusercontent.com/625114/65970222-62fc2680-e466-11e9-972a-56564db64dbb.png)

**Comment by MIKAGMR** [comment]
![DZHW-Search-Layout-08102019](https://user-images.githubusercontent.com/625114/66380950-a8fe4080-e9b8-11e9-9508-ef954ea55eb2.png)

**Comment by rreitmann** [comment]
Due to #2411 we need a link "Suche ''$query" im Datenpaket" on each search result which transfers the current query string to the tab search on the data package details page.

**Comment by rreitmann** [comment]
@MIKAGMR  see #2396

**Comment by MIKAGMR** [comment]
![DZHW-Search-Layout](https://user-images.githubusercontent.com/625114/66632203-34214580-ec08-11e9-8931-29dffee94d61.png)

**Comment by rreitmann** [comment]
Here are some remarks to consider:
![uebersichtsseite](https://user-images.githubusercontent.com/12323832/67693423-f52e1680-f9a1-11e9-9e49-c00028b4ac23.jpg)

**Comment by UteH** [comment]
Plus Anzahl Suchergebnisse?

**Comment by rreitmann** [comment]
The paginator contains the number of search results...
