### ISSUE TITLE
Display quanti & quali on the data package detail page in case of mixed method packages

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2403]
The data package detail page should display an array of both survey data types (quali & quanti) in case of mixed methods packages.

Mixed method should also be displayed.

**Comment by rreitmann** [comment]
After discussion: Mixed method will not be displayed cause it is not well defined.

**Comment by rreitmann** [comment]
@UteH We have changed OrderedStudy.surveyDataType to OrderedStudy.surveyDataTypes (a list). Now the link from the DLP to the MDM (Warenkorb bearbeiten) does not work anymore...

**Comment by UteH** [comment]
@amacado we changed the name of a field used by the DLP (see [above](https://github.com/dzhw/metadatamanagement/issues/2403#issuecomment-551783277))

Could you please change this accordingly? As we do not use this information yet (as far as I know), I hope it is not too much work.
