### ISSUE TITLE
Design start page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2404]
The usability experts indicated that we might need a start page for the MDM which contains the search input and a couple of additional texts and links.

**Comment by MIKAGMR** [comment]
![DZHW-Start-Layout](https://user-images.githubusercontent.com/625114/66380985-be736a80-e9b8-11e9-9118-89fd8a716a01.png)

We are waiting for the content of the blue boxes.

**Comment by rreitmann** [comment]
We (@UteH & me) have now discussed again about a homepage, which should be the entrance point to our search (and thus apear before the main search page). 

The homepage should contain the following elements of Smit und Partner's proposal: 

1st heading "data search"; 
2nd text about focus of fdz-dzhw (Forschungsfeldbezug) ; 
3rd search field; 
4th tiles carousel with study series and, if no series is avaiable, with study: 
5th newest data package;

**Comment by rreitmann** [comment]
@MIKAGMR please adjust the design according to my last [comment](https://github.com/dzhw/metadatamanagement/issues/2404#issuecomment-540526301)

**Comment by rreitmann** [comment]
A link to all data packages (search without query) is still missing but that will be added during implementation.
