### ISSUE TITLE
Design data package details page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2405]
The site must display all details about the data package and must allow configuration of the data package (version and access way).

**Comment by MIKAGMR** [comment]
Layout in FHD

![DZHW-Detail-Layout](https://user-images.githubusercontent.com/625114/66474559-d539c000-ea91-11e9-813e-5957965d1c99.png)

**Comment by MIKAGMR** [comment]
Layout in 1024px width

![DZHW-Detail-Layout-1024px](https://user-images.githubusercontent.com/625114/66474590-ebe01700-ea91-11e9-9ac6-1b97159be3c0.png)

**Comment by MIKAGMR** [comment]
Changed the placeholder of the second search bar

![DZHW-Detail-Layout](https://user-images.githubusercontent.com/625114/66508514-962b5f00-ead1-11e9-9f4e-38d88701ea81.png)

**Comment by rreitmann** [comment]
@MIKAGMR We have some questions:
1. How will a long study.title be displayed (Kom­Pa­ed 2014 - Tä­tig­keits­be­zo­ge­ne Kom­pe­ten­zen in päd­ago­gi­schen Hand­lungs­fel­dern (quan­ti­ta­ti­ve Teil­stu­die))? We are thinking about limiting the title to fewer characters!
2. Blue color of the search inputs disturbs us
3. Can we use the same design as the revised search (like google careers)

**Comment by MIKAGMR** [comment]
As discussed, the new draft:

![DZHW-Detail-Layout](https://user-images.githubusercontent.com/625114/66632053-ead0f600-ec07-11e9-8cd4-dc5802568677.png)

**Comment by MIKAGMR** [comment]
![DZHW-Detail-Layout](https://user-images.githubusercontent.com/625114/66649570-cb998f00-ec2e-11e9-863e-9c1ebb67a30b.png)

**Comment by rreitmann** [comment]
Outcome from todays review: We need to display all attachments of the data package in an organized way. => new issue
