### ISSUE TITLE
Implement new paginator with sorting and page size

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2406]

**Comment by MIKAGMR** [comment]
Which options should have the select elements of sorting and items per page?

**Comment by MIKAGMR** [comment]
@rreitmann Please check the implementation in the branch "mikagmr/issue2406".

Todos:
- [ ] Create sort options (elastic search) and implement these options
- [ ] Discuss design for small screens
- [ ] Add "fdz-paginator" to the package.json after it's release

**Comment by rbirkelbach** [comment]
Falls bisher ausschließlich nach Relevanz sortiert werden soll, scheint mir alles in Ordnung (in FF, Chrome, IE, Edge).
