### ISSUE TITLE
As a public user I want to know the newest data package with v1.0.0 and dp with newest subDataSet

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2407]
For the ~dlp~ Website we need to know what data package was last released. @fbaillet has the following specifications, which probably need some manual intervention as I don't think the second specification is possible to extract automatically:
1) What is the newest data package with version 1.0.0?
2) What is the newest package where a new sub dataset was added (e.g. new wave).
I think it would be sufficient to get this information via an api, as it's needed for the dlp.
https://app.slack.com/client/TNMPDL5HT/threads/thread/CNPVDQF8W-1570192658.001200

![grafik](https://user-images.githubusercontent.com/18573122/84384811-d6a62400-abee-11ea-92c9-b4aae4524276.png)

@fbaillet did I understand you correctly?

**Comment by rreitmann** [comment]
we prefer to implement #2479
