### ISSUE TITLE
Homepage for data search

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2410]
We (@UteH & me) have now discussed again about a homepage, which should be the entrance point to our search (and thus apear before the main search page). 

The homepage should contain the following elements of Smit und Partner's proposal: 

1st heading "data search"; 
2nd text about focus of fdz-dzhw (Forschungsfeldbezug) ; 
3rd search field; 
4th tiles carousel with study series and, if no series is avaiable, with study: 
5th newest data package;

**Comment by rreitmann** [comment]
duplicates #2402
