### ISSUE TITLE
Implement data package search for public users

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2428]
As designed in #2396 but without the search filters.

**Comment by MIKAGMR** [comment]
@rreitmann Please check branch Mikagmr/issue2428

**Comment by rreitmann** [comment]
@MIKAGMR here are some review remarks:
- currently data package search executes three identical remote searches after typing "test" rapidly
- we need to display at least a card saying "no results found" when there are no search results
- the progress indicator should for the search should not be in/above the input, it should be below
- when clicking on a data package search result the old query string should remain in the input in the sidenav

**Comment by MIKAGMR** [comment]
- [ ] currently data package search executes three identical remote searches after typing "test" rapidly
- [ ] we need to display at least a card saying "no results found" when there are no search results
- [ ] the progress indicator for the search should not be in/above the input, it should be below
- [ ] when clicking on a data package search result the old query string should remain in the input in the sidenav
- [ ] the search input in the sidenav on the details page should navigate to the data package search on enter

**Comment by MIKAGMR** [comment]
@rreitmann 
> the progress indicator for the search should not be in/above the input, it should be below

The indicator is below the input not in or above of it.

**Comment by rreitmann** [comment]
- [ ] currently there is no progress indicator in the search input anymore
- [ ] when authenticated the all search tabs now displays search results without icons
- [ ] When not authenticated the breadcrumb says "Datenpaketsuche (Studien)", should only be "Datenpaketsuche"
- [ ] when I am authenticated and go to any administration view the search query input appears in the sidenav

**Comment by MIKAGMR** [comment]
@rreitmann 
>> when authenticated the all search tabs now displays search results without icons
There are no icons in the new design.

**Comment by rreitmann** [comment]
- [ ] the link "Suche ... im Datenpaket" is not internationalized, put quotation marks around the query string
- [ ] the link "Suche ... im Datenpaket" must not be displayed when authenticated
- [ ] the description on the data package search result is not changed when the language changes (remains in the old language)

**Comment by rreitmann** [comment]
@MIKAGMR here are some more remarks:
- [ ] public user: the description on the data package search result is not changed when the language changes (remains in the old language)
- [ ] public user: each search is executed twice (simultaneously)
- [ ] the link "Suche ... im Datenpaket" is visible anymore when authenticated, however there appears an additional margin/padding
- [ ] "delete filter" button restores old state (previous query, previous page size,...) instead of only deleting the filters
- [ ] "delete filter" button should be placed in the same line as the filter heading
- [ ] searchHelper.addNewFilters is called many (ca. 10 times) on a filter click, some of them without elasticsearchType causing errors in the console.log
- [ ] click on fdz logo restores already unset filter options

**Comment by rreitmann** [comment]
- [ ] search result navigation shows wrong data packages (filter by study series -> click on first data package -> click next button)

**Comment by rreitmann** [comment]
- [ ] search result navigation shows wrong surveys, from other data packages (click on data package -> click first survey -> click next)

**Comment by rreitmann** [comment]
- [ ] highlight query string in search result cards

**Comment by MIKAGMR** [comment]
@rreitmann 
> when typing new query string the search shows empty search result cards
Please, could you review this again? I can not find this problem.

**Comment by rreitmann** [comment]
highlighting query string is too much effort
