### ISSUE TITLE
Refactor css and html structure

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2429]

**Comment by rreitmann** [comment]
- [ ] adjust keyboard navigation (orang marker,...)

**Comment by MIKAGMR** [comment]
- [ ]  attachments: we need to refine all paddings and margins, in most cases 16px is far too much

**Comment by MIKAGMR** [comment]
@rreitmann If you find more CSS problems in your reviews, please add these to the todo list above.

**Comment by rreitmann** [comment]
Here are my remarks for the public user:
- [ ] list in data package configurator has no vertical margins anymore, should have the same as list in details section
- [ ] the divider between the search results on the details pages is thicker than all other dividers
- [ ] vertical space beween heading "Materialien zu dem Datenpaket" and the divider below is not the same as the others
- [ ] vertical spaces in the filter panel are not equal (above and below the input and between the dividers)
- [ ] Survey Details should not show card "Weitere Informationen zum Rücklauf" when there is no image
Here are my remarks for the authenticated user:
- [ ] sidenav now has some blue entries
- [ ] project overview is slightly more aligned to the left than the others
- [ ] search: there are empty cards from the paginator when there are no search results
- [ ] search: search tabs now have margins
- [ ] titles of cards in project cockpit are now centered
- [ ] main card of project cockpit now has a padding
- [ ] buttons of the cards in project cockpit should have same width
- [ ] change password: password strength indicator looks strange
