### ISSUE TITLE
Implement detail pages in the new design

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2431]
We will not implement the complete data package details as designed here #2405 but we will convert the current detail pages into the new design....

**Comment by MIKAGMR** [comment]
@rreitmann We have to discuss a few topics tomorrow in our meeting:

- Breadcrumbs: We should build a new simplified component.
- Test data to create and test the templates in variable, publication & concept detail views.
- We have to discuss how we handle the filter (e.g. study-series) for the related object section in the detail views. 
- For another issue: We should clean (and optimise) the source code, because of unneeded or redundant loaded data.
- The actual search functionality runs fine. We could build a new search functionality for the related objects section, but it's currently not needed.

**Comment by rreitmann** [comment]
@MIKAGMR here are some review remarks:
- on the study details it says: "Projektmitarbeiter" twice
- the search on the details should display "no surveys found" if there are no
- IMHO we need a divider above the first search result and below the last one on the details pages
- when authenticated the padding-top of the md-card-content has been lost
- data set details: sub data sets card header has wrong heading (details)
- the version parameter in the url is lost when I switch tabs on the details page
- when I click on a search result on the details pages and immediately click the back button only some url params change but I stay on the details page (you need to add parameter on init without manipulating adding new browser history entries)
- search result navigator is broken (orange next/previous buttons)

**Comment by MIKAGMR** [comment]
- [ ] on the study details it says: "Projektmitarbeiter" twice
- [ ] the search on the details should display "no surveys found" if there are no
- [ ] IMHO we need a divider above the first search result and below the last one on the details pages
- [ ] when authenticated the padding-top of the md-card-content has been lost
- [ ] data set details: sub data sets card header has wrong heading (details)
- [ ] the version parameter in the url is lost when I switch tabs on the details page
- [ ] when I click on a search result on the details pages and immediately click the back button only some url params change but I stay on the details page (you need to add parameter on init without manipulating adding new browser history entries)
- [ ] search result navigator is broken (orange next/previous buttons)

**Comment by MIKAGMR** [comment]
>  on the study details it says: "Projektmitarbeiter" twice
We don't have this problem

> data set details: sub data sets card header has wrong heading (details)
I don't find it with the test data I have...

> IMHO we need a divider above the first search result and below the last one on the details pages
The dividers are not required. There is enough space between the two paginators and the search results.

>search result navigator is broken (orange next/previous buttons)
This is a bigger problem. Currently, it switched between the items in the data packet. We need to save the last search result and handle the navigator. It runs fine with the authenticated user...

**Comment by MIKAGMR** [comment]
@rreitmann I think we should think about a new issue for the broken search result navigator. The problems are two search functionalities and the searchResultNavigator Service...

**Comment by rreitmann** [comment]
@MIKAGMR Here are additional remarks for all details pages:
- [x] Instead of institutions the label is "Projektmitarbeiterinnen" and institutions are not displayed
- [x] data set details: sub data sets card header has wrong heading (details)
- [ ] In German the placeholder in the search says "Suchen Erhebungen"
- [ ] The breadcrumb says "Datenpaketsuche (Studien)" but should be Datenpaketsuche for the public user
- [ ] The breadcrumb says "Study xyz" but should be "Datenpaket xyz" for the public user
- [ ] survey details: response rate is missing, geographicCoverages are missing
- [ ] the following details pages can have attachments (Materialien): study (data package), survey, data set, instrument, concepts. The card must only be displayed if there are any attachments for the current domain object
- [ ] question details: for non-PAPI questionnaires there is the resolution displayed below the image which mises some padding at the moment
- [ ] question details: The button which displays the current image in a new tab should flow over the image
- [ ] question details: successors and predecessors in questionnaire should have a divider

**Comment by rreitmann** [comment]
- [ ] missing padding-top: project cockpit (study/surveys/... card content), study description
- [ ] when authenticated: publications are not displayed anymore
- [ ] when not authenticated: publications are displayed in the old design

**Comment by rreitmann** [comment]
- [ ] search result navigator is broken (orange next/previous buttons)
- [ ] images and links in the footer do not react on language change
- [ ] missing padding-top: study description (when authenticated)

**Comment by rreitmann** [comment]
- [ ] reload on survey details page displays 0 data-sets after switching the tabs there are two data-sets
- [ ] survey details should not display surveys tabs

**Comment by rreitmann** [comment]
- [ ] switching search tabs adds unrequired url param study=stu...

**Comment by MIKAGMR** [comment]
> we now get a 404 toast when we come with a version which does not exist anymore, the previous toast is displayed for a very short time (go to data package details, modifiy the url version to a non existing one (> = 1.0.0) and reload page), in this case the "note for application" button is gone (not in the DOM)

We remove the configurator instead of showing an empty one.

**Comment by rreitmann** [comment]
- [ ] I still get a 404 when I come with a version which does not exist anymore. Expected behaviour: redirect to latest version and display the toast which notifies the user about that fact.

**Comment by rreitmann** [comment]
- [ ] when I come with a link to a hidden shadow copy I am not redirected to the current version anymore (https://metadatamanagement-test.cfapps.io/#!/de/studies/stu-shadowstest$?version=1.0.1)

**Comment by rbirkelbach** [comment]
- subdatasets table is transposed in edge (also in public mode)

**Comment by rbirkelbach** [comment]
>     * [x]  when I come with a link to a **hidden** shadow copy I am not redirected to the current version anymore (https://metadatamanagement-test.cfapps.io/#!/de/studies/stu-shadowstest$?version=1.0.1)

There are different toasts depending on the browser. In FF it's " Sie betrachten eine versteckte Schattenkopie (1.0.1). Hier geht es zur aktuellen Version!" whereas in IE it's "Ihr Link verweist auf eine ältere Version (1.0.1) dieser Seite. Hier wird die aktuelle Version (1.0.2) dargestellt.  "

**Comment by rbirkelbach** [comment]
I'm not sure this needs a new issue, but maybe it would be good to let all objects that are a level lower in the hierarchy than study inherit publications. I felt a bit confused that publications are shown sometimes and sometimes not, even though I knew that they are often just linked with the study.

**Comment by rreitmann** [comment]
@rbirkelbach

> I'm not sure this needs a new issue, but maybe it would be good to let all objects that are a level lower in the hierarchy than study inherit publications. I felt a bit confused that publications are shown sometimes and sometimes not, even though I knew that they are often just linked with the study.

I guess u have been logged in in one browser and not in the other.

> I'm not sure this needs a new issue, but maybe it would be good to let all objects that are a level lower in the hierarchy than study inherit publications. I felt a bit confused that publications are shown sometimes and sometimes not, even though I knew that they are often just linked with the study.

This would be a new issue, which we need to discuss. Another option is not to show the publications tab at all for other objects than study (since there are no publications anyway)
