### ISSUE TITLE
As a data provider I want to put links into the annotation field 

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2444]
https://github.com/dzhw/metadatamanagement/issues/1178
https://github.com/dzhw/metadatamanagement/issues/286

**Comment by rreitmann** [comment]
We will integrate a markdown parser for specific fields. We will remove markdown from the dataset report and da|ra export.

**Comment by rreitmann** [comment]
I have added markdown support for the following fields:
`study.description`
`study.annotations`
`survey.annotations`
`survey.population.description`
`survey.geographicCoverage.description`
`dataSet.annotations`
`variable.annotations`
`variable.filterDetails.description`
`variable.generationDetails.description`
`instrument.annotations`
`question.annotations`
`relatedPublication.annotations`
`concept.description`
`concept.license`
`concept.citationHint`

**Comment by rreitmann** [comment]
Need to remove markdown from study.annotations for DLP....

**Comment by JohannaNiebuhr** [comment]
I have tested if markdown is working in the following fields: 
`study.description`
`study.annotations`
`survey.annotations`
`survey.population.description`
`survey.geographicCoverage.description`
`dataSet.annotations`
`instrument.annotations`
`concept.description`
`concept.license`
`concept.citationHint`

-> everything seems fine

The only thing i noticed: When you scroll down to related objects, the "preview" of the other objects does not display the different markdown formats right. I dont know if that is on purpose or not.

**Comment by rbirkelbach** [comment]
Headings do not work, it doesn't matter whether I use #-notation or underline headings (I get an invalid json error, even though jsonlint.com claims it's valid json).

Also, I cannot generate ds reports:
```
Liebe(r) robertbirkelbach,

beim Erzeugen Ihres Datensatzreports zu Datensatz "dat-johanna-ds1$" ist folgender Fehler aufgetreten:
FillTemplateException(errorListDto=ErrorListDto(errorDtos=[ErrorDto(entity=null, message=data-set-management.error.tex-template-error, invalidValue=The following has evaluated to null or missing:
==> validResponse.label  [in template "variables/Variable.tex" at line 164, column 65]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #if validResponse.label.en?? && valid...  [in template "variables/Variable.tex" at line 164, column 60]
----, property=null)]))
Die Administratoren des MDM wurden ebenfalls benachrichtigt und werden Sie ggf. kontaktieren.

Grüße, 
Ihr FDZ-Team.
```

**Comment by rreitmann** [comment]
- the "preview" e.g. study.description on search results removes markdown on purpose cause otherwise I cannot limit the number of displayed characters. Furthermore the user could crash the design of the cards
- headings do not really make sense since the site already contains headings and it depends on the side which heading level (h1, h2, h3,...) would be the correct one

**Comment by rreitmann** [comment]
To sum up:
- [ ] The dataset report template cannot cope with validResponses without label
- [ ] We need to test how to upload variables with markdown include

**Comment by rreitmann** [comment]
headings are allowed with leading # 
however minimum heading level will be 6 for all headings generated from markdown

**Comment by rbirkelbach** [comment]
I currently have trouble with inserting linebreaks as `\n` gets escaped to `\\n`. This is caused by the jsonlite dependency. I've checked this only for variableMetadataPreparation -- will test it now for questionMetadataPreparation.

**Comment by rreitmann** [comment]
jsonlite should automatically convert linebreaks to \n

**Comment by rbirkelbach** [comment]
All seems to be good now! The headings also have correct levels.
