### ISSUE TITLE
Implement data package filter for public users

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2446]

**Comment by MIKAGMR** [comment]
@rreitmann Check branch #2431

**Comment by rreitmann** [comment]
@MIKAGMR here are my first remarks:
- [ ] filters are not fully internationalized (clear filter button, not available)
- [ ] filters show unreleased content (study serieses) @rreitmann

**Comment by rreitmann** [comment]
- [ ] filter in url needs to be cleared on language change (check "Qualitative Daten" -> change language -> no search results)

**Comment by rreitmann** [comment]
- [ ] filter in url needs to be cleared on language change (check "Qualitative Daten" when German -> change language to English-> no search results)

**Comment by rreitmann** [comment]
- [ ] filters are not deselected when clicking back-button

**Comment by rbirkelbach** [comment]
internet explorer: I cannot select multiple filters of the same kind (e.g. qualitative and quantitative)

**Comment by rbirkelbach** [comment]
- when clicking on tags of concepts, I get a server unreachable error
- IE: I cannot select more than one checkbox of one kind and cannot uncheck the box by clicking on it.

**Comment by rreitmann** [comment]
@rbirkelbach Already fixed
