### ISSUE TITLE
Implement data package configurator for public users

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2447]

**Comment by rreitmann** [comment]
@MIKAGMR Here are some first remarks:
- [ ] data package configurator and search must be displayed only on details pages, currently it is visible on login and disclosure
- [ ] version changes must change the currently displayed details of data packae (study), survey, instrument, question, data set, variable
- [ ] access way changes must filter the related objects
- [ ] when coming from the data package search the current version must be selected

**Comment by rreitmann** [comment]
- [ ] page reload on variable, data-set, survey, instrument, question details does not show the data package configurator
- [ ] click on first data-package search result => browser back button does not work
- [ ] switching search tabs to types which are not filtered by access-way removes the filter completely (from the location) which leads to unfiltered variables

**Comment by rreitmann** [comment]
- [ ] heading should be a link to the study/data package

**Comment by rreitmann** [comment]
- [ ] study details link does not have currently selected version 
- [ ] new selected version is immediately rolled back to current version (on data package details)
- [ ] access ways differ between different versions -> reinit on selected version change

**Comment by MIKAGMR** [comment]
> access ways differ between different versions -> reinit on selected version change
Access way is always reinitialised when the version changes

**Comment by rreitmann** [comment]
when I am on the publication details coming from a data package:
- [ ] study details link does not have currently selected version (after changing the version)
- [ ] access ways are not reloaded on selected version change

**Comment by MIKAGMR** [comment]
- [ ] Button is visible when no other information is shown

**Comment by rbirkelbach** [comment]
- when clicking on tags of concepts, I get a server unreachable error
- subdatasets table is transposed in edge (also in public mode)

**Comment by rbirkelbach** [comment]
It does not load properly when I click on the links in the cart (e.g. N variables)
