### ISSUE TITLE
Implement aggregate list of attachments for data package details

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2456]

**Comment by MIKAGMR** [comment]
@rreitmann The public user cannot access the API (401 (Unauthorized)).

**Comment by rreitmann** [comment]
- [ ] card-title "Datenpakete" should be "Studie"
- [ ] remove title attribute from fdz-attachment (it causes a browser tooltip on the entire card)
- [ ] do not collapse cards on init
- [ ] we need to refine all paddings and margins, in most cases 16px is far too much

**Comment by MIKAGMR** [comment]
>  we need to refine all paddings and margins, in most cases 16px is far too much

Moved to issue #2429
