### ISSUE TITLE
Implement sort option for paginator

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2458]
Alphabetical,...

**Comment by AndyDaniel1** [comment]
We need to define the sorting criteria

**Comment by rreitmann** [comment]
I suggest: max(surveyPeriod.end) for data packages.

**Comment by UteH** [comment]
@AndyDaniel1 Prio 1? 

currently, the data packages are sorted by DAP id which makes no sense at all to external users

**Comment by UteH** [comment]
> I suggest: max(surveyPeriod.end) for data packages.

I like it because most often it's similar to newest release. Not sure though which is better for the users

**Comment by rreitmann** [comment]
Lexicographically by title, max(surveyPeriod.end), release.lastDate, release.firstDate
