### ISSUE TITLE
Use public details views for authenticated user as well

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2459]

**Comment by rreitmann** [comment]
- [ ] study search cards (when authenticated) show edit button on a different place as others
- [ ] actions on search cards should contain text buttons instead of icon buttons
- [ ] publication year on publication search results should not be right aligned
- [ ] data package publication date is not visible for public user
- [ ] others details then study/data package are still in the old design

**Comment by rreitmann** [comment]
@rreitmann:
- [ ] when this is done we can reduce the amount of data loaded for the details views
- [ ] when this is done we need to remove study details from the childrens search index

**Comment by MIKAGMR** [comment]
Moved to #2429:
- study search cards (when authenticated) show edit button on a different place as others
- actions on search cards should contain text buttons instead of icon buttons

**Comment by rreitmann** [comment]
- [ ] Json view button is only visble on study/data package details, should be visible on all details pages for authenticated users
- [ ] Link to master on shadow copy alert does not work (login, open url with version set to shadow copy version, see alert toast)

**Comment by rreitmann** [comment]
- [ ] json view button should be in the upper right corner of all details views (study is correct) 
- [ ] links to tag filter and study series filter are still wrong when authenticated (tag should point to query (on study details and concept details), study series to study-series-de/study-series-de)
- [ ] study details should not show card "Materialien zum Datenpaket" when there are no attachments at all

**Comment by rbirkelbach** [comment]
- Data package is still called study.

**Comment by rreitmann** [comment]
@rbirkelbach create a backlog item for this:

> Not sure if this belongs here, but when editing surveys, gross sample size can be smaller than net sample size.

**Comment by rreitmann** [comment]
Won't fix the edge problems....
