### ISSUE TITLE
Implement info i for version and access-way

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2460]
Info button opens a modal.
@rbirkelbach Delivers texts for both attributes in German and English

**Comment by rbirkelbach** [comment]
accessWaysInfoDE: Für unsere Datenpakete gibt es drei Zugangswege, die a) den Grad der Anonymisierung bestimmen und b) bestimmen auf welchem Weg die Daten verarbeitet werden können und ob sie zur Verwendung in der Lehre zugelassen sind. *S*cientific *U*se *F*iles (SUF) sind ausschließlich zum Zweck der Forschung zu verwenden und sind gegliedert in Download-SUF (stark anonymisiert), Remote-Desktop-SUF (mittlerer Anonymisierungsgrad) und Onsite-SUF (geringer Anonymisierungsgrad). Einen Download-SUF können Sie auf ihrem eigenen Rechner verarbeiten; Remote-Desktop-SUFs stehen Ihnen übers Internet in einer virtuellen Desktopumgebung zur Verfügung und Onsite-SUFs können Sie ausschließlich im FDZ.DZHW vor Ort analysieren. CUFs werden zum Download bereitgestellt und sind zugelassen zur Verwendung in der Lehre. Weitere Informationen finden Sie [hier](https://fdz.dzhw.eu/datennutzung/zugang).

**Comment by rreitmann** [comment]
@rbirkelbach you can add english translations here:
[German](https://github.com/dzhw/metadatamanagement/blob/development/src/main/webapp/scripts/ordermanagement/configuration/translations-de.js#L87
)
[English](https://github.com/dzhw/metadatamanagement/blob/development/src/main/webapp/scripts/ordermanagement/configuration/translations-en.js#L87)
