### ISSUE TITLE
Implement start page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2474]
as designed in #2404

**Comment by MIKAGMR** [comment]
Branch: mikagmr/start

**Comment by rreitmann** [comment]
@rbirkelbach Deployment on test system is running. Please provide text and pictures for the startpage....

**Comment by rbirkelbach** [comment]
Überarbeiteter Vorschlag:

# Datenpakete aus der Hochschul- und Wissenschaftsforschung finden

Mit der Datenpaketsuche können Sie die Metadaten der beim FDZ.DZHW hinterlegten Datenpakete schnell und einfach durchsuchen. So finden sie alle Informationen, die Sie brauchen, und können die entsprechenden Datenpakete direkt bestellen.

Entsprechden Anwendungszweck und Detaillierungsgrad stellen wir folgende Zugangswege zur Verfügung: *Scientific Usefiles* (SUF) für die Forschung und *Campus Usefiles* (CUF) für die Lehre. Bei SUFs unterscheiden wir zwischen *Download*-SUF (starke Anonymisierung), *Remote-Desktop*-SUF (mittlerer Anonymisierungsgrad) und *Onsite*-SUF (Sie analysieren die Daten lokal bei uns, haben dafür den höchsten Detailgrad).

**Comment by rbirkelbach** [comment]
@ElkeMi und ich haben uns auf folgenden Text geeinigt: 
 
# Forschungsdaten aus der Hochschul- und Wissenschaftsforschung finden

Das FDZ.DZHW stellt Datenpakete der Hochschul- und Wissenschaftsforschung zur Verfügung.
Mit der Datenpaketsuche können Sie die Metadaten der beim FDZ.DZHW hinterlegten Datenpakete schnell und einfach durchsuchen. So finden sie alle Informationen, die Sie brauchen, und können die entsprechenden Datenpakete direkt bestellen.

Je nach Anwendungszweck und Detaillierungsgrad stellen wir folgende Zugangswege zur Verfügung: *Scientific Usefiles* (SUF) für die Forschung und *Campus Usefiles* (CUF) für die Lehre. Bei SUFs unterscheiden wir zwischen *Download*-SUF (starke Anonymisierung), *Remote-Desktop*-SUF (mittlerer Anonymisierungsgrad) und *Onsite*-SUF (Sie analysieren die Daten lokal bei uns, haben dafür den höchsten Detailgrad). Informationen über die zur Verfügung stehenden Zugangswege finden Sie ebenfalls in der Datenpaketsuche.

**Comment by rbirkelbach** [comment]
English translation

# Find higher education and science research data packages

With the data package search you can quickly and easily search the metadata of the data packages stored at the FDZ.DZHW. This way you will find all the information you need and can order the corresponding data packages directly.

Depending on the application purpose and level of detail, we provide the following access ways: *Scientific Usefiles* (SUF) for research and *Campus Usefiles* (CUF) for teaching. For SUFs we distinguish between *Download-SUF* (strong anonymisation), *Remote-Desktop-SUF* (medium anonymisation) and *Onsite-SUF* (you analyse the data locally at our site, but have the highest level of detail).

**Comment by rbirkelbach** [comment]
When clicking on a study/study series, the focus is on the bottom of the newly loaded page if I have scrolled down on the start page. I think the focus should be on top of the page.

**Comment by rreitmann** [comment]
The scrolling behavior in Firefox is due to a new browser feature `overflow-anchor` and affects all of our sites. I have disabled it.

Fixed IE issues as well.
