### ISSUE TITLE
Problems while installing under OSX

### ISSUE THREAD

**Issue by Hydraner** [dzhw/metadatamanagement#2477]
Hello! 
While running `mvn clean install` I run into this error. I hope anyone can help me with this or give me a hint how to solve it:

`[INFO] Scanning for projects...
[INFO]
[INFO] ---------< eu.dzhw.fdz.metadatamanagement:metadatamanagement >----------
[INFO] Building metadatamanagement 1.0.97-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
Downloading from github: https://maven.pkg.github.com/dzhw/embedded-elasticsearch/pl/allegro/tech/embedded-elasticsearch/2.11.0/embedded-elasticsearch-2.11.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.955 s
[INFO] Finished at: 2019-12-18T12:32:19+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project metadatamanagement: Could not resolve dependencies for project eu.dzhw.fdz.metadatamanagement:metadatamanagement:war:1.0.97-SNAPSHOT: Failed to collect dependencies at pl.allegro.tech:embedded-elasticsearch:jar:2.11.0: Failed to read artifact descriptor for pl.allegro.tech:embedded-elasticsearch:jar:2.11.0: Could not transfer artifact pl.allegro.tech:embedded-elasticsearch:pom:2.11.0 from/to github (https://maven.pkg.github.com/dzhw/embedded-elasticsearch): Authentication failed for https://maven.pkg.github.com/dzhw/embedded-elasticsearch/pl/allegro/tech/embedded-elasticsearch/2.11.0/embedded-elasticsearch-2.11.0.pom 401 Unauthorized -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`

**Comment by Hydraner** [comment]
It looks like the package https://maven.pkg.github.com/dzhw/embedded-elasticsearch/pl/allegro/tech/embedded-elasticsearch/2.11.0/embedded-elasticsearch-2.11.0.pom is hidden behind some htaccess - is there any chance to get this?

**Comment by rreitmann** [comment]
This dependency comes from GitHub's Package Registry. You need to authenticate with a GitHub Token:
https://help.github.com/en/github/managing-packages-with-github-packages/configuring-apache-maven-for-use-with-github-packages#authenticating-to-github-packages

**Comment by Hydraner** [comment]
Yeay thank you! That was the hint I needed, much appreciated!
Still running in some other issues like this one, looks like some kind of versioning conflict to me

`[ERROR] Failed to execute goal on project metadatamanagement: Could not resolve dependencies for project eu.dzhw.fdz.metadatamanagement:metadatamanagement:war:1.0.96: Failure to find pl.allegro.tech:embedded-elasticsearch:jar:2.11.0 in https://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]`

Whatever I will deal with this an other time, thx for the help

**Comment by rreitmann** [comment]
@Hydraner If you just want to run the MDM locally on your machine, this might help:
https://github.com/dzhw/metadatamanagement/packages/91294?version=1.0.97-SNAPSHOT

**Comment by Hydraner** [comment]
Ah this looks pretty helpful, thanks!
