### ISSUE TITLE
Implement pinning to startpage on release

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2479]
Currently the recommended data package on the start page is hard coded...

**Comment by rbirkelbach** [comment]
If I unrelease an already pinned study and re-release it, the checkbox should have the correct status, ie. be checked.

**Comment by rreitmann** [comment]
@UteH Feel free to suggest a heading on the startpage for the pinned data package.

**Comment by UteH** [comment]
@rreitmann 
currently: "Neuestes Datenpaket" / "Most Recent Data Package" 
suggestion: "Datenpaket im Fokus" / "Featured data package"

**Comment by UteH** [comment]
hello :) ist die Doku hierfür schon aktualisiert @rbirkelbach ?
