### ISSUE TITLE
Relations of publications are confusing

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2488]
Maybe it would be good to let all objects that are a level lower in the hierarchy than study inherit publications. I felt a bit confused that publications are shown sometimes and sometimes not, even though I knew that they are often just linked with the study. It behaved this way already before the redesign, but in my opinion it's now more confusing than it was before.

@rreitmann already said that we also could hide the publications tab if there's nothing. https://github.com/dzhw/metadatamanagement/issues/2431#issuecomment-576577094

**Comment by rreitmann** [comment]
We will remove the publication tab from all details pages apart from studies/data packages...
