### ISSUE TITLE
As a publisher/data provider I want Concepts to be in the Cockpit Overview

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2500]
~Just as~ similar to relatedPublications
![grafik](https://user-images.githubusercontent.com/18573122/73544834-53074a00-443a-11ea-9299-8c0cf932040f.png)

![grafik](https://user-images.githubusercontent.com/18573122/84382458-ef143f80-abea-11ea-9ab9-e6e1c5ac605e.png)

**Comment by rreitmann** [comment]
Concept card shall display all concepts of study and contain a "create concept"-link

**Comment by rreitmann** [comment]
@UteH I have improved the error message. Please give it a try...

**Comment by UteH** [comment]
![grafik](https://user-images.githubusercontent.com/18573122/132191716-8a487600-b395-4fda-9ef4-f291ac377735.png)
