### ISSUE TITLE
move type.de/en explanation from questionMetadataPreparation from docx to vignette

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2502]
@svietgen informed me that this document was just a preliminary document and not necessarily for public purposes. I think I'll do it together with https://github.com/dzhw/metadatamanagement/issues/2498

**Comment by rreitmann** [comment]
https://metadatamanagement.readthedocs.io/de/latest/javadoc/eu/dzhw/fdz/metadatamanagement/questionmanagement/domain/QuestionTypes.html

**Comment by rbirkelbach** [comment]
We should first refine this issue. The current definitions are not good in my opinion, but I deleted the link to the docx file. https://github.com/dzhw/metadatamanagement/issues/2606 @AndyDaniel1 @UteH

**Comment by rreitmann** [comment]
We will do this with #2606
