### ISSUE TITLE
Create overview of fields in study, dataset, survey

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2504]
@dzhw/fdz-shks  Please create a list of the names of the fields in study, dataset, survey in excel or word. It needs to be finished by the end of the week.. You can come to me if you have questions.
@UteH will review it.

**Comment by JohannaNiebuhr** [comment]
@rbirkelbach ist erledigt und liegt hier: 
`\\Faust\Abt4\FDZ\7_MitarbeiterInnen\Hilfskräfte (SHK-WHK)\Johanna\MDM_Überblick_Studie_Erhebungen_Datensatz.xlsx`

**Comment by AndyDaniel1** [comment]
@JohannaNiebuhr @dzhw/fdz-shks Many thanks! Can you also insert the (exact) english field names in the document. @danbfdz and I need the document this week on Tuesday to present it to an international audience.

@UteH can you also take a look at the document to check if something is missing?

**Comment by UteH** [comment]
@AndyDaniel1 should also write down our typical attachments (e.g. data and method report, overview, questionnaire, ...) for each object?

**Comment by rbirkelbach** [comment]
@UteH what still needs to be done?

**Comment by UteH** [comment]
@rbirkelbach I am currently reviewing. 
- [ ] English field names.
- [ ] information on attachments? @AndyDaniel1 ?
- [ ] marker if field is mandatory (I suggest `*` as it is in the MDM)

**Comment by UteH** [comment]
done from my end

**Comment by AndyDaniel1** [comment]
@UteH @rbirkelbach could you tell me the directory of the table. Attachments should be included.
