### ISSUE TITLE
survey.geographicCoverages are not displayed anymore

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2517]
The geographic coverage of surveys which have more than one entry in geographicCoverages is not displayed anymore.
It has been accidentally removed during the rework of the GUI. Be aware that `geographicCoverage.description` can now contain markdown.

**Comment by rreitmann** [comment]
The markdown icon is missing for #2444.

**Comment by JohannaNiebuhr** [comment]
@rbirkelbach 
i tested in 4 browsers the geographicCoverage.description: 
 - markdown is working 
 - the change of order of sequences is working 
 - several entries are displayed

**Comment by rbirkelbach** [comment]
thank you!
