### ISSUE TITLE
Paraphrase the information on the access ways

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2527]
@AndyDaniel1 already mentioned that we should paraphrase the information on the access ways a bit, especially the Download-SUF. (de/en)

>  Einen Zugangsweg auswählen
> 
> Für unsere Datenpakete gibt es vier Zugangswege, die zum einen den Grad der Anonymisierung bestimmen und zum anderen bestimmen auf welchem Weg die Daten verarbeitet werden können und ob sie zur Verwendung in der Lehre zugelassen sind. Scientific Use Files (SUF) sind ausschließlich zum Zweck der Forschung zu verwenden.
> 
> Unsere Datenpaketkonfigurationen sind gegliedert in:
> 
>  -   download-cuf (Zulassung für Lehrzwecke; starke Anonymisierung; zum Download)
>  -   download-suf (stark anonymisiert; zum Download)
>  -   remote-desktop-suf (mittlerer Anonymisierungsgrad; Zugang über virtuelle Desktops per Internet)
>  -   onsite-suf (geringer Anonymisierungsgrad; Zugang nur vor Ort im fdz.DZHW in Hannover)
> 
> Weitere Informationen finden Sie hier.

If we do so, we should also change the wording on the new website: https://demo-fdz.dzhw.eu/de/datennutzung

![grafik](https://user-images.githubusercontent.com/18573122/77408198-a56c4380-6db7-11ea-8fa2-a2ce57724d75.png)

**Comment by danbfdz** [comment]
Ich habe einen weiteren Vorschlag formuliert, der versucht, zwei Punkte noch etwas stärker zu betonen: noch etwas stärker in Richtung download pushen; im Sinn der DSGVO §89 noch etwas stärker weg von dem Gedanken, dass nur die klassischen Anonymisierungsmaßnahmen im Sinn "statistischer Anonymisierungsmaßnahmen" (wie Aggregation) als Teil von Datensicherheit/Anonymisierung betrachtet werden, sondern die technisch organisatorischen Maßnahmen stärker daneben gestellt werden. Einerseits kennt die DSGVO die faktische Anonymisierung nicht mehr, andererseits erweitert sie die Maßnahmenoptionen expliziter als früher um die TOMs in §89
"Mit diesen Garantien wird sichergestellt, dass technische und organisatorische Maßnahmen bestehen, mit denen insbesondere die Achtung des Grundsatzes der Datenminimierung gewährleistet wird. 3Zu diesen Maßnahmen kann die Pseudonymisierung gehören, sofern es möglich ist, diese Zwecke auf diese Weise zu erfüllen. 4In allen Fällen, in denen diese Zwecke durch die Weiterverarbeitung, bei der die Identifizierung von betroffenen Personen nicht oder nicht mehr möglich ist, erfüllt werden können, werden diese Zwecke auf diese Weise erfüllt."
https://dsgvo-gesetz.de/art-89-dsgvo/

**Comment by danbfdz** [comment]
Einen Zugangsweg auswählen
Für unsere Datenpakete gibt es vier Zugangswege. Diese unterscheiden sich hinsichtlich:
1. des Nutzungszwecks (CUF für Lehre vs. SUF für Forschung), 
2. des Grades der statistischen Anonymisierung (stärker, moderat, geringer) und 
3. des technischen Weges des Datenzugangs verbunden mit unterschiedlich starken technisch-organisatorischen Datensicherheits- und Kontrollmaßnahmen (gering, moderat, stark).

Die Nutzung der Daten zum Download bedeutet die geringsten Aufwände im Rahmen der Nutzung und sollte präferiert werden, sofern das Datenpaket dieses Zugangswegs für die Nutzung ausreicht. Sofern diese Daten nicht ausreichen, können ebenfalls die anderen Zugangswege gewählt werden.

Unsere Datenpaketkonfigurationen sind gegliedert in:

```
download-cuf (Zulassung für Lehrzwecke; stärker statistisch anonymisiert; zum Download)
download-suf (stärker statistisch anonymisiert; zum Download)
remote-desktop-suf (moderater statistisch Anonymisierungsgrad; Zugang nur über virtuelle Desktops per Internet mit technischen Kontrollen)
onsite-suf (geringerer statistisch anonymisiert; Zugang nur vor Ort im fdz.DZHW in Hannover mit technischen Kontrollen)
```

**Comment by UteH** [comment]
Hi @danbfdz 👍! Ich habe nur ein paar kleine Änderungsvorschläge (Formulierung vereinheitlicht, Abkürzungen erläutert, Formatierung dazu etc.)

@AndyDaniel1 hatte noch vorgeschlagen, insb. bei Download so etwas wie "nach Antragsbewilligung" o. Ä. zu ergänzen, damit klar ist, dass man die Daten nicht selbst runterladen kann.

Könnt ihr euch ja mal anschauen

### Einen Zugangsweg auswählen

Für unsere Datenpakete gibt es bis zu vier Zugangswege. Diese unterscheiden sich hinsichtlich:
1. des Nutzungszwecks (Campus Use File (CUF) für Lehre vs. Scientific Use File (SUF) für Forschung), 
2. des Grades der statistischen Anonymisierung (stärker, moderat, geringer) und 
3. des technischen Weges des Datenzugangs (Download, Remote-Desktop, Onsite) verbunden mit unterschiedlich starken technisch-organisatorischen Datensicherheits- und Kontrollmaßnahmen (geringer, stärker, moderat).

Die Nutzung der Daten zum Download bedeutet die geringsten Aufwände im Rahmen der Nutzung und sollte präferiert werden, sofern das Datenpaket dieses Zugangswegs für die Nutzung ausreicht. Sofern diese Daten _nicht_ ausreichen, können ebenfalls die anderen Zugangswege gewählt werden.

Unsere Datenpaketkonfiguration ist gegliedert in:
- **download-cuf**: nur für Lehrzwecke; stärkerer statistischer Anonymisierungsgrad; zum Download nach Antragsbewilligung
- **download-suf**: stärkerer statistischer Anonymisierungsgrad; zum Download nach Vertragsabschluss
- **remote-desktop-suf**: moderater statistischer Anonymisierungsgrad; Zugang nur über virtuelle Desktops per Internet mit technischen Kontrollen nach Vertragsabschluss
- **onsite-suf**: geringer statistisch Anonymisierungsgrad; Zugang nur vor Ort im FDZ-DZHW in Hannover mit technischen Kontrollen nach Vertragsabschluss

**Comment by rreitmann** [comment]
@danbfdz Please provide feedback until Friday 10 am otherwise I will use the text provided by @UteH ...

**Comment by rreitmann** [comment]
@rbirkelbach please review the english version after the test system has been deployed

**Comment by rbirkelbach** [comment]
`des technischen Weges des Datenzugangs (Download, Remote-Desktop, Onsite) verbunden mit unterschiedlich starken technisch-organisatorischen Datensicherheits- und Kontrollmaßnahmen (geringer, stärker, moderat).`
should be in my opinion: `des technischen Weges des Datenzugangs (Download, Remote-Desktop, Onsite) verbunden mit unterschiedlich starken technisch-organisatorischen Datensicherheits- und Kontrollmaßnahmen (geringer, moderat, stärker).`

The same goes for the translation: `the technical way of data access (Download, Remote-Desktop, Onsite) combined with varying degrees of technical and organisational data security and control measures (lower, stonger, moderate).`
should be: `the technical way of data access (Download, Remote-Desktop, Onsite) combined with varying degrees of technical and organisational data security and control measures (lower, moderate, stonger).`

The rest is fine in my opinion.
