### ISSUE TITLE
Allow login with email address, too

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2529]
Currently one can only login using the username. Which should be fine. However, it's been a couple of times now that people ask me why they cannot log on and after a while I realize: because they try to use their email address and not their username.

**Comment by rbirkelbach** [comment]
"Failed to sign in! Please check your credentials and try again." (Chrome 81.0.4044.138) -- I used the same password as my regular test-account password and the email address the account is registered with.

**Comment by rreitmann** [comment]
I have not yet deployed it on the testsystem...

**Comment by rbirkelbach** [comment]
It works fine! I think you made a few users happy (without them knowing that you made them happy 😆 )
