### ISSUE TITLE
Refine Documentation for RDC-employees

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2541]
Similar to the issue for the user documentation, the publisher documentation needs to be overhauled. 
See e.g. https://github.com/dzhw/metadatamanagement/issues/2498#issuecomment-624505046 (done)

**Comment by svietgen** [comment]
Hello @rbirkelbach , when I remember correctly you wanted to dissolve the metadata-repos. Could you refine this part in the documentation too? e.g.: https://metadatamanagement.readthedocs.io/de/latest/variables.html
And can you tell me when you are going to dissolve the existing repos (you wanted to give this task to a SHK). Thanks!

**Comment by rbirkelbach** [comment]
> Hello @rbirkelbach , when I remember correctly you wanted to dissolve the metadata-repos. Could you refine this part in the documentation too? e.g.: https://metadatamanagement.readthedocs.io/de/latest/variables.html

Sure.

> And can you tell me when you are going to dissolve the existing repos (you wanted to give this task to a SHK). Thanks!

I'll see next week if a student employee has time. I didn't get around doing this earlier.
