### ISSUE TITLE
Netsample vs Netresponse (or something similar)

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2545]
> @rbirkelbach : eine kleine Mini-Sache noch: wir haben keine Stichprobe, deshalb muss der Begriff "Nettostichprobe" ersetzt werden durch "Nettoausschöpfung" oder so etwas Ähnliches :-)
_Originally posted by @uschwabe in https://github.com/dzhw/nac2018.1/issues/69#issuecomment-627977288_

We should discuss whether this makes sense and if yes whether we want to differentiate between net sample and net response. In my personal opinion it's not wrong to talk about a netsample in this case, because it's a self selected sample of the desired census. Nevertheless, let's discuss.

**Comment by AndyDaniel1** [comment]
Of course this is still a sample of the population (no matter if your goal was a total survey). In the case of a total survey the gross sample = N and as @rbirkelbach already stated, a certain selection mechanism leads to n, which is a (net)sample of N (the kind of the selection mechanism does not change the fact that it is still a sample). Maybe we can add a comment in the annoation field?

tl||dr: let's keep the term netsample
