### ISSUE TITLE
As a data provider I need a more precise description for some attributes

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2553]
in context with / after #2232 
triggered by the eurograduate project (@muehleck) the following attributes are not clear enough

study overview (PDF) | study (MDM)
-- | --
Surveying Institution | Institution(s)
Project contributors (Project Leader) | Authors
annotations | annotations
[example gra2005](https://metadata.fdz.dzhw.eu/public/files/studies/stu-gra2005$-2.0.0/attachments/gra2005_Overview_en.pdf) | [example gra2005](https://metadata.fdz.dzhw.eu/#!/en/studies/stu-gra2005$?page=1&size=10&type=surveys)

![grafik](https://user-images.githubusercontent.com/18573122/84381867-f1c26500-abe9-11ea-8689-2a89fe1daf9c.png)

@AndyDaniel1 
- do the attributes of MDM and study overview **have** to be the same?
  - if so, we need do make this more clear in both systems
  - if not, we need to make the differences more clear
    - e.g. Kai thought `Project contributors` might be all the country-specific staff helping to survey the people but `Authors` is a more reduced set of people who will be cited (but then the attribute `authors` is only part the citatationHint in the overview. is that enough?)
    -  do the `Institution(s)` and `Surveying Institution` mean all the country-specific institutions who did the organization of the actual field work? or the 3 main insitutions organizing the field work 
  - if it does not matter we should add this information 

nontheless
- I think we should harmonize the information. 
- [ ] we should add the field `study.dataCurators` to the study overview #2232

makes me think of #1447 again 💭

**Comment by muehleck** [comment]
Ich habe es jetzt so gehandhabt:
"Surveying institution(s)" (Dokumentation) und "institution(s)" (MDM) habe ich identisch 'befüllt' mit allen irgendwie beteiligten Institutionen, d.h. gesamtes internationales Konsortium und durchführende Partner in den Ländern. Das war der Vorschlag von Christoph Meng.
"Project contributor(s)" (Dokumentation): alle Personen, die zu den Projektteams der beteiligten Institutionen (s.o.) gehören.
"Data set citation" (Dokumentation) bzw. "Author(s)" (MDM) habe ich wieder identisch 'befüllt' mit den Personen, die in den drei Kernorganisationen mit dem Projekt beschäftigt waren und insofern wissenschaftlich und inhaltlich prägend waren und/oder maßgeblich an der Datensatzgenese und -edition beteiligt waren. Das Umfrageinstitut (DESAN) und seine Mitarbeiter*innen habe ich hier als mehr oder minder reine Service-Einrichtung nicht mit einbezogen.

**Comment by muehleck** [comment]
Falls Ihr die Bezeichnungen für Autoren, Mitarbeitende etc. glatt ziehen wollt, würde ich auch empfehlen, die Begrifflichkeit auf DE und EN zu checken. Bspw. wird im MDM aus "Authors" "Projektmitarbeiter(innen)", was ja nicht zwingend die gleiche Gruppe ist. Bei letzterer Bezeichnung wäre ich jetzt doch geneigt, alle aufzuführen, die irgendwie beteiligt waren, aber ich lasse es jetzt so. 
Ählicher Gegensatz auch bei "Institution(s)" (MDM, EN) und "Erhebende Institution(en)" (MDM, DE). Also m.E. wäre es wirklich hilfreich, das alles zu vereinheitlichen und (wie von Ute angeregt) auch Definitionen zu entwickeln.

**Comment by AndyDaniel1** [comment]
@UteH Despite the expected effort that will be required to harmonise the information, I believe that this is expedient. We should discuss this in the next refinement.

**Comment by rreitmann** [comment]
We want to rename `study.authors` to `study.projectContributors`. Displayed as 'Projektmitarbeiter'/'Project Contributor'

**Comment by UteH** [comment]
@UteH adapt overview to mdm an spread the word

**Comment by UteH** [comment]
@rreitmann ups, sollte ich das doch nicht schließen  wegen https://github.com/dzhw/metadatamanagement/issues/2553#issuecomment-642591209

**Comment by rreitmann** [comment]
We need to rename `study.authors`:
```javascript
db.getCollection('studies').updateMany({}, {$rename: {'authors': 'projectContributors'}})
```
