### ISSUE TITLE
Delete variables may cause error

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2556]
The project in question was `gra2005` with more than 3000 variables. The error message was "Sorry, etwas ist schief gelaufen" and it deleted only some variables but not all. After 3 or 4 attempts all variables were deleted.

**Comment by rreitmann** [comment]
Deletion takes more than 60s which leads to a 504 (Gateway Timeout). Refreshing the page after approximately 5 minutes shows that all variables have been delete successfully...

**Comment by rreitmann** [comment]
@rbirkelbach I have changed the error message, so that the user knows, that the variables are still being deleted...
