### ISSUE TITLE
Implement protractor test for broken links on each page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#256]
- implement redirect to error page (currently welcome)
- implement protractor tests for each link on each page

**Comment by rreitmann** [comment]
refactor protractor tests (one it() per page)

**Comment by dkatzberg** [comment]
enable the broken links with login tests for the review.

**Comment by T-e-j-k-u-m-a-r** [comment]
Hi Team, Any update on the above request?

**Comment by T-e-j-k-u-m-a-r** [comment]
How to read status message and status code from the API response using Axios + Javascript?

**Comment by rreitmann** [comment]
Sorry, but we are not using protractor anymore...
