### ISSUE TITLE
as data user I want to see the crucial attachments immediately 

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2566]
per default none of the materials are displayed on the data package page because the list of attachments might be too long, esp. for `instruments`. Nonetheless, the attachments for study are very important.

-> Could we change the default so that only the attachments of `study` are displayed by default? such as 
![grafik](https://user-images.githubusercontent.com/18573122/84008847-ae11f600-a972-11ea-9ea3-1a1189682578.png)

**Comment by rreitmann** [comment]
@UteH Do we need to discuss this? It is simple and I could do it now...

**Comment by UteH** [comment]
I think @AndyDaniel1 will agree if it's only 1 point :) 👍
