### ISSUE TITLE
Adaption of buttons in the ordering process

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2573]
As discussed earlier we need to adapt the "ordering-buttons". 

On the data package configuration panel: 

1. The Button "Zur Beantragung vormerken" should be renamed "In den Warenkorb legen". 

2. Futhermore the button should always be active, even no access way has been selected. Also the button "Datenpaket zitieren" should always be active.

3. In the case no access way has been selected, an error message should be displayed 
"Bitte wählen Sie einen Zugangsweg aus, um das Datenpaket in den Warenkorb legen zu können". 
"Bitte wählen Sie einen Zugangsweg aus, um das Datenpaket zitieren zu können". 

4. We should place a button "Zum Warenkorb" below "In den Warenkorb" and "Datenpaket zitieren". The button should only be active if the shopping cart contains items.   

5. On the shopping cart page:  Button: "Beantragen" --> "Kostenlos beantragen"

6. en translation

    "Note for application" -->  "Add to shopping cart"

    "Go to shopping cart"

    Error messages --> 
    "Please select an access way to add the data package to the shopping cart."
    "Please select an access way to cite the data package."

     Button "Order" --> "Order free of charge"

**Comment by rbirkelbach** [comment]
Just a suggestion: instead of "kostenlos beantragen" -> "kostenlos bestellen"?
