### ISSUE TITLE
why is "type" not displayed for study attachments?

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2576]
![grafik](https://user-images.githubusercontent.com/18573122/84516375-037d3880-acce-11ea-9b76-0af33ce0497f.png)

just wondering (because the table will become too big?). I think, people tend to use "Beschreibung/description" as type.

type informations is available but not displayed
![grafik](https://user-images.githubusercontent.com/18573122/84516526-34f60400-acce-11ea-8a97-107e789c49ad.png)

if someone has some time left, someone could clean this up.

**Comment by rreitmann** [comment]
I think we removed the type due to the redundancy with the description and since there are only two types: "Method report" and "Others"

**Comment by UteH** [comment]
@rreitmann thx.
Generally, I think we should harmonise the attachment attributes because it causes confusion while entering the data and title might not be neccessary once we have #2292 
maybe? 
- remove `title`
- add `type` entries : study overview, citation guideline
- display `type`

but that's another issue.
