### ISSUE TITLE
As data curator I would like version folders for projects for the variableMetadataExtractor

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2586]
should you also include version folders when exporting variables?

- then you can overwrite everything automatically 🤔
- in the bat-script you can get the version from the folder name? (we could write folder names automatically from the local into filesplit.do) then it would be less error-prone

![grafik](https://user-images.githubusercontent.com/18573122/84892857-9d622e00-b09e-11ea-88b8-8656e9587a8b.png)

**Comment by UteH** [comment]
@UteH investigate if this is neccessary or a Doppelstruktur

**Comment by UteH** [comment]
@rbirkelbach did you come up with an idea in the mean time? It feels like we have discussed this when we were talking about the overrwiting files incident in slack?

**Comment by rbirkelbach** [comment]
It'll be solved in the file copying issue.

**Comment by UteH** [comment]
which issue is that?
