### ISSUE TITLE
As a data provider/publisher I want to see the citation hint generator also when logged in

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2588]
If the study has not been released, the version could be defaulted to 1.0.0. The rationale is that we have citation hints in a couple of documents, such as overviews. Without releasing the study, it is very cumbersome to check whether the citations follow the correct syntax at the moment.

**Comment by AndyDaniel1** [comment]
@rbirkelbach good point, could improve the workflow. Please refine the requirements.
