### ISSUE TITLE
We need to gender the german version of the mdm

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2590]
We need to gender the term Datengeber (and maybe other terms) in the german version of the project cockpit as it currently excludes female and diverse users. 

![grafik](https://user-images.githubusercontent.com/17981185/85044038-674fa780-b18d-11ea-93d4-268ee6c3e8b8.png)

**Comment by annegaertner** [comment]
In the welcome text I also found "Datengeber", but also "Forscher" and "FDZ-Mitarbeiter".

![begrüßung](https://user-images.githubusercontent.com/31613371/85104366-c43c7380-b208-11ea-80ed-3f667955771e.png)

**Comment by rreitmann** [comment]
Let us collect the terms we need to improve, since this is a general issue in the MDM (GUI, Mails):
- Mitarbeiter
- Datengeber
- Publisher
- (Be)nutzer (also -doku,-gruppe)
- Datennutzer
- Administrator
- Forscher

We need to define the correct terms for singular and plural...

**Comment by AndyDaniel1** [comment]
I suggest using the ":" as gender gap seperator 

- Mitarbeiter:in ; Mitarbeiter:innen
- Autor:in; Autor:innen
- Datengeber:in; Datengeber:innen
- (Be)nutzer:in; (Be) nutzer:innen
- Datenutzer:in; Datennutzer:innen
- Administrator:in; Administrator:innen
- Forscher:in; Forscher:innen
- Datenkurator:in; Datenkurator:innen

Since "Publisher" is an english term (which is gender neutral), I would leave it that way.

**Comment by rbirkelbach** [comment]
Auf Deutsch, da mich die Sprachsprünge gerade ein wenig verrückt machen :D. 
Größtenteils finde ich es gut gelöst. Ich habe mit Andy gerade dazu telefoniert, wie wir mit dem "Drumherum" bei den oben angesprochenen gegenderten Wörtern umgehen, da es aktuell alles per default feminin ist. Dazu werde ich ein Issue eröffnen und wir behalten die Lösung von René bei. Ansonsten sind mir folgende Dinge aufgefallen:

- `Die Bearbeitung ist nicht möglich, weil die Zuständigkeit gerade bei den Datengeber:innen oder Publishern liegt.` mein Vorschlag: "[...] nicht bei Ihrer Rechtegruppe liegt." (ist auch inhaltlich korrekter)
- `'unreleased-successfully': 'Die Daten des Projektes "{{ id }}" können jetzt von zugewiesenen Publishern bzw. Datengeber:innen bearbeitet werden.', ` zu: "[...] können jetzt bearbeitet werden." (ist knapper)
- `'update-not-allowed': 'Es muss mindestens 1 Datengeber:in eingetragen sein.'` zu "Es muss mindestens ein:e Datengeber:in eingetragen sein" - sonst liest der Screenreader "Es muss mindestens eins Datengeber [Pause] in eingetragen sein"
- `'move-author-down-tooltip': 'Klicken, um die ausgewählten Autor:in nach unten zu verschieben.', ` zu `           'move-author-down-tooltip': 'Klicken, um die ausgewählte Autor:in nach unten zu verschieben.', `
- `'delete-author-tooltip': 'Klicken, um die ausgewählte Autor:in dieses Konzept zu löschen.', ` zu `'delete-author-tooltip': 'Klicken, um die ausgewählte Autor:in dieses Konzeptes zu löschen.', `
