### ISSUE TITLE
We need a property aggregatedSurveyTitle.de/en

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2592]
As pointed out in this [comment](https://github.com/dzhw/FDZ_Allgemein/issues/508#issuecomment-647955787), the way the citation guideline leads us to create citations for data and methods reports, citation guideline documents cannot be generated automatically in the future without a field in which a dataprovider/publisher declares something along the lines of an aggregated survey title. 

Also in this context a string dmbAuthors is needed for the same reasons as @svietgen correctly remarked.

**Comment by rreitmann** [comment]
We currently do not maintain input for the DMB.
