### ISSUE TITLE
as a dataprovider/publisher I want to have assertions for the input data

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2610]
One important assertion is that the stata datasets must not contain "system missings" (`.`, `.a` etc).
Another one is that the stata dataset must have a language.

I think for the first point an error message is a good way to deal with it. For the second point, we could adapt the software to be able to deal with datasets which don't have languages assigned.

Edit: I leave assertion in the title, but I thought about it more and think error messages are more appropriate to deal with it. These should come before the jsons are assembled.

**Comment by rreitmann** [comment]
There must be either "de" or "en" as language in the data set, otherwise we do not know for which language the labels are specified for. I have added assertions for languages as well as system missings.
