### ISSUE TITLE
As a data user I want to see the derivedVariables

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2611]
are they not displayed anymore?

- [adbi15](https://metadata.fdz.dzhw.eu/#!/de/variables/var-nac2018-ds1-adbi15?page=1&size=10&type=surveys&version=1.0.0): Promotionsfach (offene Angabe) (a)
- [adbi15_g3](https://metadata.fdz.dzhw.eu/#!/de/variables/var-nac2018-ds1-adbi15_g2?page=1&size=10&type=questions&version=1.0.0): Promotionsfach: Fächergruppe (destatis) (c)

**Comment by UteH** [comment]
also true for `PanelIdentfier`🤔 ?

**Comment by rreitmann** [comment]
We will show (at most two) links after the variable name which lead to the variable search datapackage details. The query string will be the identifier.

**Comment by UteH** [comment]
![grafik](https://user-images.githubusercontent.com/18573122/92112827-a7b6dd00-edee-11ea-9ecb-090ce1164366.png)

**Comment by rbirkelbach** [comment]
- Releasing causes some sort of exception at the moment, hence I cannot test the public user's view.
- `derived Variables ("gra2005-ds1-aocc222j")` -> I would prefer if it would look like this: `derived Variables aocc222j`, but let's discuss this tomorrow in the daily standup meeting.

**Comment by rreitmann** [comment]
Test and Dev have file without contentType which causes the error on release. The following script guesses the contentTypes:
```javascript
db.getCollection('fs.files').find({'metadata._contentType':{$exists:false}}).forEach(function(file) {
    if (file.filename.endsWith('.pdf')) {
        file.contentType = "application/pdf";
        file.metadata._contentType = "application/pdf";
        db.getCollection('fs.files').save(file);
    }
    if (file.filename.endsWith('.xls')) {
        file.contentType = "application/vnd.ms-excel";
        file.metadata._contentType = "application/vnd.ms-excel";
        db.getCollection('fs.files').save(file);
    }
    if (file.filename.endsWith('.xlsx')) {
        file.contentType = "application/x-tika-msoffice";
        file.metadata._contentType = "application/x-tika-msoffice";
        db.getCollection('fs.files').save(file);
    }
    if (file.filename.endsWith('.png')) {
        file.contentType = "image/png";
        file.metadata._contentType = "image/png";
        db.getCollection('fs.files').save(file);
    }
    if (file.filename.endsWith('.svg')) {
        file.contentType = "image/svg+xml";
        file.metadata._contentType = "image/svg+xml";
        db.getCollection('fs.files').save(file);
    }
});
```

**Comment by rreitmann** [comment]
@rbirkelbach Now your variables have been released: https://test.metadata.fdz.dzhw.eu/#!/de/studies/stu-gra2005?page=1&size=10&type=variables&version=2.2.0
