### ISSUE TITLE
As a data user I need know how to order data packages more quickly on my mobile device

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2612]
@AndyDaniel1 noticed that it's a bit hard to find because the buttons are nested in the burger menu button 

.... is there another way 🤔 ?

**Comment by AndyDaniel1** [comment]
I have tested this issue with several test subjects and it seems to be a real problem. 0 out of 5 adults managed to find the order button without my help (on a mobile device).

**Comment by rreitmann** [comment]
We will implement an orange FAB which is only visible when the sidenav is not visible. It opens the sidenav.
