### ISSUE TITLE
As a data provider I would like to have a controlled vocabulary as "search as you type suggestions" while entering tags

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2613]
We need to evaluate ways to include a controlled vocabulary (a thesaurus) in the mdm to standardize tags. 

Idea: Propose tags from a thesaurus as "search as you type suggestions"

**Comment by UteH** [comment]
e. g. https://elsst.ukdataservice.ac.uk/

**Comment by rreitmann** [comment]
We need to get in contact with ukdataservice in order to use elsst within our application:
https://elsst.ukdataservice.ac.uk/elsst-guide/obtaining-elsst.aspx

**Comment by rreitmann** [comment]
I got the following reply when asking for a license and technical details:
> Thank you for your enquiry regarding the ELSST thesaurus. We are very glad to hear of your interest in the product. As we are in the process of moving its ownership from the University of Essex to the Consortium of European Social Science Data Archives (CESSDA), we are no longer able to issue a licence. We shall let you know, however, as soon as the new licence arrangements are in place. The CESSDA licence will be a Creative Commons licence.

**Comment by rreitmann** [comment]
We will continue discussing this issue as soon as CESSDA gets in touch with us...

**Comment by AndyDaniel1** [comment]
@AndyDaniel1 will contact Gesis (Germany CESSDA Partner)

**Comment by rreitmann** [comment]
We are pleased to announce that the European Language Social Science Thesaurus (ELSST) is now freely accessible and available on the CESSDA Platform at https://elsst.cessda.eu/ as one of a suite of web-based tools. It is now covered by a CC-BY-SA 4.0 licence.
We hope you will find it useful for your purposes.

**Comment by UteH** [comment]
whooooop whoooooooooooop 🎉

**Comment by UteH** [comment]
Whats the situation here again 🙈 ? 
***

https://thesauri.cessda.eu/swagger-ui/index.html 👀

**Comment by rreitmann** [comment]
We need to check the APIs for tags...

**Comment by rreitmann** [comment]
The following endpoint allows searching for concepts (with paging and wildcards):
https://thesauri.cessda.eu/swagger-ui/index.html#/Vocabulary-specific%20methods/get__vocid__search

`vocid=elsst`
`lang=de` or `lang=en`
`query=aber*`

The API is completely public thus we could easily integrate it. 

@AndyDaniel1 Please check if the thesaurus (https://thesauri.cessda.eu/elsst/en/) is a good (exclusive) source for our tags in German and English from your point of view.

**Comment by rreitmann** [comment]
There are some other open topics we need to discuss:
1. Is CC BY-SA 4.0 compatible with our License (AGPL 3) 
2. Which labels do we want to use as our tags (only prefLabel or altLabel as well)?

**Comment by AndyDaniel1** [comment]
Just a quick note to keep this in mind: The API of the VerbundFDB accepts only one specific controlled vocabulary (possibly the keyword list of FIS education: https://www.fachportal-paedagogik.de/literatur/schlagwortregister.html). If we want to deliver keywords to VerbundFDB, we need to use this list for our keywords OR map our keywords to the controlled list.

**Comment by AndyDaniel1** [comment]
We should get back to this. da|ra uses (obviously) the STW and THESOZ API: 
![grafik](https://user-images.githubusercontent.com/17981185/230024460-27125d29-7b14-4d4f-9407-aaea854d031d.png)

**Comment by AndyDaniel1** [comment]
In addition, we should also think about broader classifications: 
![grafik](https://user-images.githubusercontent.com/17981185/230024997-5824dc02-55e3-441e-9b98-8552fadc27da.png)

**Comment by tilovillwock** [comment]
The following tasks are necessary to complete this feature:
* identify the places the tag autocomplete field needs to replace the regular inputs
* build a service to integrate the API on the fly
* build a dedicated component with the new Angular API and integrate into the legacy templates

**Comment by AndyDaniel1** [comment]
Use the TheSoz Thesaurus: https://lod.gesis.org/thesoz/de/thesoz/de

The new feature should be implemented in the interfaces of data packages and concepts

**Comment by tilovillwock** [comment]
> Use the TheSoz Thesaurus: https://lod.gesis.org/thesoz/de/thesoz/de

A cursory search of the website did not reveal a well defined API or a download of the entire dataset. From what I can tell it should be possible to parse the HTML document and extract the REST URLs for each individual entry. This could prove to be error-prone though. Maybe we simply extract the strings from the index column to the left?

<img width="400" alt="Bildschirmfoto 2023-10-23 um 16 59 11" src="https://github.com/dzhw/metadatamanagement/assets/111056906/3fb1b9b8-4a7c-48da-abab-00542ee0a611">

@AndyDaniel1

**Comment by tilovillwock** [comment]
The Swagger documentation for the other thesaurus resource was helpful but it still took some trial and error. As far as I can tell it's conceivable to implement a script that scrubs the entire vocabulary by using the following URLs:

```bash
# index groups A-Z
curl https://lod.gesis.org/rest/v1/thesoz/index/?lang=de
# index group entries
curl https://lod.gesis.org/rest/v1/thesoz/index/${group}?lang=de
```

We should scrub both the default `prefLabel` as well as the optional `altLabel` if present. Since this is a one-off task we should investigate if we can make this a dynamically loadable Angular module unless the size is prohibitive. In that case we could simply make this an Elasticsearch Index.

**Comment by tilovillwock** [comment]
We are going to introduce a dedicated thesoz tag input field that autocompletes to entries that also include the Reference ID from the catalog (e.g. `concept_10037561` leads to http://lod.gesis.org/thesoz/concept_10037561).

**Comment by AndyDaniel1** [comment]
I got new input concerning the TheSoz and the mapping between TheSoz and ELSST is much worse than expected. Therefore we should implement an ELSST Keyword suggestion for the time being.

**Comment by AndyDaniel1** [comment]
If Issue is completed proceed with: https://github.com/dzhw/metadatamanagement/issues/3307

**Comment by AndyDaniel1** [comment]
![grafik](https://github.com/user-attachments/assets/f6b042ef-754f-421c-91ae-e347fd876d51)
![grafik](https://github.com/user-attachments/assets/5b384324-85c6-4faa-8fbf-bfc89b3eb972)

Add an info-i for ELLST stating: 

de: "Die Schlagworte, auf die hier verwiesen werden kann, stammen aus dem The European Language Social Science Thesaurus (ELSST). ELSST ist ein breit angelegter, mehrsprachiger Thesaurus für die Sozialwissenschaften. Er ist Eigentum des Consortium of European Social Science Data Archives (CESSDA) und seiner nationalen Dienstleister und wird von diesen herausgegeben. Der Thesaurus besteht aus über 3.300 Konzepten und deckt die wichtigsten sozialwissenschaftlichen Disziplinen ab: Politik, Soziologie, Wirtschaft, Bildung, Recht, Kriminalität, Demografie, Gesundheit, Beschäftigung, Informations- und Kommunikationstechnologie sowie Umweltwissenschaften. ELSST ist unter einer Creative Commons Attribution-ShareAlike 4.0 International License (http://creativecommons.org/licenses/by-sa/4.0/) lizenziert. Weitere Informationen: https://elsst.cessda.eu/

en: "The tags that can be referenced here are derived from the The European Language Social Science Thesaurus (ELSST). ELSST is a broad-based, multilingual thesaurus for the social sciences. It is owned and published by the Consortium of European Social Science Data Archives (CESSDA) and its national Service Providers. The thesaurus consists of over 3,300 concepts and covers the core social science disciplines: politics, sociology, economics, education, law, crime, demography, health, employment, information and communication technology, and environmental science. ELSST is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (http://creativecommons.org/licenses/by-sa/4.0/).For more information: https://elsst.cessda.eu/"

**Comment by AndyDaniel1** [comment]
the above mentioned adjustment is still pending

**Comment by AndyDaniel1** [comment]
![grafik](https://github.com/user-attachments/assets/609ff71a-c39c-4337-8285-166331281752)

example info-i

**Comment by AndyDaniel1** [comment]
The info-i should also be added to the ELLST field of concepts

**Comment by AndyDaniel1** [comment]
Thank you for the implementation, looks good! One last minor remark: Can you move the info-i next to the text?

![Image](https://github.com/user-attachments/assets/635cb601-ce9b-4f38-ab7d-bca3eadab0dc)

**Comment by tilovillwock** [comment]
@AndyDaniel1 changes were made and deployed to testing stage 👍

**Comment by AndyDaniel1** [comment]
@tilovillwock thank you for the quick response .

I can see the change for Analysis packages but not for data packages and concepts

![grafik](https://github.com/user-attachments/assets/6f2faeb1-5858-4a2f-9362-3901d7f16053)
![grafik](https://github.com/user-attachments/assets/b745138c-5d0f-4bb0-8c04-56e76ec263fc)
![grafik](https://github.com/user-attachments/assets/dbda967e-177e-474d-9cc6-a709e4d70e2f)

**Comment by AndyDaniel1** [comment]
works fine
