### ISSUE TITLE
As public user I would like to have an overview of all concepts in the mdm 

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2614]
![grafik](https://user-images.githubusercontent.com/18573122/92110594-404b5e00-edeb-11ea-8b81-7cf911346eeb.png)

**Comment by rreitmann** [comment]
Concepts will be a new filter for public users.

**Comment by rreitmann** [comment]
@rbirkelbach Please decide during testing whether we need to concatenate multiple concepts by "or" or by "and". Currently it is "and" which means a user wants to find a data package which contain all selected concepts.

**Comment by rbirkelbach** [comment]
It only shows one concept at the moment, even after linking additional concepts with an instrument.
