### ISSUE TITLE
As data user I assume I had problems with the connection between dlp and mdm

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2615]
One user received an error message when trying to send in the application in the dlp and the application crashed. So the user was IN the DLP not in the MDM.

We are not sure what happened and if it is related to the MDM **but** dlp developer assumed:
![grafik](https://user-images.githubusercontent.com/18573122/86795562-face1700-c06d-11ea-866d-24af3ec5da45.png)

> Ich habe den Fehler mit der aktuellen Konfiguration und Codebase nicht nachstellen können. Bei den Fehlermeldungen ist mir besonders die von guzzlehttp aufgefallen, da diese Typischerweise auftritt, wenn die Kommunikation zwischen MDM und Drupal nicht richtig funktioniert.
Sollte der Fehler wieder auftreten wäre das ein Ansatzpunkt.

Maybe u can investigate if something unfamiliar happened around 9:22 am on July 2nd? 🕵️‍♂️ 

If not we will not do anything further as it has not occurred again by now.

**Comment by rreitmann** [comment]
Neither can I reproduce it nor find anything in the logs.
