### ISSUE TITLE
As a data publisher I want to know what metadata to double check and by whom

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2617]
As discussed in the nacaps "retro", let's define what fields need to be double checked.

**Comment by UteH** [comment]
#2624

**Comment by rreitmann** [comment]
@rbirkelbach @svietgen Please discuss this together...

**Comment by rbirkelbach** [comment]
We never managed to discuss this. Sorry.

**Comment by rreitmann** [comment]
This should be discussed by the "Dauerbetrieb"...
