### ISSUE TITLE
As a data provider or RDC employee I need an excel template for questions.xlsx

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2623]
As I hade some error messages in https://github.com/dzhw/gra2013/issues/1#issuecomment-670348403 I would appreciate it if we had an excel template for questions.xlsx. During the Effi project we did create one with dropdown menus, automated transations etc. Maybe this could be reviewed and updated and then stored in https://dzhw.github.io/questionMetadataPreparation/articles/general_workflow_and_tips.html

questions.xlsx: adjust formula of `type.en` to 
```
=WENN(GLÄTTEN(K2)="Einfachnennung";"Single Choice";
WENN(GLÄTTEN(K2)="Offen";"Open";
WENN(GLÄTTEN(K2)="Mehrfachnennung";"Multiple Choice";
WENN(GLÄTTEN(K2)="Itembatterie";"Item Set";WENN(GLÄTTEN(K2)="Matrix";"Grid";"")))))
```

**Comment by UteH** [comment]
https://github.com/dzhw/metadatamanagement-io/wiki/Vorlagen-f%C3%BCr-Datengeber

**Comment by rreitmann** [comment]
We should maintain a template questions.xlsx within `questionMetadataPreparation`.

**Comment by rreitmann** [comment]
We will wait until we get feedback to the current template...
