### ISSUE TITLE
As publisher I need to know how to check/approve the question metadata

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2624]
- if origin is handcrafted
- if origin is zofar

e.g. 
- check whether questionnaire and question.image and question.texts are the same
- check whether question.texts are stored in the appropriate attribute
- only by student assistant or by WiMi?

**Comment by rbirkelbach** [comment]
For reference this is what's included in the documentation at the moment: https://dzhw.github.io/questionMetadataPreparation/articles/general_workflow_and_tips.html#check-and-prepare-metadata-for-transforming-them-from-zofar-format-to-handcrafted-format and https://dzhw.github.io/questionMetadataPreparation/articles/general_workflow_and_tips.html#check-question-metadata-and-images

**Comment by UteH** [comment]
I think a team member of data processing should evaluate this (on the fly).

maybe issue can be closed until further needs are defined
