### ISSUE TITLE
Implement an option to not display number of Variables/Analyzable Variables (for qualitative datasets)

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2656]
I'm pretty sure there are quite many instances in the qualitative context when there are no clearly defined variables. @DilekIkiz please correct me if I'm wrong.

**Comment by DilekIkiz** [comment]
Yes, I agree with you. I wouldn't know when there should be variables in a qualitative context.

**Comment by rreitmann** [comment]
We will hide the columns (variables and analyzable Variables) if all assigned surveys are qualitative.

**Comment by rreitmann** [comment]
In addition to hiding the columns I have implemented the following:
- search tab 'variables' is not shown if all surveys are qualitative
- data package in shopping cart does not show variable count anymore if all surveys are qualitative
