### ISSUE TITLE
Resize und center "Alle Datenpakete anzeigen" (de/en)

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2677]
The string "Alle Datenpakete anzeigen" is too small and should be resized (x 1.33). Additionally the string should be centered. 
![grafik](https://user-images.githubusercontent.com/17981185/97483304-8e965c80-1957-11eb-862a-f8529ce3fe3d.png)

**Comment by rreitmann** [comment]
@AndyDaniel1  You mean like this?
![Bildschirmfoto von 2020-10-29 09-10-48](https://user-images.githubusercontent.com/12323832/97542284-c5f02200-19c6-11eb-9cf9-02e79d68bbcb.png)

**Comment by AndyDaniel1** [comment]
@rreitmann perfect!
