### ISSUE TITLE
Specify common API requirements

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2678]
We should discuss how we could implement an API that allows external users to consume the metadata from our database. 

I've a special use case that I will  present in the next refinement.

**Comment by AndyDaniel1** [comment]
Is the issue #1980 related to this issue?

**Comment by AndyDaniel1** [comment]
We will wait until we have a specific use case.

**Comment by UteH** [comment]
@rreitmann specifies technical details

**Comment by AndyDaniel1** [comment]
@rreitmann  will specify the technical details

**Comment by rreitmann** [comment]
Here are some links which show features of popular APIs:
 - https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api
 - https://docs.github.com/en/free-pro-team@latest/rest/overview/openapi-description
 - https://docs.github.com/en/free-pro-team@latest/rest/overview/libraries
 - https://developer.twitter.com/en/docs/twitter-api/getting-started/guide

Open Topics at our side are:
Authentication (Token based?), Rate Limiting, CORS, Error Serialization, Hypermedia/HATEOAS, Authorization (especially filtering forbidden resources), Conditional Requests (ETags), Client Libraries, API documentation, API versioning

**Comment by rreitmann** [comment]
Here is the dara API description:
- https://www.da-ra.de/technische-informationen/doi-registrierung/
