### ISSUE TITLE
As a data user I would like to have a more appropriate term for "panel variable" 

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2683]
The term panel variable on the variable detail pages is not very suitable since we also have logitudinal variables in trend studies (see the forthcoming ssypool). 

"Longitudinal Variable" (Längsschnittvariable) could be a more suitable term.

**Comment by rreitmann** [comment]
"Repeated Measure Variable" (Wiederholungsmessung) is a better term

**Comment by AndyDaniel1** [comment]
Correction: "Repeated Measurement" ("Wiederholungsmessung")

**Comment by rreitmann** [comment]
Rename field in mongoDB:
```javascript
db.getCollection('variables').updateMany({},{$rename: {'panelIdentifier':'repeatedMeasurementIdentifier'}})
```

**Comment by rbirkelbach** [comment]
Test data package: gra2005, variable: aocc292c.
