### ISSUE TITLE
Ensure variableMetadataPreparation runs in original project folders

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2685]
After a successful run ask the user whether to copy the directory into the `project_directory/Metadatenexport` so that the data package properly bundled. The user will need to input the release version.

**Comment by rreitmann** [comment]
After a short discussion we think that we need to completely remove the step of copying the "Doku"-Dataset to/from the separate project structure in `Q:\\Variablenexport\Projekte`. The `variableToJson.bat` shall use the dataset under `../Metadatenexport/Aktualisierung`.
