### ISSUE TITLE
As a publisher I need a way to update single attachments without releasing other altered metadata/attachments

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2689]
Today while talking about the release notes, the point of errata came up. We want to be able to update the release notes attachment in certain circumstances without releasing already otherwise changed metadata. E.g. v1.0.0 is released and in the meantime already changes for v2.0.0 are done. However, some mistake was found which cannot be fixed instantly but we'd like the users to know about the mistake (e.g. a variable has been recoded wrong). This should be noted in the release notes in the errata section. In a situation like this it would be great if we could update a single attachment without releasing all the other stuff which is already saved as a shadow copy. (note: When this issue is done, the versioning concept has to be adapted.)

**Comment by rreitmann** [comment]
Current idea to have a link to the release notes in the data package details. We need to investigate where we can maintain the release notes...

**Comment by UteH** [comment]
As we are about to release updates (gra2013, gra1989, ssy17, ...) we will send users to the release notes according to the email template. Please have this in mind.

**Comment by rreitmann** [comment]
We will not implement this...
