### ISSUE TITLE
Bug in paginator

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2692]
When I put a search string in the variable search field and then try to switch to the next page of search results (via arrow) , the mdm jumps to instruments. 

![grafik](https://user-images.githubusercontent.com/17981185/98571880-495a1f00-22b5-11eb-934b-623b5a1dbc6a.png)
![grafik](https://user-images.githubusercontent.com/17981185/98571905-50812d00-22b5-11eb-8fc9-e8b3ecc490a1.png)

**Comment by rreitmann** [comment]
This does not happen on the data package details page but on the others (here survey details).
