### ISSUE TITLE
Add and document validation for Data Sets

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#270]

**Comment by rreitmann** [comment]
- validate id
- validate description
Don't forget i18n validation messages...

**Comment by rreitmann** [comment]
Documentation can be found here:
https://github.com/dzhw/metadatamanagement/wiki/Domain-Model#dataset

**Comment by rreitmann** [comment]
@anfranken Please test when available in the GUI

**Comment by anfranken** [comment]
- id
1.  Pattern: there is no validation if you have a number at the ende of the id

**Comment by rreitmann** [comment]
@anfranken Please re-test.
