### ISSUE TITLE
Publisher: I want to be able to revert to a previous release state while retaining changes that were done since then not-publicly

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2704]
This issue came up with @anneweber just now and we'd be happy if this could be discussed in the refinement today. Backstory:
There's a project on prod which has been released a long time ago. Since then, quite a lot of small changes in both, the input field as well as attachments were done, which were not meant for immediate release. However, an accidental release under the same version number occurred later and we're not sure since it's been so long what all has changed. 

Hence, the following feature request: Would it be possible to implement a rollback function to get back to a previous release publicly (ie user facing) while maintaining the changes that were done since the old release to which we want to roll back?

**Comment by rreitmann** [comment]
We decided to improve the current version and will not rollback to the previous (not existing anymore) one.
