### ISSUE TITLE
Publisher: I want to have a checkbox and maybe a list of things that changed since the last release in the release dialogue.

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2705]
As a publisher I want (the first 2 seem to be quickly done, whereas the 3rd will be more difficult)
- a warning in prod in the release dialogue reminding me that this is the prod system to prevent releases which shouldn't happen;
- a checkbox: grey out the release button unless it's checked and the publisher has confirmed this is an intentional release
- a list of all the changed objects and attachments since the last release.

**Comment by rreitmann** [comment]
First two items are no problem. Will be implemented. Last one must be investigated.

**Comment by rreitmann** [comment]
List of changed objects has been postponed to #2764
