### ISSUE TITLE
Add and document validation for Surveys

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#271]

**Comment by rreitmann** [comment]
- validate id
- validate fieldPeriod
- validate title length

**Comment by rreitmann** [comment]
Don't forget i18n validation messages

**Comment by rreitmann** [comment]
Documentation can be found here:
https://github.com/dzhw/metadatamanagement/wiki/Domain-Model#survey

**Comment by rreitmann** [comment]
@anfranken Please test when available in the GUI

**Comment by dkatzberg** [comment]
Notice: No open period intervals.

**Comment by anfranken** [comment]
You won't get the right error message with an open period intervall:
{eu.dzhw.fdz.metadatamanagement.domain.validation.validperiod.message}
