### ISSUE TITLE
As a public user I want to have a quick way to return to the variable search of the data package when I'm on a variable detail page. 

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2714]
When I'm on a variable detail package to inspect some details (e.g. distribution) I have no quick way to return to the data package variable search. The quickest way is to click on one of the other objects in the breadcrumb and then scroll down to the related objects and click on variables, but this is not very intuitive.  

I would assume that the average user expects the variable search to be found in the search for related objects... the same place where it is located on the data packet detail page (I am fully aware of the fact that it cannot be located here, since variables are not related objects to variables ;-) ). 

Maybe we can place a link to the variable search of the selected data package somewhere on the variable detail page 🤔  ?

**Comment by rreitmann** [comment]
The browsers back button is supposed to help here. We need to investigate if users have this in mind...
