### ISSUE TITLE
Add and document validation for Variables

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#272]

**Comment by rreitmann** [comment]
Documentation can be found here:
https://github.com/dzhw/metadatamanagement/wiki/Domain-Model#variable

**Comment by rreitmann** [comment]
@dkatzberg Please ensure that enum-like attributes are validated like https://github.com/dzhw/metadatamanagement/blob/master/src/main/java/eu/dzhw/fdz/metadatamanagement/domain/validation/ValidFilterExpressionLanguageValidator.java#L36

This includes the following
- RuleExpressionLanguages
- FilterExpressionLanguages
- AccessWays
- AtomicQuestionTypes
- DataTypes
- ScaleLevels

**Comment by rreitmann** [comment]
@anfranken Please test it :-)

**Comment by anfranken** [comment]
- Error-message (if the id is wrong): "The RDC-ID of the V**A**riable" 
-dataType: you can't identify that you have a missmatch of the variable types between german and english with that error message: "The value for data type is not valid. Allowed values in german: string, numerisch. Allowed values in english: string, numeric."
- scale level: you can't identify that scale level is mandatory from the error message
-label: if you only upload label.en or -.de and not both, you will get an unspecific error message: "An internal server error occurred."
- All variable error messages for variables: Maybe it's confusing if you read dataset if you import only variables ("**Dataset** with RDC-ID auto-price has not been saved!"  -> "Variable with RDC-ID…")
- variable.genrationDetail.description (error message): Maybe it maks it a bit clearer "The max length of the rule description is 2048 signs." -> "The max length of the **generation** rule description of **the variable** is 2048 signs." (same for the german message)
-variable.value.isAMissing: import doesn't work (you don't get an error message) if it is a not "false" or "true"

**Comment by dkatzberg** [comment]
@limouri : 
* All variable error messages for variables: Maybe it's confusing if you read dataset if you import only variables ("Dataset with RDC-ID auto-price has not been saved!" -> "Variable with RDC-ID…")
* variable.value.isAMissing: import doesn't work (you don't get an error message) if it is a not "false" or "true"

For the first todo, have a look here:
https://github.com/dzhw/metadatamanagement/blob/master/src/main/webapp/i18n/en/dataAcquisitionProject.json#L33
This field is used as a global message and not only for data sets. It is confusing if it used for e.g. variables.

@anfranken The rest should be done.
