### ISSUE TITLE
As a user I need to understand what the different question images mean

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2722]
briefly explain that the same question is simply shown here in different resolution

https://metadata.fdz.dzhw.eu/#!/de/questions/que-nac2018-ins1-B21.1?page=1&size=10&type=variables&version=1.0.0
![grafik](https://user-images.githubusercontent.com/18573122/99414051-b47ba500-28f6-11eb-864a-629caf7cf8d0.png)

**Comment by rreitmann** [comment]
We should display an explanation next to the "Auflösung":
Abhängig von der Bildschirmauflösung wurde die Frage unterschiedlich dargestellt.
