### ISSUE TITLE
Sorting of the materials on the datapackage detail site

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#2748]
Can you tell me how the materials on the datapackage detail site (in this case: instruments) are sorted?

We have 5 waves for the phd panel and currenty the instrument materials are sorted in a different way than I would have suspected:
https://metadata.fdz.dzhw.eu/de/data-packages/stu-phd2014?page=1&size=10&type=surveys&version=4.0.0
![image](https://user-images.githubusercontent.com/22055122/100995827-99e13700-3558-11eb-9bb7-e9836cffe5e9.png)

I (as a data provider) can't change the order, right (because this happens automatically)?
If so: can we first sort by Type and than by File Name?

**Comment by rreitmann** [comment]
In your case (instrument attachment) they are sorted be `indexInInstrument` and `instrumentNumber`. `indexInInstrument` is the row in the table on the instrument details page.

**Comment by svietgen** [comment]
Thanks for the information!
But Fragebogen is always indexInInstrument` = 1 in every of the first five instruments. And is still behind an attachment of instrument 6. 
Or am I missing something?

**Comment by rreitmann** [comment]
The indexInInstrument does not always correspond directly to the row. E.g. if you delete one attachment then the index of the others is not changed which can lead to higher numbers. In your case indexInInstrument is 0 for most of your "Fragebogen" and for the "Kodierlisten". For the "Fragebogen" of wave two indexInInstrument is 1. I guess the attachment with indexInInstrument equal to 0 has been deleted which causes this.
This behavior has not been a problem until we introduced the aggregated list of attachments on the data package details page. I have to find a solution which "normalizes" the indicesInInstrument before aggregating them...

**Comment by svietgen** [comment]
Ah ok, I got it!

> I have to find a solution which "normalizes" the indicesInInstrument before aggregating them...

That would be great, thanks!

**Comment by rreitmann** [comment]
I have implemented the normalization of the indices, however the result is not the same as sorting by type and filename. We will discuss this in the next refinement.

**Comment by rreitmann** [comment]
We need to define a sort number for the instrument attachment types. We would then order by type, instrumentNumber and indexInInstrument.
