### ISSUE TITLE
As a (test) data user I can't order my data packages

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2753]
![grafik](https://user-images.githubusercontent.com/18573122/102053775-90718d80-3de8-11eb-8b1e-cd4b4fdb1bdb.png)

only on test

**Comment by rreitmann** [comment]
For some reason the dataFormats (Stata, SPSS,...) are not available on test and dev...

**Comment by rreitmann** [comment]
The cause of this issue is a spring boot update (#2744). the following code behaves differently in 2.4.x:
```java
BeanUtils.copyProperties(projection, this);
```

It seems that collection attributes are not coped anymore...
