### ISSUE TITLE
As a data provider, I want the stem of the variable names (of a study series) to be unique if it is not the same measurement

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2754]
Data providers want to use the MDM as a management system for their metadata. An important aspect is the stem of a variable name, as it distinguishes between repeated measurements (same stem over time) and different measurements (different stem over time). 

Maybe we can provide a string comparison for future project where warings occure when a variable stem already exsists in the MDM.

**Comment by rreitmann** [comment]
The projects need to take care about this themselves.
