### ISSUE TITLE
We need to mark data packages from external data providers 

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2770]
Since the quality standards for data packages from external data providers are quite volatile, we should mark these data packages on the data package detail page as external. 

 Let's discuss what could be a good solution for this (esp. wording).

**Comment by rreitmann** [comment]
@AndyDaniel1 please refine how to present internal and external data packages...

**Comment by AndyDaniel1** [comment]
I will come back to this issue when the prio gets higher

**Comment by AndyDaniel1** [comment]
In addition to #3257 we need an general hidden attribute which marks external data packages.

**Comment by AndyDaniel1** [comment]
The filter seems not to be working. Will have another look at it next week
