### ISSUE TITLE
rename the Field "Welle/wave" on the survey detail page

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2779]
The term "Welle/wave" as an indicator of the sequence of surveys is too specific. 

It should be renamed to 

de: Erhebungsnummer
en: survey number

Additionally I would add a hint for the field which states:
 
de: Bitte tragen Sie hier die Ordnungsnummer der Erhebung ein, wie sie im Erhebungsdesign angelegt ist (z.B. Nummer der Panelwelle).
en: Please enter the serial number of the survey as it is implemented in the survey design (e.g. number of the panel wave).

**Comment by rreitmann** [comment]
@AndyDaniel1 surveyNumber is already used, we need to come up with a better term which reflects gra2005 and ssypool for instance...

**Comment by AndyDaniel1** [comment]
Unfortunately there is not better (short) term for a number that indicates the order of  survey than survey number. Due to the fact that survey number has already been used, we have to chose a longer term:

**de: Ordnungsnummer der Erhebung
en: serial number of the survey** 

As suggested above, I would also add an info-i:

**de: Bitte tragen Sie hier die Ordnungsnummer der Erhebung ein, wie sie im Erhebungsdesign angelegt ist (z.B. Nummer der Panelwelle).
en: Please enter the serial number of the survey as it is implemented in the survey design (e.g. number of the panel wave).**

**Comment by rreitmann** [comment]
@AndyDaniel1 We compute the highest "serial number" in the data package and display it as "Number of waves" if and only if `dataPackage.surveyDesign` is 'Panel'. Is that still correct?

**Comment by rreitmann** [comment]
Migrate Mongo DB:
```javascript
db.getCollection('surveys').find({}).forEach(function(survey) {
    if (survey.wave != null) {
        survey.serialNumber = survey.wave;
        delete survey.wave;
        survey.version = survey.version + 1;
        survey.lastModifiedDate = new Date();
        db.getCollection('surveys').save(survey);
    }
})
```

**Comment by rreitmann** [comment]
@AndyDaniel1 The changes are available on the test system. Please verify...

**Comment by AndyDaniel1** [comment]
@rreitmann I checked the field name, error messages and hints (de & en)... everything is implemented correctly.
