### ISSUE TITLE
Import relatedPublications directly from Citavi

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2782]
in the [template / manual](https://metadatamanagement.readthedocs.io/de/latest/related_publications.html) it says we should curate the related `StudyIds` for a relatedPublication. 

I am wondering
- if this is right as studyId has been changed to dataPackageId? ( #2632  #2647 ) 
   - it seems like it should be dataPackageIds
     https://metadatamanagement.readthedocs.io/de/latest/javadoc/eu/dzhw/fdz/metadatamanagement/relatedpublicationmanagement/domain/RelatedPublication.html?highlight=datapackageids#datapackageids
- I think currently, the studyIds/dataPackageIds are ignored for the MDM import intentionally
   - does that mean that we have to (re-)assign all publications with each new import? Maybe reinstall xls-id-assignment 🤔 ? But then only publishers can assign publications
   - if the assignment can only be done manually in the cockpit I think we should create a workflow that prevents a mismatch of Citavi-StudyIds and MDM-dataPackageIds

**Comment by UteH** [comment]
I assume atm the assignment is only possible via the Cockpit not via the citavi db / xls import to avoid overwriting

**Comment by rreitmann** [comment]
@UteH The documentation is outdated. The assignment is only maintained in the project cockpit. DataPackageIds of the excel file are ignored.A new import should not overwrite existing assignments therefore there should be no need for a reassignment after each import.

**Comment by UteH** [comment]
Ok, thanks for the update! 

> A new import should not overwrite existing assignments therefore there should be no need for a reassignment after each import.

that sounds great! We discoverd that "older" data packages  (gra2009, gsl2008)  do no have publications assigned anymore. Do you have an idea why?

**Comment by rreitmann** [comment]
@Ute I will investigate this...

**Comment by rreitmann** [comment]
Currently there are on prod no publications which are older than 2021-01-28. This could either be a bug or someone has deleted all publications manually before importing them again.

**Comment by rreitmann** [comment]
Apparently all publications have been deleted accidentally on 2021-01-28 by providing an excel file with missing id columns (instead it was "BibTex Key"). Currently I think we should consider removing the publication assignment from the cockpit and ensure that the excel file exported from CITAVI contains all required information so that there is no need for manual adjustment, neither in the excel file nor in the MDM.

**Comment by AndyDaniel1** [comment]
Next steps (please add if I missed s.th.): 

- Prepare Citavi database for mdm export 
  - remove the fields: dataSetIds, instrumentIds, surveyIds, variableIds, questionIds, studySerieses.de
  - rename field studyids to dataPackageIds (@rreitmann please check)
  - add fields annotations.de ; annotations.en

- export data base to .xls and send it to @rreitmann 

- check all relations to the datapackages  

- add annotation of stata scripts of jaksztat et al (@AndyDaniel1 will provide the string)

**Comment by rreitmann** [comment]
@AndyDaniel1 `studySerieses.de` is still used by the MDM, however it is not visible for the public user. Shall I remove it completely within this issue?

**Comment by AndyDaniel1** [comment]
@rreitmann how much effort thatwould take?

**Comment by rreitmann** [comment]
@AndyDaniel1 0,5 PT, however I think there are publications which cannot be related to a concrete data package but to study serieses. I have never been a happy with them cause they weaken the definition of related publications.

**Comment by AndyDaniel1** [comment]
@rreitmann that is correct, I completely forgot about this fact. I think it makes sense to keep track of potential related publications of future SUF, but referring to a study series without a released data package  in the mdm makes little sense. Maybe we can keep these pubs in the citavi database as "potential rel. pub" without exporting them. The question that remains: should we keep releations to study series when there is also a reference to a data package?

**Comment by rreitmann** [comment]
@AndyDaniel1 If there is always a reference to one or more concrete data packages there is IMHO no need for the relation to study series...

**Comment by AndyDaniel1** [comment]
@rreitmann I'm not sure about that. Maybe a data user wants all publications of a study series in one list, would that be possible without this releation and without selecting all data packages of one study series? If that is possible we can remove the study series releation

**Comment by rreitmann** [comment]
@AndyDaniel1 Filtering imported publications by study series would still be possible without explicitly maintaining that relation...

**Comment by rreitmann** [comment]
In todays daily we have decided to remove studySeries.de from Citavi and from the MDM.
