### ISSUE TITLE
assignment of relatedPublications to data packages is missing

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2783]
@anneweber noticed that many assignment of relatedPublications to data packages are missing (meaning the publications are not findable for the public user). 

Assessment:
> alle Publikationen, die erst kürzlich hochgeladen wurden, sind da; alle anderen fehlen

I assume(!), all assigments were done manually.
I assume(!), the previous manual assignments were lost with a more current import where only the most current projects were corrected manually.

Also, the annotations are missing.

I assume(!), all annotations are gone because of a new import. These may be the only annotations, but we are not sure. The Citavi db does not entail annotations at all.

How can we recreate the annotations? Then we can fix it.

If #2782 is done, the re-assignment can be fixed.

**Comment by rreitmann** [comment]
duplicates #2782
