### ISSUE TITLE
number of waves is not displayed for public user

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2784]
on the data package detail page, the number of waves (#2779) is only displayed if you are logged in.

@AndyDaniel1 and I can't think of a reason why 🤔

**Comment by rreitmann** [comment]
@UteH For public users some details (including number of waves) are displayed in the sidenav where you can order the data package.

**Comment by UteH** [comment]
🤦 thank you @rreitmann ! 

Case closed or do you want to refine the panel on the left @AndyDaniel1 ?

**Comment by rreitmann** [comment]
Public users and authenticated users shall see the same information on the details view despite the fact that some information is shown twice...
