### ISSUE TITLE
Analyze: Automated generation of data package overview 

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2785]
Since the data package overviews should be handy and printable version of the data package metadata we should implement a automated generation of this kind of documents.

**Comment by UteH** [comment]
https://github.com/dzhw/metadatamanagement/issues/1447

**Comment by rreitmann** [comment]
We need to review the project overview and decide which information is missing in the MDM and which information is not required in the overview.

**Comment by rreitmann** [comment]
@AndyDaniel1 and @UteH: I have reviewed the data package overviews of the following project:
- gra2005
- nac2018 (de and en)
- ssypool (de and en)

I have added comments to the word documents here:
[overviews.zip](https://github.com/dzhw/metadatamanagement/files/6677018/overviews.zip)

I think we should talk about this in the next refinement...

**Comment by rreitmann** [comment]
We have discussed the fields of the data package overview. Specification can be found in the comments here:
[gra2005_Overview_de.docx](https://github.com/dzhw/metadatamanagement/files/6709278/gra2005_Overview_de.docx)

In addition to the overviews we have discussed so far, I will have a look at the following projects:
lib2016
egr2018

**Comment by rreitmann** [comment]
egr2018 has no topics which we haven't discussed yet. However, lib2016 has some:
[lib2016_Overview_en.docx](https://github.com/dzhw/metadatamanagement/files/6724695/lib2016_Overview_en.docx)
