### ISSUE TITLE
Display First and Last name in the cockpit and email notification

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2788]
As a user of the mdm cockpit, I would like to see the first and last name of a user in the settings instead of the user name (if first and last name are entered). 

![grafik](https://user-images.githubusercontent.com/17981185/109308502-6570d480-7842-11eb-9043-84db31d28422.png)

It would also be nice if the email notification uses first and last name (if avaiable) instead of user name.

**Comment by rreitmann** [comment]
We need to adjust the registration form to contain first name and last name. Furthermore the project cockpit needs to deal with empty first name and last name. However it should search these fields and display them if available.

**Comment by AndyDaniel1** [comment]
We should evaluate if this issue is still relevant in the context of #2231

**Comment by tilovillwock** [comment]
Add first and last name to user registration form in order to find them more easily in project settings and the administration panel.

**Comment by tilovillwock** [comment]
@AndyDaniel1 we should add first and last name to the user editing form as well. Should we make this mandatory when editing an existing user as well?

**Comment by tilovillwock** [comment]
> * should we make first and last name mandatory when editing an existing user as well?

No.

> * should existing users be forced to provide their first and last name?

No.

> * which emails should include first and last name from now on (this was mentioned in the issue title and below the screenshot)

All email templates with a greeting should preferably use first and last name and fallback to login.

**Comment by AndyDaniel1** [comment]
Although I am logged in and can make changes, I get an error message saying that I cannot perform actions because I was not logged in.

![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/ac3c1775-0892-414a-a72b-e284e318f4d7)

**Comment by tilovillwock** [comment]
@AndyDaniel1 have you by chance modified your own user's role before these errors started to appear? That's the only time I've ever encountered this. Logging out and back in again usually fixed this behaviour.

**Comment by AndyDaniel1** [comment]
@tilovillwock No, not that I was aware of. But now the error message no longer appears. I'll test it a few more times. If it was a single artefact that I can no longer reproduce, I will close the issue.

**Comment by AndyDaniel1** [comment]
✔ works well
