### ISSUE TITLE
Mehrsprachigkeit von Materialien zum Datenpaket

### ISSUE THREAD

**Issue by ElkeMi** [dzhw/metadatamanagement#2789]
Das Template zur Zitationsanleitung, s. `\\FAUST\Abt4\FDZ\2_Standards\Zitationsanleitung` ist Deutsch und Englisch. Im MDM muss beim Hochladen von Dokumenten deren Sprache angegeben werden. Zurzeit ist die Sprachauswahl jedoch auf eine Sprache limitiert. 

* Vielleicht könnte man künftig die Kombination Deutsch/Englisch zulassen/einpflegen, denn sie ist ab sofort bei jedem SUF zu erwarten?

**Comment by rreitmann** [comment]
@svietgen We currently think that the effort for changing this is too high. Please get in touch with @AndyDaniel1 in order to improve the documentation for this...

**Comment by ElkeMi** [comment]
@rreitmann @AndyDaniel1 @svietgen 
Then we should have an agreement on what language should be filled in - German or English.

**Comment by AndyDaniel1** [comment]
@ElkeMi yes I will adress this in my meeting with Sandra. We will put it in the documentation.

**Comment by AndyDaniel1** [comment]
will be resolved with #2786
