### ISSUE TITLE
Issues with error messages variables import

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2796]
@anneweber reported the following issues with the error messages: 

Bei der Fehlermeldung "Die Liste der Erhebungsnummern einer Variable benötigt mindest ein Element und darf nicht leer sein!" steht "mindest" anstatt "mindestens"
Bei der Fehlermeldung "(Fehler) Variable mit FDZ-ID var-gra1993-ds1-asonstj$ wurde nicht gespeichert: Das Json hat im Feld "distribution.statistics" einen Fehler." hatte ich den Eindruck, dass das konkrete Problem das fehlende Skalenniveau war. Kommt die Fehlermeldung "Das Skalenniveau einer Variable darf nicht leer sein!" evtl. nur, wenn zusätzlich auch keine Erhebungsnummer eingetragen ist? 
![grafik](https://user-images.githubusercontent.com/17981185/110098283-4cb37200-7da0-11eb-83bd-dc6efeed3b09.png)

**Comment by rreitmann** [comment]
@anneweber  Can you provide the input json which caused the message "Das Json hat im Feld "distribution.statistics" einen Fehler.""...

**Comment by anneweber** [comment]
@rreitmann 
Unfortunately, I have already deleted the json file, but I could tell you how it should probably be possible to reconstruct it.

**Comment by anneweber** [comment]
@rreitmann 
`\\faust\Abt4\FDZ\4_Datenaufnahme\Intern\Absolventenpanel\gra1993\v1.0.0\4_Dokumentation\variables\_alt\variables`

--> The problem occurs with variable `asonstj`. Only the scale level is missing, so this should be the reason for the error message.
