### ISSUE TITLE
Wrong/missing information when importing data citation via DOI in Citavi

### ISSUE THREAD

**Issue by se-lang** [dzhw/metadatamanagement#2797]
I get some wrong and some strange imformation when importing citation information in citavi. This applies also to other graduate panel cohorts. 

As example from the citation guideline gra2013:
![grafik](https://user-images.githubusercontent.com/35341060/110100597-de23e380-7da2-11eb-9429-fdbc23052fb6.png)

What I get when importing information in Citavi via DOI:
![grafik](https://user-images.githubusercontent.com/35341060/110100415-af0d7200-7da2-11eb-8801-51318e405d3a.png)

In my opinion the following information is wrong/missing/strange:
- Deutsches Zentrum Für Hochschul- Und Wissenschaftsforschung (DZHW) as author (wrong)
- "Data Collection: 2014/2015. Version 2.0.0" should be included as subtitle (missing)
- "FDZ Des DZHW" as "Mitarbeiter should rather be institution (wrong)
- Hannover is missing
- year is 2021 instead of 2020 (either this or the citation guideline is wrong)

And related to this: In my opinion the methods reports for example should have their own DOIs for more convenient citation-especially as those have different authors. --> #2798

**Comment by AndyDaniel1** [comment]
Again we have the problem with the wrong name of the FDZ, which is also discussed here: https://github.com/dzhw/FDZ_Allgemein/issues/565

**Comment by rreitmann** [comment]
We will replace "FDZ des DZHW" with "FDZ-DZHW" and try to offer a BibTex export wich can be imported by CITAVI. The Metadataimport via DOI is powered by DataCite and cannot be improved...

**Comment by UteH** [comment]
we need to list these attributes this way to be harvested by our cooperation partner VerbundFDB

- FDZ-DZHW (FDZ des DZHW) as distributor 
  ![grafik](https://user-images.githubusercontent.com/18573122/112012609-a13d4800-8b29-11eb-84c0-f4985f96ade5.png)
- DZHW as insitution
  ![grafik](https://user-images.githubusercontent.com/18573122/112012940-e8c3d400-8b29-11eb-842b-0ae853958691.png)

datacite and and citavi don't seem to handle the information appropriately ...

**Comment by rreitmann** [comment]
BibTex has some limitations which prevent a perfect Citavi import:
1. There is no type 'data package' or similar, thus we have to use `@misc`
2. There is no field 'data curators' or similar, thus we use `editor` instead
3. `@misc` does not support field `institution` but we provide it anyway
4. `@misc` does not support field `address` but we provide it anyway
5. There is only one field `title` (no subtitle or similar), thus we concatenate title, survey period, accessway and version.

**Comment by rreitmann** [comment]
We cannot generate BibTex on IE11 :(

**Comment by svietgen** [comment]
### Import of DMB via BibTex-Key:
![image](https://user-images.githubusercontent.com/22055122/115850808-89a5f780-a426-11eb-8ce3-eb8662260692.png)

### Import of DataPackage via BibTex-Key:
![image](https://user-images.githubusercontent.com/22055122/115852009-e0f89780-a427-11eb-91b2-a086fcd29023.png)
![image](https://user-images.githubusercontent.com/22055122/115852052-f1107700-a427-11eb-8e5d-9c18e5246b65.png)

This is working (taking into account the limitations mentioned here https://github.com/dzhw/metadatamanagement/issues/2797#issuecomment-820378544)
