### ISSUE TITLE
bug in entries for institution filter 

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2805]
https://metadata.fdz.dzhw.eu/de/search?page=1&size=10&type=data_packages&study-series=Sozialerhebung
![grafik](https://user-images.githubusercontent.com/18573122/110785017-b2a16d00-826a-11eb-9982-f0755867a546.png)

not sure what's going on there
- entries are wird
- number of entries is often 0 (which is not correct)

**Comment by rreitmann** [comment]
The zeros are correct cause there is another filter `study-series=Sozialerhebung`. Friederike Schlücker has been used as Institution by @AndyDaniel1 ...
