### ISSUE TITLE
add info for zofar questions metadata

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2810]
From Zofar to handcrafted:
`question.text` is (for technical reasons) always empty for the page `index`. We need to extract it from `additionalQuestionText.de/en` manually

**Comment by rreitmann** [comment]
We need to add this here: https://dzhw.github.io/questionMetadataPreparation/articles/general_workflow_and_tips.html#from-zofar-to-handcrafted-1

**Comment by rreitmann** [comment]
Additionally the link from readthedocs is broken...
