### ISSUE TITLE
As a publisher I need a more comprehensive da|ra documentation

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2814]
not sure if this is a MDM issue 🤔 if not I will transfer it to "Dauerbetrieb"

https://github.com/dzhw/metadatamanagement/wiki/Dara-DOI
I think, currently, the documentation focuses on mandatory attributes for a DOI registration. I would appreciate a more comprehensive documentation of the actual dara export for us publishers, e. g. 
- which attributes are currently sent to dara esp. after VerbundFDB export (e. g. TimeDimension, distributor, ...)
- which attributes we send to dara are mandatory according to VerbundFDB (is there a current scheme document by the VerbundFDB)? All of them?
- a link to the javadoc documentation which refers to the specific mdr-vocabulary used (e. g. https://metadatamanagement.readthedocs.io/de/latest/javadoc/eu/dzhw/fdz/metadatamanagement/surveymanagement/domain/Survey.html?highlight=sampling#sample)

**Comment by UteH** [comment]
btw: publication of the VerbundFDB on the metadataset https://www.forschungsdaten-bildung.de/files/fdbinfo_8_Metadatenset_v1.0.pdf

**Comment by rreitmann** [comment]
@UteH Please review the reworked documentation:
https://github.com/dzhw/metadatamanagement/wiki/Metadata-and-DOI-registration-at-dara

**Comment by UteH** [comment]
# Review remarks
I like the reworked documentation very much, it is very well structured! 

I only added some more contextual infos for RDC colleagues who are not familiar with datacite or VerbundFDB etc.
- [x] add an exemplary link to a registered data package
- [x] I would like to link to https://github.com/dzhw/FDZ_Allgemein/wiki/Strukturierte-Metadaten#schnittstellen-und-standards-zu-unseren-metadaten (and vice versa). I added a [further question](https://github.com/dzhw/metadatamanagement/wiki/Metadata-and-DOI-registration-at-dara#what-happens-to-the-registered-data-package-information-at-dara) and linked to the wiki page. Maybe a side note but I want to connect the information. 
- [x] some minor changes
 
I do have some minor notes to discuss:
- when available: add link to documentation on how to actually send the metadata to dara (with the release button)
- when available: add link to documentation on shadow copies and hidden shadow copies
- add an exemplary link to a hidden shadow copy? not possible, none on prod
- I would like to discuss and - if necessary - differentiate the scenarios of 
  - "overwrite" when you use the same version (related to https://github.com/dzhw/FDZ_Allgemein/issues/589)
  - "update" when you use a different/higher version
  ![grafik](https://user-images.githubusercontent.com/18573122/116668477-c1202100-a99d-11eb-971c-c039f9d9b099.png)
- both MDM columns are empty? 
  ![grafik](https://user-images.githubusercontent.com/18573122/116675775-7bb42180-a9a6-11eb-8938-cfbdb66e6362.png)
- not every MDM (computed) property has the the suffix "in de an en" -> check again?
- sequences 3.1 and 9 are not marked as required in da|ra scheme, only recommended. is the mdm documentation correct?

**Comment by rreitmann** [comment]
@Ute I have improved the documentation regarding your discussion items. Let me know if there are still some things missing...
