### ISSUE TITLE
Document variableMetadataPreparation for end users

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2834]

**Comment by rreitmann** [comment]
@svietgen Let me know if I need to improve some parts of the documentation, otherwise feel free to close this issue...

**Comment by svietgen** [comment]
@rreitmann I have changed a few points as discussed and reviewed the documentation. The "@johanna"-comments are discussed here https://github.com/dzhw/dataPackageTemplate/issues/182#issuecomment-829083600
Therefore I close this issue. 
Thanks for revising the documentation!!
