### ISSUE TITLE
Filter selection disappears

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#2844]
I am logged in and used a filter to search for surveys. In this case I used the survey filter "Institut" to filter the Institut für Höhere Studien" which resulted in 16 hits. 
![image](https://user-images.githubusercontent.com/22055122/114394839-f524d500-9b9b-11eb-8bc0-b0a01cc53cbb.png)

When I klick the next button, the filter "disappears":
![image](https://user-images.githubusercontent.com/22055122/114394913-0a99ff00-9b9c-11eb-9f06-977da392fe6c.png)

The same happens, when I am not logged in and use the filter from the left sidebar. For example "Erhebungsdatentyp Quantitative Daten" with 26 results. When I klick "next" to see the next results, the check mark disappears.

**Comment by rreitmann** [comment]
@svietgen thank you, will be fixed with the next release.
