### ISSUE TITLE
Labels with metadata standards?

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2846]
I am dreaming of some nice labels like
- DC (Dublin Core) via da|ra
- schema.org via DataCite

Inspired by Anne as she pointed out that we should make public which standards we use.

It gets complicated in detail because the standards are different for the objects. But I still think we should work towards some standards and labels accordingly

**Comment by rreitmann** [comment]
We would like to offer direct export links. Someone has to provide the links from da|ra and DataCite.

**Comment by rreitmann** [comment]
Here is some additional info:
https://github.com/dzhw/FDZ_Allgemein/wiki/Strukturierte-Metadaten#schnittstellen-und-standards-zu-unseren-metadaten

**Comment by UteH** [comment]
this is how dataverse does it
https://data.aussda.at/dataset.xhtml?persistentId=doi:10.11587/28KQNS
![grafik](https://user-images.githubusercontent.com/18573122/117047629-66c2ef80-ad12-11eb-8593-7a2ba7145c7a.png)

**Comment by rreitmann** [comment]
On "dev" and "test" the DOI used for downloading metadata is hard coded to "10.21249/DZHW:gra2005:2.0.1" because there are no test systems for OAI-PMH and data cite which contain our test metadata....

**Comment by McWallis** [comment]
Hej @rreitmann, Andy told me that you need someone to review. I would help you.

**Comment by McWallis** [comment]
Here my review: 

dublin core - german/english the same. all lines contain the appropriate
da|ra - german/english the same. all lines contain the appropriate. (more informatinons then dublin core)
DDI 3.1 -  german/english the same. some things are not displayed. 770184_Universe Scheme; 770184_Funder (here should be  BMBF), Individual (for da|ra here are the datasets)
DDI 3.2 -  german/english the same. some things are not displayed. Individual (for da|ra here are the datasets)
data_cite xml- german/english the same. all lines contain the appropriate
data_cite json - german/english the same. all lines contain the appropriate
data_cite json - german/english the same. all lines contain the appropriate

@rreitmann hope this is ok, if not let me know.

**Comment by rreitmann** [comment]
- The XMLs or JSONs always contain both languages.
- We will add some text which indicates that the metadata export is powered by da|ra and currently in beta status.
