### ISSUE TITLE
Cleanup the test system

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#2853]
I guess this is a "nice-to-have", but it would really help if there was an overview of selected test-repos that are useful for different kind of issue tests. 

Until we have this, it definitely makes sense to do post-validation beforehand to check if a repo can be released.

**Comment by rreitmann** [comment]
@svietgen Just to clarify: Do you mean test projects in the test system?

**Comment by svietgen** [comment]
@rreitmann Yes, that's what I mean 👍

**Comment by rreitmann** [comment]
We should ask FDZ_Allgemein about which test projects should not be deleted...
