### ISSUE TITLE
As a data provider I want controlled/automated vocabulary for metadata of attachments

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#2854]
Currently it is time-consuming to add attachments and it involves a lot of copy-paste from other repos. This concerns mainly the DataPackage-Attachments.

Can we add controlled or automated vocabulary for our main attachments?

For the **DataPackage-Attachments** we currently have the Attachment-Types "Method Report" and "Other". We could add the Types "Citation Guideline", "Data Package Overview" and "Changelog" as we are normally uploading all of these. 

For these Attachments Types we could add controlled vocabulary for the Field "Description (de/en)" instead of copy-pasting it from other repos. 
  
Description Suggestions (en/de): 
- Method Report: Data and Methods Report / Daten- und Methodenbericht
~- Citation Guideline: Citation Guideline / Zitationsanleitung~
~- Data Package Overview: Data Package Overview / Datenpaketübersicht~
- Release Notes: Release Notes / Release Notes

This is a request from @AndyDaniel1 as well (please add your thoughts if I missed something)

**Comment by AndyDaniel1** [comment]
@svietgen thank you for putting the discussion into an issue. I would suggest to add this feature also for instruments. 

Types and [automated descriptions]: 

Idea: Include the automatically the survey information in the description

Questionnaire [applied survey instrument [of survey x]] / Fragebogen [Angewendetes Erhebungsinstrument [von Erhebung x]]
Variable Questionnaire [Variable Questionnaire [of survey x]] / Variablenfragebogen [Variablenfragebogen [von Erhebung x]]
Question Flow [visualization of the survey procedures controlled by filter questions [of survey x]] / Filterdiagramm [grafische Darstellung des durch Filterfragen gesteuerten Befragungsablaufs [von Erhebung x]]
Coding Scheme [individual description] / Codierliste

example of gra2009 for the discussion: 

![grafik](https://user-images.githubusercontent.com/17981185/115840843-68d8a480-a41c-11eb-940c-dc17f5f67555.png)


Perhaps we can also discuss whether it is useful to include some qualitative "instrument" types as well. We should discuss this with @DilekIkiz .

**Comment by UteH** [comment]
works!

But if I had first had "Daten- und Methodenbericht" in the chooser and then change to "Sonstiges", the title and description of the "Daten- und Methodenbericht" remain. I would have expected them to be blank again

**Comment by rreitmann** [comment]
As agreed during our daily: We will not delete title and description for the user.
