### ISSUE TITLE
As data provider I need a subdataset category for .csv files

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2857]
We need to add .csv to this list

![grafik](https://user-images.githubusercontent.com/17981185/116091505-2b3a7c80-a6a5-11eb-897c-1b01b6657696.png)

**Comment by rreitmann** [comment]
@AndyDaniel1 I have implemented this. Since this is sent to the DLP: Are we sure the DLP can handle additional data formats?

**Comment by AndyDaniel1** [comment]
@rreitmann Thank you for the (very) quick implementation 🚀 !! @UteH do you think we have an DLP issue here? If this has to be adapted in the DLP we should first think about other data formats we may need to avoid unnecessary additional work.

**Comment by UteH** [comment]
@AndyDaniel1 I think this is not a problem. 
@rreitmann can let me know when the code is on the test mdm? Then you or I could test if it works

**Comment by rreitmann** [comment]
I have tested this on the test system (dlp stage) by ordering a CUF and an On-Site-Suf. In both cases CSV was correctly displayed by the DLP.

**Comment by AndyDaniel1** [comment]
@rreitmann @UteH thanks to both of you!!
