### ISSUE TITLE
Document data set metadata

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2864]
here: https://github.com/dzhw/FDZ_Allgemein/wiki/Strukturierte-Metadaten#datensatz-dataset

**Comment by JohannaNiebuhr** [comment]
@rreitmann the documentation looks good and understandable to me. Only one thing:  
![image](https://user-images.githubusercontent.com/34309755/121357929-80b7a980-c932-11eb-9f98-808349b97465.png)
-> What do you mean by "ohne Erweiterung"?

**Comment by rreitmann** [comment]
@JohannaNiebuhr Filename "Erweiterungen"/Extensions are for instance ".dta", ".csv" and ".Rdata"...

**Comment by JohannaNiebuhr** [comment]
@rreitmann ok I didn't know its called "Erweiterung" :D. Maybe an example would help in that field than:  
* "Dateiname der konkreten Analysedatei (Bsp: gra2005_tS_p_c_2-0-1)"  
But I am also fine with no example, cause I would just check the example given here:   
![image](https://user-images.githubusercontent.com/34309755/121471185-8c04e680-c9bf-11eb-93c2-0747b1f063ed.png)  
Either way is fine with me ;)

**Comment by rreitmann** [comment]
@JohannaNiebuhr I have added an example. Thank you for reviewing this issue...
