### ISSUE TITLE
Bug? Sorting by release date does not work as expected

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2865]
Sorting by first and most recent release date results in an unexpected sort order. Valcom2 (the latest release) is in first place in both cases.

![grafik](https://user-images.githubusercontent.com/17981185/117013180-eab7b000-acef-11eb-836a-53499c6373bb.png)
![grafik](https://user-images.githubusercontent.com/17981185/117013227-f73c0880-acef-11eb-9472-8bd45235356d.png)

**Comment by rreitmann** [comment]
@AndyDaniel1: Both `release.firstDate` and `release.lastDate` of` valcom2s1` are set to 2021-05-03 which is in both cases the newest date in the database. Seems you expect something different!?

**Comment by rreitmann** [comment]
We will only order by `release.firstDate` and call it "Releasedatum"...
