### ISSUE TITLE
As a data provider I want to register via email link (remove  MDM registration link)

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#2882]
We still get registrations from data users and/or have difficulties to assign usernames to our data providers.

Can we remove the registration link on the MDM login site and send it via mail to our data providers? This prevents data users from registering, while allowing us to better manage data provider roles.

**Comment by rreitmann** [comment]
We could remove the register link of the MDM and instead add a link to the "Datennutzungsantrag" in the DLP...

**Comment by UteH** [comment]
"Datenübergabeantrag"?
