### ISSUE TITLE
as a data provider I want to specify more than one sponsor

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2890]

**Comment by rreitmann** [comment]
A search for "," in the sponsor field revealed the following "strange" sponsors:

```javascript
{
    "_id" : "stu-est2016$",
    "sponsor" : {
        "de" : "Bamberg Graduate School of Social Sciences (BAGSS), Universität Bamberg . Gefördert durch die Exzellenzinitiative.",
        "en" : "Bamberg Graduate School of Social Sciences (BAGSS), University of Bamberg. Funded by the German excellence initiative."
    }
}

{
    "_id" : "stu-dps2018$",
    "sponsor" : {
        "de" : "Universität Kassel, Wikimedia, Stifterverband, Volkswagenstiftung",
        "en" : "University of Kassel, Wikimedia, Stifterverband, Volkswagen Foundation"
    }
}

{
    "_id" : "stu-es7$",
    "sponsor" : {
        "de" : "Europäische Union, Teilnehmende Länder, Erasmus+, Bundesministerium für Bildung und Forschung (BMBF) und das Ministerium für Bildung, Kultur und Wissenschaft der Niederlande",
        "en" : "Participating countries, Erasmus +, Federal Ministry of Education and Research (Germany) and the Ministry of Education, Culture and Science (The Netherlands)"
    }
}
```

@AndyDaniel1, @UteH: Can one of you map these to a sponsors array (e.g.: `sponsors: [ {de: "Sponsor1", en: "Sponsor1}, {de: "Sponsor2", en: "Sponsor2"}]`?

**Comment by rreitmann** [comment]
Migrate MongoDB:
```javascript
db.getCollection('data_packages').find({}).forEach(function(dataPackage) {
    if (dataPackage.sponsor) {
        dataPackage.sponsors = [];
        dataPackage.sponsors.push(dataPackage.sponsor);
        delete dataPackage.sponsor;
        dataPackage.version = dataPackage.version + 1;
        dataPackage.lastModifiedDate = new Date();
        db.getCollection('data_packages').save(dataPackage);
    }
})
```

**Comment by UteH** [comment]
Mh, I think we would need to ask the data providers or the responsible rdc employee to sort that out...


### stu-est2016  @AndyDaniel1 
 - "de" : "Bamberg Graduate School of Social Sciences (BAGSS), Universität Bamberg . Gefördert durch die Exzellenzinitiative.",
 - "en" : "Bamberg Graduate School of Social Sciences (BAGSS), University of Bamberg. Funded by the German excellence initiative."


### stu-dps2018 @DilekIkiz agreed ✔️ 
 - "de" : "Universität Kassel, Wikimedia, Stifterverband, Volkswagenstiftung",
 - "en" : "University of Kassel, Wikimedia, Stifterverband, Volkswagen Foundation"
 -> here we can just separate into 
 - "de" : "Universität Kassel; Wikimedia; Stifterverband; Volkswagenstiftung"
 - "en" : "University of Kassel; Wikimedia; Stifterverband; Volkswagen Foundation"


## stu-es7 @AndyDaniel1 
- "de" : "Europäische Union, Teilnehmende Länder, Erasmus+, Bundesministerium für Bildung und Forschung (BMBF) und das Ministerium für Bildung, Kultur und Wissenschaft der Niederlande",
 - "en" : "Participating countries, Erasmus +, Federal Ministry of Education and Research (Germany) and the Ministry of Education, Culture and Science (The Netherlands)"

**Comment by UteH** [comment]
Testing was successful

**Comment by rreitmann** [comment]
Migrate stu-dps2018:
```javascript
db.getCollection('data_packages').find({masterId: "stu-dps2018$"}).forEach(function(dataPackage) {
    var sponsorsDe = dataPackage.sponsors[0].de.split(',');
    var sponsorsEn = dataPackage.sponsors[0].en.split(',');
    var sponsors = [];
    sponsorsDe.forEach(function(sponsor, index) {
        sponsors.push({
            de: sponsorsDe[index].trim(),
            en: sponsorsEn[index].trim()
        })
    });
    dataPackage.sponsors = sponsors;
    db.getCollection('data_packages').save(dataPackage);
})
```
