### ISSUE TITLE
Document how and what we track with Matomo

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2891]

**Comment by rreitmann** [comment]
@AndyDaniel1, @UteH: The documentation can be found here: https://github.com/dzhw/metadatamanagement/wiki/Web-Analytics Who can review it?

**Comment by UteH** [comment]
@rreitmann I have read the text. I think it gives a good overview. Without having access I can't really review it in detail, I think.

**Comment by rreitmann** [comment]
@UteH As mentioned in the text, you could request access from Ruth Cordes. However, if this is too much effort I think we can close this issue...

**Comment by AndyDaniel1** [comment]
@rreitmann Many thanks for the comprehensible documentation!! As already discussed yesterday, it gives a good overview but we should add some more information limitations of the application. Maybe we can also add some examples with screenshots for  specific analytical questions to get a better understand of how the application works. Please don't take the last two suggestions as a direct request for you, René . All FDZ users of Matomo should expand the doc over time.
