### ISSUE TITLE
Delete metadata-repos

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#2897]
As mentioned in this issue (https://github.com/dzhw/metadatamanagement/issues/2541#event-4823789803) the metadata-repos (like "phd2014-metadata") are outdated and Robert wanted to delete them. He asked Annika (@liedtke-dzhw ) to transfer the files to Faust and (when I remember correctly) she finished this task. Annika, please tell me if this is wrong - unfortunately I couldn't find the other issue where you discussed this task. 

Can we now delete the metadata-repos?

**Comment by liedtke-dzhw** [comment]
@svietgen right, I finished the task
