### ISSUE TITLE
should the serial number be displayed on the survey detail page?

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2906]
relates to #2779 

It could be the case that a panel with the waves (serial numbers) 1, 3, 5 and 7 will be released as a data package. In this cases it might be helpful for the public user to get this information (since the survey number would be 1, 2, 3). 

This could also be relevant for cross sectional data packages like the SE.

**Comment by rreitmann** [comment]
Additionally to displaying it on the details page we want to order the survey search results by serialNumber...

**Comment by AndyDaniel1** [comment]
The numbers of waves displayed on the detail page should reflect the number of waves in the data package not number of max. waves in the study design (reflected by the highest serial number).  So, in the case of panel studies, we should count the number of surveys in the data package and display that number on the detail page. Unfortunately this could also lead to confusion since some data packages have more waves than actual time points... since some parallel surveys (with different samples) were conducted (gra2005: 6 waves 3 for traditional students; 3 for BA students). I would still suggest displaying the number of surveys as number of waves on the detail pages (in case of panel studies), as this reflects the correct number of time points in most cases.

**Comment by AndyDaniel1** [comment]
tests completed ✔️

**Comment by AndyDaniel1** [comment]
Sorry, I forgot one important thing: We need to add an info-i for the serial number field on the **_survey detail page_**: 

de: Die Ordnungsnummer der Erhebung repräsentiert die Nummer der Erhebung, wie sie im Erhebungsdesign angelegt ist (z.B. Nummer der Panelwelle).
en: The serial number of the survey represents the number of the survey as it is implemented in the survey design (e.g. number of the panel wave).

**Comment by rreitmann** [comment]
@AndyDaniel1 I have added the info i. Please verify...

**Comment by AndyDaniel1** [comment]
check ✅
