### ISSUE TITLE
prepare findability interview

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2908]
I would like to prepare/discuss the topics of the findability interview I mentioned before

> Please feel free to forward this invite to anyone interested in your organization!
> Agenda: 
> 10 minutes short introduction to findability
> 20 minutes interview: 
> - The use of meta information for your site: Are you considering using additional metadata or metadata standards to describe your websites, in addition to your existing set of meta elements? Would you provide information on your decisions to choose these elements, or any considerations for other metadata standards that did not make it to the final selection?
>   - Potential application of Schema.org, Dublin Core, etc.
>   - Are you considering using any (SEO) tools to analyze and/or optimize your sites?
>   - Are you interested in increasing your reach by being included/indexed in new dataset search services, such as BASE, GESIS Dataset Search, etc.?
>   - An important part of access to any site these days is mobile access. Are you interested in receiving SOE (optimization) feedback for your sites (desktop and mobile)?
> 
> You may send us any concrete inquiry beforehand.

**Comment by rreitmann** [comment]
We need an appointment next week. I need to prepare that...

**Comment by rreitmann** [comment]
- Dublin Core is simple but who parses it?
- Schema.org/Dataset is a little more complicate but would help with Google Dataset Search
- Regarding SEO Tools: We use Google Search Console and Matomo (not exactly SEO), but there is no responsible person. Additional tools would be great to know!
- we are interested in being listed in more search services
- Google Search Console says that mobile usability is ok, however more feedback is welcome

**Comment by UteH** [comment]
my notes on the meeting: https://github.com/dzhw/KonsortSWD-TA2-M1-Supporting-RDCs/issues/37#issuecomment-865761350
