### ISSUE TITLE
Add field "additional links" on the data package detail page 

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2910]
Add field "additional links" on the data package detail page to enable data provider to provide links (e.g. project homepage)

de: Weiterführende Links
en: Additional Links

**Comment by rreitmann** [comment]
Optional name (de and en) for the link....

**Comment by AndyDaniel1** [comment]
The field is implemented correctly (I tested it for the Data Package Detail Page and Data Package Overview). 

Perhaps we should include a short example in the interface explaining what format the URL should be entered in. I guess that many users think of an URL as `www.xyz.de` . The `xxx://yy.xyz.en` format is not intuitive for the average user and can lead to confusion if the `www.xyz.de` is not accepted by the interface. 

I would add the hint: 

en: Please enter the URL as in the following example: http://www.dzhw.eu
de: Bitte tragen Sie die URL wie in dem folgenden Beispiel ein: http://www.dzhw.eu

**Comment by rreitmann** [comment]
@AndyDaniel1 I have changed the hints so that they now include an example. Please verify...

**Comment by AndyDaniel1** [comment]
Thank you René for the quick adjustment. From my point of view, the implementation is now complete ✔️
