### ISSUE TITLE
We need to add new metadata fields on the data package detail page which represent the allowed use cases and possible restrictions for the data use 

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2912]
Field 1:
[en] allowed use cases: [List with uses cases]
[de] erlaubte Nutzungszwecke: [Liste mit erlaubten Nutzungszwecken]

We have to deliver the list [de en]

Field 2:
[en] special restrictions for the data use: [free text field]
[de] spezielle Beschränkungen für die Datennutzung: [Freitextfeld]

-> also send this via order management to DLP

**Comment by UteH** [comment]
datorium:
![grafik](https://user-images.githubusercontent.com/18573122/123446439-2c225880-d5d9-11eb-973f-44f032efa906.png)

press?
statistical non-profit purposes?

**Comment by AndyDaniel1** [comment]
journalistic purposes and statistical non-profit purposes ✅ maybe should also add governmental purposes (as specification of the latter)

**Comment by UteH** [comment]
we could also add restricted user groups like for scs?

**Comment by AndyDaniel1** [comment]
duplicate https://github.com/dzhw/metadatamanagement/issues/3214
