### ISSUE TITLE
Analyze requirements for ROR IDs (=persistent identifier institutions)

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2930]
#2758

**Comment by rreitmann** [comment]
Here are the guidlines for displaying ROR IDs:
https://ror.org/display-guidelines/

REST API for searching ROR IDs:
https://ror.readme.io/docs/rest-api

**Comment by rreitmann** [comment]
RORs schould be used in "sameAs"-Attribute of "Organization"s in schema.org.
