### ISSUE TITLE
As a data provider, I would like to publish one or more scripts (code) that will be used for a specific publication. 

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2952]
**_New domain object code/skript/analysis script/replication script/publication script (name has yet to be defined) has to be defined with the following attributes (en/de):*_* 

- **resourceType**: [constant: collection] [mandatory/da|ra]

- **resourceIdentifier**: dzhw:${dataAcquisitionProject.­masterId}:1.0.0

- **title/Titel:** [i18n-string]

- **description/Beschreibung:** [i18n-string]

-  **Annotations/Anmerkungen:** [i18n-string]

- **dataUrl** : Prod URL of data package version [mandatory/da|ra]

- **autors/Autoren**: [list of persons]  [at least one entry manatory/da|ra]

- **related publication/verbunde Publikation**: An assignment of a publication is mandatory for a release of a analysis package. The assignment will be managed by the related publication manager; if a publication is assigned to the analysis package should be checked in a (post) validation process prior to a release #2980 
 
- **Software Packages/Softwarepakete**: [list of software packages ]  (Hint: Please choose the software package(es) the script is written for / Bitte wählen Sie das/die Softwarepaket(e) ein, für die dieses Skript geschrieben wurde)  [mandatory/da|ra]: Stata, SPSS, R, Python, Latent GOLD, AMOS, MAXQDA, Mplus, Matlab, Julia, JASP. PSPP, Almo, PRISM, SAS, STATISTICA, Mathematica, gretl, Jamovi, RapidMiner, GAUSS, SPARQL.   

- **Version of Software Package/Version des Softwarepaketes** [mandatory]

- **Used Language(s)/Verwendete Sprache(n)**: [list of languages] (Hint: Please indicate the language you used for the comments in the script/Bitte geben Sie die Sprache an, die Sie für die Kommentare im Drehbuch verwendet haben)

- **doi**: [is assigned at release] [madatory/da|ra]

- **Version (publication date) / Version (Veröffentlichungsdatum)**: [is assigned at release] [mandatory/da|ra]

- **availability/Verfügbarkeit**: [delivery/verfügbar; not available/nicht verfügbar]  [mandatory/da|ra]

_**Still to be decided**_:

- **Instition/Institution**: Should we mention institions

- **Förderer/Sponsors**: Should we mention sponsors

 - **Data Curation/Datenkuratierung**: Should we mention the data curators? 

- **License/Lizenz**: If no contract is signed we will need a license like cc-by-sa 

- **availablityType**: [Application necessary] (if an application process has to passed)

- **How do we handle analysis/replication data**

_**Additional Infos:**_
Name/labeling: Gesis denotes scripts with code/syntax in the title of the data packages ([Example 1](https://search.gesis.org/research_data/SDN-10.7802-2293); [Example 2](https://search.gesis.org/research_data/SDN-10.7802-1693))

**_Attachments:_**
It will be possible to attach the actual scripts 

- Title 
- Some of the metadata mentioned above are in my opinion metadata of the attachment (let's discuss this): 
  - Autors 
  - Software Packages (incl. version of the package)
  - Used Language

**Comment by AndyDaniel1** [comment]
Question: Where do we store the metadata of scripts if we don't have them as attachments (if they are only available via an order)? 
Suggestion: The (metadata of the) scripts are not attachments (as with the analysis data) and they are always displayed on the detail page. Each script should have an attachment where the actual file can be stored if a direct download is possible.

**Comment by rreitmann** [comment]
@AndyDaniel1 Do we need tags for analysis packages?

**Comment by AndyDaniel1** [comment]
@rreitmann yes! Especially in this case it could be easy to assign tags, because the topic of the related publication is quite narrow.  The tags should be mandatory, Thanks for the good hint!!

**Comment by AndyDaniel1** [comment]
✔️ works as expected
