### ISSUE TITLE
As public user I want to search/filter for analysis packages

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2953]
If we implement #2952, we also need search and filter options that present datapackages and scripts as the public user expects. 

Idea: 

2 Tabs (see screenshots): Datapackages & Scripts

Tab Datapackages is selected by default. Search results for datapackages and scripts are represented by number of hits in the Tab (see mockup). 

We also need to include unique filters for scripts  (according to the attributes defined in #2952 ) 

![grafik](https://user-images.githubusercontent.com/17981185/130940356-b3c16d39-d2a6-4525-ac00-ce56fbac1967.png)

**Comment by rreitmann** [comment]
- | ] filter must be cleared when changing type (e.g. sponsors of data packages are different from sponsors of analysis packages)
- [ ] sorting by "Erhebungszeitraum" does not make sense for analysis packages -> remove from dropdown

**Comment by rreitmann** [comment]
- [ ] Data Packages and Analysis Packages should have black color on the filter panel (instead of blue)

**Comment by rreitmann** [comment]
- [ ] if I switch the package and there has been a filter then two searches are executed (see network tab in dev tools)

**Comment by rreitmann** [comment]
- [ ] filter is cleared after search is executed: search for analysis packages and filter by sponsor then click on data packages -> no results

**Comment by AndyDaniel1** [comment]
✔️ works as expected

**Comment by AndyDaniel1** [comment]
![grafik](https://user-images.githubusercontent.com/17981185/145039713-6edfbdfa-2785-47ce-ae72-305860d83a7d.png)

Add an info-i for each filter:

Data Packages: 

en: Data packages are Scientific Use Files or Campus Use Files that are intended for broad use in science or teaching.
de: Bei Datenpaketen handelt es sich um Scientific Use Files oder Campus Use Files, die für eine breite Nutzung in Wissenschaft bzw Lehre vorgesehen sind.


Analysis Packages: 
en: Analysis packages are analysis scripts and analysis data that were used to create a specific publication and thus enable its replication.
de: Bei Analysepaketen handelt es sich um Analyseskripte und Analysedaten, die zur Erstellung einer spezifischen Pubilkation verwendet wurden und ermöglichen damit deren Replikation.

**Comment by AndyDaniel1** [comment]
✔️
