### ISSUE TITLE
As dataprovider or publisher I want to add attachments to analysis packages

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2979]
- extension of #2978

fields of attachments need to be defined:
- title
- language
- description

**Comment by rreitmann** [comment]
- [ ] after adding an attachment the edit-dialog shows the following in german and english
![Bildschirmfoto von 2021-11-11 14-45-59](https://user-images.githubusercontent.com/12323832/141308912-7509cba9-bb0c-4575-b7b5-74c3f7f07eee.png)

unable to do further testing

**Comment by rreitmann** [comment]
- [ ] the table header shows english translations in German
![image](https://user-images.githubusercontent.com/12323832/141312726-9490dbf3-ffd9-44a6-b99d-b8483186d537.png)
- [ ] when I restore a previous version of the attachment metadata all fields are empty

**Comment by rreitmann** [comment]
- [ ] when I restore a previous version of the attachment metadata then the save button is not active (only ok if I restore the latest version)

**Comment by rreitmann** [comment]
- [ ] when I change the file and confirm the warning and cancel the attachment dialog, then the table shows an already deleted file

**Comment by MIKAGMR** [comment]
@rreitmann I cannot reproduce this behavior.

**Comment by AndyDaniel1** [comment]
✔️ works as expected
