### ISSUE TITLE
As public user or data provider/publisher I want to see the details of an analysis package

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2982]
- check if details page needs to contain schema.org metadata (https://schema.org/Code)
- details pages need to be prerendered

**Comment by rreitmann** [comment]
- [ ] there is no analysis package overview -> remove code

**Comment by rreitmann** [comment]
- [ ] scripts are not displayed
- [ ] datapackages are not displayed
- [ ] license is optional -> hide card if license is not available
- [ ] page remains empty if there is no institution
- [ ] there is no creation of analysis package overviews (remove pdf button)

**Comment by rreitmann** [comment]
- [ ] attachments: table border over filename has an offset
- [ ] analysis data: some labels have a colon some do not have a colon (use colons everywhere)
- [ ] analysis data - custom data package: availabilityType is displayed twice 
- [ ] do not show multiple dividers if a card is missing (e.g. license, analysis data, attachments)

**Comment by MIKAGMR** [comment]
New Ticket #3030 for the pixel offset: ~~attachments: table border over filename has an offset~~

**Comment by rreitmann** [comment]
- [ ] page title and og:title are not set (compare with data package details)

**Comment by rreitmann** [comment]
- [ ] when I am on the analysis package details page the search field must lead to the analysis package search and not to the data package search

**Comment by AndyDaniel1** [comment]
✔️ works as expected
