### ISSUE TITLE
As public user I want to order analysis packages

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2983]
- shopping cart will receive all referenced dataPackages (optional) + analysisPackage with one click
- access ways are constant
- version must be selectable

**Comment by rreitmann** [comment]
- [ ] if I click on "Order free of charge", I get the following error: angular.js:15697 TypeError: Cannot read properties of null (reading 'products')
    at createAnalysisPackageForOrder (shopping-cart.controller.js:317)
    at shopping-cart.controller.js:335
    at Array.forEach (<anonymous>)
    at Object.ctrl.order (shopping-cart.controller.js:330)
- [ ] tooltips show "Datenpaket" instead of "Analysepaket" (in the side panel)
- [ ] shopping cart: tooltip on analysis package title is in english although german is the current language

**Comment by MIKAGMR** [comment]
" if I restore a previously saved order and add an analysis package then only the corresponding data package is added but the analysis package is missing"

We have to change the shopping cart to handle more than one product in the addToCart method.

**Comment by rreitmann** [comment]
- [ ] version info i dialog must describe versions of analysis packages
- [ ] when the shopping cart is completely empty (no order id) and I add an analysis package with a data package then I get the same data package twice

**Comment by rreitmann** [comment]
@AndyDaniel1 text for version "info i" needs to be defined

**Comment by AndyDaniel1** [comment]
@UteH and I discussed the shopping cart for analysis packages and suggest the following changes: 

-  In addition to the number of scripts, the number of **_accessible_** custom data packages should also be displayed in the shopping cart: For this example, this would mean: 1 script and 1 custom data package (since the other custom data package is not accessible): https://test.metadata.fdz.dzhw.eu/de/analysis-packages/ana-bachelorinparadise12?page=1&size=10&type=related_publications&version=2.0.0

**Comment by rreitmann** [comment]
@AndyDaniel1 Please retest...

**Comment by rreitmann** [comment]
@AndyDaniel1 Please provide the text for the version info i on the analysis package details page.

**Comment by AndyDaniel1** [comment]
Our analysis packages are available in a three-digit version. The digits of the version number indicate how big the changes to the data are. You will be notified if changes are made to the first two digits.

    First digit (Major): Changes/Adding to/of one or more analysis scripts and/or one or more custom data packages.
    Second digit (Minor): Changes to metadata/documentation.
    Third digit (Patch): Adding/deleting language versions.

For most data users, the most recent version of the data is relevant.


Unsere Analysepakete liegen dreistellig versioniert vor. Die Stellen der Versionsnummer legen nahe, wie groß die Änderungen an den Daten sind. Bei Änderungen an den ersten beiden Stellen werden Sie benachrichtigt.

    Erste Stelle (Major): Änderungen an oder Hinzufügen von einem oder mehreren Analyseskript(en) und/oder benutzerdefinierten Analysedaten
    Zweite Stelle (Minor): Änderungen der Metadaten/Dokumentation.
    Dritte Stelle (Patch): Hinzufügen/Löschen von Sprachversionen.

Für die meisten Datennutzer:innen ist die aktuellste Version der Daten relevant.

**Comment by AndyDaniel1** [comment]
for a final test of this issue we have to wait for the DLP-implementation

**Comment by AndyDaniel1** [comment]
The DLP implementation and ordering process seems to be working as expected.
