### ISSUE TITLE
Remove study from Order API

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2986]
After the DLP has been changed to use `product.dataPackage` instead of `product.study` we can delete `product.study`.

**Comment by rreitmann** [comment]
This is a follow up of #2984

**Comment by tilovillwock** [comment]
@AndyDaniel1 this came up while working and #3233. I think we should consider removing for good now as part of those tickets.

**Comment by AndyDaniel1** [comment]
@tilovillwock yes, that is a good idea

**Comment by AndyDaniel1** [comment]
@UteH please have a look at this issue
