### ISSUE TITLE
Search-as-you-type with pjax

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#3]
As developers we want to integrate jquery pjax in order to increase cross browser compatibility when doing partial page requests.

**Comment by rreitmann** [comment]
Chrome caches partial server responses and displays them when using the back button, therefore we have currently disabled caching completely for variable search.
https://github.com/defunkt/jquery-pjax should solve the back button problem and we could therefore enable caching again.

**Comment by rreitmann** [comment]
Use http://cdnjs.com/libraries/jquery.pjax

**Comment by dkatzberg** [comment]
the jquery.pjax 1.9.6 version has bugs, which hit us. i am using the version from the pjax github until the next release. for more information about the fixed bugs, take a look here: https://github.com/defunkt/jquery-pjax/compare/v1.9.6...master

**Comment by rreitmann** [comment]
@dzhw/devops Currently I see the following issues with pjax
- After search for "Staat" and clicking the details link and hitting the back button the partial page is displayed
- Form submission with pjax does a full page refresh on iOS

**Comment by rreitmann** [comment]
Created issue for full page reload on iOS: https://github.com/defunkt/jquery-pjax/issues/571

**Comment by rreitmann** [comment]
Created issue for back button problem on Chrome: https://github.com/defunkt/jquery-pjax/issues/572

**Comment by rreitmann** [comment]
We are currently replacing the survey period filter with pjax even though it is "static". This causes focus problems. A better way would be to only replace the dynamic parts of the page with jquery.

**Comment by rreitmann** [comment]
Here is a jquery example for replacing multiple divs: http://www.webdeveloperjuice.com/2010/04/01/filling-multiples-divs-by-single-ajax-call-using-jquery/

**Comment by rreitmann** [comment]
There is currently another issue with PJAX: If you do search-as-you-type and hit the browsers back button, than the datepicker does not work anymore.

**Comment by rreitmann** [comment]
There is another issue with PJAX and form submission: If you filter by survey title (ALLBUS for instance) and click the Back button then the title remains selected.

**Comment by rreitmann** [comment]
@dzhw/devops We have decided to remove the PJAX library to workaround the issues we have documented above.

**Comment by rreitmann** [comment]
@anfranken Please retest search-as-you-type
