### ISSUE TITLE
Fill tex template with metadata for variable report

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#30]
As publisher I want to be able to upload a Tex template. This template will be filled with metadata and returned to the publisher.

**Comment by rreitmann** [comment]
http://www.nixo-soft.de/de/category/Downloads/page/libs/JavaLatexReport.php
http://blog.jovicazoric.com/2013/09/24/create-a-pdf-document-using-latex-and-java/

**Comment by rreitmann** [comment]
Fileupload:
https://github.com/danialfarid/ng-file-upload/wiki/spring-mvc-example

Download (Stream) from Mongo:
http://stackoverflow.com/questions/32394697/how-to-send-an-retrieved-image-from-mongo-using-gridfs-in-spring-rest-call

**Comment by dkatzberg** [comment]
@rreitmann Please review the code changes.

I will enhance the tex template and the latex service beside the review.

**Comment by dkatzberg** [comment]
Found a bug. I will fix it first.

**Comment by dkatzberg** [comment]
@anfranken  : Only Windows: Test barrier free pdf: http://www.access-for-all.ch/en/pdf-lab/pdf-accessibility-checker-pac.html

**Comment by rreitmann** [comment]
User tests are skipped. Work is continued in #334.
