### ISSUE TITLE
File name validation during file upload

### ISSUE THREAD

**Issue by MIKAGMR** [dzhw/metadatamanagement#3014]
If an uploaded file starts with a dot, this file is no longer deletable.

The API URL path is changed:
Current state: '/api/analysis-packages/ana-analysis01$/attachments.filename'
Target state: '/api/analysis-packages/ana-analysis01$/attachments/.filename'

**Comment by rreitmann** [comment]
There are more file uploads which have the same problem:
- [x] src/main/webapp/scripts/analysispackagemanagement/resources/analysisPackageAttachment.resource.js
- [ ] src/main/webapp/scripts/analysispackagemanagement/resources/scriptAttachment.resource.js
- [ ] src/main/webapp/scripts/conceptmanagement/resources/conceptAttachment.resource.js
- [x] src/main/webapp/scripts/datapackagemanagement/resources/dataPackageAttachment.resource.js
- [ ] src/main/webapp/scripts/datasetmanagement/resources/dataSetAttachment.resource.js
- [ ] src/main/webapp/scripts/instrumentmanagement/resources/instrumentAttachment.resource.js
- [ ] src/main/webapp/scripts/surveymanagement/resources/surveyAttachment.resource.js

**Comment by rreitmann** [comment]
Files with two dots in the filename (e.g. ".mongorc.js") cannot be uploaded.
