### ISSUE TITLE
As authenticated user I want to search for analysis packages

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#3016]

**Comment by rreitmann** [comment]
- [ ] sponsor filter and institution filter are empty although there are sponsors and institutions
- [ ] search view must hide data packages tab and concepts tab, when the selected project is an analysis package project
- [ ] search view must hide analysis packages tab, when the selected project is a data package project
- [ ] floating action buttons for delete all and edit (compare with data packages tab) are missing when analysis package project is selected
- [ ] should we be able to filter analysis packages by data package?
- [ ] should we be able to filter data packages by analysis package?

**Comment by MIKAGMR** [comment]
@rreitmann 

"search view must hide data packages tab and concepts tab, when the selected project is an analysis package project"

We should disable the tabs and not hide it. We have a property in our tab object array for this use case.

**Comment by AndyDaniel1** [comment]
works as expected ✔️
