### ISSUE TITLE
Add analysis packages to start page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#3025]
For web crawlers we need at least a link to the analysis package search on the start page. Further requirements need to be defined...

**Comment by AndyDaniel1** [comment]
- The link to the data packages should be on the left side. 
- Is it possible to specify the current number of data packages and analysis packages in brackets after the strings (see screenshot)?
![grafik](https://user-images.githubusercontent.com/17981185/143600159-c44299d5-3560-48be-866c-b77ec9bc6a79.png)

**Comment by rreitmann** [comment]
@AndyDaniel1 Please retest...

**Comment by AndyDaniel1** [comment]
✔️

**Comment by AndyDaniel1** [comment]
Just a change request by @danbfdz : 

Please change the Strings as follows: 

en:
Show all Data Packages (SUF, CUF)   
Show all Analysis Packages (Scripts)

de:
Alle Datenpakete anzeigen (SUF, CUF)
Alle Analysepakete anzeigen (Skripte)

**Comment by AndyDaniel1** [comment]
✔️
