### ISSUE TITLE
The shopping cart is not being displayed in the Firefox browser

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3035]
When I try to open my shopping cart in the Firefox browser, this happens:

![grafik](https://user-images.githubusercontent.com/17981185/144418275-5b3528c2-b3c4-49bf-b99f-e60618acbb87.png)

 In my browser this is a persistent problem.

**Comment by rreitmann** [comment]
@AndyDaniel1 I guess that this is a compatibility problem of the old shopping cart in your browser and the new app version. On prod we clear the shopping cart when a new version is deployed. Try to delete Cookies and Website Data in Firefox as described here:
https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox#w_clear-cookies-for-the-current-website
