### ISSUE TITLE
Update angularjs material

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#3044]

**Comment by rreitmann** [comment]
Update is on hold in branch `material-update` due to the following layout issues:
![Bildschirmfoto von 2021-12-13 14-26-56](https://user-images.githubusercontent.com/12323832/146149582-2467cf14-7d69-48f1-813c-676175aa4528.png)
![Bildschirmfoto von 2021-12-13 14-15-18](https://user-images.githubusercontent.com/12323832/146149602-b8ece73c-6826-41bd-93f9-be36f328c20c.png)

It needs further testing of all GUI components.

**Comment by ekrgr** [comment]
Should be fixed with PR #3072
