### ISSUE TITLE
Show string if script is not avaiable via direct download

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3054]
If no script is uploaded as a file for direct download, we need to add a string in the relevant row in the "Datei"/"File" column:

de: Das Skript ist nicht über einen direkten Download verfügbar, bitte bestellen Sie das Analysepaket über den Warenkorb.
en: The script is not available via direct download, please order the analysis package via the shopping cart. 

![grafik](https://user-images.githubusercontent.com/17981185/146224758-2d87e965-27de-4fcb-b815-a308bb1e73e3.png)

As an alternative (If the string is too long), we could add asterisk in the row and add a string below the list. In this case the string below the list should only be displayed if an asterisk is displayed in the list. 
![grafik](https://user-images.githubusercontent.com/17981185/146227560-bc0e04dd-59fd-4e53-9e80-21fa304fe20d.png)

**Comment by UteH** [comment]
I prefer option 2 as the string is quite long

suggestion if option 2 does not work: shorten string to "muss beantragt werden" / "Must be ordered"

**Comment by rreitmann** [comment]
@AndyDaniel1 I have implemented option two. Please test as soon as this build has been completed:
https://github.com/dzhw/metadatamanagement/actions/runs/1587088397

**Comment by AndyDaniel1** [comment]
@rreitmann @UteH Thank you for the quick response and implementation. I tested the issue and it works as expected!!
