### ISSUE TITLE
As a user I want to filter for related publications

### ISSUE THREAD

**Issue by svietgen** [dzhw/metadatamanagement#3095]
I searched for a publication in the MDM and it was too difficult to find what I am looking for. 
Can we add a "filter" at the sidebar to filter for publications?
It might look like this:

![pub_filter](https://user-images.githubusercontent.com/22055122/165131212-4fc391f4-6bec-4738-8ce0-c8794b2439c6.png)

The filter should be added only to the sidebar (not to the starting page). 

"Erscheinungsjahr" and "Sprache" should be added as filter options.

**Comment by AndyDaniel1** [comment]
✔️
