### ISSUE TITLE
typo at info i for Analysepakete

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#3105]
"Analsepakete (Skripte)" ℹ️ 
> Analysepakete enthalten Analyseskripte und Analysedaten, die zur Erstellung einer spezifischen Pubilkation verwendet wurden und ermöglichen damit deren Replikation.

-> Publikation

~currently not yet visible on prod because we do not have analysis packages yet~

test: https://test.metadata.fdz.dzhw.eu/de/search?page=1&size=10&type=analysis_packages

**Comment by ekrgr** [comment]
fixed with 340b2b5d14045ef73a990635105585e32a4d3349

**Comment by AndyDaniel1** [comment]
✔️
