### ISSUE TITLE
Karma Test loads Navbar / Main Template

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#311]
The Navbar and Main Template will by load by Karma Unit Tests, where they shouldn't. E.g.: survey.resource.spec.js or file.resource.spec.js .

The tests expect the get calls for the Navbar and Main template by the call of '$httpBackend.flush()'. This is the reason for the try catch block around the flush call. The loading of the templates must be defined by a more general configuration for the tests or worse the application.

This is a not traceable behavior und should be fixed.

**Comment by rreitmann** [comment]
We do not focus on karma tests at the moment.
