### ISSUE TITLE
Developer Wiki page contains dead link to publication upload process page

### ISSUE THREAD

**Issue by moellerth** [dzhw/metadatamanagement#3121]
The [wiki page for developers](https://github.com/dzhw/metadatamanagement/wiki/Entwickler%3Ainnen-Doku)  contains a dead link to the wiki page describing the process of uploading a new publication in section "1.4 Publikationen". 
Another wiki page about the [metadata import](https://github.com/dzhw/metadatamanagement/wiki/Metadata-Import) could be found containing information about how the Citavi Export has to look like to import it as a publication. If this page is holding all information available it should be linked to the developers wiki. 
As no exact information could be found on how users can upload the Citavi export file within the application it might be beneficial to add instructions.

**Comment by AndyDaniel1** [comment]
@moellerth thanks for the hints on the links. 

The link was not dead but not accessible as this repo is private. I have granted access to outside collaborators.

I added the additional Link to the dev wiki
