### ISSUE TITLE
Deactivate Users even if they are assigned to projects

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3122]
Currently it is not possible to deactivate users if they are still assigned to projects in the cockpit. We need to implement global removal of users from projects when we deactivate them.

We should add a warning en/de: "If you deactivate the user she/he will be removed from the following projects [list of assigned projects]." "Wenn Sie die/den Nutzer:in deaktivieren wird sie/er aus den folgenden Projekten entfernt [Liste mit zugeordneten Projekten]"

Current error message (followed by a list of assigned projects): 
![grafik](https://user-images.githubusercontent.com/17981185/189858792-f6380860-e740-4fcf-b089-65984a00b7fb.png)

Thanks to @kleindaniel81 & @anneweber for bringing this topic back up.

**Comment by moellerth** [comment]
Currently it is possible to add deactivated users to a project via the project cockpit. As this contradicts the intended approach that deactivated users cannot be assigned to a project, we would like to filter the list of available users by their status as part of the implementation.

**Comment by AndyDaniel1** [comment]
![grafik](https://user-images.githubusercontent.com/17981185/217545224-89e07738-fede-4b5f-a7dd-3b40adf12b35.png)

it is still not possible to deactivate users when they are assigned to projects (see screenshot)

**Comment by AndyDaniel1** [comment]
Seems to be working well ✔️
