### ISSUE TITLE
Add new Field "Förderkennzeichen /Funding reference" to datapackage detailpage

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3129]
We need a new _**optional**_ metatdata field for "Förderkennzeichen / Funding reference" on the datapackage detailpage.

title
en: "Funding reference"
de: "Förderkennzeichen"

We don't need an I18n-String as the Funding reference is a number or a combination of numbers, letters and/or special characters

The field should be placed between "Gefördert von" und "Projektmitarbeiter:innen": 
![grafik](https://user-images.githubusercontent.com/17981185/191491657-d33bc9ce-9019-433c-b378-6af6c59e568e.png)

**Comment by cschwartze** [comment]
@AndyDaniel1 Just to be sure and for clear understanding: this implies also the possibility of new entry in sponsors context, for **each** sponsor/donor...right? Like shown in screenshot...

![FKZ](https://user-images.githubusercontent.com/111130290/192766798-20936345-4657-4f52-b295-cb9034035ba1.png)

**Comment by cschwartze** [comment]
@AndyDaniel1 In case of several sponsors with optional funding reference number, the readability in one line may not be optimal. I propose therefore to display/layout information as follows (listed below each other).
![multiple_sponsors](https://user-images.githubusercontent.com/111130290/195021644-3c08598c-3014-4881-bb16-469c86c0feb3.png)

**Comment by AndyDaniel1** [comment]
@cschwartze yes, this is a good solution. When the implementation has reached a testable state, please deploy the feature to the test system and add the label "testing" to this issue.

**Comment by cschwartze** [comment]
@AndyDaniel1 As sponsor data also included in analysis packages, I will apply all adjustments to forms, layouts, latex templates (reports) an so on to the analysis packages.

**Comment by AndyDaniel1** [comment]
@cschwartze sorry for the late reply. Yes this could be done for analysis packages as well.

**Comment by AndyDaniel1** [comment]
✔️
