### ISSUE TITLE
Change the german de-string "Datenaufbereitungsprojekt" to "Datenaufnahmeprojekt"

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#3144]
Change the german string "Datenaufbereitungsprojekt" to "Datenaufnahmeprojekt"

![grafik](https://user-images.githubusercontent.com/18573122/194338969-dc1a1fe3-8603-4282-91b6-696923d21f7d.png)

**Comment by AndyDaniel1** [comment]
@UteH I'm not sure what you mean by "the strings contain only "data package"". Which strings are you referring to? I think the string "Datenaufbereitungsprojekt" is meant in the general sense that analysis packages are also prepared in Datenaufbereitungsprojekten. But perhaps the English term "data acquisition project" is more specific, as it refers to "Datenaufnahme". Should we rename the de string to "Datenaufnahmeprojekt"?

**Comment by UteH** [comment]
@AndyDaniel1 mh I think you are right 🤔 That's my bad, I got confused with the terms. Analysis package is part of a _data aquisition project_. 

I second that the translation "Datenaufnahmeprojekt" is more accurate. 

sorry for the confusion 😅 !

**Comment by AndyDaniel1** [comment]
I think the term "Datenaufbereitungsprojekt"  is a confusing and could lead to misunderstandings, so a renaming is appropriate. I have changed the title and description of the issue accordingly.

**Comment by UteH** [comment]
Thank you!

**Comment by AndyDaniel1** [comment]
✔️
