### ISSUE TITLE
Add information and consent on cc0 license (via da|ra) to annotation and description field of datapackage

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3151]
As the information of the annotation and description field will be published under a cc0 license by da|ra (after release) we should add an explicit hint and consent. This hint should always be present (not the standard solution proposed in #3166 )

de: "Bitte beachten! Die in dieses Feld eingegebenen Texte werden unter einer cc0 1.0 Lizenz über den da|ra-Dienst (https://www.da-ra.de/) veröffentlicht. Mit der Eingabe und dem Abspeichern stimmen Sie den entsprechenden Lizenzbedingungen zu. Weitere Informationen zu den Lizenzbedingungen finden Sie unter https://creativecommons.org/publicdomain/zero/1.0/deed.de"

en: "Please note! The texts entered in this field are published under a cc0 1.0 license via the da|ra service (https://www.da-ra.de/). By entering and saving, you agree to the corresponding license terms. For more information on the license terms, please visit https://creativecommons.org/publicdomain/zero/1.0/"

Annotations:
![grafik](https://user-images.githubusercontent.com/17981185/195818832-8cc2b5dd-b183-4fe3-a2e3-e1c6907b9855.png)

Description:
![grafik](https://user-images.githubusercontent.com/17981185/195819039-ae1e6f74-4b26-4f7a-b170-196dcf95881b.png)

**Comment by ewolf47** [comment]
@AndyDaniel1 is there any news concerning the wording? 
Also: should the links (see red markings on screenshot) in the hints be clickable?
![consent_links](https://user-images.githubusercontent.com/118182853/202429196-f520eec0-97ea-4625-89c3-eb490ca3f316.png)

**Comment by danbfdz** [comment]
Ja, das passt auch aus meiner Sicht inhaltlich so :)

**Comment by AndyDaniel1** [comment]
@ewolf47 thanks for the reminder. As daniel said, the wording can be used for the hints. The links should be clickable.

**Comment by AndyDaniel1** [comment]
✔️
