### ISSUE TITLE
Github Actions: Update Runner Image

### ISSUE THREAD

**Issue by tilovillwock** [dzhw/metadatamanagement#3157]
Github will remove the Ubuntu 18.04 image used in our actions by April 2023:

https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

As described in the blog post Actions also fail temporarily to raise awareness. We should ideally upgrade to [22.04](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on) right away and test the workflow to make sure they still work correctly.

**Comment by AndyDaniel1** [comment]
✔️
