### ISSUE TITLE
Disappearing hints after interaction with input

### ISSUE THREAD

**Issue by ewolf47** [dzhw/metadatamanagement#3166]
@AndyDaniel1 After clicking into a form-field and switching to another the hints disappear.
Is this actually the desired behavior? It seems wrong that the user is not able to see those hints after interacting with a form-field

But it also seems to be a conscious decision, because the actual code holds an ng-if block that controlls the visibility of the hint:
`<div class="fdz-input-hint" ng-if="!dataPackageForm.annotationsDe.$dirty && !dataPackageForm.annotationsDe.$touched">`

Alternative:
`<div class="fdz-input-hint" ng-if="ctrl.dataPackage.annotations.de == null || ctrl.
dataPackage.annotations.de == ''">`
In this case the hint would be visible as long as there is no content present in the form-field. Which means, if the user wants to see a hint he can always clear a field to make the hint visible again.

![touched_dirty_hints](https://user-images.githubusercontent.com/118182853/202453934-0b8390d5-c1d0-4362-8948-830eada7e3c9.gif)

**Comment by ewolf47** [comment]
@AndyDaniel1 
a small note: for fields that display a red error message if the input is not valid (e.g. mandatory fields), I would still remove the hint text once the field has been interacted with (see "Titel (auf Englisch)") in the animation below). If the hint text would always be displayed, it looks kind of strange, because the info from the hint text is basically duplicated with the error message (see "Titel (auf Deutsch)" in the animation below).

Is this approach in your best interest?

![hints_with_errors](https://user-images.githubusercontent.com/118182853/203497776-40c11cc6-1f64-4b98-a0cc-8dce1967078a.gif)

**Comment by ewolf47** [comment]
> 
> Is this approach in your best interest?
> 

As briefly discussed with @AndyDaniel1 in the webconf I commited this approach to the feature branch

**Comment by AndyDaniel1** [comment]
✔️
