### ISSUE TITLE
Button for reporting publications hides data protection link

### ISSUE THREAD

**Issue by moellerth** [dzhw/metadatamanagement#3173]
As it can be seen in the screenshot the button for reporting publications partially hides the data protection link. The button and the link should not overlap.

![button-datenschutz](https://user-images.githubusercontent.com/111288610/204213681-ed2d568b-0cbd-4295-a53c-bb9ffdce48df.png)

**Comment by moellerth** [comment]
This behavior is not limited to the start page and seems to be a general problem because it also appears in editing mode with the "start editing button".

**Comment by AndyDaniel1** [comment]
Ok, then we need to think about moving the data protection link.

**Comment by AndyDaniel1** [comment]
✔️
