### ISSUE TITLE
Automated tweet and website news entry as part of the publication of data packages

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3206]
**_Has to be refined._**

Idea: 

- Standardised Tweet / Website news entry when datapackage is released 
   - option to choose between en/de or to release both
   - Should there be a possibility to edit the tweet / the website news entry? (Twitter character limit needs to be verified when tweet(s) are/is edited; Could be a dialog after release checks are done)
- Checkbox in release dialog to activate tweet process (like check box to pin datapackages on MDM Mainpage)

**Comment by SaCodematix** [comment]
@AndyDaniel1 Here is a use case 

- A tweet text is provided as a placeholder, which can be edited and adapted by the user if required
- This placeholder tweet text by default contains both the German and Englisch version, e.g. ` Ein Datenpaket wurde freigegeben! {Titel DE } / A data package was released! { Titel EN }` bspw. ` Ein Datenpaket wurde freigegeben! DZHW-Absolventenpanel 2005  / A data package was released! DZHW Graduate Panel 2005 `
- Should the release version be included in the tweet text?
- Should a link be included in the tweet text? For example, MDM-URL or DOI-URL?
- The release dialog contains a checkbox to (de)activate the tweet process, e.g. 
   - en: `Do you want to publish a post about the data package on X (formerly Twitter)?`
   - de: "Wollen Sie einen Post über das freigegebene Datenpaket auf X (ehemals Twitter) veröffentlichen?"
- The release dialog also contains a textarea field with the tweet text placeholder, which might be disabled if the checkbox is deactivated. If the release was successful, the tweet will be posted. No additional dialog after the release dialog and its checks are done to avoid further appearing dialogs.

se case beschreiben 

twitter developer account free anlegen, access secret

java backend, umgebungsvariablen aws dara zugagssdaten senstive--variables.ts readme

**Comment by AndyDaniel1** [comment]
> @AndyDaniel1 Here is a use case of how the tweet process could work:
> 
>     * A tweet text is provided as a placeholder, which can be edited and adapted by the user if required
> 
>     * This placeholder tweet text by default contains both the German and Englisch version, like ` Ein Datenpaket wurde freigegeben! {Titel DE } / A data package was released! { Titel EN }`, e.g.  `Ein Datenpaket wurde freigegeben! DZHW-Absolventenpanel 2005  / A data package was released! DZHW Graduate Panel 2005`
> 
>     * Should the release version be included in the tweet text?
yes

 
>     * Should a link be included in the tweet text? For example, MDM-URL or DOI-URL?
yes, the doi of the data/analysis package link should be included 

>     * The release dialog contains a checkbox to (de)activate the tweet process, e.g.
>       
>       * en: `Publish a post about the data package on X (formerly Twitter).`
>       * de: `Post über das freigegebene Datenpaket auf X (ehemals Twitter) veröffentlichen.`
> 
✔️ 


>     * The release dialog also contains a textarea field with the tweet text placeholder, which might be disabled if the checkbox is deactivated. If the release was successful, the tweet will be posted. Therefore, no additional dialog will appear after the release dialog to avoid further dialogs.
✔️ 
 
> 
> Mockup sample: ![Image](https://private-user-images.githubusercontent.com/66066952/289885537-6bb70fc6-4dbd-4aa3-88a2-b69c0a60257d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjczNTIsIm5iZiI6MTcwMjQ2NzA1MiwicGF0aCI6Ii82NjA2Njk1Mi8yODk4ODU1MzctNmJiNzBmYzYtNGRiZC00YWEzLTg4YTItYjY5YzBhNjAyNTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDExMzA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YjFlMzUxMTEyMGFlYjMyZGJkZjcwNTU5NjViNDcyNjYwYTMwYTk2Nzk4NjgzZTc3NzcwMjIwMDVmNTMxMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ygickl5BsA3arloRFXcL0H15rb8v8CZaejxMLgJLqNE)
> 
>     * You would have to create a twitter developer account (free plan, limited to 1500 tweets) with your current twitter account, because we need the credentials for the authorization. For developing and testing, we will use our test account. https://developer.twitter.com/en

I already registered a developer account. Please inform me when you need the keys/tokens.

**Comment by AndyDaniel1** [comment]
@SaCodematix thank you for the very good mockup! Find my answers above.

**Comment by AndyDaniel1** [comment]
@SaCodematix could we include a dialog to include images in the posts? Maybe we can think about a standard image (which we will provide) that will be posted.

**Comment by SaCodematix** [comment]
> @SaCodematix could we include a dialog to include images in the posts? Maybe we can think about a standard image (which we will provide) that will be posted.

I will include it in the research about the twitter api.

**Comment by SaCodematix** [comment]
@AndyDaniel1  Do you have a specific wish for the standard image which will be automatically added to the tweets? I used the social survey JPG for testing and demonstration purposes.  

![Image](https://github.com/dzhw/metadatamanagement/assets/66066952/9c7ef6dc-4c68-4589-a9ed-1091d3c2eac7)


![Image](https://github.com/dzhw/metadatamanagement/assets/66066952/b21145c5-45a7-4cbf-8a04-c7ad7e34c5d7)

**Comment by AndyDaniel1** [comment]
@SaCodematix I would pass this task on to our designer, but I doubt that we will get an answer before January.

**Comment by AndyDaniel1** [comment]
@SaCodematix One additional comment on the tweet. The DAPID, should not be included in the tweet, only the Version number in brackets. [...] Eurostudent VII (Version 1.0.0) [...] 
![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/101db84d-2615-4b9c-b830-f784a0e0d84b)

**Comment by AndyDaniel1** [comment]
Would it be possible to choose between three predefined images?

As the images display a text, the version of the images available for selection should depend on the selected language. The total number of images stored would then be 6, the images to choose from 3 (for each language version).

example 1:
de [ ] en[x]
pic1_en; pic2_en; pic3_en
 
example 2: 
de [x] en[ ]
pic1_de; pic2_de; pic3_de

**Comment by AndyDaniel1** [comment]
@SaCodematix

**Comment by SaCodematix** [comment]
@AndyDaniel1 I added the tweet functionality to the relase type "regular release". Do you also want this functionality for "beta release" or "re-release"?

**Comment by AndyDaniel1** [comment]
@SaCodematix the tweet functionality should be implemented for releases >=1.0.0 , not for beta releases.

**Comment by AndyDaniel1** [comment]
warning successive tweets

**Comment by AndyDaniel1** [comment]
As discussed, this function will be deactivated until further notice.
