### ISSUE TITLE
License attributes for every element of an analysis package

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3220]
We need to implement license attributes for every element of an analysis package.

Since every analysis file (script) and every dataset might have different license terms.

![grafik](https://user-images.githubusercontent.com/17981185/230385184-dd05bf73-0dfb-4993-b8ed-40495841b15d.png)

For Datapackages we need a license attribute for External Datapackages and Custom Data Packages. 
![grafik](https://user-images.githubusercontent.com/17981185/230386287-c9a8f8f8-dc85-4fcc-9208-3165263c24df.png)

For FDZ-DZHW Datapackages we don't need a license attribute here. If a FDZ-DZHW datapackage has a license this information will be stored on the detail page of the datapackage. If this is the case in the future the corresponding information could be displayed here.

**Comment by tilovillwock** [comment]
@AndyDaniel1 should we provide an autocomplete for common licenses or is this going to be a freeform text field for now?

**Comment by AndyDaniel1** [comment]
> @AndyDaniel1 should we provide an autocomplete for common licenses or is this going to be a freeform text field for now?

It should be a freeform

**Comment by moellerth** [comment]
@AndyDaniel1 Two questions arose during the implementation:
1. For custom data packages it is possible to add multiple data sources. Should it be possible to add a license for each data source or only for the custom data package in general?
2. In our understanding the license for FDZ-DZHW data packages should be extracted directly from the corresponding data package dataset within MDM. Data packages currently do not have a license attribute. Does this issue include adding the license attribute and reading it from the data package or will there be a separate issue for this in the future?

**Comment by AndyDaniel1** [comment]
@moellerth 
1. yes every data source should have a license 
2. this would be a separate issue

**Comment by AndyDaniel1** [comment]
✔ works well
