### ISSUE TITLE
Internet Explorer unsupported hint

### ISSUE THREAD

**Issue by tilovillwock** [dzhw/metadatamanagement#3232]
Upgrading to a hybrid app model (#3227) introduces some breaking changes for Internet Explorer. It's my understanding that the target audience is unlikely to use Internet Explorer so this shouldn't be a real issue. Nonetheless we should implement a hint similar to the JavaScript disabled one explaining that the app doesn't work in it.

Viable IE detection code:
```javascript
const isIE = () => {
    const ua = navigator.userAgent;
    return ua.indexOf('MSIE') > -1 || ua.indexOf('Trident') > -1;
};
```

```javascript
const isIE = !!document.documentMode;
```
`documentMode` is an IE-only feature.

@AndyDaniel1

**Comment by AndyDaniel1** [comment]
✔ works well
