### ISSUE TITLE
String attachment method report

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3239]
![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/6360d7ee-024a-415a-a827-b0278d906cae)

Please edit the string that is automatically inserted into the description field of the attachment if the type "Method report" is selected.

de: "Der Bericht umfasst allgemeine Informationen zum Datenpaket."
en: "The report includes general information on the data package."

**Comment by anneweber** [comment]
@AndyDaniel1 https://github.com/dzhw/Datenpaketdokumentation/issues/22

**Comment by AndyDaniel1** [comment]
After testing update process documentation

**Comment by AndyDaniel1** [comment]
✔️ works well
