### ISSUE TITLE
Implement flag for qualidata net 

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3241]
Not everything has been decided yet, but in the near future all qualitative studies need to be flagged so they can be harvested by QualiDataNet. Presumably, the flag will be "qda".

**Comment by AndyDaniel1** [comment]
<alternativeIDs>
  <alternativeIDs>
     <intentifer>2</indetifier>
     <type>QDN</type>
  </alternativeIDs>
</alternativeIDs>

**Comment by AndyDaniel1** [comment]
alternatvieID 2 - QDN

**Comment by AndyDaniel1** [comment]
![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/1d579772-7bcf-4a22-9f02-4ab6ba1b5904)

**Comment by AndyDaniel1** [comment]
![Image](https://github.com/dzhw/metadatamanagement/assets/17981185/130957be-c903-4dc5-aeea-4c0a4fcde010)

**Comment by tilovillwock** [comment]
* requires a database migration for all data packages to add `alternativeID` according to this [schema](https://github.com/dzhw/metadatamanagement/issues/3241#issuecomment-1833999327)
* metadata changes need to be propagated to da|ra
* at least one survey with type "qualitative data" (`Survey::dataType == DataTypes.[QUALITATIVE_DATA|ALL]`) is required to mark a data package with this ID

**Comment by AndyDaniel1** [comment]
Looks good ✅
