### ISSUE TITLE
Search Card does not indicate that it is possible to search for a specific keyword in the data package

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3248]
If a person is logged into the test system and searches for data on a specific keyword, the Search Card does not indicate that the specific keyword can be searched for in the data package found. This string should appear whenever the keyword is found in the data package (or a related object). 

**Prod as public user**
![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/b7b487dc-b552-44e7-994f-ff3b38149f40)

**Test if logged in** 
![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/1ffd30ff-78fa-4935-852c-996718c427c2)

**Test as public user**
![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/3fdcdfc0-07cd-47b0-a9c2-2d1196b2c038)

**Comment by ewolf47** [comment]
Pull Request: https://github.com/dzhw/metadatamanagement/pull/3253

**Comment by AndyDaniel1** [comment]
✔️ Issue fixed
