### ISSUE TITLE
We need a search function for the user management interface

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3255]
We need a search function for the user management interface that allows us to search for usernames, email addresses and names (when #2788 is implemented)

![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/e14d0be3-6363-4652-8989-c36cb9e1a914)

**Comment by tilovillwock** [comment]
> that allows us to search for usernames, email addresses and names

We should also add columns for first and last name to the table view.

**Comment by AndyDaniel1** [comment]
✔ works well
