### ISSUE TITLE
New hidden attribute "Data transmission via the VerbundFDB"

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3257]
We need a hidden attribute  "Data transmission via the VerbundFDB" "Datenmeldung über den VerbundFDB" for the data package detail page, which is only visible for the role "publisher". 

The publisher should be able to filter data packages according to this attribute. 

The attribute does not have to be transmitted to the DLP.

**Comment by AndyDaniel1** [comment]
![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/b13c9677-e0ec-43f5-b77e-3240f5f25cc3)

**Comment by moellerth** [comment]
@AndyDaniel1 Should the new attribute field be a text field (like title or annotations) or another field type? Should this attribute be added to analysis packages, too?

**Comment by AndyDaniel1** [comment]
@moellerth it should be a checkbox (boolean true/false)

Title of the attribute in the interface:

de: "Data transmission via the VerbundFDB
en: "Datenmeldung über den VerbundFDB"

**Comment by ewolf47** [comment]
@AndyDaniel1 
Did I understand correctly that the new field is "false" by default? This means that data packages for which the checkbox has not been explicitly activated or deactivated are also counted as "not transmitted via VerbundFDB". Or should a distinction be made between data packages that are explicitly marked as "not transmitted via VerbundFDB" and data packages for which no selection has been made at all?

**Comment by AndyDaniel1** [comment]
@ewolf47 Yes, that is correct. The default setting is "not transmitted via VerbundFDB", the selection "true" has to be made explicitly by the publisher.
