### ISSUE TITLE
Fallback strategy for when DA|RA is not reachable

### ISSUE THREAD

**Issue by tilovillwock** [dzhw/metadatamanagement#3263]
While testing another feature we realized that DA|RA not being reachable does not prevent a package from being released. As a consequence the user is left with uncertainty whether the package actually has been released since no confirmation message is displayed and the release dialog is not closed. More importantly a new DOI isn't registered right away and as far as we can tell no further attempts are made at a later time.

As such we should decide:
1. Is not registering a DOI a deal breaker?
2. Should we provide an action to manually register a DOI?

If it's a deal breaker we need to adjust the workflow in order to give meaningful feedback to the user and prevent the release process from completing.

For your consideration @AndyDaniel1

**Comment by SaCodematix** [comment]
@AndyDaniel1 

Should we leave the error message worded in general terms "Contact the administrator [...]" or should we perhaps refer to the "Give feedback" functionality in the footer? E.g.

de: "Der da|ra-Service zur Registierung der doi ist aktuell nicht verfügbar. Nutzen Sie die Funktion "Feedback geben" in der Fußzeile, um den Administator zu kontaktieren, und versuchen Sie es später erneut."

en: "The da|ra service for registering the doi is currently not available. Use the "Give feedback" function in the footer to contact the administrator and try again later."

![grafik](https://github.com/dzhw/metadatamanagement/assets/66066952/d56332a1-70c1-468a-b360-1d6313bb8641)

**Comment by AndyDaniel1** [comment]
@SaCodematix Yes, that's a good point, I would add the feedback address directly. I've just updated the error message above.

**Comment by AndyDaniel1** [comment]
Should be finally tested in the production system if da|ra is actually unavailable
