### ISSUE TITLE
Adjust registration form

### ISSUE THREAD

**Issue by tilovillwock** [dzhw/metadatamanagement#3270]
- The registration page cannot be accessed from the login page (or from anywhere else apart the URL directly). Should we add a "Register" link to the login page that allows new users to access the registration page?
- The registration page does not display the validation requirements directly. Should it show some of the validations directly, e.g. which fields are required, which pattern is used to validate the field, ...?
- If an account already exists with the specified e-mail address, the user is informed after submitting the form and may have to fill in all fields again. Should this check as to whether the e-mail address is already in use be carried out beforehand? Is the information to the user that an email address is already in use GDPR-compliant?

**Comment by tilovillwock** [comment]
@SaCodematix could you clarify the last point about checking an existing user's email beforehand? Is this warning already in place or did you want to discuss this as a privacy issue before implementing such a check?

**Comment by AndyDaniel1** [comment]
> * The registration page cannot be accessed from the login page (or from anywhere else apart the URL directly). Should we add a "Register" link to the login page that allows new users to access the registration page?

We have deliberately removed the link as we only want registrations after we have contacted the data provider. 

> 
>     * The registration page does not display the validation requirements directly. Should it show some of the validations directly, e.g. which fields are required, which pattern is used to validate the field, ...?

Yes, that makes sense. 

> 
>     * If an account already exists with the specified e-mail address, the user is informed after submitting the form and may have to fill in all fields again. Should this check as to whether the e-mail address is already in use be carried out beforehand? Is the information to the user that an email address is already in use GDPR-compliant?

Yes, we should check this beforehand. It should be GDPR compliant, but I will pass this question on to our data protection officer.

**Comment by AndyDaniel1** [comment]
relation to this issue #2788

**Comment by SaCodematix** [comment]
> @SaCodematix could you clarify the last point about checking an existing user's email beforehand? Is this warning already in place or did you want to discuss this as a privacy issue before implementing such a check?

This was about 2 separate things. 
1. Currently, the information that an email already exists is in place and is displayed after the user has clicked on the "Register" button, the form has been reset, and the user unfortunately may have to fill in all fields again. The question therefore arose as to whether it would be better to display the information that an email already exists before the user clicks on "Register" and the form will be reset.
2. In addition, the question arose as to whether the information that an email already exists is GDPR-compliant at all (regardless of whether this information is displayed before or after clicking on "Register").

**Comment by AndyDaniel1** [comment]
@SaCodematix 

> Currently, the information that an email already exists is in place and is displayed after the user has clicked on the "Register" button, the form has been reset, and the user unfortunately may have to fill in all fields again. The question therefore arose as to whether it would be better to display the information that an email already exists before the user clicks on "Register", which would trigger the form to be reset.

yes this would be better


> In addition, the question arose as to whether the information that an email already exists is GDPR-compliant at all (regardless of whether this information is displayed before or after clicking on "Register").

this is still under review by our data protection officer

**Comment by AndyDaniel1** [comment]
✔️
