### ISSUE TITLE
DOI of analysispackages do not redirect to correct landingpage

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3294]
I just published this analysis package and it seems that the doi redirect is faulty. The released analysis package is also not findable for public users. We need a hotfix for this bug.

https://metadata.fdz.dzhw.eu/de/analysis-packages/ana-kracke2023?page=1&size=10&type=related_publications

![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/70101dd8-6769-4c92-b3c7-6339a28886f3)
![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/d156acd6-c83c-4c13-9404-335cc467958a)
![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/9cc75bea-7cfc-4a58-a574-d46240f16cdf)

**Comment by AndyDaniel1** [comment]
@tilovillwock this issue is fixed, right?

**Comment by tilovillwock** [comment]
> @tilovillwock this issue is fixed, right? From my point of view, everything is working perfectly again.

It is. I was not able to reproduce the issue after we deployed the fix.
