### ISSUE TITLE
Adjust the text in the info i for the access ways

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3302]
has to be refined 

![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/5a861fba-ab11-4dd7-a6e2-25d63c7a7710)

**Comment by anneweber** [comment]
- keep only first sentence and lower part:
![image](https://github.com/dzhw/metadatamanagement/assets/17066262/2052658b-db97-468e-a6ca-4523b58535b8)
![image](https://github.com/dzhw/metadatamanagement/assets/17066262/70b92134-714c-462c-9f56-a5ee9bafafa1)
- however, it should be checked with the linked website whether the short descriptions for each access way are appropriate/correct/complete.

**Comment by ewolf47** [comment]
@AndyDaniel1 @anneweber

Regarding checking the short descriptions of the respective access ways. I'm not really into it technically. So here are a few things that I have noticed. Any changes to the wording should finally be formulated by you, so I can change it in the code:

**CUF: Download**
So far it says "nur für Lehrzwecke". However, the linked list also includes seminar papers, term papers, Bachelor's/Master's theses, dissertations/habilitations and scientific articles in specialist journals/research projects. My suggestion: Perhaps it should be reworded like this: "nur für Lehr- und Forschungszwecke"
Under "Statistische Maßnahmen", "sehr hoch" is mentioned in the linked list. In comparison, _SUF: Download_ is only classified as "hoch". However, the info window currently lists "stärkerer statistischer Anonymisierungsgrad" for both access ways. My suggestion: For _CUF: Download_ "sehr hoher statistischer Anonymisierungsgrad" and for _SUF: Download_ "hoher statistischer Anonymisierungsgrad".

**SUF: Download**
So far, the info window does not list the purposes for which the data may be used. The linked list is identical to the _CUF: Download_ list except for "Wissenschaftliche Lehre und Übungszwecke". I don't know whether this is relevant at all, or whether this information has been deliberately omitted. My suggestion would be to add the following sentence to the info window: "nur für Forschungszwecke"

**SUF: Remote desktop**
analogous to SUF-Download

**SUF: On-Site**
analogous to SUF-Download

**Comment by AndyDaniel1** [comment]
Kudos for thinking about the content here too! You have identified some important points here we missed! 

**CUF: Download**
Theses are regarded as teaching purposes, thus the purpose is correct for this. BUT we should remove dissertations/habilitations and scientific articles in specialist journals/research projects from the list.

_Good suggestion:_
> For CUF: Download "sehr hoher statistischer Anonymisierungsgrad" and for SUF: Download "hoher statistischer Anonymisierungsgrad". 

**SUF-Remote**
Here it is vice versa compared to the CUF. The list should exclude bachelor theses and keep master theses (is also correct for CUF) dissertations/habilitations and scientific articles in specialist journals/research projects. 

The current hint on the purposes should be completely removed here, as it could be that the the purposes are board. Instead we should include a hint on the respective field implemented in #3275 . en "Please check the info on the approved uses on the data package detail page" de "Bitte prüfen Sie die erlaubten Nutzungszwecke auf der Datenpaketdetailseite"

**SUF: On-Site**
analogous to SUF-Download


**_Again! Thank you for the very good remarks!_**

**Comment by AndyDaniel1** [comment]
@ewolf47

**Comment by ewolf47** [comment]
@AndyDaniel1 
> BUT we should remove dissertations/habilitations and scientific articles in specialist journals/research projects from the list.

Do I understand correctly that we should edit the list on "https://www.fdz.dzhw.eu/de/datennutzung"? If so, should the following items be removed? (should @UteH decide on that?)
![Image](https://github.com/dzhw/metadatamanagement/assets/118182853/82145dc6-5648-4a26-a969-c28d082554fe)


For the changes in the info modal on the MDM page, I have adapted the text as follows:


![Image](https://github.com/dzhw/metadatamanagement/assets/118182853/63a4a958-eba4-4483-85e0-4338836ab080)

**Comment by AndyDaniel1** [comment]
@ewolf47 no we have to discuss this further. I will come back to this issue next week

**Comment by anneweber** [comment]
@AndyDaniel1 (@UteH ) Hier mein Vorschlag:

![image](https://github.com/dzhw/metadatamanagement/assets/17066262/ec479e3d-4aa3-471e-8b0d-f4deea1c1bac)

**Comment by AndyDaniel1** [comment]
@anneweber sehr gut, passt für mich so. Danke!

**Comment by anneweber** [comment]
## Deutsch

Für unsere Datenpakete gibt es bis zu vier Zugangswege:

- **CUF: Download** erstellt für die wissenschaftliche Lehre und Übungszwecke; sehr hoher statistischer Anonymisierungsgrad; nach Antragsbewilligung verfügbar per Download
- **SUF: Download** erstellt für wissenschaftliche Forschungszwecke; hoher statistischer Anonymisierungsgrad; nach Vertragsabschluss verfügbar per Download
- **SUF: Remote-Desktop** erstellt für wissenschaftliche Forschungszwecke; moderater statistischer Anonymisierungsgrad; nach Vertragsabschluss verfügbar per Internet über virtuellen Desktop mit technischen Kontrollen
- **SUF: On-Site** erstellt für wissenschaftliche Forschungszwecke; geringer statistischer Anonymisierungsgrad; nach Vertragsabschluss verfügbar vor Ort im FDZ-DZHW in Hannover mit technischen Kontrollen

Mehr Informationen: https://fdz.dzhw.eu/de/datennutzung

## Englisch

There are up to four access ways for our data packages:

- **CUF: Download** created for academic teaching and training purposes; very high statistical anonymization level; available for download after application approval
- **SUF: Download** created for scientific research purposes; high statistical anonymization level; available for download after conclusion of data use agreement
- **SUF: Remote-Desktop** created for scientific research purposes; moderate statistical anonymization level; available via internet using virtual desktop with technical controls after conclusion of data use agreement
- **SUF: On-Site** created for scientific research purposes; low statistical anonymization level; available on site at the FDZ-DZHW in Hanover with technical controls after conclusion of data use agreement

More information: https://fdz.dzhw.eu/en/data-usage

**Comment by AndyDaniel1** [comment]
Thanks for the translation @anneweber . I only had one small modificaiton regarding the checks (see below. 

- **CUF: Download** created for academic teaching and training purposes; very high statistical anonymization level; available for download after application approval
- **SUF: Download** created for scientific research purposes; high statistical anonymization level; available for download after conclusion of data use agreement
- **SUF: Remote-Desktop** created for scientific research purposes; moderate statistical anonymization level; available via internet using virtual desktop with technical ~controls~ **_in/output checks_** after conclusion of data use agreement
- **SUF: On-Site** created for scientific research purposes; low statistical anonymization level; available on site at the FDZ-DZHW in Hanover with ~controls~ **_in/output checks_** after conclusion of data use agreement

**Comment by anneweber** [comment]
## Deutsch

Für unsere Datenpakete gibt es bis zu vier Zugangswege:

- **CUF: Download** erstellt für die wissenschaftliche Lehre und Übungszwecke; sehr hoher statistischer Anonymisierungsgrad; nach Antragsbewilligung verfügbar per Download
- **SUF: Download** erstellt für wissenschaftliche Forschungszwecke; hoher statistischer Anonymisierungsgrad; nach Vertragsabschluss verfügbar per Download
- **SUF: Remote-Desktop** erstellt für wissenschaftliche Forschungszwecke; moderater statistischer Anonymisierungsgrad; nach Vertragsabschluss verfügbar per Internet über virtuellen Desktop mit Input/Output-Prüfungen
- **SUF: On-Site** erstellt für wissenschaftliche Forschungszwecke; geringer statistischer Anonymisierungsgrad; nach Vertragsabschluss verfügbar vor Ort im FDZ-DZHW in Hannover mit Input/Output-Prüfungen

Mehr Informationen: https://fdz.dzhw.eu/de/datennutzung

## Englisch

There are up to four access ways for our data packages:

- **CUF: Download** created for academic teaching and training purposes; very high statistical anonymization level; available for download after application approval
- **SUF: Download** created for scientific research purposes; high statistical anonymization level; available for download after conclusion of data use agreement
- **SUF: Remote-Desktop** created for scientific research purposes; moderate statistical anonymization level; available via internet using virtual desktop with input/output checks after conclusion of data use agreement
- **SUF: On-Site** created for scientific research purposes; low statistical anonymization level; available on site at the FDZ-DZHW in Hanover with input/output checks after conclusion of data use agreement

More information: https://fdz.dzhw.eu/en/data-usage
