### ISSUE TITLE
Propagated DOI-Link seems to be incomplete

### ISSUE THREAD

**Issue by tilovillwock** [dzhw/metadatamanagement#3313]
Ordering a Data Package or Analysis Package currently does not carry over a valid DOI-URL. It's unlikely that the ingestion process in DLP is responsible since the JSON blob is simply written to the database without any processing steps as far as I'm aware of. Maybe the Order API is missing something.

**Acceptance Criteria**
* Ordering a Data Package or Analysis Package correctly propagates the DOI-URL
* the URL is included on the product tab of a data usage application (if it exists)

**Comment by tilovillwock** [comment]
@UteH @AndyDaniel1 we're confused as to how the DOI URL ever worked in DLP in the first place. The attribute is only ever stored in the Elasticsearch index and neither the MDM Order API nor the endpoints for analysis packages and data packages include the DOI attribute in their respective responses because it's simply not stored in the database.

In any case: we've extended the Order API to include it and DLP will render it properly in the application process and management views.

**Comment by UteH** [comment]
testing:

DOI works:

https://stage.fdz.dzhw.eu/en/node/17653#content-products-tab

![grafik](https://github.com/dzhw/metadatamanagement/assets/18573122/e0a235bf-8403-4d47-bb7b-dcbcb1c5c5ea)
