### ISSUE TITLE
LaTex Template issue related to sponsor field

### ISSUE THREAD

**Issue by tilovillwock** [dzhw/metadatamanagement#3314]
A user tried to create a report for their data package and failed multiple times. This seems to be a regression that is related to #3129. We need to investigate if this is due to a missing migration step or if there's a bug with the data package form.

Details from the automated email:

> FillTemplateException(errorListDto=ErrorListDto(errorDtos=[ErrorDto(entity=null, message=data-set-management.error.tex-template-error, invalidValue=The following has evaluated to null or missing:
> ==> sponsor.en  [in template "Main.tex" at line 62, column 105]
> 
> ----
> Tip: It's the step after the last dot that caused this error, not those before it.
> ----
> Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
> ----
> 
> ----
> FTL stack trace ("~" means nesting-related):
> 	- Failed at: ${sponsor.en} auto-escaped  [in template "Main.tex" at line 62, column 103]
> ----, property=null)]))

**Comment by tilovillwock** [comment]
@AndyDaniel1 @DilekIkiz Das Problem wurde behoben.

**Comment by DilekIkiz** [comment]
Prima! Ich werde es gleich mal ausprobieren :)
