### ISSUE TITLE
da|ra registration seems to be broken

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3317]
@DilekIkiz reports that sending metadata to da|ra seems to be broken, maybe it's just a temporary problem. @tilovillwock please check this. 

![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/766935fd-fbb1-454b-859a-163cb16e1a7a)

**Comment by tilovillwock** [comment]
@AndyDaniel1 @DilekIkiz apologies for the inconvenience. As far as I can tell it's not a DARA issue but rather that the application was suddenly unable to open a database connection for some reason. I checked the database status and it's all working fine today. So the only solution I can provide for now is to simply "try again".

**Comment by DilekIkiz** [comment]
@tilovillwock, unfortunately, the problem does not seem to have been resolved.

![Screenshot (587)](https://github.com/dzhw/metadatamanagement/assets/37400886/69add5da-45cf-458a-8e8a-cfaeadad9e27)

**Comment by AndyDaniel1** [comment]
@tilovillwock I just recall, that our credentials for the authentication on the website have been reset last week, I'll write you more details via slack

**Comment by tilovillwock** [comment]
@DilekIkiz We've deployed a fix and everything looks normal. Could you try again? Thanks for your patience!

@AndyDaniel1 This took some doing because one of the terraform modules was broken. Deployment did go through now.

**Comment by DilekIkiz** [comment]
@tilovillwock Unfortunately, I received the same error message again this time. 
![Screenshot (589)](https://github.com/dzhw/metadatamanagement/assets/37400886/c3d59a62-5389-4dc2-a256-49e71f2a9257)

**Comment by tilovillwock** [comment]
@AndyDaniel1 I tested the failing request manually using the new credentials you provided and it's still reporting back that we're making an unauthorized request. Short of the credentials being wrong the only other thing I can see looking through DARA's API documentation is that the account needs to have the role of `publication agent`.

@DilekIkiz We'll report back as soon as we can verify that requests will go through.

**Comment by AndyDaniel1** [comment]
@tilovillwock does the da|ra registration work again? If not, we need a quick solution as deadlines are approaching. If you need any support from our side please inform me

**Comment by AndyDaniel1** [comment]
solved
