### ISSUE TITLE
Add filters for new attributes resulting from #2770 &  #3257

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3330]
The attributes resulting from #2770 &  #3257 should be a filter option in the filter for data packages (see screenshot)

![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/5047862b-e366-428f-bc36-4fe7618ce23f)

**Comment by moellerth** [comment]
@AndyDaniel1 

The filters in the project overview and those in the provider search are currently designed differently. 

In the provider search, a filter is first selected via "Filter für die Datenpaketsuche/Select filters for study search.", whereupon the corresponding filter appears and the required value can then be set. In the project overview, the value is selected directly. 

At the moment, the "Filter for data packages" filter in the project overview is designed for finding data package projects that require the corresponding partial content (surveys, instruments, etc.). In my opinion, the desired filters for "is external data package" and "Transmission via VerbundFDB" do not fall within the search scenario "Does the data package project have the partial content ...?". Should they still be listed as options for this filter or be implemented according to the "Remarks for User Service" filter? As the "remarks" filter seems to be similar to the filters required here, a uniform implementation for the new and the "remarks" filter would be advisable to not confuse users.

**Comment by AndyDaniel1** [comment]
@moellerth Yes you are right it should be implemented according to the Remarks for User Service filter

**Comment by tilovillwock** [comment]
Is completed and awaits review. Will be deployed later today.

**Comment by AndyDaniel1** [comment]
works ✔️
