### ISSUE TITLE
LaTex Report generation failed again

### ISSUE THREAD

**Issue by tilovillwock** [dzhw/metadatamanagement#3338]
Error message:

```
java.lang.RuntimeException: Latex compilation failed: directory 'file [/app/doc]', command 'make'
```

Link: https://metadata.fdz.dzhw.eu/de/data-sets/dat-nac2018-ds1$

@anneweber we're investigating the issue.

**Comment by tilovillwock** [comment]
@anneweber unfortunately we're hitting a memory limit with the report generation process. I assume that the number of variables is the culprit. 

@AndyDaniel1 This is a duplicate of #3326. We're trying to reproduce this problem locally so that we can work on a solution. Unfortunately this will take some time.

**Comment by AndyDaniel1** [comment]
will be further processed in #3326
