### ISSUE TITLE
Upgrade tex based variable report

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#334]
- move to dataset
- extend text template in cooperation with @Andy20 and @bjhuss

**Comment by Andy20** [comment]
### table requirements

**nominal and ordinal variables with <=20 values**
- the table consists of the attributes: Codes (Values); Label; Frequencies; Percent; Valid Percent; sum (valid); sum (total). 
- valid and missing values should be seperated in the backend via the missing attribute ("missing":true/false)
- missing values should be situated below the valid values and seperated by \hline ( see also [example table](metadatamanagement-io/development/excel/2016-04-06_Vorlage_Tabelle_Variablenreport.xlsx) )
- the tables should be in german 


**nominal (and ordinal) variables with >20 values**
- use the table for nomial/ordinal variables as defined above
- if a variable has more than 20 values display only the first _and_ last 10 values and seperate them with one line consiting of three dots (...) (see also [example table, sheet nominal_ordinal_Liste](metadatamanagement-io/development/excel/2016-04-06_Vorlage_Tabelle_Variablenreport.xlsx) )

**metric variables**
- there will be no tables for metric variables.

**Comment by anneweber** [comment]
- please delete the attribute "DataType" from the template
- please correct "Quartil**e**"/"Qu**e**rtil**e**" to "**Quartil**"
- please change the column name "Label" in the table to "Wertelabel"

**Comment by dkatzberg** [comment]
@anneweber Thank you for your proposals. I changed all your wishes in the template.

**Comment by dkatzberg** [comment]
@rreitmann Please, review the report upgrade:
- Tests
- DataSetReportService
- Freemarker Tex Templates in the IO Project

**Comment by bjhuss** [comment]
@dkatzberg: Please change the numbering of figures and tables in the variable report. The numbering should be orientated on the related variable.

You can do so by adding a package and a command:

- [ ] `\usepackage{chngcntr}`
- [ ] `\counterwithin{figure}{subsection}`
- [ ] `\counterwithin{table}{subsection}`
