### ISSUE TITLE
Error message "server is not available" when importing publications

### ISSUE THREAD

**Issue by henrikeschmidtchen** [dzhw/metadatamanagement#3341]

**Comment by henrikeschmidtchen** [comment]
![Anmerkung 2024-04-22 155225](https://github.com/dzhw/metadatamanagement/assets/72195141/760db70d-6d88-4f45-b0ac-9488408ed93e)

When I try to upload the publications to the MDM via Excel list as usual, I get this error message. Even after trying several times, the publications do not load.

**Comment by tilovillwock** [comment]
@henrikeschmidtchen are you confident that this was not a network issue? This error only ever appears if your browser can't reach the backend and the backend had no downtime on Monday. Could you try again and see if it still happens?

If it does could you provide the excel file that you're trying to import. I don't see any related errors in the log around that time.

**Comment by tilovillwock** [comment]
For what it's worth: we did make some changes to the upload recently regarding citation details. Maybe it's a regression of #3249.

**Comment by henrikeschmidtchen** [comment]
I tried again and the error message appears again.
This is excel file I used: [relatedPublications.xlsx](https://github.com/dzhw/metadatamanagement/files/15090260/relatedPublications.xlsx)

(fyi: if the Excel import works for you, it is okay that some publications cannot be imported because information is missing there.)

**Comment by tilovillwock** [comment]
> I tried again (also with another browser) and the error message appears again. This is the excel file I used: [relatedPublications.xlsx](https://github.com/dzhw/metadatamanagement/files/15090260/relatedPublications.xlsx)
We can confirm the bug. Apparently the data we tested #3249 with didn't have this problem.

We're working on a solution.

**Comment by ewolf47** [comment]
@henrikeschmidtchen I have adapted the process. There was a problem retrieving some information via poi.org. I have removed this part from the code for the time being. The latest version has been rolled out in the production system and you can now test  whether the import of publications works again.

**Comment by henrikeschmidtchen** [comment]
@ewolf47 Thank you for fixing the problem so quickly, now it works again.
