### ISSUE TITLE
Add validation of uniqueness of AtomicQuestion.name within one questionnaire

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#344]
- document
- implement

**Comment by dkatzberg** [comment]
@rreitmann Review this new validator, please.

**Comment by rreitmann** [comment]
@anfranken Please test....

**Comment by anfranken** [comment]
@dkatzberg 
If I change the AQ.auto-foreign.name (io-project auto) == 1
I get	followingerror message:
{ "serverUsed" : "ds051334.mlab.com:51334" , "ok" : 1 , "n" : 0 , "err" : "E11000 duplicate key error index: CloudFoundry_lgqla64e_80apdeqm.atomic-questions.$name_1_questionnaireId_1 dup key: { : \"1\", : \"auto-qu1\" }" , "code" : 11000}; nested exception is com.mongodb.MongoException$DuplicateKey: { "serverUsed" : "ds051334.mlab.com:51334" , "ok" : 1 , "n" : 0 , "err" : "E11000 duplicate key error index: CloudFoundry_lgqla64e_80apdeqm.atomic-questions.$name_1_questionnaireId_1 dup key: { : \"1\", : \"auto-qu1\" }" , "code" : 11000}

**Comment by dkatzberg** [comment]
The reason is the definition of the compound index for atomicquestions:
`@CompoundIndex(def = "{name: 1, questionnaireId: 1}", unique = true)`
The name is unique. If you try to save the same name of two different questions in one save operation, you get the message from the mongo db.
