### ISSUE TITLE
Validation Changes

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#346]
These fields should be no longer mandatory:
* Variable.label
* ~~Variable.GenerationDetails.RuleExpression~~
* ~~Variable.GenerationDetails.RuleExpressionLanguage~~
* ~~Variable.FilterDetails.FilterExpression~~
* ~~Variable.FilterDetails.FilterExpressionLanguage~~

**Comment by rreitmann** [comment]
A few remarks:
- Variable.label is currently used for variable search and displayed in list dialogs
- The objects Variable.GenerationDetails and Variable.FilterDetails are not mandatory, this is currently a bug in the client

**Comment by rreitmann** [comment]
One label (Variable.label.de or Variable.label.en) must be present, this should be coded for all I18nStrings.

**Comment by anfranken** [comment]
- Variable.Value.ValueClass should not overlap
- Variable.Value.Code should be unique in a variable
- Variable.Value.ValueClass/isAMissing: a value with a valueclass can't be a missing (isAMissing == false) but a variable with valueclasses can have missingcodes

**Comment by anfranken** [comment]
- atomicQuestion.variableId = atomicQuestion.Id and must be mandatory

**Comment by anfranken** [comment]
- atomicQuestion.variableId = atomicQuestion.Id and must be mandatory
- atomicQuestion.QuestionnaireId: Mandatory
- dataSet.VariableIds: Min Size 1
- dataSet.SurveyIds: Min Size 1
- variable.DataSetIds: Min Size 1
- variable.SurveyId: Min Size 1 (there is a mistake in our domain model, id can have more than one survey)
- survey.DataSetIds: Min Size 1

**Comment by rreitmann** [comment]
Just a remark:
Implement and document in wiki and excel interfaces if necessary

**Comment by anfranken** [comment]
variable.scaleLevel is mandatory at the moment: but this is only true if the variable.dataType is numeric

**Comment by rreitmann** [comment]
@dkatzberg Please review and fix the following tests:
- eu.dzhw.fdz.metadatamanagement.filemanagement.rest.FileResourceTest.testValidUpload()
- eu.dzhw.fdz.metadatamanagement.datasetmanagement.rest.DataSetsReportResourceTest.testValidUpload()

**Comment by dkatzberg** [comment]
@anfranken Test the new validators, please.

**Comment by anfranken** [comment]
- the validation for variable.value.class will not be tested because we don't need it anymore
- validation variable.scaleLevel (numeric = madatory, string = must be empty) seems not to work. If you upload a variable with variable.dataType = string and variable.scaleLevel = empty you get an error message that no scaleLevel is set. And if you upload a variable with variable.dataType = string and any variable.scaleLevel it works fine.

**Comment by anfranken** [comment]
if you upload a variable  with variable.dataType = string you got the error message: "Variable with RDC-ID xxx has not been saved!". I think there is still a problem with the validation between dataType and scaleLevel.
