### ISSUE TITLE
Post-Validation for domain objects

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#347]
The post-validation should be started by an user after all data is uploaded. The post-validation should validate all relations and the consistence between domain objects.

The first post validation should check the lists DataSet.variablesIds and Variable.dataSetIds. On the one hand we use the VariableRepository to load all variables by a given DataSetId for the latex template, because this is only a call to the MongoDB. On the other hand we use the list DataSet.variablesIds for the latex template. A consistence is important for a correct variable report between these two lists.

**Comment by anfranken** [comment]
post validation for ids:
- survey
 - survey.VariableIds: there must be a variable with that id
 - survey.QuestionnaireId:  there must be a questionaire with that id
 - survey.DataSetId:  there must be a dataset with that id
- dataSet
 - dataSet.SurveyIds:  there must be a survey with that id
 - dataSet.VariableIds:  there must be a variable with that id
- variable
 - variable.SurveyId:  there must be a survey with that id
 - variable.DataSetIds:  there must be a dataset with that id
 - variable.SameVariablesInPanel:  there must be a variable with that id
- atomicQuestion
 - atomicQuestion.VariableId:  there must be a variable with that id
 - atomicQuestion.QuestionnaireId:  there must be a questionaire with that id

**Comment by dkatzberg** [comment]
What is with the project id?

**Comment by anfranken** [comment]
@dkatzberg I think we don't need a post validation for the project id, because you validate it at the creating of the project

**Comment by dkatzberg** [comment]
survey.VariableIds: there must be a variable with that id

**Comment by dkatzberg** [comment]
@rreitmann Please, review this issue.

**Comment by rreitmann** [comment]
@dkatzberg please change the following items:
- [ ] change validation of sameVariablesInPanel
- [ ] document post validation in wiki
- [ ] change method names (backend) to imperatives 
- [ ] discuss validation of variable.atomicQuestionId with @anfranken

**Comment by dkatzberg** [comment]
@rreitmann We discussed that the given rule is wrong. We changed the specification of validation of variable.atomicQuestionId the to the actual implementation.

**Comment by rreitmann** [comment]
@dkatzberg The error message for sameVariablesInPanel does currently not display the missing id....
