### ISSUE TITLE
Highlight query in variable search results

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#36]
As public user I want to see where my search query matches the result,...

**Comment by rreitmann** [comment]
Use hihlighting only in fields name, label, question, survey title.

**Comment by rreitmann** [comment]
We are currently using ngrams for partial word matching. This leads to strange highlighting results:
https://metadatamanagement.cfapps.io/de/variables/search?query=allbus+staat&_surveyTitle=on&surveyPeriod.startDate=&surveyPeriod.endDate=&_scaleLevel=on&_scaleLevel=on

This query ("allbus staat") highlights "alle".

**Comment by rreitmann** [comment]
The following query does currently not highlight the partial match "schaft":
https://metadatamanagement.cfapps.io/de/variables/search?query=schaft&_surveyTitle=on&surveyPeriod.startDate=&surveyPeriod.endDate=&_scaleLevel=on

**Comment by rreitmann** [comment]
@anfranken Please test the highlighting of search results.

**Comment by anfranken** [comment]
@rreitmann: don't understand why some objects are highlighted 
![high_staat](https://cloud.githubusercontent.com/assets/13656277/10216632/c9610fa6-682a-11e5-953f-5a1b63c557c5.png)
![high_sem](https://cloud.githubusercontent.com/assets/13656277/10216633/cc6bd91a-682a-11e5-8595-8a579cfb3115.png)
![high_person](https://cloud.githubusercontent.com/assets/13656277/10216669/1548afe6-682b-11e5-930a-def0b66faa89.png)

**Comment by rreitmann** [comment]
The examples by @anfranken  illustrate the problems with highlighting using ngrams.
