### ISSUE TITLE
Add required attributes (for variable report) to variable

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#360]

**Comment by anfranken** [comment]
- variable.value needs a new attribute validRelativeFrequency: Double
- for variable.value.*Frequency we need total values

**Comment by rreitmann** [comment]
- variable.value.validRelativeFrequency (Double) will be added to domain model and value.json
- variable will get a new subobject valueSummary with attributes totalAbsoluteFrequency (Integer), totalValidAbsoluteFrequency (Integer), totalRelativeFrequency (Double), totalValidRelativeFrequency (Double)
- all mentioned fields are mandatory

we need to adjust variables.xlsx, value.json and documentation...

**Comment by rreitmann** [comment]
ValueSummary is mandatory if there is at least one Value....

**Comment by anfranken** [comment]
@rreitmann totalRelativeFrequency is not needed becaus it's always 100 %

**Comment by rreitmann** [comment]
@anfranken I have removed totalRelativeFrequency from domain model and variables.xlsx

**Comment by rreitmann** [comment]
@anfranken Please test this issue
