### ISSUE TITLE
Split import files of variable import in manually and automatically generated files

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#368]
- document in wiki
- refactor file generation
- change client only

**Comment by anfranken** [comment]
- manually

- automatically 
 - variable.distribution
 - variable.dataType
 - variable.scaleLevel
 - variable.name
 - variable.label.en
 - variable.label.de

**Comment by rreitmann** [comment]
After a discussion with @anfranken we change only the variable import within this issue. Data sets will be changed within #465. Surveys and Questions will follow...

**Comment by rreitmann** [comment]
Changes have been documented here:
https://github.com/dzhw/metadatamanagement/wiki/Interfaces#variable-import
