### ISSUE TITLE
Validate file structure of variable zip import file

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#375]
Check the json file names within the sub folder "values" of a variable zip import file.

The problem:
The values are not mandatory, so if the file name is wrong, there is no validation for missing values of variables.

The solution:
Extract the variable name from the file name of the json value files. If there is no valid variable to a value json file, throw an exception.

**Comment by rreitmann** [comment]
In addition to the case mentioned by @dkatzberg we need to validate that there is exactly one variables.xlsx file in the zip.

**Comment by rreitmann** [comment]
@anfranken Please test this. We do now validate that there is a /variables directory and a variables.xlsx
