### ISSUE TITLE
Implement distribution object for variables

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#378]
For proper generation of histograms and other statistical data we need to refactor the variable object and introduce a distribution object as shown here:
https://github.com/dzhw/metadatamanagement/wiki/Domain-Model#overview

The following tasks have to be done:
- change interface description in wiki
  - distributions instead of values
  - move statistics from xlsx to json
- change java domain model
- change variables parser in client
- adjust validation
  - response.value must be a number for metric variables
  - distribution.total* are mandatory
  - further validations need to be discussed and **documented**

**Comment by dkatzberg** [comment]
@anfranken All actual noted validators are implemented. We have to discuss further validators for this issue.
@anfranken We need new test data.

**Comment by rreitmann** [comment]
@anfranken I guess you have already imported variables with the new structure, but please check it nevertheless.

**Comment by anfranken** [comment]
@rreitmann at the moment you don't get any variables.tex if you generate a variable report

**Comment by rreitmann** [comment]
@anfranken dataSets.xlsx of abs2005 does not contain any variable ids thats why the report does not show any. Let me know if you find further issues....
