### ISSUE TITLE
Upgrade jszip to 3.0.0 (bower.json)

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#385]
Upgrade jszip from 2.6.0 to 3.0.0 (bower.json)

**Comment by dkatzberg** [comment]
@limouri There is a problem with js-xlxs and the new jszip 3.0.0 version.

**Comment by limouri** [comment]
[https://github.com/SheetJS/js-xlsx/issues/408](url)

**Comment by limouri** [comment]
SheetJS/js-xlsx#408

**Comment by rreitmann** [comment]
We can't upgrade jszip cause they have changed parsing the zip from synchronous to asynchonous (promise based) processing. js-xlsx does depend on the synchronous behavior as well as we do.
