### ISSUE TITLE
Implement cross references within dataset report

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#387]
set latex labels for
- sections
- boxplot and histogram
- value table

**Comment by dkatzberg** [comment]
The added lables:

\label{subSection:${variable.name}}
\label{tableVariable:${variable.name}}
\label{tableQuestion:${variable.name}}
\label{tableStatistics:${variable.name}}
\label{tableValues:${variable.name}}
\label{boxPlot:${variable.name}}

**Comment by dkatzberg** [comment]
Added the lables and cross references to the wiki.

https://github.com/dzhw/metadatamanagement/wiki/Tex-Template
