### ISSUE TITLE
Rename attributes of variable.filterDetails

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#393]
- variable.filterDetails.filterExpression -> variable.filterDetails.expression
- variable.filterDetails.filterDescription -> variable.filterDetails.description
- variable.filterDetails.filterExpressionLanguage -> variable.filterDetails.expressionLanguage

**Comment by rreitmann** [comment]
Don't forget to document the changes in wiki (interfaces, validation, picture).
