### ISSUE TITLE
Fix redirect and load bug

### ISSUE THREAD

**Issue by limouri** [dzhw/metadatamanagement#396]
- by given an invalid project id in the url, the state shold be redirected to the error page
- resolve the promise issue while loading the project details page

**Comment by dkatzberg** [comment]
@limouri should be redirected to error page, if you type manually a wrong url.

**Comment by dkatzberg** [comment]
@anfranken You can test this issue only at the project details page and one step before. Please test this issue. If you have some question, you should ask @limouri.

**Comment by rreitmann** [comment]
@anfranken Please test that you are redirected for all missing domain objects. For example: https://metadatamanagement.cfapps.io/#/de/variables/hurz
