### ISSUE TITLE
Redirect and load bug in the client application

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#403]
Not every invalid url redirectes to the error page. This behavior is fixed for the project details page within this issue #396 . This local fix should not be repeated/copied for every state/valid page like survey details, datasets and so on. This needs a fix for the whole client application.
An another problem is, that the most pages/states have a different behavior, if a invalid url is called by an user. This should be done by a fix, which works for the whole client application.

**Comment by rreitmann** [comment]
Not relevant anymore.
