### ISSUE TITLE
Defintion of data products (AIP, DIP)

### ISSUE THREAD

**Issue by Andy20** [dzhw/metadatamanagement#409]
We have to define the characteristics of the master data (**A**rchival **I**nformation **P**ackage) and the delivered data (**D**issemination **I**nformation **P**ackages) which are a subsets of the AIP.

The charcteristics of the data can be devided into two broad categories: 
- datasets
- documentation 

I already drafted a [short definition in german](https://github.com/dzhw/metadatamanagement-io/blob/master/OAIS/OAIS_Def.docx) a few weeks ago (translation upcoming).

**Comment by Andy20** [comment]
Due to liabilities associtated with data documentation and data managment I will not be able to work on this issue until the end of may. Nevertheless I thought it might be helpful to put it on the record ;-) .

**Comment by anfranken** [comment]
for a better understanding of AIP and DIP: https://en.wikipedia.org/wiki/Open_Archival_Information_System

**Comment by Andy20** [comment]
thanks for the reference. Just for clearification: we don't need to implement the OAIS in its broad complexity. Rather we have find a very practical defintion that is closely oriented toward our metadatasystem. I already drafted a rough definition (currently only in german). You can find it [here](https://github.com/dzhw/metadatamanagement-io/blob/master/OAIS/OAIS_Def.docx)

**Comment by rreitmann** [comment]
IMHO, this should be covered within #519

**Comment by rreitmann** [comment]
@Andy Has this been covered within #519?

**Comment by Andy20** [comment]
For now we can close this issue. Due to the fact that we will not implement a role-concept in the near future all variables (if accessible or not) will be searchable. The variables which are not accessible are flaged with _a in the variablename/ID. For this variables the access-way-attribute should be "not accessible".
