### ISSUE TITLE
Create conceptual data package page

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#411]
Create a conceptual data package page. 

* This page should be visitable by variable details pages
* This page has a download link to a variable report pdf
* Visitable by main page
* TODO design by @kpstephan

**Comment by rreitmann** [comment]
![img_1733](https://cloud.githubusercontent.com/assets/12323832/14982873/ddf14964-1139-11e6-96a1-25961eb13f31.JPG)

**Comment by rreitmann** [comment]
@anfranken Please test the page especially on IE and Firefox...

**Comment by anfranken** [comment]
with the IE, we have some problems with the design
![see here](https://cloud.githubusercontent.com/assets/13656277/15817766/e6af48ac-2bd9-11e6-80db-4b89e130b199.png)

**Comment by rreitmann** [comment]
@anfranken Please retest
