### ISSUE TITLE
update tables for metric variables in the TeX-file

### ISSUE THREAD

**Issue by Andy20** [dzhw/metadatamanagement#422]
The following demands should be fulfilled for metric tables: 

- [x] there should be a table for metric variables with reduced informations in the valid section and full information in the missing section.
- [x] for the valid cases the table should onyl include the total number of cases
- [x] for the missing cases the table should include the differentiated missing codes with corresponding case numbers
- [x] the bottom line of the table should include the total number of cases (valid and missing) 
- [x] the table should include a cloumn with percentages (including all cases)

 _see also_ [example table, sheet Tabellen Layout_Metrische Variablen](https://github.com/dzhw/metadatamanagement-io/blob/aaa238105671ac21e08b73722938a16ed2cbf0e2/development/excel/2016-04-07_Inhalte_Variablenreport.xlsx)

**Comment by rreitmann** [comment]
@Andy20 Please verify the table for metric variables...

**Comment by Andy20** [comment]
good job!!
