### ISSUE TITLE
Reading Aid

### ISSUE THREAD

**Issue by Sarcletti** [dzhw/metadatamanagement#425]
Especially for (younger) researchers not no familiar with variable documentations, it would be useful to have a reading aid: for an example see:
https://www.neps-data.de/Portals/0/NEPS/Datenzentrum/Forschungsdaten/SC5/6-0-0/SC5_6-0-0_Codebook_en.pdf (page 5 of the pdf, page 1 of the document)
As some of the contents depend on the scale level, perhaps more than one reading aid would be useful.

**Comment by Andy20** [comment]
Thanks for this comment :-) . @anneweber has already put this proposal on our agenda and it will be implemented.

**Comment by rreitmann** [comment]
@Andy20 Is this still relevant for our system or can we close this issue?

**Comment by Andy20** [comment]
This highly relevant and was one of our core-ideas to get a userfriendly report. IMHO this should be implemented soon.

**Comment by rreitmann** [comment]
But do we need to implement anything for this, or can you simply provide a customized template which contains a reading aid?

**Comment by Andy20** [comment]
No, you don't have to implement anything. It's just a template that will be provied by one member of the Sowi-Team. @kpstephan has to decide weather or not it should to be part of the next version of the var.report.

**Comment by kpstephan** [comment]
I will insert a reading aid into the dataset report
