### ISSUE TITLE
Add FDZ logo to navbar

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#44]

**Comment by rreitmann** [comment]
@anfranken Please test the FDZ Logo

**Comment by anfranken** [comment]
@dkatzberg Layout problem IE: min width 280
![Screnshot](https://cloud.githubusercontent.com/assets/13656277/10012552/4e3c15a0-6109-11e5-95ce-3a5b66ef0ab3.png)

**Comment by anfranken** [comment]
:thumbsup:
