### ISSUE TITLE
Add frequency distributions to variables

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#45]
As public user I want to see freequency distributions of variables.

**Comment by dkatzberg** [comment]
We will use: http://krispo.github.io/angular-nvd3/#/

**Comment by rreitmann** [comment]
@anfranken Please test the variable charts...

**Comment by anfranken** [comment]
@dkatzberg: upper frequency distributions is crashed after minimization (IE) ![frequencydistributions](https://cloud.githubusercontent.com/assets/13656277/13595546/8d6b7b94-e50c-11e5-80f0-603b1dab3b75.png)

**Comment by dkatzberg** [comment]
The design has no priority. The issue is given by a wrong use of the bootstrap coloumn with two diagramms. This will be fixed by a redesign of the page.
