### ISSUE TITLE
Change layout of variable report

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#451]
A few remarks:
- histogram
  - [x] change the colour of the histogram to the DZHW design
- Frequencies table: 
 - ~~the listing of the values should start at the first line of the table~~
 - [x] and if you have a continuous variable with less than 10 values please show a frequencies table like for ordinal or nominal variables and no graphics any more 
- boxplot
 - [x] maybe we can put the boxplot beside the statistical parameters
- line break
 - [x] information of the question or the description will become very long. Therefor it would be great if you can write over more than one line
- decimal separator
 - [x] I think it would look better if there will be only a decimal separator and no separator between thousand
- new order for  statistical parameters 
 - [x] 1. Arithmetisches Mittel, 2. Standardabweichung, 3. Minimum, 4. Unteres Quartil, 5. Median, 6. Oberes Quartil, 7. Maximum, 8. Schiefe, 9. Wölbung
- show more statistical parameters for ordinal variables
 - [x] Minimum, Unteres Quartil, Median,  Oberes Quartil,  Maximum

**Comment by dkatzberg** [comment]
@anfranken @Andy20 Specifiy in more details:

>'and if you have a continuous variable with less than 10 values please show a frequencies table like for ordinal or nominal variables and no graphics any more' 

Open question:
How should the table look like? Which data should be presented? Should the value table filled with more details?

**Comment by rreitmann** [comment]
@anfranken or @Andy20 Please have a look on the report...
