### ISSUE TITLE
Implement new variable.dataType: date

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#458]
Some variables contain dates which we need to import as well and display in the report as well as in the client.

**Comment by rreitmann** [comment]
[ ] validate if dataType date that validResponse.value is a date according to iso
[ ] change validation of ValidResponseValueMustBeANumberOnContinuousScaleLevelValidator (should validate numeric dataTypes)
[ ] adjust documentation
[ ] don't forget unit test

**Comment by rreitmann** [comment]
@dkatzberg Please move validators to distribution.validResponses

**Comment by dkatzberg** [comment]
@rreitmann This is not possible. The validators need the dataType field from the variable. They have to be at the variable.

**Comment by rreitmann** [comment]
@anfranken Please test the new dataType

**Comment by anfranken** [comment]
At the moment there seems to be an validation problem with the scale level

**Comment by anfranken** [comment]
I tested it with one example variable. I think we have to do define and implement more validation for that type (see #610).
