### ISSUE TITLE
How do we handle string variables in the variable report?

### ISSUE THREAD

**Issue by Andy20** [dzhw/metadatamanagement#469]
Should we display valid responses for string variables? We need a table for the string variables due to the fact that they also contain nummerical values for the missing values.

**Comment by rreitmann** [comment]
Currently there is no special treatment for dataType=string. Just import the variable with scaleLevel=nominal and it should be displayed in the report...

**Comment by rreitmann** [comment]
@Andy20 Is this still an issue or can we close it?

**Comment by Andy20** [comment]
Due to the fact that string variables will usually be subject to measures of anonymization this is currently not a problem but I'm not sure if this is still an issue for future purposes. @anfranken what do you think?

**Comment by rreitmann** [comment]
@anfranken Please answer @Andy20's question

**Comment by anfranken** [comment]
If a distribution can be shown or not will be a decision of a researcher at any time. So i think it's a better process that the researcher will decide if he will import a variable with or without a distribution.
