### ISSUE TITLE
Remove session timeout

### ISSUE THREAD

**Issue by limouri** [dzhw/metadatamanagement#470]
Currently we have session timeouts from time to time even though the user interacts with the server. Since no one asked for session timeouts we remove them for the moment.

**Comment by rreitmann** [comment]
@anfranken Please check if the evil timeout is gone ;-)

**Comment by anfranken** [comment]
at the moment there is still a session timeout

**Comment by rreitmann** [comment]
@anfranken Please check if it's finally gone
