### ISSUE TITLE
Reimplement Navbar with Angular-Material

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#473]
Reimplement Navbar with Angular-Material

**Comment by dkatzberg** [comment]
@anfranken Please test the new navbar and toolbar.

**Comment by anfranken** [comment]
Navbar is looking strange at the FF 
![navbar FF](https://cloud.githubusercontent.com/assets/13656277/16196756/965756ca-36ff-11e6-9861-9f38a10b5074.png)

**Comment by rreitmann** [comment]
@anfranken Firefox issue should be fixed, please retest in all browers.
