### ISSUE TITLE
LaTex error sb2008

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#489]
If you compiling the sb2008 data you get this error: TeX capacity exceeded, sorry [main memory size=3000000]. };

**Comment by dkatzberg** [comment]
Replace in Main.tex file the line:
`\usepackage[utf8]{inputenc}`
with
`\usepackage[utf8]{luainputenc}`
and compile the file with LuaLatex. That works. LuaLatex has a dynamic main memory size.
