### ISSUE TITLE
Define attributes visible on search result cards

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#516]

**Comment by anfranken** [comment]
Variable
- heading: 
 - variable.label 
 - (variable.name)
- body:
 - variable.type
 - variable.scaleLevel
 - variable.dataSet[*].name (#519)
 - variable.survey[*].title
 - variable.concept[*].name ???

**Comment by anfranken** [comment]
Question:
- heading
 - question.id
 - question.number
- body
 - question.questionText
 - question.type
 - question.questionaire.name (#520)

**Comment by anfranken** [comment]
data set:
- heading:
 - 
- body:
 -

**Comment by anfranken** [comment]
survey:
- heading:
 - 
- body:
 -
