### ISSUE TITLE
Model new attributes for dataset

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#519]
- name

**Comment by anfranken** [comment]
Linked physical data sets

**Comment by rreitmann** [comment]
We need to model the concrete data set types (see #380 as well). Each concrete data set must have the following attributes:
- Number of Variables
- Number of Observations
- Number of real variables (without anonymization for instance)
- name
- access way

**Comment by rreitmann** [comment]
Data set must have the following additional attributes:
- name
- type
- Number of Observations
- Number of Variables

**Comment by rreitmann** [comment]
- extend domain model
- document validation
- extend import interface description

**Comment by anfranken** [comment]
We want to change at interfaces and documnetation later (see #605).
