### ISSUE TITLE
Implement Buttons in Navbar (New Project and Delete Project)

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#526]
Implement Buttons in Navbar (New Project and Delete Project):

- [x] Implement Add Project Button 
   - [x] With Dialog
   - [x] Added new Project to Autocomplete
- [x] Load all Project not just page 1
- [x] i18n of String in Navbar
- [x] Tooltips for Buttons
- [x] Implement Delete Project 
   - [x] With Dialog
   - [x] With User Messages
   - [x] Removed deleted Project from Autocomplete
   - [x] Deleted Element is no longer choosen, after deletion.

**Comment by dkatzberg** [comment]
- [ ] Refactor Buttons in Navbar
 - [ ] Built a directive for the buttons

**Comment by rreitmann** [comment]
@anfranken Wait until #549 is ready...

**Comment by limouri** [comment]
md-tooltip doesn't work on firefox

**Comment by limouri** [comment]
Urls are not bookmarkable. Search url should have a project id parameter for a specific search within a specific project.

**Comment by dkatzberg** [comment]
@anfranken Please test in all browsers...
