### ISSUE TITLE
Design future dialogs

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#538]

**Comment by anfranken** [comment]
as a small inspiration:
-   [ddionrails](http://www.ddionrails.org/)
-  [Data cite](https://search.datacite.org/)
-  [Uk data service](http://www.data-archive.ac.uk/find) 
-  [ICPSR](https://www.icpsr.umich.edu/icpsrweb/ICPSR/studies?q=income&searchSource=icpsr-landing)
-  [ODESI](http://search1.odesi.ca/#/)
-  [ISHN](http://catalog.ihsn.org/index.php/catalog)
-  [DataONE](https://www.dataone.org/)
-  [IPUMS](https://international.ipums.org/international/)
-  [CESSDA](http://cessda.net/Data-Catalogue)
-  [Réseau Quetelet](http://www.reseau-quetelet.cnrs.fr/spip/)
- [gesis](https://dbk.gesis.org/dbksearch/index.asp?db=dl)

**Comment by anfranken** [comment]
Variable detail page:
- Label (name)
- variable informations
  	- typ
	- scale level
	- statistics
	- generation rules (fold-out )
	- access ways
- maybe ???
        - atomic question test
	- filter rules 
- distribution informations:
	- charts
	- frequency table  (fold-out )
- linkes elements:
	- project/studie
	- data sets
	- surveys
	- questions
	- linkes variables
	- concepts

**Comment by anfranken** [comment]
Question detail page:
- question information
 - question text
 - number 
 - introduction
 - instruction
 - type
- picture
- linked elements: 
 - project
 - questionaire
 - other questions (precursor/successor)
 - variables

**Comment by anfranken** [comment]
data set detail page:
-

**Comment by anfranken** [comment]
questionaire detail page:
-

**Comment by anfranken** [comment]
study detail page:

**Comment by rreitmann** [comment]
see https://github.com/dzhw/metadatamanagement/wiki/Design-Vision
