### ISSUE TITLE
Refactor Alerts for Toast Compability

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#539]
Alerts are used actually, but we startet to using toast from angular-material. 
- [ ] Remove Alert Directive
- [ ] Refactor Alert Controller for Toast Compability
- [ ] Remove unused Code from Alert files.
- [ ] Refactor all Alert Calls for Using Toast/Refactor Alert controller

**Comment by rreitmann** [comment]
duplicates #867
