### ISSUE TITLE
Variable search card layout problem

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#546]
there is an layout problem, if you reduce the size of the IE window (#535):
![search card ie](https://cloud.githubusercontent.com/assets/13656277/16839427/47fc52ea-49cf-11e6-9fd8-5b21fb4de941.png)

**Comment by rreitmann** [comment]
@limouri Please remove truncate string class from question result..

**Comment by rreitmann** [comment]
@anfranken Please test in all browsers...

**Comment by dkatzberg** [comment]
@anfranken please test in all browsers again.
