### ISSUE TITLE
JobLogging should have no dependency of translate

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#549]
Remove and rewrite alle translate dependencies of JobLoogingSerivce

**Comment by dkatzberg** [comment]
@rreitmann @limouri 

Last issue within this issue ;)

For reproducing:
1.) Choose a project
2.) Start post validation
3.) Have a look into the log
You see Strings like "Variable 0 has a relation to the unknown surveyid (1)"

0 and 1 are replace variables within the json and given by a jsonfied string:
Take a look here: 
https://github.com/dzhw/metadatamanagement/blob/850acc7e364bf4ef54683bb063ae5c4c7b2dc83b/src/main/webapp/scripts/dataacquisitionprojectmanagement/services/postValidation.service.js#L35-L37

**Comment by anfranken** [comment]
No tranlation:
![translationerrordelete](https://cloud.githubusercontent.com/assets/13656277/17553011/b485d8c0-5f03-11e6-85b7-c8bba25cc5a2.png)
- Message if you want to delete all data at the beginning of the upload 
 - search.deleteMessages.deleteVariablesTitle
 - search.deleteMessages.deleteVariables
![translationerrorjoblog](https://cloud.githubusercontent.com/assets/13656277/17553021/c01c26f8-5f03-11e6-88bb-e9a1a9823f77.png)
- Log-message 
 - dataAcquisitionProject.detail.logMessages.variable.notSaved
