### ISSUE TITLE
Rename domain object bibliographical reference to citation

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#569]
There will be #566 and #567 instead...

**Comment by rreitmann** [comment]
- remove from code
- remove from domain model
- remove from documentation

**Comment by rreitmann** [comment]
- rename in code and domain model
- define import interface
- define and implement (backend-only) new attributes

**Comment by dkatzberg** [comment]
@limouri If you're done, just remove the review flag.

**Comment by anfranken** [comment]
Our first idea to use an excelexport from citavi doesn’t work, because there must be a mapping from the ciatvi field to the bibtex fields.

**Comment by anfranken** [comment]
Now we will export a BibTex-file from Citavi an will parse this to a JSON-document. After this we will import this JSON
