### ISSUE TITLE
Question Detail Page

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#578]
- [x] Implement the design vision of the Question Detail Page ( https://github.com/dzhw/metadatamanagement/wiki/Design-Vision#question-details )

**Comment by dkatzberg** [comment]
The field Question.title does not exist. The header line should be 
`Question {{instrument.title}} {{question.number}}`
The instrument does not exist actually, so it has to be temporary
`Question TODO:instrument.title {{question.number}}`

**Comment by dkatzberg** [comment]
@limouri 
- [ ] Add comments, please.
- [ ] Translate all Strings
- [ ] Diasable Instrument, Study, Notepad Button (just an error, no function at the moment)

**Comment by dkatzberg** [comment]
@anfranken Test the details page in different browsers, please.

**Comment by limouri** [comment]
CSS global changes should be combined in style classes

**Comment by anfranken** [comment]
The basic implementation of the design vision is alright. In furture we maybe can redesign some parts (e.g. #642).
