### ISSUE TITLE
Add DZHW logo to welcome page

### ISSUE THREAD

**Issue by kpstephan** [dzhw/metadatamanagement#60]

**Comment by rreitmann** [comment]
@anfranken Please test the dzhw logo

**Comment by anfranken** [comment]
@rreitmann @dkatzberg  
Firefox  (layout problem):  if you reduce the window size  
![dzwhlogo_smallwindow](https://cloud.githubusercontent.com/assets/13656277/10077962/fe046ac0-62e2-11e5-8d2b-2815b5d642f7.png)

**Comment by anfranken** [comment]
@rreitmann @dkatzberg 
Internet explorer (layout problem) ??
![dzwhlogo_ie](https://cloud.githubusercontent.com/assets/13656277/10078514/589d0116-62e5-11e5-9276-234488878357.png)

**Comment by anfranken** [comment]
@dkatzberg nice try :stuck_out_tongue_winking_eye:
New layout problem (IE, Chrome, FF): overlapping of th BMBF and DZHW Logo at a reduced window size

![dzhwlogo_overlapping](https://cloud.githubusercontent.com/assets/13656277/10095100/91acb6ae-6367-11e5-88fd-b9768ceab0f9.png)
