### ISSUE TITLE
Extend import interfaces for dataSet

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#605]
There are some changes (#519) which are not documented in the interfaces yet.

**Comment by rreitmann** [comment]
We need to find out what has to be done (check domain model and implementation).

**Comment by dkatzberg** [comment]
Add to DataSet Implementation the following fields:
- [ ] type
- [ ] subDataSets

**Comment by rreitmann** [comment]
@anfranken Please test the import. Details page is not ready yet. If we deploy to test then we need to reindex elasticsearch!

**Comment by limouri** [comment]
Fixed parse errors de289b96804cf4aece209ae07d82b37eef6a94dc
