### ISSUE TITLE
Refine handling of variables with dataType string or date

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#610]
If a variable is a date we need other validation/ statistics then if we have with numeric or string variables.

**Comment by rreitmann** [comment]
@anfranken Please define what you need....

**Comment by anfranken** [comment]
I know this is not a validation, but for example the min, max or median shouldn't be longer of the type "Double" because it now looks like the "ISO 8601 Date".

**Comment by rreitmann** [comment]
This seems to be a bigger issue then I thought. The entire data model of variables cannot cope with values which are not a number but ordinal!

**Comment by rreitmann** [comment]
Variables with dataType string or date can have statistics and validResponses as well. Currently we cannot import any statistics for these kinds of variables.

**Comment by rreitmann** [comment]
WIthin this issue we will only model and define additional validations...

**Comment by rreitmann** [comment]
statistics.minimum, statistics.maximum, statistics.firstQuartile, statistics.secondQuartile must be parsable according to variable.dataType
plotly chart and data table have to be displayed if and only if there is at least one validresponse or one missing. If the scalelevel is continuous then the chart is a histogram and not a bar chart.
