### ISSUE TITLE
Implement Study Import

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#618]
Planed for 3 Points:
- [x] Define Interface and update the Wiki
- [x] Create Test Study Import File
- [x] Implement Study Import

Additional Todos:
- [x] Create Study Resource
- [x] Implement Study Tab
- [x] Remove Fake Study Page
- [x] Implement Delete Studies (Backend / FrontendController)
- [x] Implement Update Study Elasticsearch after Mongo Update
- [x] Added Support for Releases

**Comment by dkatzberg** [comment]
@limouri Some string do not work in the dialog. The upload itself seems to work.

**Comment by rreitmann** [comment]
@MaxDerPraktikant Please test the study import again. Especially check if the search contains the actual study.
