### ISSUE TITLE
Create domain object "question"

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#62]
As public user I want to search for questions...

**Comment by rreitmann** [comment]
Questions are related to variables (1 question -> 1..n variables and 1 variable -> 0..1 question)

**Comment by rreitmann** [comment]
- Create full textsearch without filters
- Create search and details page
- create testdata

**Comment by dkatzberg** [comment]
Reference the issue #65 for fixing the bug in the search.js

**Comment by dkatzberg** [comment]
missing validation. back to development.

**Comment by dkatzberg** [comment]
Open UI changes:
* Change "related variables" table to a panel of links under the "option" panel on the left side
