### ISSUE TITLE
Implement Study Details Page

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#621]
( https://github.com/dzhw/metadatamanagement/wiki/Design-Vision )

- [ ] Implement the design vision of the Study Details Page
- [x] Move the Study Tab to the Second Positon after the 'All' Tab
- [ ] Extend Tabs for Study Tab (Save state, new study-result element like the other ones)

**Comment by rreitmann** [comment]
@MaxDerPraktikant Please check the study details on all browsers

**Comment by anfranken** [comment]
I think we don't need a link to the questions on the study page.
