### ISSUE TITLE
Implement a Related Publication Page without any Functions

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#622]
This issue should have a related publication page for a demonstration, without any function and only for the visualisation.

- [x] Implement Hard coded Tab
- [x] Implement One Element in the Tab
- [x] Implement a Related Publication Page without any Functions
- [x] Activate Related Publication Dialog at Study Detail Page

**Comment by rreitmann** [comment]
@MaxDerPraktikant Please test the related publications page.
