### ISSUE TITLE
Add "generated" variables

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#63]
As public user I want to see which variables are computed by other variables...

**Comment by rreitmann** [comment]
- Enhance testdata
- Add list of "pre variables" to variable document (variables can contain variables can contain ...)
- Do not modify the create and update dialog

**Comment by dkatzberg** [comment]
Open UI changes:
* Change "notice" to a more specific information
* Change "related variables" table to a panel of links under the "option" panel on the left side
