### ISSUE TITLE
Display bug IE (question detail page)

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#638]
if you watch this [page](https://metadatamanagement.cfapps.io/#/de/questions/se19-ins1-01) ate the IE there is a display bug:
![dbqdp](https://cloud.githubusercontent.com/assets/13656277/18054880/ff0d3300-6e05-11e6-825b-96e3d1eeb362.png)

**Comment by rreitmann** [comment]
@MaxDerPraktikant Please check if this is still a problem. Close if not....

**Comment by MaxDerPraktikant** [comment]
Yes, it's still current and also valid for the variable detail page

**Comment by rreitmann** [comment]
@anfranken Is this still a problem? If not, please close this bug...
