### ISSUE TITLE
Create domain object "concept"

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#64]
As Public User I want to search for concepts

The Domain Object "Concept" should be created as author specific (e.g. Big5 Short Scale by B. Rammstedt).

There should be relations to study and question level (related by Concept ID).  

There should be an interface to edit the attributes of a "Concept".

The attributes of the DO "Concept" should be derived from the paper written by @annegaertner .

**Comment by AndyDaniel1** [comment]
**Broad Definition**
Concepts represent theoretical (latent) contructs which are measured in an instrument by questions and items. 

**Relations**
Due to the fact that the same concept could be used in different studies, the relation between a concept and studies is 1-n . 

Out of pure theory, the relation between concepts and questions is 1-1 because the same concept should always be measured in the same manner. 
Problem: In fact exist different ways to measure concepts and due to this the concept question relation is (in fact) 1-n.  

Further we should discuss if concepts have study/survey specific attributes like reliability and validity in survey xy (which contradicts the concept studies relation of 1-n). 

**Attributes**
General attributes of the domain object concept are (to be done): 

-

**Comment by rreitmann** [comment]
Here is the picture of what we talked about today:
![20190430_113255](https://user-images.githubusercontent.com/12323832/56962297-7f620300-6b56-11e9-855a-7272e5209be9.jpg)

Missing things:
- icon for domain object concept
- german translation for concept
- attachment types (do we need types)

**Comment by annegaertner** [comment]
I suggest the following attachment types:
- **documentation** (this is the document that describes the whole development of a concept)
- **answer sheet** (this displays the actual part of the instrument that surveys the concept, e. g. a certain question including question text and all possible answers) -> _I am not sure whether this information repeats as soon as the their is information on "questions". Since not all studies contain "questions", I thought this attachment might be useful._
- **other**

**Comment by rreitmann** [comment]
In order to clarify the definition of a concept: Big5 itself is not a concept, it is a (or the) model for conceptualizing "Personality".

**Comment by rreitmann** [comment]
We need to implement the following things:

- [ ] Create/Edit concept
   - [ ] Page title and toolbar header are set correctly
   - [ ] Only Publisher can edit/create concepts
   - [ ] Validations (see asterisks in picture above)
   - [ ] Historization of concepts
   - [ ] All details can be edited
       - [ ] tag editor for concepts (different validation then study.tags)
       - [ ] md-chips based chooser for original languages      
   - [ ] Create/Edit concept attachments
      - [ ] Validations 
      - [ ] Historization of concept attachment metadata
- [ ] Delete concept
   - [ ] Only Publisher can delete concept
   - [ ] Concepts which are used by questions or instruments cannot be deleted
- [ ] Concept search
   - [ ] Filter by study, survey, instrument, question, data set, variable
   - [ ] Search by content of concept
- [ ] Concept Details View
   - [ ] All users can see concepts and can follow the links to either the linked masters (if logged in) or the current version of the linked domain object
   - [ ] Page title and toolbar header are set correctly
   - [ ] Links to one study, survey, instrument, question, data set, variable
   - [ ] All concept details are displayed
   - [ ] All attachments are displayed and downloadable
- [ ] Study Details, Survey Details, Instrument Details, Question Details, Data Set Details, Variable Details
   - [ ] Link to one concept
   - [ ] Link to many concepts
- [ ] instrument edit
   - [ ] data provider and publisher can assign concepts
   - [ ] md-chips based field for assigning multiple concepts (can be empty)
   - [ ] concept must exit validator
- [ ] question upload
   - [ ] data provider and publisher can assign concepts
   - [ ] upload question with multiple conceptIds
   - [ ] concept must exit validator

**Comment by rreitmann** [comment]
@rbirkelbach Latest icon version has been integrate, however line weight is IMHO to high

**Comment by rbirkelbach** [comment]
Could you make a screenshot with the other icons next to it? As far as I can see it's not already deployed to the dev system

**Comment by rreitmann** [comment]
![image](https://user-images.githubusercontent.com/12323832/58318005-3e88a180-7e17-11e9-82ab-81af93cef241.png)

**Comment by rbirkelbach** [comment]
It looks as if the lines are a tiny bit thicker than the lines of the other icons (although I don't know how to verify this). I think it would be good to have the oval a bit wider and then use a tiny bit wider rectangles in combination with a bit thinner lines. Do you agree?

**Comment by rreitmann** [comment]
yep

**Comment by rbirkelbach** [comment]
I sent her an email with some suggestions.

**Comment by rreitmann** [comment]
Here are some review remarks:
- [ ] when I try to delete a concept in use I must get an **alert** toast which does not disappear without clicking on it
- [ ] when I try to delete a concept in use which is used by instruments and questions, I can only see an error message for questions
- [ ] original languages should be just a comma separated list on the details card of the details page

**Comment by rreitmann** [comment]
- [ ] countryCodes.resource.js is still under surveymanagement
- [ ] filtering concepts by instruments shows "4 concepts found" although there are just 2 (nestedInstruments, instruments in concept are not deduplicated as well)

**Comment by rbirkelbach** [comment]
- english label is missing for `concept-management.edit.label.id
`- `con-text$` is unintuitive. Better to add `con-` and `$` automatically after the user entered the `text`

**Comment by rbirkelbach** [comment]
In the details I'd put the DOI last, because the user will probably decide to click on it only after they read the other details and evaluated whether it's interesting for them or not.

**Comment by rbirkelbach** [comment]
- {{question-management.error.question.concept-ids.not-exists}} has no label

**Comment by rbirkelbach** [comment]
Link from question to concept works, but no link shown the other way around (from concept to question)

**Comment by rreitmann** [comment]
@rbirkelbach you can retest when PR #2264 has been merged...

**Comment by rreitmann** [comment]
We still need to document concepts here:
https://github.com/dzhw/metadatamanagement/wiki/Domain-Model

**Comment by rbirkelbach** [comment]
![](https://cdn.shopify.com/s/files/1/1419/0132/products/bugSpray.jpg?v=1537389671) was very effective. I couldn't reproduce the bugs.

**Comment by UteH** [comment]
@rbirkelbach @rreitmann I there a _user_ documentation of `concept` yet? I could not find it in readthedocs

**Comment by rreitmann** [comment]
Nope

**Comment by annegaertner** [comment]
@UteH I already started a documentation, which should be transferred to readthedocs after finalization, but is here for now: `\\faust\Abt4\FDZ\2_Standards\Skalendokumentation (Modul A3)\Vorarbeiten\MDM_Konzepte_Prozess_Anleitung.docx`
