### ISSUE TITLE
Reduce bidirectional relationships

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#649]
Currently we have bidirectional relationships in our domain model which require effort (post validation) and can be replaced by queries. For instance variable <-> question is a many to one relationship and we currently store the variableIds in the question as well as all the questionId in the variable. Storing the list of variableIds is not necessary and causes complexity during import.

**Comment by rreitmann** [comment]
The following bidirectional relationships will be replaced by unidirectional relationships:
- study <-> dataAcquisitionProject (only study will contain the dataAcquisitionProjectId)
- study <-> instrument (only instrument will contain the studyId)
- survey <-> instrument (only instrument will contain the surveyId)
- study <-> relatedPublication (only relatedPublication will contain a list of studyIds)
- study <-> survey (only survey will contain the studyId)
- study <-> dataSet (only dataSet will contain the studyId)
- survey <-> dataSet (only dataSet will contain a list of surveyIds)
- variable <-> dataSet (only dataSet will contain an ordered list of variableIds)
- variable <-> question (only variable will contain an optional questionId)

**Comment by dkatzberg** [comment]
@limouri Relation Variable <-> Study does not work

**Comment by dkatzberg** [comment]
@limouri Handling of non existing study . If you click at other pages on the study link, you will be redirected to the error page, if the study does not exist.

**Comment by rreitmann** [comment]
We will cover the error page in #671

**Comment by dkatzberg** [comment]
Please test all connection/relations between implemented domain objects,
