### ISSUE TITLE
Replace datepicker with simple year input

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#65]
A datepicker with a explicite date is not necessary. A simple year input is sufficient. The datepicker would be remove completly and replaced by two simple year input fields.

**Comment by dkatzberg** [comment]
The search.js has a bug within the the datepicker reference within the Issue #62. The problem is that the question-search include no datepicker .The easiest way for fixing the bug is to implement this issue.

**Comment by anfranken** [comment]
no check for max endtime
