### ISSUE TITLE
Add dara metadata attributes to study

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#650]
We need to identify all mandatory attribute for DOI registration:
http://www.da-ra.de/fileadmin/media/da-ra.de/Technik/dara_v3.1_de_en_18112014.xsd
http://www.da-ra.de/fileadmin/media/da-ra.de/PDFs/MDS_Tabelle_3_1_201503_de.pdf

Attention: The xsd gives more details (sub elements).

**Comment by rreitmann** [comment]
this relates to #667

**Comment by rreitmann** [comment]
should be defined in #1316

**Comment by UteH** [comment]
is this issue outdated?

**Comment by rreitmann** [comment]
No, as far as I remember. Someone (I think @AndyDaniel1) has to identify all attributes of DARA which are missing in our domain model so that we can enhance our domain model and send this information to DARA...

**Comment by rreitmann** [comment]
Closed in favor of the VFDB issues...
