### ISSUE TITLE
New categories for question.type

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#651]
There are many questions which have a mixed type at the moment (e.g. single choice - open). Maybe we need a rule to classify them or we need new categories for the type.

**Comment by rreitmann** [comment]
What about one new type called "mixed" or similar?

**Comment by rreitmann** [comment]
@anfranken Is this still relevant for current data?

**Comment by anfranken** [comment]
At the moment we abuse the type matrix for the mixed typ, but that isn't a good solution.
