### ISSUE TITLE
Change Validation for study

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#663]
- [x] Update Wiki
- [x] Update Validation (increase institution length 128 and citation hint length to 2048)
- [x] Update i18n Strings

**Comment by rreitmann** [comment]
@MaxDerPraktikant Please ensure that studies can be imported now...

**Comment by MaxDerPraktikant** [comment]
@rreitmann The max length of the study title is still 128 and needs to be expanded.

**Comment by rreitmann** [comment]
@MaxDerPraktikant You have been too fast. The fixed title is now online!
