### ISSUE TITLE
Allow upload of directories instead of zip.

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#664]
Currently the users have to clone a github repository and zip the contents of a subdirectory to upload variables for instance. A better approach would be to select or drag and drop a directory and upload its contents. This would avoid polluting the repository.

This should be possible in all recent browsers except IE:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitDirectory

**Comment by anfranken** [comment]
It's importent to test this issue in all browsers, beacuase we had some trouble with the FF

**Comment by rreitmann** [comment]
This issue is not ready yet. Not all browsers will be supported, however there will be a workarround!

**Comment by rreitmann** [comment]
I have successfully tested the directory functionality in Firefox Nightly. Seems that Mozilla has not yet moved this feature to the normal releases :-(
