### ISSUE TITLE
Connect german and english search

### ISSUE THREAD

**Issue by MaxDerPraktikant** [dzhw/metadatamanagement#668]
A researcher copies something for example "graduate" out of an english article and paste it directly in our german search. 
In the moment he would get no output, but it would be more practical if the search would give him the output for "Absolventen".

**Comment by rreitmann** [comment]
We postpone this issue until we have english data...

**Comment by rreitmann** [comment]
The current idea is to save all domain objects in one index metadata (not metadata_de,en).

**Comment by rreitmann** [comment]
![img_2316](https://cloud.githubusercontent.com/assets/12323832/22687252/83bb6b80-ed27-11e6-8fba-0c2a3e5e7649.JPG)

**Comment by rreitmann** [comment]
We will refactor search completely. The idea is to have only one index containing the complete mongo objects plus related sub documents as defined here: #692

**Comment by rreitmann** [comment]
@anfranken: Please check if all defined attributes can be searched for and also check navigation by keyboard in firefox and IE.

**Comment by rreitmann** [comment]
@anfranken: Please check again if all defined attributes can be searched for and also check navigation by keyboard in firefox and IE.
