### ISSUE TITLE
Automatic Tests for JavaScript

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#67]

**Comment by dkatzberg** [comment]
http://searls.github.io/jasmine-maven-plugin/
Jasmine allows tests within the continuous integration building process with maven

**Comment by dkatzberg** [comment]
Instanbul is a code coverage tool for javascript, which works with jasmine
https://github.com/yahoo/istanbul
https://github.com/maenu/grunt-template-jasmine-istanbul
https://bryce.fisher-fleig.org/blog/setting-up-istanbul-with-jasmine/

Or more alternatives:
http://blog.johnryding.com/post/46757192364/javascript-code-coverage-with-phantomjs-jasmine

**Comment by rreitmann** [comment]
This can be closed thanks to JHipster :-)
