### ISSUE TITLE
Use search result cards in every place where domain objects are listed

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#672]
- use elasticsearch queries instead of mongo queries
- implement *-list dialogs which reuse search result card
- remove unused code

**Comment by rreitmann** [comment]
For the developer:
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-get.html
https://www.elastic.co/guide/en/elasticsearch/guide/current/_finding_multiple_exact_values.html

**Comment by dkatzberg** [comment]
@limouri  please review my last two commits.

**Comment by dkatzberg** [comment]
@anfranken please test all 'Related Information' buttons...
