### ISSUE TITLE
Extend the Survey Domain Object

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#678]
Add the following field to the Survey Domain Object:
- [x] I18nString population
- [x] i18nString sample
- [x] i18nString surveyMethod
- [x] Update Projections
- [x] Update Elasticsearch Mapping
- [x] Update Client (e.g. Importer)
- [x] Update Search Document
- [x] Implement Validation for the new fields

**Comment by anfranken** [comment]
The german translation of the valiadtion message has to be corrected:
sample -> Stichprobe (not Beispiel)
It also would be nice if the validation messages could be clustered. For example first all sample validation erros afterwards the population and so on.

**Comment by anfranken** [comment]
there is no validation of the mandatoriness of grossSampleSize/sampleSize/responseRate

**Comment by limouri** [comment]
see #756
