### ISSUE TITLE
Implement the Related Publication Domain Object

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#679]
- [x] Implement the Related Publication Domain Object
- [x] Rename abstract to publicationAbstract
- [x] Implement Validation Rules
- [x] Implement Elasticsearch Mapping for Related Publication
- [x] Rebuild the Fake Page (compare #622 ) with dynamic data from the DB and Backend
- [x] Implement Projections
- [x] Implement Unit Tests
- [x] Update Interface
- [x] Implement the Importer

**Comment by dkatzberg** [comment]
@limouri TODOs for rest of this issue:
- [ ] If you click on the 'All'-Tab, The count of the related publication tab is 0. Reason: Related Publication has no Project ID! You have to extend the query. I did this as a workaround for the search query: https://github.com/dzhw/metadatamanagement/blob/master/src/main/webapp/scripts/searchmanagement/services/search.dao.js#L57-L58
- [ ] The Buttons on the right side of the details page have to be implemented
- [ ] JUnit Test for the Related Publication Delete Resource (Backend)

The rest of this issue should be done

**Comment by rreitmann** [comment]
@anfranken Please test the whole workflow with related publications. The following issue already summarizes missing validations: #741

**Comment by rreitmann** [comment]
@anfranken Added filter by studyId. Please test the whole workflow with related publications. The following issue already summarizes missing validations: #741

**Comment by anfranken** [comment]
- change german string 
 - Abstrakt -> Abstract
 - Quelle -> Quellenangabe
- see #759
