### ISSUE TITLE
Rename atomicQuestionText Field in Variable

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#680]
- [x] Rename atomicQuestionText Field to relatedQuestionStrings
- [x] Update Domain Model
- [x] Update Projections
- [x] Update Unit Tests
- [x] Update Elasticsearch Mapping
- [x] Update Interface
- [x] Update Client (e.g. Importer)
- [x]  Update IO Files for Variable

**Comment by dkatzberg** [comment]
@rreitmann Please review. :)

**Comment by rreitmann** [comment]
@dkatzberg Please adjust validation documentation and implementation for this field as well.

**Comment by rreitmann** [comment]
@anfranken Please test if this field can be imported and is searchable. I think you have to adjust your file generation routines

**Comment by anfranken** [comment]
@dkatzberg why is it called relatedQuestionString**s** isn't it only one string?

**Comment by dkatzberg** [comment]
@anfranken Some Strings from question are merged to this only one string. this is the reason why it is called Strings
