### ISSUE TITLE
Refine variable details page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#684]
- adjust headings in cooperation with @kpstephan 
- adjust labels in cooperation with @kpstephan 
- move total*frequencies to footer of distribution table
- remove whiskers
- remove totalvalid\* from statistics card

**Comment by kpstephan** [comment]
please adjust headings and labels (german):

Variableninformationen
  add Name: variablename (in addition to title )
  add Label: variablelabel (in addition to title) 

Statistische Grafik => Abbildung Häufigkeiten/Verteilung

Statistiken => Deskriptive Maßzahlen

Details der Generierung => don't display this if variable is not a generated variable

**Comment by MaxDerPraktikant** [comment]
Please put "absolute Häufigkeiten" into the list of statistics

**Comment by limouri** [comment]
@MaxDerPraktikant  please test with diverse browsers

**Comment by anfranken** [comment]
If I go over the frequencies table with my mouse courser the border of the column seems to switch.
page: https://metadatamanagement.cfapps.io/#/de/variables/abs2005-aocc251
browser: IE, FF

**Comment by rreitmann** [comment]
@anfranken please retest this issue
