### ISSUE TITLE
Refine question page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#685]
- [x] use buttons with correct icons (see variable details page)
- [x] instrumente must be instrument
- [x] change instrument.title to study.title
- [x] use md-headline for headlines

**Comment by rreitmann** [comment]
@MaxDerPraktikant Please test the question page in all browsers and in all languages...

**Comment by anfranken** [comment]
@limouri why did we change instrument.title to study.title? The rest is fine

**Comment by dkatzberg** [comment]
@anfranken because we have no instrument and needed an regular title.
