### ISSUE TITLE
Refine study page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#686]
- use correct buttons (see variable details)
- adjust headings and label in cooperation with @kpstephan 
- icon of related publication must be the book (see search tab)
- use md-heading for all headings

**Comment by kpstephan** [comment]
please adjust headings and labels(german):

Details der Studie
  Institution => Erhebende Institution
  Autoren => Projektmitarbeiter(innen)
  Sponsoren => gefördert von:
  Veröffentlichungen => delete this item
  Notizen => delete this item
  Zitat Hinweis => Zitation

Zugehörige Informationen
  Instrument => Instrumente

Erhebungsdetails => Erhebungen

Datensatzinformationen => Datensätze

Instrumenteninformationen => Instrumente

**Comment by limouri** [comment]
@MaxDerPraktikant  please test with diverse browsers

**Comment by anfranken** [comment]
@limouri should there really be a link to all questions of that study? And do we need a link to the instruments if we there will be a card with instruments?
