### ISSUE TITLE
Implement Survey Detail Page

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#708]
- [x] Implement Survey Detail Page. Use the Design Vision and the Domain Model as Basic

**Comment by rreitmann** [comment]
@dkatzberg Please review this issue

**Comment by dkatzberg** [comment]
@anfranken please test this issue.

**Comment by anfranken** [comment]
@limouri there are many attributes of survey which are not implemented on the detail page. Do we have a new issue for that?

**Comment by limouri** [comment]
see #756
