### ISSUE TITLE
Implement Dataset Details Page

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#709]
- [x] Implement the Dataset Details Page based on the Design Vision and the Domain Model
- [x] Update the importer
- [x] Discuss the presentation of SubDataSets and afterwards implement it

**Comment by dkatzberg** [comment]
Implement first: #605 before this issue!

**Comment by rreitmann** [comment]
@anfranken Please test the data-set details page in all browsers
