### ISSUE TITLE
Implement the Instrument Details Page

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#710]
- [ ] Add a new Search Tab
- [ ] Implement an importer for Instrument
- [ ] Update the Interface in the Wiki
- [ ] Update Instrument Domain Model with the attribute 'title'
- [ ] Implement Details Page based on Design Vision and Domain Model
- [ ] add type e.g "papi, cati,..."
- [ ] add title

**Comment by kpstephan** [comment]
display the "related information" links in the following order
- Studie
- Erhebung
- Fragen

**Comment by rreitmann** [comment]
- harmonize with orher details pages (see #790)

**Comment by rreitmann** [comment]
@dkatzberg Please review the implementation

**Comment by dkatzberg** [comment]
- [ ] Please add more comments at the client code. 
- [ ] Fix the Bug
`angular.js:13920 TypeError: Cannot read property 'indexOf' of undefined
    at http://localhost:8080/scripts/instrumentmanagement/services/instrumentUpload.service.js:122:33`

I took the interface definition of the instrument and uploaded it. Afterwards, this error happens. 

After the fix, I have to check the details page as well and do some more tests. I could't do it at all, because of the error.

**Comment by rreitmann** [comment]
Reopened cause there are two bug:
- 'Variablenfragebogen' cannot be imported
- Attachment size is limited to 1MB (should be 5MB)

**Comment by rreitmann** [comment]
@anfranken Please retest the fixes
