### ISSUE TITLE
Change template of data set report

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#725]
- the expression of the filterdetails should also show the language, like at the application
- use a line break as a line break (e.g. generation detail)

**Comment by dkatzberg** [comment]
@rreitmann one variable is astu021g_g2 in the dataset 1 of abs2005 for testing

**Comment by rreitmann** [comment]
@MarenStephan Please verify whether the compiled report is ok.

**Comment by kpstephan** [comment]
We decided not to display the filterdetails in data set report. An external Link to the variable detail page is displayed instead in the data set report (see issue #956 ).
