### ISSUE TITLE
Model new attributes for variable

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#736]
- [x] Change description to annotations: I18nString
- [x] ~~Add codingScheme (files)~~ (will be taken care of in #774)
- [x] Add statistics.mode (String) 
- [x] Add statistics.deviance (Double)
- [x] Add statistics.meanDeviation (Double)
- [x] Add relatedVariables (List<String>) (see #724) (Strings are Variabe.id, manually created)

**Comment by dkatzberg** [comment]
Validation:
