### ISSUE TITLE
Model new attributes for question

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#737]
- [x] add topic (I18nString)

**Comment by dkatzberg** [comment]
- [ ] Validation for topic: I18nSize.LARGE

Default TODOs:
- [ ] Added new Attribute to Domain Model
- [ ] Added Validation to Wiki Documentation
- [ ] Added new Attribute at Client Upload
- [ ] Added new Attribute to Backend Implementation

**Comment by dkatzberg** [comment]
@rreitmann Check the changes on domain model, interface and wiki documentation please.
