### ISSUE TITLE
Model new attributes for study

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#738]
- [x] dataAvailability (EN: "Available", "In preparation", "Not available"; DE: "Verfügbar", "In Aufbereitung, "Nicht verfügbar") I18nString
- [x] surveyDesign (EN: "Cross-section", "Panel"; DE: "Querschnitt", "Panel") I18nString

**Comment by dkatzberg** [comment]
Validation: 
- [ ] dataAvailability: Mandatory, Only given values by I18n Enums are valid
- [ ] surveyDesign: Mandatory, Only given values by I18n Enums are valid

**Comment by dkatzberg** [comment]
@limouri Check the updated domain model, the wiki documentation and the interface for study please.

**Comment by limouri** [comment]
Please change dataAvailable to dataAvailability in domain model
