### ISSUE TITLE
Model new attributes for survey

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#739]
- [x] grossSampleSize (Integer)
- [x] sampleSize (Integer)
- [x] responseRate (Double)

**Comment by dkatzberg** [comment]
Notice:
- reponseRate is a svg images, which will be upload too (compare to question text image at question)

**Comment by dkatzberg** [comment]
Validation:
- [ ] grossSampleSize: Mandatory
- [ ] sampleSize: Mandatory
- [ ] responseRate: Mandatory

**Comment by dkatzberg** [comment]
@limouri Check the changes on the domain model, the wiki documentation and the interaces

**Comment by anfranken** [comment]
you can find some example svgs for the response rates [here](https://github.com/dzhw/metadatamanagement-io/tree/master/project/abs2005/data/surveys/images)
