### ISSUE TITLE
Add validations to RelatedPublication

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#741]
- [x] implement a validation that ensures that at least one "foreign key" is used.
- [x] implement a validation that ensures that at least one study is used.
- [x] implement a post validation for related publications which is started by a FAB button on the related publication search tab. This post validation should validate existence of all "foreign keys".
- [x] implement a post-validation that ensures that a referenced domain object exists
- [x] implement a post-validation that ensures if a domain object (not study) is referenced then the corresponding study must be referenced as well

@anfranken Is an empty studyIds array valid? Implicitly if a researcher uses one of our domain objects she uses a study as well... Answer: No, if a publication uses a variable than it must use the corresponding study as well.

**Comment by rreitmann** [comment]
@dkatzberg Here are my remarks:
- [ ] never use repository.findAll (see RelatedPublicationPostValidationService)! Load slices by page instead
- [ ] all post-validation strings belong to related publication and should not be stored in the domain objects post-validation strings
- [ ] the FAB button should be blue and between "reload" and "add"
- [ ] The string "related" or "zugehörige" should not be used in the user interface (see english tooltip). For the user it is just a publication.
- [ ] there are missing i18n strings for post-validation (e.g. "variable-has-not-a-referenced-study" in english)
- [ ] Where are the i18n message string for validations OneForeignKeyIsUsed and OneStudyIsUsed?

**Comment by dkatzberg** [comment]
@rreitmann I have implemented all your remarks. Have a look, please.

**Comment by rreitmann** [comment]
@anfranken: Please test the new post validation and the new validations :-)
