### ISSUE TITLE
Change id patterns for all domain objects

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#743]
~In order to have better results when searching for ids the numbers in the ids should be prefixed with leading zeros. For example if you currently search for a question by abs2005-ins1-1 you will find all questions starting with abs2005-ins1-1 which includes abs2005-ins1-1, abs2005-ins10, abs2005-ins11, ...~

~A better question id would be abs2005-ins1-00001 for the first question in the questionnaire.~

**Comment by rreitmann** [comment]
Current idea is to have ids like the following: que-abs2005-ins1-1!, stu-abs2005!, pub-Schaeper.2005!

**Comment by rreitmann** [comment]
- [ ] Implement client side id builder for each type
- [ ] add study id to all domain objects
- [ ] change id pattern validation for all domain objects
- [ ] change link to details pages
- [ ] change imports on client side

**Comment by dkatzberg** [comment]
@limouri and you @rreitmann are updating the links between detail pages. I marked that as finished, but it based on your progress. 

@rreitmann Please review this issue.
