### ISSUE TITLE
Implement new Attributes for question

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#751]
Implement the modeled attributes for question (see #737 )
- [x] Update Domain Object
- [x] Implement Validations (Backend)
- [x] Update Projection
- [x] Update ElasticSearch Mapping
- [x] Update JUnit Object Builder
- [x] Update QuestionSearchDocument

No update for importer is needed. We got a Json File and parse it.

**Comment by limouri** [comment]
Please add topic field to QuestionSearchDocument
