### ISSUE TITLE
Implement new attributes for Study

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#755]
Implement the model of the new attributes for study (#738 )
- [x] Update the importer
- [x] Update Domain Object
- [x] Implement Validations (Backend)
- [x] Update Projection
- [x] Update ElasticSearch Mapping
- [x] Update JUnit Object Builder
- [x] Update StudySearchObject
- [x] Add DataAvaibilities Class
- [x] Add SurveyDesigns Class

**Comment by limouri** [comment]
- Please check the 'ValidSurveyDesign' and 'ValidDataAvaibility' validations. the check 'if isNullOrEmpty' is not correct and should be deleted.
- Please change the comment 'check for scale levels'
