### ISSUE TITLE
Refine survey details page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#764]
See specification here: https://github.com/dzhw/metadatamanagement/wiki/design-visions/SurveyDetails.pdf

**Comment by rreitmann** [comment]
Related information should be displayed as links as defined by @kpstephan.

**Comment by kpstephan** [comment]
display the links in the following order
- Studie
- Instrument
- Datensätze
- Erhebungen der gleichen Studie

**Comment by kpstephan** [comment]
related information: the list "Erhebungen der gleichen Studie" must not contain the documented survey itself. Please remove it from the list.

**Comment by rreitmann** [comment]
@limouri Here are my remarks:
- [ ] *SearchResource are no resources they are services and should be named *SearchService and moved to services
- [ ] This https://github.com/dzhw/metadatamanagement/blob/a10599e354972ec3f15a4402d89a46a207d4544f/src/main/webapp/scripts/surveymanagement/views/survey-detail.controller.js#L16 fails if there are no hits
- [ ] currentLanguage must be obtained from LanguageService in controllers not from $rootScope (https://github.com/dzhw/metadatamanagement/blob/a10599e354972ec3f15a4402d89a46a207d4544f/src/main/webapp/scripts/surveymanagement/views/survey-detail.controller.js#L36)
- [ ] This service remembers the current language: https://github.com/dzhw/metadatamanagement/blob/a10599e354972ec3f15a4402d89a46a207d4544f/src/main/webapp/scripts/surveymanagement/resources/surveySearch.resource.js#L6
- [ ]  The count queries in *SearchResource should not be term searches but term filters (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-filtered-query.html#query-dsl-filtered-query)
- [ ] controllerAs must not start with capitals (e.g InstrumentDetailController)
- [ ] related* directives for displaying related domain objects
- [ ] as stated by @kpstephan exclude current survey from list of surveys (add must not filter)

**Comment by rreitmann** [comment]
Remarks to survey-detail.controller.js
- [ ] paramObject must not be a global var
- [ ] StudySearchResource is not a resource
- [ ] DataSetSearchResource is not a resource and must not count by surveyTitles
- [ ] SurveySearchService must exclude current surveyId from count (filter must not)
- [ ] we do not need ctrl.showStudy
- [ ] we do not need ctrl.showRelatedInstruments
- [ ] DataSetSearchDialogService must not count by surveyTitle
- [ ] DataSetSearchDialogService and SurveySearchDialogService must not use the current count

**Comment by rreitmann** [comment]
Remarks to survey-detail.controller.js
- [ ] paramObject must not be a global var
- [ ] StudySearchResource is not a resource
- [ ] DataSetSearchResource is not a resource and must not count by surveyTitles
- [ ] SurveySearchService must exclude current surveyId from count (filter must not)
- [ ] we do not need ctrl.showStudy
- [ ] we do not need ctrl.showRelatedInstruments
- [ ] DataSetSearchDialogService must not count by surveyTitle
- [ ] DataSetSearchDialogService and SurveySearchDialogService must not use the current count

**Comment by rreitmann** [comment]
@kpstephan Please check the survey details page.

**Comment by kpstephan** [comment]
check results:

Details card
    Bruttostichprobe and Nettostichprobe: use seperator 1000
        (please write new issue if this can not be implemented in the current sprint) 
    Rücklauf: use "," instead of "." if Language is german  
        (please write new issue if this can not be implemented in the current sprint)

Related objects card
    change noch nicht vorhanden => nicht vorhanden

Card Weitere Informationen zum Rücklauf
    this card is not displayed, heading cannot be tested, SVG-Contend (de/en) cannot be tested

**Comment by kpstephan** [comment]
changes ok
Card "Weitere Informationen zum Rücklauf" ok

**Comment by anfranken** [comment]
@rreitmann I would expect that the picture would behave like question.png if I zoom in or out. If that is wrong than we can close the issue

**Comment by rreitmann** [comment]
@anfranken: We should replace these images by plotly cause font sizes do in the SVG do not scale if you zoom.
