### ISSUE TITLE
Refine question details page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#768]
- rework related information panel (as defined by @kpstephan)
- add maximizie/minimize and copyToclipboard to technicalRepresentation.source label
- add predecessor card and successor card
- harmonize common details (see #790)

**Comment by kpstephan** [comment]
display the links in the following order
- Studie
- Instrument
- Variablen
- Publikationen

**Comment by rreitmann** [comment]
@kpstephan test question details view

**Comment by kpstephan** [comment]
results:

Detail Card, Eingangsfilter
- in small client windows (e.g. mobile browser) the buttons (clippboard, maximise/minimise) overlap the content 

Search Card
- change String "Single Choice" of attribute type ?> "Einfachnennung", if language is german

Card related objects
- change strings "noch nicht vorhanden" => "nicht vorhanden"

Card Technical Representation
- change formatting of QML-source-code: reduce indent of rows
  (see Question 10.2, 19. Sozialerhebung)
- in small client windows (e.g. mobile browser) the buttons (clippboard, maximise/minimise) overlap the content

**Comment by kpstephan** [comment]
@anfranken please fix input data (see above) (at a later time)
- String "single choice"
- QML-source code

**Comment by anfranken** [comment]
- For "String "single choice"" see #864
- @kpstephan for the QML-source code we need a better generation process because the escaping of the xml for the json isn't feasible at the moment
