### ISSUE TITLE
Refine data set details page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#769]
- rework related information panel (as defined by @kpstephan)
- implement new design vision https://github.com/dzhw/metadatamanagement/wiki/Design-Vision#data-set-details
- implement data-set-report-button as FAB only visible for authenticated users
- harmonize with other details pages (see #790)
- move dataSet.description to heading

**Comment by kpstephan** [comment]
display the links "related objects" in the following order

Studie
Erhebungen
Variablen
Datensätze der gleichen Studie
Publikationen

**Comment by rreitmann** [comment]
@kpstephan Please test the data set details.

**Comment by kpstephan** [comment]
results:

Details card
    Don't display Beschreibung

Card related Objects, Modal Dialog
   Dialog doesn't contain all elements (e.g. Variables, Personendatensatz 
   DZHW-Absolventenpanel2005 )

   change strings "Noch nicht vorhanden" => "Nicht vorhanden"

Card Sub-Datensätze
    Change Strings:
        title "Sub-Datensätze" => "Datenprodukte"
        "Zugangsweg" => Datenprodukt
        "Analysierte Variablen" => Analysierbare Variablen
        "Beobachtungen" => Fälle

Table
    Format first row as title row (e.g. centered, bold)

**Comment by kpstephan** [comment]
changes ok

**Comment by anfranken** [comment]
-  de: Datenprodukt -> en:  Access Way or de: Fälle -> en: Number Of Observations ... this is a bit confusing.
-

**Comment by rreitmann** [comment]
@anfranken How will we proceed with the missing english strings?
