### ISSUE TITLE
Implement new attributes for variable

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#772]
A couple of new attributes have been defined in #736.
- extend importer
- extend domain objects
- extend search document and mapping
- implement additional validation and post validation

**Comment by dkatzberg** [comment]
- [x] Update the importer
- [x] Update Domain Object
- [x] Implement Validations (Backend)
- [x] Update Projection
- [x] Update ElasticSearch Mapping
- [x] Update JUnit Object Builder
- [x] Update VariableSearchObject
