### ISSUE TITLE
Model new domain object codingScheme

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#774]
Coding schemes are currently maintained in an excel file. We need to import coding schemes (project independent) which consist of some metadata and a file. Variables and (maybe) questions need to link to coding schemes.

**Comment by Andy20** [comment]
Poential attributes of this domain object might be: 
- ID
- type (controlled vocabulary required)
- sourceReference
- name
- attributes (e.g. regions, degrees) 
- annotations 
- year
- studyIds 
- questionIds (?)
- variableIds

Attachment: coding scheme (.xls/.pdf)

**Comment by rreitmann** [comment]
@Andy20 Can you provide the excel file in which you currently maintain coding schemes?

**Comment by Andy20** [comment]
yes of course. I will provide the file tomorrow when I'm back in Hannover. When do you have time to talk about it?

**Comment by rreitmann** [comment]
A few remarks:
- We need to display all used coding schemes on the study details page and on the question details page.
- PostValidation needs to check whether the referenced coding scheme exists
- We must not delete coding schemes which are used by a variable

**Comment by Andy20** [comment]
provide list of types (en|de) 
- [ ... ]
- misc.

**Comment by Andy20** [comment]
We only need two types of coding schemes: 

_de_
- einfache Codierlisten
- Referenzlisten

_en_
- simple coding scheme
- reference scheme
 
These types are exhaustive thus we don't need a type miscellaneous. Beside this I'm not really satisfied with the term "reference scheme" as it describes hierarchical nested simple coding schemes. Maybe I'll come up with a better term 'til monday. You'll find a description of the two types (in german) in the [FDZ-Allgemein-Wiki](https://github.com/dzhw/FDZ_Allgemein/wiki/DA4.4-Zusatzdokumente-zusammenstellen#anlegen-von-codierlisten-f%C3%BCr-generierte-variablen-und-aussehen-der-verbalisierten-generationdetails).

**Comment by Andy20** [comment]
I've checked the extension of the domain model as well as the excel-interfaces for codingSchemes and related attachments. All alterations/extensions are well implemented. 

From my pov the provision of the id by the user should not be a problem, since the structure of the id is straight forward.
