### ISSUE TITLE
Hide Plot and distribution table if there is no distribution

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#778]
- For some variables it doesn't make sense to show the distribution (e.g. for the identification number). 
- In some cases it wouldn't be allowed to show the distribution (e.g. some string variables)

**Comment by rreitmann** [comment]
On the variable details page we will display a diagram and the distribution table if and only if there is a distribution. If the scale level is continuous the diagram will be a histogram.

**Comment by rreitmann** [comment]
- [ ] validresponses must be camel case
- [ ] remove unused icon and css class
- [ ] remove notAvailable flag

**Comment by rreitmann** [comment]
@anfranken Please test these changes.
