### ISSUE TITLE
Reporting of subpopulations

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#779]
At the moment it isn't possible to report different populations within a dataset. You only can see the variable.distributions of the variables of the dataset and not the distributions of the subDataSets.

**Comment by rreitmann** [comment]
This has to be discussed within #811

**Comment by rreitmann** [comment]
Today we have agreed on reworking subpopulations in the following way:
Surveys and Data Sets must not have multiple populations. A Data Set must contain at most one sub data set per access way. Variables are contained in exactly one data set.

**Comment by rreitmann** [comment]
@anfranken Are there variables which are not contained in a data-set (e.g. not accessible ones), or are these variables in a data-set but not in any sub-data-set...

**Comment by rreitmann** [comment]
No, every variable belongs to exactly one data set.
