### ISSUE TITLE
Remove spring-data-elasticsearch and switch to Jest

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#78]
https://github.com/searchbox-io/Jest/tree/master/jest

**Comment by rreitmann** [comment]
https://github.com/spring-io/sagan/blob/master/sagan-site/src/main/java/sagan/support/health/ElasticsearchHealthIndicator.java

**Comment by dkatzberg** [comment]
TODO: Put the hard coded url from the file ElasticsearchClientConfiguration in a config yml file.

**Comment by rreitmann** [comment]
@dkatzberg done

**Comment by dkatzberg** [comment]
The changes are okay. :) 
TODO: Add JUnit tests for this classes, please.

**Comment by rreitmann** [comment]
@dkatzberg The classes are covered sufficiently by the existing unit tests...
