### ISSUE TITLE
Model new attributes for related publication

### ISSUE THREAD

**Issue by kpstephan** [dzhw/metadatamanagement#791]
authors: String
yearOfPublication: Integer
abstractSource: i18nString

**Comment by anfranken** [comment]
Couldn't you take yearOfPublication and and authors from the sourceReference?

**Comment by rreitmann** [comment]
We renamed following attributes:
- yearOfPublication -> year
- publicationAbstract -> abstract

@kpstephan We do not understand the meaning of abstractSource! What is this, why is it an I18nString?

**Comment by rreitmann** [comment]
abstractSource is a string containing information about where the abstract text comes from. It must be maintained in English an German.
