### ISSUE TITLE
rework statistical information of variable detail page

### ISSUE THREAD

**Issue by kpstephan** [dzhw/metadatamanagement#801]
Please change Title en:
Deskriptive Maßzahlen / summary statistics

Please insert for each measure:
NAME_OF_MEASURE (ABBREVIATION_in_Latex_Style): VALUE

please insert measures and headings in the following oder:

[without heading]
1. Anzahl unterschiedlicher Beobachtungen / number of different observations, no abbreviation for this measure,  (level of measurement: k,o,n)
2. Minimum / minimum, abbreviation: min,  (level of measurement: k,o)
3. Maximum / maximum, abbreviation: max (level of measurement: k,o)

Zentrale Tendenz / central tendency
4. Arithmetisches Mittel / mean, abbreviation: X(bar), (level of measurement: k)
5. Median / median, abbreviation: x(tilde), (level of measurement: k,o)
6. Modus / mode, abbreviation: h (level of measurement: k,o,n)

Streuung / dispersion
7. Standardabweichung / standard deviation, abbreviation: s, (level of measurement: k)
8. durchschnittliche Abweichung / mean absolute deviation, abbreviation: MAD,  (level of measurement: k)
9. Devianz / deviation, abbreviation: d, (level of measurement: k,o,n)

Verteilung / distribution
10. Schiefe / skewness, abbreviation: v, (level of measurement: k)
11. Wölbung / kurtosis, abbreviation: w, (level of measurement: k)

**Comment by rreitmann** [comment]
- [ ] Headings must not be display if there are no values
- [ ] Don't use <small> to style the <h3> tags
- [ ] Headings should have the same style as the labels (bold, font-size) of the statistics

**Comment by rreitmann** [comment]
@anfranken Please test the new order and headings of statistical information

**Comment by anfranken** [comment]
X\bar -> x\bar
better identification of the headings

**Comment by anfranken** [comment]
@dkatzberg please deploy the changes also on the testsystem
