### ISSUE TITLE
Add informations to variable details page

### ISSUE THREAD

**Issue by kpstephan** [dzhw/metadatamanagement#803]
left card:
add attribute Anmerkungen: variable.annotations / annotations: variable.annotations 
between Zugangswege and Eingangsfilter
don't display the attribute when it is empty

card related objects:
add Panelvariablen: / panel variables: variable.sameVariablesInPanel

**Comment by dkatzberg** [comment]
the annotations field was added before.

**Comment by rreitmann** [comment]
@anfranken Please test only these changes of the variable details page...
