### ISSUE TITLE
Rework study details page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#813]
- reorder study details
- reimplement related objects (see #790)
- remove surveys, datasets and instruments
- add 4 empty cards with heading
- harmonize with other details pages (see #790)

(see design vision  https://github.com/dzhw/metadatamanagement/wiki/Design-Vision#study-details)

**Comment by rreitmann** [comment]
@kpstephan Please test the study details page

**Comment by kpstephan** [comment]
test results and further changes:

Card related objects
display in following order
- Erhebungen
- Datensätze
- Publikationen

Card "Beschreibung der Studie"
change title -> "Studienbeschreibung"

titles for empty cards in  following order
- "Verfügbare Datenprodukte" / "Available Data Products"
- "Eckdaten der Erhebungen" / "Basic Data of Surveys"
- "Materialien zum Download" / "Downloads"
- last empty card only with "..."

**Comment by kpstephan** [comment]
@limouri 
card related objects
please remove link to questions

**Comment by kpstephan** [comment]
@anfranken: page is ready for further tests
