### ISSUE TITLE
Move variable.relatedVariables to excel import file

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#816]

**Comment by rreitmann** [comment]
@anfranken Is this still relevant? If not, please close this issue...

**Comment by anfranken** [comment]
Yes it is still relevant. But  now it isn't variable.sameVariablesInPanel any more, instead it is variable.relatedVariables. And it is import that it will be in the excel, because it couldn't be generated automatically.

**Comment by rreitmann** [comment]
@limouri relatedVariables is a comma separated list of ids => you need to split the list and trim each entry in the resulting array....

**Comment by rreitmann** [comment]
@anfranken Please test the import of relatedVariables....
