### ISSUE TITLE
Validate the structure of the Template.zip for data sets reports

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#821]
Add a validation for a check of the file structure within the Template.zip for data sets reports. Return a "Bad Request" with ErrorListDto and display it to the user.

**Comment by dkatzberg** [comment]
@rreitmann please review this issue

**Comment by rreitmann** [comment]
@dkatzberg:
- [ ] DataSetReportService is a Singleton => attributes are not thread-safe

**Comment by rreitmann** [comment]
@anfranken Please test this before we implement #846
