### ISSUE TITLE
Use html5 urls without #

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#823]
For later usage of prerender (see https://prerender.io/documentation) we need to use html5 pushstate in order to have normal urls without '#'.

**Comment by rreitmann** [comment]
@dkatzberg Please review the new client urls...

**Comment by dkatzberg** [comment]
@anfranken Please test the website. Visit some pages and have a look on the url. there shouldn't any hashtag.

**Comment by rreitmann** [comment]
Bug: If the user comes with an invalid id of a domain object (/de/variables/hurz) than he is redirected to /null :-(

**Comment by rreitmann** [comment]
@anfranken  Please test the fix

**Comment by rreitmann** [comment]
If you go directly to https://metadatamanagement-dev.cfapps.io/ than the String "Metadatamanagement" is sometimes not replaced by "Metadatensuche" :-(

**Comment by rreitmann** [comment]
Without # in the url the browser initializes our javascript app more often (when you past an url into the app). I am going to use the standard hashbang (#!)....
