### ISSUE TITLE
Rework jhipster generated error handling

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#828]
- [x] Remove ErrorDto, ErrorConstants, FieldErrorDto, ParameterizedException,...
- [x] remove fieldError handling from errorMessageResolver.service.js
- [x] remove fieldError handling from alert.directive.js
- [x] use toasts instead of alerts for server error (5xx) => remove alert.directive.js)
- [x] ensure that import of instrument attachments still works (with validation)
- [x] ensure that register user still works (with validation)

**Comment by dkatzberg** [comment]
This issue has a following issue: #867

**Comment by rreitmann** [comment]
- [ ] we still need the error view under {de,en}/error cause we redirect to it when there is no state for the given client url (/de/hallo)
- [ ] you have removed jobcompletetoast controller and template although we need it for displaying the protocol
- [ ] simpleMessageToasts have been hidden after 10 seconds automatically (and that was good, job logging toasts can be displayed forever...)

**Comment by rreitmann** [comment]
@anfranken Please test this after talking to me :-)
