### ISSUE TITLE
Migrate from Postgres to MongoDB

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#83]

**Comment by rreitmann** [comment]
@limouri Please verify that I merged your changes correctly...

**Comment by rreitmann** [comment]
@anfranken Please test the whole application (registration process, bookmarkable urls, i18n, disclosure, logos,...) If you find something come to me and we decide if we open a bug issue...

**Comment by anfranken** [comment]
A few remarks:
There is no disclosure if you are logged in.
It's not possible to register.
The language is always english after login.
(IE) There are no icons at the navbar.

**Comment by rreitmann** [comment]
I have created bugs for the last items (see #86 and #85). @limouri works on the first items.

**Comment by limouri** [comment]
@anfranken please test the two first items
