### ISSUE TITLE
Define <h1> for all domain object details views

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#835]
The `<h1>`  of all details views should be unique in our system and should be reused on all search result cards. For instance 'Erhebungsinstrument ' + survey.title which we currently use for instruments is not unique!

**Comment by rreitmann** [comment]
study: study.title => validate uniqueness, mandatory in english and german

variable: variable.label + ' (' + variable.name + ')' => mandatory in english and german
We should use more beautiful urls like: https://metadatamanagement.cfapps.io/de/studies/se19/data-sets/ds1/variables/cmt01_g1

survey: survey.title => validate uniqueness, mandatory in english and german
https://metadatamanagement.cfapps.io/de/studies/se19/surveys/sy1

question: 'Frage ' + question.number + ': + 'instrument.description' => we need instrument.description
We should use more beautiful urls like: https://metadatamanagement.cfapps.io/de/studies/se19/instruments/ins1/questions/1

instrument: 'instrument.description' => validate uniqueness, mandatory in english and german
We should use more beautiful urls like: https://metadatamanagement.cfapps.io/de/studies/se19/instruments/ins1

data-set: 'data-set.description' => validate uniqueness, mandatory in english and german
We should use more beautiful urls like: 
https://metadatamanagement.cfapps.io/de/studies/se19/data-sets/ds1

publications: 'publication.title' => validate uniqueness, mandatory
We should use more beautiful urls like: 
https://metadatamanagement.cfapps.io/de/publications/Jaksztat.2014

**Comment by rreitmann** [comment]
During implementation of this issue I have fixed a bug which caused a wrong mapping of data-sets into elasticsearch => reindex all

**Comment by rreitmann** [comment]
@dkatzberg, @limouri, @anfranken: I have implemented a new mandatory attribute for instruments: description (I18nString)

**Comment by dkatzberg** [comment]
@anfranken Please check every page. If you visit an empty page/error page there should be just a default title.

**Comment by anfranken** [comment]
@rreitmann I'm not sure if we need the ids in the title anymore, because now the user not really need to know how the id looks like.

It wasn’t possible to test instrument, data-set and question because the detail page doesn't work at the moment.
