### ISSUE TITLE
Remove citation from application

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#840]
Delete all code and documentation related to citations. There is currently no need for it....

**Comment by rreitmann** [comment]
currently there are still some citation fragments in the wiki

**Comment by dkatzberg** [comment]
@limouri Check Wiki und Application, please.

**Comment by limouri** [comment]
Removed from:
- [ ] Interfaces
- [ ] ID-Generation
- [ ] Domain Model
