### ISSUE TITLE
Reorganize displayed Informations for Detail Pages

### ISSUE THREAD

**Issue by limouri** [dzhw/metadatamanagement#844]
**Question Detail Page:**
   - [x] Add shortcut to variables in the related objects card
   - [x] Title should have the following structure: Question + ' ' + {{QuestionNumber}} + ' ' + {{SurveyTitle}}

**Question Search Card:**
   - [x] Header should have the following structure: Question + ' ' + {{QuestionNumber}} + ' ' + {{SurveyTitle}}

**Variable Detail Page:**
   - [x] Add shortcut to question in the related objects card (already done)

**Instrument Detail Page:**
   - [x] Harmonize common details (see #790)
   - [x] Content of table row should be left justified

**Comment by rreitmann** [comment]
@kpstephan Please test the changes

**Comment by kpstephan** [comment]
changes ok
@anfranken please test the "rest"
