### ISSUE TITLE
Rework search controller

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#845]
Currently the search controller does not react on all location changes (see #789). We need to refactor this controller in order to prepare it for filtered search.

We need two "private" functions which store all search params in the location and read all search params from the location. Furthermore we should only start a new search if and only if the location changes.

Additionally we should move all upload logic into the corresponding upload services.

Implement this before #847

**Comment by rreitmann** [comment]
@limouri Please review my changes and test the imports...

**Comment by limouri** [comment]
please see #847 to found more changes

**Comment by limouri** [comment]
- [ ] Search functionality should be tested (project change, paging ....)

- [ ] Home button functionality should be tested
