### ISSUE TITLE
Implement drag and drop for dataset report

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#846]
- [x] add drop area to dataset details page
- [x] allow directory dropping (we zip it before uploading it to the server)

**Comment by dkatzberg** [comment]
@limouri The code looks ok. I can't test the issue, because of the changes of the data-set and the no longer working generation of dataset reports. We should discuss about this problem and do we want close this issue without testing?

**Comment by anfranken** [comment]
@dkatzberg @limouri I'm not sure if we should close it without testing. Maybe we should test it later after #878?

**Comment by anfranken** [comment]
We will test this issue after #896
