### ISSUE TITLE
Implement link to search for variables of data set

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#847]
- [x] add datasetId to variable search document
- [x] implement filter by datasetId for search controller
- [x] replace modal dialog with link to search state

**Comment by rreitmann** [comment]
@anfranken Please test the variable list of a data-set

**Comment by anfranken** [comment]
There is no list of variables if you import a data-set with and the related variables. You only get "Variables:
Not available!" on the data-set detail page.

**Comment by anfranken** [comment]
For the problem above see #939
