### ISSUE TITLE
Glyphicons in navbar are not visible in IE

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#85]
@anfranken Please add you IE version to this issue

**Comment by anfranken** [comment]
![ie_navbar_noicon](https://cloud.githubusercontent.com/assets/13656277/11186127/870c40ec-8c80-11e5-8a77-0a9459f500fb.png)
![ie-version](https://cloud.githubusercontent.com/assets/13656277/11186200/e6598668-8c80-11e5-9528-f9cc0774bc16.png)

**Comment by rreitmann** [comment]
This might be related: http://stackoverflow.com/questions/25281286/bootstrap-3-2-0-glyphicons-are-not-displaying-in-internet-explorer

**Comment by rreitmann** [comment]
@anfranken please give it another try..

**Comment by rreitmann** [comment]
The glyphicons are displayed correctly when we run the server locally. This might be an issue on cloudfoundry. I have already asked Pivotals support for help...

**Comment by rreitmann** [comment]
We are now using the icons from a CDN.

**Comment by rreitmann** [comment]
https://connect.microsoft.com/IE/feedbackdetail/view/992569/font-face-not-working-with-internet-explorer-and-http-header-pragma-no-cache

**Comment by rreitmann** [comment]
https://github.com/jhipster/generator-jhipster/issues/2239
