### ISSUE TITLE
Variable details page: change behaviour of copyToClipboard and minimise/maximise Buttons

### ISSUE THREAD

**Issue by kpstephan** [dzhw/metadatamanagement#856]
Detail Card, Eingangsfilter
- in small client windows (e.g. mobile browser) the buttons (clippboard, maximise/minimise) overlap the content 

Card Generation Details
- Generation Rule: in small client windows (e.g. mobile browser) the buttons (clippboard, maximise/minimise) overlap the content

**Comment by rreitmann** [comment]
duplicates #860
