### ISSUE TITLE
Internationalization of instrument attachments

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#859]
It would be nice if you could have the possibility to upload an attachment in German language and English

**Comment by rreitmann** [comment]
- [ ] don't forget the documentation

**Comment by rreitmann** [comment]
- [ ] we will create a new attribute language which is a valid ISO 639-1 two letter code
- [ ] we will create a new attribute description which is an I18nString (validation see old title)
- [ ] title will no longer be an I18nString, it has to be a valid string in the language of the attachment

**Comment by rreitmann** [comment]
https://www.bib-bvb.de/web/kkb-online/sprachencode-nach-iso-639

**Comment by rreitmann** [comment]
- [ ] rework language filter: name should be displayIsoLanguage, list should be a map

**Comment by rreitmann** [comment]
@anfranken Please test the changes...
