### ISSUE TITLE
New dataSet attribute format

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#865]
It would be nice if the user could differ between the formats of the dataset. For example a wide format of a dataSet which means that the dataSet has a unique identifier or the long format which means that you need two identifiers for a unique identification.
- German: breit, lang
- Englisch: wide, long

**Comment by dkatzberg** [comment]
@rreitmann I updated the Domain Model (image and validation spec.). Please have a look to them.  Check the code.

**Comment by rreitmann** [comment]
@anfranken Please test this issue...
