### ISSUE TITLE
data set report: escape of quotation marks

### ISSUE THREAD

**Issue by fbaillet** [dzhw/metadatamanagement#872]
In the data set report of the Absolventenpanel 05 there is a problem with the escape of the quotation marks. For examples see:

- **Genereation detail description of variable astu011e_g2d:** 
 _Für die Zuordnung der darin nicht enthaltenen älteren Fächercodes 47 ("Krankenpege-Ausbildung->STB: **SS**ozialwesen") und 112 (**SS**ozialpsychologie-> STB "Psychologie")_

- **Genereation detail description of variable astu011k_g2**:
_Die generierte Variable hat die Ausprägung 1 **Ü**niversität"_

- **Genereation detail description of variable astu011k_g4r:**
_Hochschulen im Ausland erhielten den Code 22 **Ä**usland"_

**Comment by dkatzberg** [comment]
@limouri Try to build a Pdf File with the new version of the tex template. Check for example the Variable: afec021h_g1o There should be only correct quotation marks
