### ISSUE TITLE
Implement replacement of sameVariablesInPanel

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#875]
As discussed in #839 we want to replace sameVariablesInPanel with a string panelIdentifier:
- [x] remove sameVariablesInPanel from domain object and search document including post validation
- [x] add panelIdentifier to domain object and search document
- [x] add validation for panelIdentifier (Max Length MEDIUM, Alphanumeric (with German Umlauts and ß), Pattern (DataAcquisitionProjectId + "-" + "ds" + "dataSetNumber" + "-" + string))
- [x] replace current search on variable details page by a link to the search

**Comment by rreitmann** [comment]
@anfranken Do not test before #877 is ready...

**Comment by anfranken** [comment]
The validation should be (Max Length MEDIUM, Alphanumeric (with German Umlauts, "ß" and  , "_"), Pattern (DataAcquisitionProjectId + "-" + "ds" + "dataSetNumber" + "-" + string), because at the moment we extract the panelIdentifier of the variablenames and they also have "_".
