### ISSUE TITLE
Implement changes for variable.dataType string and date

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#876]
As discussed here #610 we need to implement the following change:
- [x] change type of statistics.minimum, statistics.maximum, statistics.median, statistics.firstQuartile, statistics.thirdQuartile to String
- [x] add validation as defined in the wiki
- [x] display the statistics as numbers, dates or strings according to their dataType on the variableDetails page

**Comment by rreitmann** [comment]
@dkatzberg Here are a few remarks:
- [ ] "ISO Standard ..." must not be presented to the user in a validation message.  Use pattern "yyyy-MM-dd".
- [ ] The frequency table on the variables details page does not use your new filter...
- [ ]  Plotly does not display the distribution correctly...

**Comment by rreitmann** [comment]
@anfranken Please test this issue on prod (fka test) :-)

**Comment by anfranken** [comment]
"The value for data type is not valid. Allowed values in english: string, numerisch. Allowed values in english: string, numeric" is an old error message which i get
