### ISSUE TITLE
Rework variable management

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#877]
As discussed in #779 and #833 we need to change the relation between variables and data-sets as well as the relation between variables and questions:
## Domain Object
- [x] remove questionId (including search document)
- [x] add dataSetId, dataSetNumber, indexInDataSet, surveyNumbers to domain object and search
document
- [x] add sub domain object RelatedQuestion (add to search document) 
- [x] cross check with current domain model
## Validation
- [x] change validation of variable.id
- [x] change validation of variable.name
- [x] remove validation of variable.surveyIds
- [x] add validation for dataSetNumber, indexInDataSet, surveyNumbers
- [x] add validation of sub domain object RelatedQuestion 
- [x] cross-check with current documentation in wiki 
## Post-Validation
- [x] change post-validation of questionId to validation of questionIds
- [x] add post-valiadtion of data-set id 
## Import
The import has to be reworked:
- [x] Import by data-set directory
- [x] Generate variableId from projectId, dataSetNumber and variable.name  
- [x] Generate surveyIds from projectId, and surveyNumber
- [x] Generate dataSetId from projectId and dataSetNumber
- [x] Generate instrumentId from projectId and instrumentNumber
- [x] Generate relatedQuestion.questionId from questionNumber and instrumentNumber
- [x] synchronize variableBuilder with interface example
## GUI
- [x] Change client urls for variable details to /de/studies/{projectId}/data-sets/{dataSetNumber}/variables/{variableName} including search results cards

**Comment by dkatzberg** [comment]
- [ ] Dataset/UI: Change link to variables (must use dataSetId and sortBy indexInDataSet) (from Issue #878 )

**Comment by dkatzberg** [comment]
- [ ] dataSetId has to be mandatory (validation)

**Comment by dkatzberg** [comment]
- [ ]  Missing the i18n String: {{variable-management.error.generation-details.ruleExpressionLanguage.valid-rule-expression-language}}

**Comment by dkatzberg** [comment]
The import of variable management doesn't import the name. I got the following error message: 
"Die 2. Variable in Datensatz variables hat keinen Namen!"
- [ ] Added Name of Variable to import

**Comment by rreitmann** [comment]
@limouri Here are my remarks:
- [ ] All error messages must use ds* and variable.name instead of fdzId
- [ ] use comment in variableUploadService
- [ ] rename index to datasetIndex
- [ ] use "private" methods

**Comment by rreitmann** [comment]
@anfranken Please test the variable management issues on prod

**Comment by anfranken** [comment]
If the language is german the variable.distribution.plot has wrong labels on the x-axis. I think there is a comma missing.

**Comment by dkatzberg** [comment]
@rreitmann just the second commit is relevant. the third commit removes the changed from the first commit.

**Comment by rreitmann** [comment]
@anfranken please retest
