### ISSUE TITLE
Rework data set management

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#878]
The following changes have been discussed within #779 and need to be implemented:
## Domain Object
- [x] remove variableIds from domain object and search document
- [x] add number and surveyNumbers to domain object and search document
- [x] cross check with current domain model
## Validation
- [x] change id pattern (add number)
- [x] add validation for number 
- [x] add validation for surveyNumbers
- [x] validate uniqueness of subDataSet.accessWay 
- [x] cross check with current documentation in wiki
## Post-Validation
- [x] remove validation of variableIds
## Import
- [x] use one excel file with two sheets instead of multiple
- [x] generate dataSetIds from projectId and dataSet.number  
- [x] generate surveyIds from projectId and surveyNumber
## GUI
- [x] Change client urls for data-set details to /de/studies/{projectId}/data-sets/{dataSetNumber} including search results cards
- ~~[ ] Change link to variables (must use dataSetId and sortBy indexInDataSet)~~

**Comment by dkatzberg** [comment]
The point 'Change link to variables (must use dataSetId and sortBy indexInDataSet)' has to be done in the issue #877

**Comment by rreitmann** [comment]
@anfranken You can test this issue on dev as soon as it is deployed

We need to keep in mind to delete all data sets from mongo, and recreate indices in elasticsearch...
