### ISSUE TITLE
Rework survey management

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#879]
In order to further hide ids from the user we need to implement the following changes:
## Domain Object
- [x] add number
- [x] cross check with current domain model
## Validation
- [x] change id pattern (add number)
- [x] validate number
- [x] cross check with current documentation in wiki
## Import
- [x] Generate surveyIds from survey.number
- [x] Change upload to contain survey number instead of id in the  name  of the response rate image
## GUI
- [x] Change client urls for survey details to /de/studies/{projectId}/surveys/{surveyNumber}

**Comment by dkatzberg** [comment]
Please add the survey.number to the pattern validation for the point: 'change id pattern (add number)' At the moment there is a [0-9] number pattern. that is wrong, because there have to be the survey.number.

**Comment by dkatzberg** [comment]
@anfranken Please test:
- [ ] Import
- [ ] Changed Validation 
- [ ] Details Page (no errors and all detail data will be correctly displayed)
