### ISSUE TITLE
Rework question management

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#880]
In order to hide all ids from the user we need to implement the following changes
## Domain Object
- [x] add instrumentNumber to domain object (including search document)
- [x] add successorNumbers to domain object (including search document)
- [x] remove surveyId
- [x] cross check with current domain model
## Validation
- [x] change validation of question.id
~~- [ ] change validation of question.number~~
- [x] add validation for instrumentNumber
- [x] remove validation of instrumentId
- [x] cross check with current documentation in wiki
## Post-Validation
- [x] remove surveyId validation
## Import
The import has to be reworked:
- [x] Import by instrument directory
- [x] Generate questionId from projectId, instrumentNumber and question.number 
- [x] Generate instrumentId from projectId, and instrumentNumber
- [x] Allow upload of images having only the number in the file name (e.g. 1.png)
## GUI
- [x] Change client urls for question details to /de/studies/{projectId}/instruments/{instrumentNumber}/questions/{questionNumber} including search results cards

**Comment by dkatzberg** [comment]
@rreitmann @anfranken What is the "change validation of question.number" ? I can't find any difference to the actual validation.

**Comment by rreitmann** [comment]
@dkatzberg I guess I thought that there has not been any uniqueness validation by now but apparently I was wrong :-)

**Comment by anfranken** [comment]
In the interface the successor has to be an array of strings. And you have to generate a questionid of the number of the successors at the import.

**Comment by anfranken** [comment]
I think the validation for "unique within dataAcquisitionProject" isn't woking at the moment

**Comment by rreitmann** [comment]
Currently there is the following issue: Image are read by questionNumber therefore images of instrument 2 overwrite images of instrument 1....

**Comment by rreitmann** [comment]
@anfranken Please re-test.
