### ISSUE TITLE
Rework instrument management

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#881]
In order to hide all ids from the user we need to implement the following changes
## Domain Object (Instrument)
- [x] add number
- [x] replace surveyId by ~~surveyIds~~ surveyNumbers
- [x] cross check with current domain model
## Domain Object (InstrumentAttachmentMetadata)
- [x] add instrumentNumber
- [x] cross check with current domain model
## Validation
- [x] change validation of instrument.id
- [x] add validation for instrument.number
- [x] add validation for instrument.surveyNumbers
- [x] add validation for attachment.instrumentNumber
- [x] cross check with current documentation in wiki
## Post-Validation
- [x] change post-validation of surveyId to validation of surveyIds
## Import
The import has to be reworked:
- [x] Generate instrumentId from projectId and instrument number
- [x] Generate surveyIds from projectId, and surveyNumber
- [x] synchronize builders with interface example
## GUI
- [x] Change client urls for instrument details to /de/studies/{projectId}/instruments/{instrumentNumber} including search results cards

**Comment by rreitmann** [comment]
@anfranken Please test this issue. We need to remove all existing instruments and reindex elasticsearch...

**Comment by anfranken** [comment]
For the Firefox the upload doesn't work:
- if you upload a directory  you get this error: "The file "instruments.xlsx" could not be read!"
- if you upload “all files” the application doesn't find the attachments

**Comment by limouri** [comment]
@anfranken please update your browser firefox to the latest version

**Comment by anfranken** [comment]
I think the validation for "unique within dataAcquisitionProject" isn't woking at the moment.
We need a new validation(see #935)

**Comment by limouri** [comment]
Please see #920
