### ISSUE TITLE
Upgrade angular to 1.6.0 AND angular-translate to 2.13.1 (bower.json)

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#885]
Upgrade angular-translate from 2.13.0 to 2.13.1 (bower.json)

**Comment by dkatzberg** [comment]
@rreitmann Angular Update to 1.6.x 
Please check the bigger update.

**Comment by rreitmann** [comment]
Protractor tests are failing since this update...

**Comment by dkatzberg** [comment]
@rreitmann Major Update. Please review the changes.
