### ISSUE TITLE
Fix data-set report after domain model changes

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#896]
In #877 and #878 we have changed the relation between variables and data-sets. Therefore we must fix the data-set report.

**Comment by anfranken** [comment]
After implementing this issue we should also test #846

**Comment by rreitmann** [comment]
This issue must wait until #918 will have been implemented.

**Comment by rreitmann** [comment]
To sum up the relation between data-sets and variables has been modified as well as the relation between variables and questions. Therefore we need to adjust the java code which loads the data for the template as well as Main.tex and Variable.tex
