### ISSUE TITLE
Implement missing translations for data set details

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#897]
As mentioned by @anfranken here #769, there are missing translations for "Datenprodukt" and "Fälle".

**Comment by rreitmann** [comment]
Datenprodukt -> Data Product
Analysierbare Variablen -> Analyzable Variables
Fälle -> Observations

**Comment by dkatzberg** [comment]
@anfranken Have a look, if you find any more missing translation. I found the missing translation by importing elements with errors.
