### ISSUE TITLE
Rework related objects of instrument details page

### ISSUE THREAD

**Issue by limouri** [dzhw/metadatamanagement#913]
We display currently only one survey (as a link to Survey-Detail-Page) on Instrument-Detail-Page, but after the domain model has been changed (see #881), we should change this to link to search for surveys of instrument.

**Comment by rreitmann** [comment]
We will rework all links to related objects on the instrument details page. If there is exactly one related object we will display a direct link, if there are more than one related objects we will display a link to the search.

**Comment by rreitmann** [comment]
Within this issue I had to extend the elasticsearch mapping of surveys => we need to recreate the indices...

**Comment by dkatzberg** [comment]
@anfranken Please test the changes on the instrument detail page

**Comment by anfranken** [comment]
If I upload instrument data of the abs2005: I can see that the instrument abs2005-ins1 has two numbers of surveys (in mongoDB) but you only see one related survey.

**Comment by rreitmann** [comment]
during the import there has been a problem if the list of numbers contains spaces (e.g.: 1, 2).

**Comment by rreitmann** [comment]
@anfranken Please reimport the instruments and test again...
