### ISSUE TITLE
Refine related objects of variable detail page 

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#942]

**Comment by anfranken** [comment]
- panelvariable: there aren't any variableIds anymore. Now we will use panelidentifier
- dataSet: one variable has only one dataSet
- question: now a variable can have more than one question

**Comment by rreitmann** [comment]
Implement all 1:n relations as link to search. If there is only one hit use direct link (see instrument details page).

**Comment by rreitmann** [comment]
@anfranken Please check the related objects links...
