### ISSUE TITLE
Show more attributes of question on question details page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#954]
- [x] add type, topic, questionText, instruction, introduction, number to GUI
- [x] use overflow hidden for image and put a FAB maximize-button over the image which open the image in a new tab

**Comment by rreitmann** [comment]
@anfranken Please test the changes...

**Comment by anfranken** [comment]
In the IE(11.0.9600.18538) is a layout bug  with the responsive design:
![questionpicturebug](https://cloud.githubusercontent.com/assets/13656277/23168805/c7dc8c54-f849-11e6-99e8-9373ee829f59.png)

**Comment by rreitmann** [comment]
@anfranken We had to fix the layout on all details pages. Please test all details pages in all browsers..
