### ISSUE TITLE
Change the i18nString for the reference / link into the Excel Sheets

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#955]
We wrote i18nString for the links into the Excel Sheet, for example "There is an error for the nth. Object." The Dataset Report warning using a string like "There is an error ob the object in the nth line of the Excel Sheet." The second one is more helpful. 

-[ ] Change all i18nString, which have a reference / link into the Excel Sheet. The line number/index of the Excel Sheet should be used in the futher

**Comment by kimsommer** [comment]
When survey numbers are missing and dublicates exist, counter does not work correctly.

![surveynumber_dublicate_missing](https://user-images.githubusercontent.com/19772575/31081319-cf4b3b74-a78b-11e7-8be7-2a324e42f1af.png)

**Comment by dkatzberg** [comment]
The counter is wrong because of the empty survey number field. This does not increase the index variable.
