### ISSUE TITLE
Define variable details page content for dataset report and implement template for german language

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#956]
There are some differences in the presentation of a variable between the dataset report and the variable details page.

This elements are missing on the variable details page, but exist in the dataset report:
- Details
  - Beschreibung (alle)
  - Panelvariablen (alle)

- Frage: (alle)
  - Nummer (alle)
  - Einleitung der Frage (alle)
  - Ausfüllanweisung (alle)
  - Fragetext (alle)

- Deskreptive Maßzahlen:
  - Unteres Quartil (alle)
  - Oberes Quartil (alle)
  - Boxplot (kontinuierliche Daten)
  
This elements are missing on the variable report:
- Deskreptive Maßzahlen: (nominal)
  - Modus (alle)
  - Durchschnittliche Abweichung (ordinal)
  - Devianz (alle)
  - Abbildung Häufigkeiten (ordinal, nominal)

- Häufigkeiten
  - Missing Column  (alle)
  - Prozent gültig (kontinuierlich)

**Comment by rreitmann** [comment]
@kpstephan Focus on publishing...

**Comment by kpstephan** [comment]
we decided to implement a detail page template that contains only basic information and a link to the corresponding MDM variable detail page and a link to the corresponding question detail page (if one is present).

**Comment by rbirkelbach** [comment]
When I try to upload the root folder of the template for the dataset `dat-gra2005-ds1` I get the following 
```
error:

Bei einem Freemarkerskript liegt eine unbekannte Referenz in der Datei "variables/Variable.tex" vor (Zeile, Zeichen): (105,116): validResponse.label
Erzeugen von Tex Dokument Abgebrochen! 
```

**Comment by rbirkelbach** [comment]
@kpstephan please give me the vm to compile the report.

**Comment by rbirkelbach** [comment]
@kpstephan please tell me the correct password of the virtual machine.

**Comment by rbirkelbach** [comment]
[Main.log](https://github.com/dzhw/metadatamanagement/files/2479242/Main.log)
Also, it does not compile using Katzi's documentation:

```
 lualatex Main.tex
 biber Main
 lualatex Main.tex
 lualatex Main.tex
```

The log file shows what happens when trying to run the first line using the current version of TeXlive for Ubuntu, as I do not have the correct login data.
