### ISSUE TITLE
Visible Datasets after Deleting them

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#970]
I deleted the dataset by uploading a wrong folder. The datasets will be still visible and clickable after the deletion. If I enter one, I got a 404 error message.

I saw the dataset delete entries in the elasticsearch update queue.

**Comment by rreitmann** [comment]
Needs further investigation

**Comment by rreitmann** [comment]
The update queue get processed asynchronously therefore this is by design...
