### ISSUE TITLE
Undefined download document of DSR

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#975]
If you create a dataSetReport you getting a file, which is a zip-document but without a .zip-ending

**Comment by rreitmann** [comment]
Rumors say that this only occurs on the firefox :-) => Needs further documentation

**Comment by rreitmann** [comment]
Additionally the zip contains an unwanted directory (download_FILES)

**Comment by svietgen** [comment]
@dkatzberg It works with Chrome but not with Firefox ("Sorry, etwas ist schief gelaufen...")

**Comment by svietgen** [comment]
@dkatzberg I tried it again and now it works ¯\_(ツ)_/¯
