### ISSUE TITLE
Move Buttons from Toolbar to SideNave

### ISSUE THREAD

**Issue by limouri** [dzhw/metadatamanagement#982]
Login, Logout, Register and Language button should be moved...

**Comment by anfranken** [comment]
The register button seems to have an layout problem if you less than 600 pixel at the width of a page:
![registerbuttonbug](https://cloud.githubusercontent.com/assets/13656277/23557120/3fd82690-002f-11e7-9de8-7a4841c077ca.png)

**Comment by rreitmann** [comment]
@anfranken Good catch! Should be fixed now...
