### ISSUE TITLE
Improve performance of survey upload

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#983]
Instead of deleting all existing surveys we want to delete only the surveys which are not present in the excel any more and update or insert the other ones.

**Comment by KeLange** [comment]
I uploaded the survey file with 2 surveys. When I then delete survey 1 in the Excel sheet and upload the surveys again, survey 1 is still in the system.

![screenshot983](https://cloud.githubusercontent.com/assets/25637592/24742237/ae28efdc-1aa9-11e7-9208-227bbe44f8aa.png)

**Comment by rreitmann** [comment]
Currently there is a bug when we load domain objects projected with the IdAndVersionProjection. Sometimes only the version is returned. The bad thing is that by now I could not find a way to provoke/reproduce this problem.

**Comment by rreitmann** [comment]
I am not using a globally registered projection anymore.
