### ISSUE TITLE
Change order of search tabs

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#988]
The new order shall be: All, Study, Survey, Instruments, Questions, Data Sets, Variables, Related Publications

**Comment by anfranken** [comment]
You only deployed that on the dev-server and in my opinion it isn't a good order because the variable-page which is the most evolved is at the end

**Comment by dkatzberg** [comment]
We discussed this in the review. The next change of the order will be after some usability tests in the future.
